enum DeltaSkills
{
	SKILL_CASUAL,
	SKILL_EASY,
	SKILL_NORMAL,
	SKILL_HARD,
	SKILL_EXPERT
}

enum DeltaSoundChannels
{
	CHAN_HEALTH_SOUNDS = 6, 	// things like damage and healing sounds
	CHAN_HEARTBEAT,				
	CHAN_FALL_WIND,				// we have this on its own channel just in case <3
	CHAN_MOVEMENT				// things like grinding sound when Kris is sliding
}

enum DeltaMessageType
{
	MSG_TYPE_NORMAL,			// uses normal border
	MSG_TYPE_DARKWORLD			// uses dark world border
}

enum DeltaMessageState
{
	MSG_STATE_INITDELAY = 0,	// (0) initial delay before a message shows
	MSG_STATE_TYPING,			// (1) actively typing
	MSG_STATE_SKIPPING,			// (2) skipping to the end
	MSG_STATE_HOLD_INPUT,		// (3) message is finished, awaiting player input
	MSG_STATE_HOLD_SCRIPT,		// (4) message is finished, awaiting dismissal from script
	MSG_STATE_FINISHED			// (5) message is finished, we're moving to next one
}

enum DeltaMessageInputResponse
{
	MSG_IGNORE,					// ignore input
	MSG_SKIP					// skip to end of message
}