class DeltaMessageBox : Object ui
{
	DeltaMessageBox nextMessage;
	DeltaMessageHandler handler;
	DeltaMessageState messageState;
	
	protected TextureID cornerTex, sideTex;
	protected string goalMessage, displayedMessage;
	protected sound typeSound;
	protected int curTics, curCharIndex, soundTimer;
	
	static DeltaMessageBox Create(string message = "", int delayTics = 0,
		TextureID cornerTex = null, TextureID sideTex = null,
		sound typeSound = "delta/type", bool localize = true)
	{
		if (localize)
			message = StringTable.Localize(message);
		
		return new("DeltaMessageBox").Init(message, delayTics, cornerTex,
			sideTex, typeSound);
	}
	
	protected DeltaMessageBox Init(string message, int delayTics,
		TextureID cornerTex, TextureID sideTex, sound typeSound)
	{
		self.cornerTex = cornerTex;
		self.sideTex = sideTex;
		goalMessage = message;
		curTics = delayTics;
		self.typeSound = typeSound;
		
		curCharIndex = 0;
		displayedMessage = "";
		messageState = MSG_STATE_INITDELAY;
		return self;
	}
	
	virtual void Tick()
	{
		if (soundTimer)
			soundTimer--;
		
		if (messageState >= MSG_STATE_HOLD_INPUT)
			return;
		
		if (curTics > 0)
		{
			curTics--;
			return;
		}
		
		ProcessNextCharacter();
	}
	
	virtual void ProcessNextCharacter()
	{
		if (messageState == MSG_STATE_INITDELAY)
			messageState = MSG_STATE_TYPING;
		
		bool printed = false,
			playSound = true,
			usesAsterisk = goalMessage.GetNextCodePoint(0) == int("*");
		
		while (!printed || messageState == MSG_STATE_SKIPPING)
		{
			let [chr, nextIndex] = goalMessage.GetNextCodePoint(curCharIndex);
			int next = goalMessage.GetNextCodePoint(nextIndex);
			
			if (curCharIndex >= goalMessage.CodePointCount() && messageState < MSG_STATE_HOLD_INPUT)
				messageState = MSG_STATE_HOLD_INPUT;
			
			int temp;
			
			switch (chr)
			{
				case "^":
					string str = goalMessage.Mid(nextIndex, 1);
					int timer = str.ToInt(10);
					
					if (timer < 5)
						curTics = max(1, timer) * TICRATE / 6;
					else
					{
						switch (timer)
						{
							case 5:
								curTics = TICRATE;
								break;
							case 6:
								curTics = TICRATE * 4 / 3;
								break;
							case 7:
								curTics = 2 * TICRATE;
								break;
							case 8:
								curTics = 3 * TICRATE;
								break;
							case 9:
								curTics = 5 * TICRATE;
								break;
							default:
								curTics = 5;
								break;
						}
					}
					
					[temp, nextIndex] = goalMessage.GetNextCodePoint(nextIndex);
					playSound = false;
					printed = true;
					break;
				case "/":
					messageState = MSG_STATE_HOLD_INPUT;
					playSound = false;
					printed = true;
					break;
				case "&":
					displayedMessage.AppendCharacter("\n");
					
					if (usesAsterisk && goalMessage.Mid(nextIndex, 1) != "*")
						displayedMessage.AppendFormat("  ");
					
					printed = true;
					break;
				case "%":
					/*
						if we use %% instead of just %, message will
						hang until scripts manually move us on
						(different from /, which waits for player
						input)
					*/
					
					playSound = false;
					printed = true;
					
					if (goalMessage.Mid(nextIndex, 1) == "%")
					{
						messageState = MSG_STATE_HOLD_SCRIPT;
						[temp, nextIndex] = goalMessage.GetNextCodePoint(nextIndex);
						break;
					}
					
					handler.NextMessage();
					break;
				case "\c":
					if (goalMessage.Mid(nextIndex, 1) == "[")
					{
						int i;
						
						// we're casting this shit cuz fuuuuck actually working with this </3
						for (i = nextIndex; i < int(goalMessage.Length());)
						{
							int _chr, _next;
							[_chr, _next] = goalMessage.GetNextCodePoint(i);
							i = _next;
							
							if (_chr == int("]"))
								break;
						}
						
						displayedMessage.AppendFormat("\c" .. goalMessage.Mid(nextIndex, i-nextIndex));
						nextIndex = i;
						break;
					}
					
					displayedMessage.AppendFormat(goalMessage.Mid(curCharIndex, 2));
					[temp, nextIndex] = goalMessage.GetNextCodePoint(nextIndex);
					break;
				default:
					// don't play typing sound for punctuation
					if (IsPunctuation(chr))
						playSound = false;
					else if (chr == int(" ") && IsPunctuation(next))
						playSound = false;
					
					displayedMessage.AppendCharacter(chr);
					printed = true;
					break;
			}
			
			curCharIndex = nextIndex;
		}
		
		if (playSound)
			PlayTypeSound();
	}
	
	bool NextCharacterExists()
	{
		let [chr, nextIndex] = goalMessage.GetNextCodePoint(curCharIndex);
		let [next, secondNextIndex] = goalMessage.GetNextCodePoint(nextIndex);
		
		if (curCharIndex+1 >= goalMessage.CodePointCount())
			return false;
		if (goalMessage.Mid(chr, nextIndex - curCharIndex) == "/")
			return false;
		if (goalMessage.Mid(chr, secondNextIndex - curCharIndex) == "%%")
			return false;
		
		return true;
	}
	
	virtual void TakeInput(InputEvent evt)
	{
		if (messageState == MSG_STATE_TYPING)
			messageState = MSG_STATE_SKIPPING;
		else if (messageState == MSG_STATE_HOLD_INPUT)
			handler.NextMessage();
	}
	
	virtual void PlayTypeSound()
	{
		if (soundTimer)
			return;
		
		soundTimer = 2;
		S_StartSound(typeSound, 1);
	}
	
	virtual void Draw(double smoothRatio)
	{
		if (messageState == MSG_STATE_INITDELAY)
			return;
		
		// dark world dialogue box is 296 x 82 px
		// light world is 289 x 76
		int boxScale = max(1, min(Screen.GetWidth() / 960, Screen.GetHeight() / 480));
		Vector2
			boxSize = (340 * boxScale, 76 * boxScale),
			boxPos = ((Screen.GetWidth() - boxSize.x) / 2.,
				(Screen.GetHeight() - boxSize.y - (40. * boxScale)));
		
		if (cornerTex && sideTex)
		{
			Screen.Dim(0xff000000, 1, int(boxPos.x), int(boxPos.y),
				int(boxSize.x), int(boxSize.y));
			
			Screen.DrawTexture(cornerTex, true, boxPos.x, boxPos.y, DTA_ScaleX,
				boxScale, DTA_ScaleY, boxScale);
			Screen.DrawTexture(cornerTex, true, boxPos.x, boxPos.y + boxSize.y,
				DTA_ScaleX, boxScale, DTA_ScaleY, boxScale, DTA_Rotate, 90);
			Screen.DrawTexture(cornerTex, true, boxPos.x + boxSize.x,
				boxPos.y + boxSize.y, DTA_ScaleX, boxScale, DTA_ScaleY,
				boxScale, DTA_Rotate, 180);
			Screen.DrawTexture(cornerTex, true, boxPos.x + boxSize.x, boxPos.y,
				DTA_ScaleX, boxScale, DTA_ScaleY, boxScale, DTA_Rotate, -90);
			
			// top
			Screen.DrawTexture(sideTex, true, boxPos.x, boxPos.y,
				DTA_ScaleX, boxSize.x, DTA_ScaleY, boxScale);
			// bottom
			Screen.DrawTexture(sideTex, true, boxPos.x + boxSize.x, boxPos.y + boxSize.y,
				DTA_ScaleX, boxSize.x, DTA_ScaleY, boxScale, DTA_Rotate, 180);
			// left
			Screen.DrawTexture(sideTex, true, boxPos.x, boxPos.y + boxSize.y,
				DTA_ScaleX, boxScale, DTA_ScaleY, boxSize.y, DTA_Rotate, 90);
			// right
			Screen.DrawTexture(sideTex, true, boxPos.x + boxSize.x, boxPos.y,
				DTA_ScaleX, boxScale, DTA_ScaleY, boxSize.y, DTA_Rotate, -90);
		}
		else
		{
			int thicc = int(3 * boxScale);
			Screen.Dim(0xff000000, 1, int(boxPos.x) - thicc*2, int(boxPos.y) - thicc*2,
				int(boxSize.x) + thicc*4, int(boxSize.y) + thicc*4);
			Screen.DrawLineFrame(0xffffffff, int(boxPos.x) - thicc*2, int(boxPos.y) - thicc*2,
				int(boxSize.x) + thicc*4, int(boxSize.y) + thicc*4, thicc);
		}
		
		Screen.DrawText(smallFont, Font.CR_UNTRANSLATED, boxPos.x, boxPos.y,
			displayedMessage, DTA_ScaleX, boxScale, DTA_ScaleY, boxScale);
	}
	
	bool IsPunctuation(int chr)
	{
		if (chr < int("0"))
			return true;
		if (chr > int("9") && chr < int("A"))
			return true;
		if (chr > int("Z") && chr < int("a"))
			return true;
		if (chr > int("z") && chr < int("À"))
			return true;
		
		return false;
	}
	
	string GetMessage() const
	{
		return goalMessage;
	}
	
	string GetDisplayedMessage() const
	{
		return displayedMessage;
	}
	
	DeltaMessageState GetMessageState() const
	{
		return messageState;
	}
}

class DeltaMessageHandler : ScreenJob
{
	string debugString;
	DeltaMessageBox message;
	bool keyCurrentlyPressed; // used to prevent repeat inputs
	
	static DeltaMessageHandler Create(DeltaMessageBox msg = null)
	{
		return new("DeltaMessageHandler").Init(msg);
	}
	
	virtual DeltaMessageHandler Init(DeltaMessageBox msg = null, int flags = 0,
		double fadeT = 250.)
	{
		Super.Init(flags, fadeT);
		noWipe = true;
		
		AddMessage(msg);
		return self;
	}
	
	override void OnTick()
	{
		Super.OnTick();
		
		if (!message)
			return;
		
		message.Tick();
	}
	
	override bool OnEvent(InputEvent evt)
	{
		if (!message)
			return true;
		
		if (evt.type == InputEvent.Type_KeyUp)
		{
			keyCurrentlyPressed = false;
			return true;
		}
		
		if (evt.type == InputEvent.Type_KeyDown && !System.SpecialKeyEvent(evt))
		{
			if (keyCurrentlyPressed)
				return true;
			
			message.TakeInput(evt);
			keyCurrentlyPressed = true;
			return true;
		}
		
		return true;
	}
	
	virtual void NextMessage()
	{
		if (message.GetMessageState() == MSG_STATE_HOLD_SCRIPT && message.NextCharacterExists())
		{
			message.messageState = MSG_STATE_TYPING;
			message.ProcessNextCharacter();
			return;
		}
		
		if (!message.nextMessage)
		{
			jobState = finished;
			message = null;
			return;
		}
		
		message = message.nextMessage;
	}
	
	virtual void AddMessage(DeltaMessageBox targetMessage)
	{
		if (!targetMessage)
			return;
		
		targetMessage.handler = self;
		
		if (!message)
		{
			message = targetMessage;
			return;
		}
		
		let msg = message;
		
		while (msg.nextMessage != null)
		{
			msg = msg.nextMessage;
		}
		msg.nextMessage = targetMessage;
	}
	
	override void Draw(double smoothRatio)
	{
		Super.Draw(smoothRatio);
		Screen.DrawText(smallFont, Font.CR_UNTRANSLATED, 0, 0, debugString);
		
		if (!message)
			return;
		
		message.Draw(smoothRatio);
	}
	
	DeltaMessageState GetMessageState()
	{
		if (!message)
			return -1;
		
		return message.GetMessageState();
	}
}