// all our random static functions (mostly math related rn) go here
class DeltaUtil
{
	clearscope static double Lerp(double a, double b, double t, bool _clamp = true)
	{
		if (_clamp)
			t = clamp(t, 0, 1);
		
		return a + ((b - a) * t);
	}
	
	clearscope static int Sign(double value)
	{
		if (value < 0)
			return -1;
		if (value > 0)
			return 1;
		
		return 0;
	}
	
	clearscope static double Map(double value, double minIn, double maxIn,
		double minOut, double maxOut, bool _clamp = true)
	{
		return Lerp(minOut, maxOut, (value - minIn) / (maxIn - minIn), _clamp);
	}
	
	clearscope static Vector2 Vector2Lerp(Vector2 a, Vector2 b, double t, bool _clamp = true)
	{
		double
			x = Lerp(a.x, b.x, t, _clamp),
			y = Lerp(a.y, b.y, t, _clamp);
		
		return (x, y);
	}
	
	clearscope static Vector3 Vector3Lerp(Vector3 a, Vector3 b, double t, bool _clamp = true)
	{
		double
			x = Lerp(a.x, b.x, t, _clamp),
			y = Lerp(a.y, b.y, t, _clamp),
			z = Lerp(a.z, b.z, t, _clamp);
		
		return (x, y, z);
	}
	
	clearscope static Vector3 GetActorForward(Actor a, bool countPitch = true)
	{
		if (!a)
			return (0, 0, 0);
		
		let zOffset = countPitch ? cos(-a.pitch) : 1;
		return (zOffset*cos(a.angle), zOffset*sin(a.angle), countPitch ? sin(-a.pitch) : 0);
	}
	
	clearscope static Vector3 GetActorRight(Actor a, bool countRoll = false)
	{
		if (!a)
			return (0, 0, 0);
		
		let zOffset = countRoll ? cos(a.roll) : 1;
		return (zOffset*sin(a.angle), zOffset*-cos(a.angle), countRoll ? sin(a.roll) : 0);
	}
	
	clearscope static Vector3 GetActorUp(Actor a)
	{
		if (!a)
			return (0, 0, 0);
		
		return -(GetActorForward(a) cross GetActorRight(a));
	}
	
	clearscope static Color HSVtoRGB(Color hsv)
	{
		let h = hsv.r/255.,
			s = hsv.g/255.,
			v = hsv.b/255.,
			c = v * s,
			x = c * (1 - abs((h*6.) % 2 - 1)),
			m = v - c;
		
		let r2 = 0.,
			g2 = 0.,
			b2 = 0.;
		
		if (h >= 5/6.)
		{
			r2 = c;
			b2 = x;
		}
		else if (h >= 4/6.)
		{
			r2 = x;
			b2 = c;
		}
		else if (h >= 3/6.)
		{
			g2 = x;
			b2 = c;
		}
		else if (h >= 2/6.)
		{
			g2 = c;
			b2 = x;
		}
		else if (h >= 1/6.)
		{
			r2 = x;
			g2 = c;
		}
		else
		{
			r2 = c;
			g2 = x;
		}
		
		int r = int((r2 + m) * 255),
			g = int((g2 + m) * 255),
			b = int((b2 + m) * 255);
		
		Color col = Color(hsv.a, r, g, b);
		return col;
	}
	
	/*
	clearscope static Color RGBtoHSV(Color rgb)
	{
		
	}
	*/
	
	clearscope static string GetTimeString(double tics, int showMsecs = DeltaHud.SMT_ONLY_IF_NO_MINS)
	{
		let totalSeconds = tics / GameTicRate,
			iTotalSeconds = int(totalSeconds),
			timeHours = iTotalSeconds / 3600,
			timeMinutes = (iTotalSeconds / 60) % 60,
			timeSeconds = totalSeconds % 60;
		
		if (timeHours)
			return String.Format("%u:%02u:%02u", timeHours, timeMinutes, timeSeconds);
		
		if (showMsecs == DeltaHud.SMT_NEVER || (showMsecs == DeltaHud.SMT_ONLY_IF_NO_MINS && timeMinutes))
			return String.Format("%u:%02u", timeHours? timeHours : timeMinutes,
				timeHours? timeMinutes : timeSeconds);
		
		if (showMsecs == DeltaHud.SMT_ONLY_IF_NO_MINS && !timeMinutes)
			return String.Format("%2.2f", timeSeconds);
		
		if (timeSeconds >= 10)
			return String.Format("%u:%4.2f", timeMinutes, timeSeconds);
		return String.Format("%u:0%.2f", timeMinutes, timeSeconds);
	}
	
	// maintained for backwards compatibility, use TriggerPainChance
	play static void ForceActorPain(Actor a, Name mod)
	{
		a.TriggerPainChance(mod, true);
	}
	
	play static void StartHitstop(Actor originator, Array<Actor> affected, int tics = 7, bool flash = true)
	{
		if (!originator)
			return;
		
		originator.freezeTics = tics;
		
		if (flash)
		{
			originator.A_StartSound("delta/kris/shield_parry");
			if (originator.player)
				originator.A_SetBlend("white", 0.3, tics, "white", 0.15);
		}
		
		int count = affected.Size();
		if (!count)
			return;
		
		if (netgame)
		{
			for (int i = 0; i < count; i++)
			{
				affected[i].freezeTics = tics;
				if (affected[i].player && flash)
					affected[i].A_SetBlend("white", 0.3, tics, "white", 0.15);
			}
			
			return;
		}
		
		let iter = ThinkerIterator.Create();
		Actor act;
		
		while (act = Actor(iter.Next()))
		{
			act.freezeTics = tics;
			
			if (act.player && flash)
				act.A_SetBlend("white", 0.3, tics, "white", 0.15);
		}
	}
	
	play static void RollForParryExplosion(Actor parried,
		double explodeChance = 0.2, int hpThresholdExclusive = -20)
	{
		// don't affect RNG if this will nullify the call anyway
		if (parried.health >= hpThresholdExclusive)
			return;
		if (frandom[explodeChance](0, 1) > explodeChance)
			return;
		
		let exp = DeltaBadExplosion(Actor.Spawn("DeltaBadExplosion",
			level.Vec3Offset(parried.pos,
				(0, 0, GetDefaultByType(parried.GetClass()).height / 2.))));
		exp.master = parried;
		exp.scale = parried.scale;
	}
	
	// returns as [predicted angle, predicted pitch]
	play static double, double PredictTarget(Actor context, class<Actor> missile, double maxTurn = 0., double maxPitch = 0.)
	{
		if (!context)
			return 0, 0;
		if (!missile || !context.target)
			return context.angle, context.pitch;
		
		let targVel = context.target.vel,
			targDir = targVel == (0, 0, 0)? (0, 0, 0) : targVel.Unit(),
			dist = context.Distance3D(context.target),
			missSpd = Actor.GetDefaultSpeed(missile),
			targOffset = targDir * dist * ((missSpd == 0)? 0 : targVel.Length() / missSpd),
			coords = level.SphericalCoords(context.pos, context.target.pos + targOffset,
				(context.angle, context.pitch));
		
		let targetAngle = -coords.x,
			targetPitch = -coords.y;
		
		if (maxTurn != 0)
			targetAngle = clamp(targetAngle, -maxTurn, maxTurn);
		if (maxPitch != 0)
			targetPitch = clamp(targetPitch, -maxPitch, maxPitch);
		
		return context.angle + targetAngle, context.pitch + targetPitch;
	}
}

class DeltaSpriteCacher : Actor abstract
{
	States
	{
		Cache:
			KCGN A 1;
			KCSW A 1;
			KICN A 1;
			Stop;
	}
}

class DeltaDebugPositionMarker : Actor
{
	int lifeTime;
	double startAlpha;
	
	Default
	{
		RenderStyle "Stencil";
		Alpha 0.5;
		
		+NOBLOCKMAP
		+NOINTERACTION
		+FORCEXYBILLBOARD
	}
	
	States
	{
		Spawn:
			DTNC A -1 Bright;
			Stop;
	}
	
	override void Tick()
	{
		Super.Tick();
		
		if (lifeTime <= 0 || IsFrozen())
			return;
		
		lifeTime--;
		A_FadeOut(startAlpha / lifeTime);
	}
	
	static DeltaDebugPositionMarker SpawnMarker(Vector3 pos, int lifetime = -1, Color col = 0xffffffff, double alpha = 1.)
	{
		let marker = DeltaDebugPositionMarker(Spawn("DeltaDebugPositionMarker", pos));
		marker.SetShade(col);
		marker.A_SetRenderStyle(alpha, STYLE_TranslucentStencil);
		marker.startAlpha = alpha;
		marker.lifetime = lifetime;
		return marker;
	}
	
	clearscope static void SpawnMarkerClearscope(Vector3 pos, int lifetime = -1, Color col = 0xffffffff, double alpha = 1.)
	{
		let buffer = new("NetworkBuffer");
		buffer.AddVector3(pos);
		buffer.AddInt(lifetime);
		buffer.AddInt(col);
		buffer.AddDouble(alpha);
		EventHandler.SendNetworkBuffer("CreateDebugMarker", buffer);
	}
}

class DeltaHitscanGrazeChecker : LineTracer
{
	double fireLength;
	bool firstFire;
	Array<DeltaPlayer> grazed;
	
	protected Actor _source;
	protected DeltaPlayer _actualHit;
	
	static DeltaHitscanGrazeChecker Create()
	{
		return new("DeltaHitscanGrazeChecker").Init();
	}
	
	virtual DeltaHitscanGrazeChecker Init()
	{
		fireLength = 0;
		firstFire = false;
		grazed.Clear();
		_source = null;
		_actualHit = null;
		return self;
	}
	
	virtual void CheckHitscanGraze(Actor source, Vector3 attackPos,
		Vector3 hitPos)
	{
		_source = source;
		let diff = level.Vec3Diff(attackPos, hitPos),
			dir = diff.Unit(),
			epsilon = 16.;
		fireLength = diff.Length() + epsilon;
		firstFire = true;
		grazed.Clear();
		
		if (Trace(attackPos, source.curSector, dir, fireLength, TRACE_NoSky,
			Line.ML_BLOCKHITSCAN | Line.ML_BLOCKEVERYTHING, ignore: source))
		{
			if (results.HitType == TRACE_HitActor)
				_actualHit = DeltaPlayer(results.HitActor);
		}
		
		firstFire = false;
		
		double
			minOffs = -32,
			maxOffs = 32;
		int iterations = 8;
		
		for (double ofsSide = minOffs; ofsSide <= maxOffs; ofsSide += (maxOffs - minOffs) / iterations)
		{
			Vector3 actualPos = level.Vec3Offset(attackPos, DeltaUtil.GetActorRight(source) * ofsSide);
			Trace(actualPos, source.curSector, dir, fireLength, TRACE_NoSky,
				Line.ML_BLOCKHITSCAN | Line.ML_BLOCKEVERYTHING, ignore: source);
		}
	}
	
	override ETraceStatus TraceCallback()
	{
		if (firstFire)
			return TRACE_Stop;
		if (results.HitType != TRACE_HitActor)
			return TRACE_Stop;
		
		let ply = DeltaPlayer(results.HitActor);
		if (ply && ply != _actualHit && !_source.IsFriend(ply) && grazed.Find(ply) == grazed.Size())
		{
			grazed.Push(ply);
			return TRACE_Continue;
		}
		
		return TRACE_Skip;
	}
}