enum DeltaCrouchState
{
	CS_STANDING,
	CS_CROUCHING,
	CS_SLAMMING,
	CS_SLIDING
}

enum DeltaSoundChannels
{
	CHAN_HEALTH_SOUNDS = 6, // things like damage and healing sounds
	CHAN_HEARTBEAT = 7,
	CHAN_MOVEMENT = 8		// things like grinding sound when kris is sliding
}

enum DeltaMessageType
{
	MSG_TYPE_NORMAL,		// uses normal border
	MSG_TYPE_DARKWORLD		// uses dark world border
}

enum DeltaMessageState
{
	MSG_STATE_INITDELAY,	// initial delay before a message shows
	MSG_STATE_TYPING,		// actively typing
	MSG_STATE_HOLD			// whole message is shown
}

enum DeltaMessageInputResponse
{
	MSG_IGNORE,				// ignore input
	MSG_SKIP,				// skip to end of message
	MSG_FINISH				// finish message, move on to next thing
}

enum DeltaTpResult
{
	TP_FAIL,
	TP_USE,
	TP_INFINITE
}

enum DeltaPsp
{
	PSP_LEGS = -100,
	PSP_OFFHAND = -50
}

enum HeartbeatSetting
{
	HB_OFF,
	HB_ON,
	HB_KRIS_ONLY
}

enum DeltaRecoilType
{
	RECOIL_LAND,
	RECOIL_WEAPON,
	RECOIL_DAMAGE
}

enum DeltaCrosshairState
{
	DELTA_XHR_NEUTRAL,
	DELTA_XHR_FRIENDLY,
	DELTA_XHR_ENEMY
}

enum DeltaGrenadeType
{
	GRENADE_NORMAL,
	GRENADE_STICKY,
	GRENADE_CONTACT
}

enum DeltaWeaponAnimType
{
	DELTA_WEAPONANIM_MELEE,
	DELTA_WEAPONANIM_GUN,
	DELTA_WEAPONANIM_MAGIC
}