enum DeltaCrouchState
{
	CS_STANDING,
	CS_CROUCHING,
	CS_SLAMMING,
	CS_SLIDING
}

enum DeltaSoundChannels
{
	CHAN_HEALTH_SOUNDS = 6, // things like damage and healing sounds
	CHAN_HEARTBEAT = 7,
	CHAN_MOVEMENT = 8		// things like grinding sound when kris is sliding
}

enum DeltaVoicePriority
{
	VOX_LEAST_IMPORTANT,
	VOX_BREATHING,
	VOX_MOVEMENT,
	VOX_PAIN,
	VOX_DIALOGUE,
	VOX_DEATH,
	VOX_MOST_IMPORTANT
}

enum DeltaMessageType
{
	MSG_TYPE_NORMAL,		// uses normal border
	MSG_TYPE_DARKWORLD		// uses dark world border
}

enum DeltaMessageState
{
	MSG_STATE_INITDELAY = 0,	// initial delay before a message shows
	MSG_STATE_TYPING = 1,		// actively typing
	MSG_STATE_HOLD_INPUT = 2,	// message is finished, awaiting player input
	MSG_STATE_HOLD_SCRIPT = 3	// message is finished, awaiting dismissal from script
}

enum DeltaMessageInputResponse
{
	MSG_IGNORE,				// ignore input
	MSG_SKIP				// skip to end of message
}

enum DeltaTpResult
{
	TP_FAIL,
	TP_USE,
	TP_INFINITE
}

enum DeltaPsp
{
	PSP_LEGS = -100,
	PSP_OFFHAND = -50
}

enum HeartbeatSetting
{
	HB_OFF,
	HB_ON,
	HB_KRIS_ONLY
}

enum DeathCounterType
{
	DC_OFF,
	DC_LEVEL,
	DC_ENTIRE_RUN
}

enum SpeedrunStats
{
	SPD_OFF,
	SPD_TIMER,
	SPD_SPEED,
	SPD_BOTH
}

enum LevelStats
{
	LVLSTATS_OFF,
	LVLSTATS_INFO,
	LVLSTATS_KILLS_SECRETS,
	LVLSTATS_ALL
}

enum ShowMillisecondsType
{
	SMT_ONLY_IF_NO_MINS = -1,
	SMT_NEVER = 0,
	SMT_ALWAYS
}

enum DeltaRecoilType
{
	RECOIL_LAND,
	RECOIL_WEAPON,
	RECOIL_DAMAGE
}

enum DeltaCrosshairState
{
	DELTA_XHR_NEUTRAL,
	DELTA_XHR_FRIENDLY,
	DELTA_XHR_ENEMY
}

enum DeltaGrenadeType
{
	GRENADE_NORMAL,
	GRENADE_STICKY,
	GRENADE_CONTACT
}

enum DeltaWeaponAnimType
{
	DELTA_WEAPONANIM_MELEE,
	DELTA_WEAPONANIM_GUN,
	DELTA_WEAPONANIM_MAGIC
}

enum DeltaFootstepType
{
	FOOTSTEP_NONE,
	FOOTSTEP_BOOTS,
	FOOTSTEP_FLUFF,
	FOOTSTEP_HOOVES
}