// all our random static functions (mostly math related rn) go here
class DeltaUtil
{
	clearscope static double Lerp(double a, double b, double t, bool _clamp = true)
	{
		if (_clamp)
			t = Clamp(t, 0, 1);
		
		return a + ((b - a) * t);
	}
	
	clearscope static int Sign(double value)
	{
		if (value < 0)
			return -1;
		if (value > 0)
			return 1;
		
		return 0;
	}
	
	clearscope static Vector2 Vector2Lerp(Vector2 a, Vector2 b, double t, bool _clamp = true)
	{
		double
			x = Lerp(a.x, b.x, t, _clamp),
			y = Lerp(a.y, b.y, t, _clamp);
		
		return (x, y);
	}
	
	clearscope static Vector3 Vector3Lerp(Vector3 a, Vector3 b, double t, bool _clamp = true)
	{
		double
			x = Lerp(a.x, b.x, t, _clamp),
			y = Lerp(a.y, b.y, t, _clamp),
			z = Lerp(a.z, b.z, t, _clamp);
		
		return (x, y, z);
	}
	
	clearscope static Vector3 GetActorForward(Actor a, bool countPitch = true)
	{
		if (!a)
			return (0, 0, 0);
		
		let zOffset = countPitch ? cos(-a.pitch) : 1;
		return (zOffset*cos(a.angle), zOffset*sin(a.angle), countPitch ? sin(-a.pitch) : 0);
	}
	
	clearscope static Vector3 GetActorRight(Actor a, bool countRoll = false)
	{
		if (!a)
			return (0, 0, 0);
		
		let zOffset = countRoll ? cos(a.roll) : 1;
		return (zOffset*sin(a.angle), zOffset*-cos(a.angle), countRoll ? sin(a.roll) : 0);
	}
	
	clearscope static Vector3 GetActorUp(Actor a, bool countRoll = false)
	{
		if (!a)
			return (0, 0, 0);
		
		return GetActorForward(a) cross GetActorRight(a, countRoll);
	}
	
	clearscope static string GetTimeString(double tics, int showMsecs = SMT_ONLY_IF_NO_MINS)
	{
		int timeHours = tics / TICRATE / 3600;
		tics -= timeHours * TICRATE * 3600;
		int timeMinutes = tics / TICRATE / 60;
		tics -= timeMinutes * TICRATE * 60;
		int timeSeconds = floor(tics / TICRATE);
		
		if (timeMinutes == 60)
		{
			timeMinutes = 0;
			timeHours++;
		}
		
		if (timeSeconds == 60)
		{
			timeSeconds = 0;
			timeMinutes++;
		}
		
		if (showMsecs == SMT_NEVER || (showMsecs == SMT_ONLY_IF_NO_MINS && timeMinutes))
			return String.Format("%u:%02u", timeHours? timeHours : timeMinutes,
				timeHours? timeMinutes : timeSeconds);
		
		if (showMsecs == SMT_ONLY_IF_NO_MINS && !timeMinutes)
			return String.Format("%2.2f", tics / TICRATE);
		
		if (timeHours)
			return String.Format("%u:%02u:%02u", timeHours, timeMinutes,
				floor(tics / TICRATE));
		
		let remainder = tics / TICRATE;
		if (remainder >= 10)
			return String.Format("%u:%.2f", timeMinutes, tics / TICRATE);
		
		return String.Format("%u:0%.2f", timeMinutes, tics / TICRATE);
	}
	
	play static void ForceActorPain(Actor a, Name mod)
	{
		if (a.Health <= 0 || a.bNoPain)
			return;
		
		state pain = a.FindStateByString("Pain." .. mod);
		
		if (!pain)
			pain = a.ResolveState("Pain");
		if (!pain)
			return;
		
		a.SetState(pain);
	}
}

class DeltaSpriteCacher : Actor abstract
{
	States
	{
		Cache:
			KCGN A 1;
			KCSW A 1;
			Stop;
	}
}

class DeltaDebugPositionMarker : Actor
{
	int lifeTime;
	double startAlpha;
	
	Default
	{
		RenderStyle "Stencil";
		Alpha 0.5;
		
		+NOBLOCKMAP
		+NOINTERACTION
		+FORCEXYBILLBOARD
	}
	
	States
	{
		Spawn:
			DTNB A -1 Bright;
			Stop;
	}
	
	override void Tick()
	{
		Super.Tick();
		
		if (lifeTime <= 0 || IsFrozen())
			return;
		
		let cam = players[consolePlayer].camera;
		
		if (cam)
		{
			let sc = min(0.25, Distance3D(cam) / 200.);
			A_SetScale(sc);
		}
		
		lifeTime--;
		A_FadeOut(startAlpha / lifeTime);
	}
	
	static DeltaDebugPositionMarker SpawnMarker(Vector3 pos, int lifetime = -1, Color col = 0xffffffff, double alpha = 1.)
	{
		let marker = DeltaDebugPositionMarker(Spawn("DeltaDebugPositionMarker", pos));
		marker.SetShade(col);
		marker.A_SetRenderStyle(alpha, STYLE_TranslucentStencil);
		marker.startAlpha = alpha;
		marker.lifetime = lifetime;
		return marker;
	}
}

class DeltaHitscanGrazeChecker : LineTracer
{
	double fireLength;
	bool firstFire;
	Array<DeltaPlayer> _grazed;
	
	protected Actor _source;
	protected DeltaPlayer _actualHit;
	
	virtual void CheckHitscanGraze(Actor source, Vector3 attackPos,
		Vector3 hitPos)
	{
		_source = source;
		let diff = level.Vec3Diff(attackPos, hitPos),
			dir = diff.Unit();
		fireLength = diff.Length();
		firstFire = true;
		_grazed.Clear();
		
		if (Trace(attackPos, source.curSector, dir, fireLength, TRACE_NoSky,
			ignore: source))
		{
			if (results.HitActor)
				_actualHit = DeltaPlayer(results.HitActor);
			
			fireLength = results.distance;
		}
		
		firstFire = false;
		
		double
			minOffs = -32,
			maxOffs = 32;
		int iterations = 8;
		
		for (double ofsSide = minOffs; ofsSide <= maxOffs; ofsSide += (maxOffs - minOffs) / iterations)
		{
			Vector3 actualPos = level.Vec3Offset(attackPos, DeltaUtil.GetActorRight(source) * ofsSide);
			Trace(actualPos, source.curSector, dir, fireLength, TRACE_NoSky,
				ignore: source);
		}
	}
	
	override ETraceStatus TraceCallback()
	{
		if (firstFire)
			return TRACE_STOP;
		if (!results.HitActor)
			return TRACE_STOP;
		
		let ply = DeltaPlayer(results.HitActor);
		if (ply && ply != _actualHit && !_source.IsFriend(ply) && _grazed.Find(ply) == _grazed.Size())
		{
			_grazed.Push(ply);
			return TRACE_Continue;
		}
		
		return TRACE_Skip;
	}
}