class DeltaGlobals : StaticEventHandler
{
	protected string _curMapset; // using a string to make this more easily moddable
	// Strings we'll be using out of the box:
	// - default,
	// - LegacyOfRust,
	// - AncientAliens,
	// - BTSX1,
	// - BTSX2,
	// - BTSX3,
	// - Sunlust
	
	override void OnRegister()
	{
		if (_curMapset != "")
			return; // skip this if we already have the mapset we've loaded
		
		/*
			methodology borrowed from SevHUD, code found here:
			https://github.com/SeventhSentinel/sevhud/blob/master/zscript/SevHUD/SevHUD_mapset.zc
		*/
		_curMapset = "default";
		
		string checksum;
		
		if (LevelInfo.MapExists("MAP01"))
		{
			checksum = LevelInfo.MapChecksum("MAP01");
			
			if (checksum == "bf34c34c5dfc8bb47228cc304f9a6748")
				_curMapset = "LegacyOfRust";
			else if (checksum == "ff9c6545037c5e5e27ce0dacd24cdd37")
				_curMapset = "BTSX1";
			else if (checksum == "067cf96073db3cc4a8d887ee240f88da")
				_curMapset = "BTSX2";
			else if (checksum == "4efe4658dc515d0eac6b5b11e4c98ae5")
				_curMapset = "AncientAliens";
			else if (checksum == "56f7ec7f82136186fd133d644d36c28d")
				_curMapset = "Sunlust";
			else if (checksum == "6d1c95a2b07af77823c42500d96277c3")
				_curMapset = "NotEvenRemotelyFair";
		}
		
		Console.Printf("\n\c[DeltaRalsei]Mapset is " .. _curMapset
			.. "\nfirst map checksum: " .. checksum .. "\n\n");
	}
	
	clearscope string GetMapset()
	{
		return _curMapset;
	}
	
	clearscope static DeltaGlobals GetGlobals()
	{
		let globals = StaticEventHandler.Find("DeltaGlobals");
		if (!globals)
			return null;
		
		return DeltaGlobals(globals);
	}
	
	clearscope static DeltaLevelEvents GetLevelEvents()
	{
		let ev = EventHandler.Find("DeltaLevelEvents");
		if (!ev)
			return null;
		
		return DeltaLevelEvents(ev);
	}
}