struct GrazeEvent play version("2.4")
{
	PlayerPawn thing;
	Actor grazeSource;
}

struct DeltaDamageEvent
{
	Actor victim, source, inflictor;
	int amount;
	double height; // used for if victim is killed, and thus immediately reduces height
}

class DeltaEvents : EventHandler
{
	DeltaDamageEvent[300] damageEvents;
	Actor[100] reviving;
	
	override void WorldLoaded(WorldEvent e)
	{
		EnableNetworking(true);
	}
	
	override void WorldTick()
	{
		ReviveTick();
		DamageEventTick();
	}
	
	protected void DamageEventTick()
	{
		if (!damageEvents.Size())
			return;
		
		for (int i = 0; i < damageEvents.Size(); i++)
		{
			if (!damageEvents[i].victim)
				continue;
			if (damageEvents[i].amount <= 0)
				continue;
			
			if (damageEvents[i].victim is "DeltaPlayer")
			{
				if (damageEvents[i].victim.health <= 0)
				{
					let ded = DeltaDeadPopup.SpawnPopup("DeltaDeadPopup",
						damageEvents[i].victim, damageEvents[i].source, 5);
				}
				else
					DeltaDamagePopup.SpawnNumbers(damageEvents[i].victim,
						damageEvents[i].source, damageEvents[i].amount);
				
				EventHandler.SendInterfaceEvent(
					playerNum: damageEvents[i].victim.PlayerNumber(),
					name: "DeltaPlayerDamage",
					arg1 : damageEvents[i].source ?
						damageEvents[i].source.GetNetworkID() : 0,
					arg2 : damageEvents[i].inflictor ?
						damageEvents[i].inflictor.GetNetworkID() : 0,
					arg3: damageEvents[i].amount
				);
			}
			else
				DeltaDamagePopup.SpawnNumbers(damageEvents[i].victim,
					damageEvents[i].source, damageEvents[i].amount);
			
			damageEvents[i].victim = null;
			damageEvents[i].source = null;
			damageEvents[i].amount = 0;
		}
	}
	
	protected void ReviveTick()
	{
		if (!reviving.Size())
			return;
		
		for (int i = reviving.Size() - 1; i >= 0; i--)
		{
			Actor revivee = reviving[i];
			
			if (!revivee)
				continue;
			if (revivee.InStateSequence(revivee.curState, revivee.FindState("Raise")))
				continue;
			if (revivee.Health <= 0)
				continue;
			
			DeltaPopup.SpawnPopup("DeltaHealMaxPopup", revivee);
			revivee.A_StartSound("delta/heal", CHAN_AUTO);
			reviving[i] = null;
		}
	}
	
	override void WorldHitscanFired(WorldEvent e)
	{
		/*
		DeltaDebugPositionMarker.SpawnMarker(e.attackPos, TICRATE * 3, 0x00ff00, 1);
		DeltaDebugPositionMarker.SpawnMarker(e.damagePosition, TICRATE * 3, 0xff0000, 1);
		
		let diff = level.Vec3Diff(e.attackPos, e.damagePosition),
			dir = diff.Unit(),
			leng = diff.Length();
		double MARKER_DIST = 30.;
		
		for (double i = MARKER_DIST; i <= leng - MARKER_DIST/2; i += MARKER_DIST)
		{
			DeltaDebugPositionMarker.SpawnMarker(level.Vec3Offset(e.attackPos, dir * i), TICRATE * 3, 0xffff00, 0.5);
		}
		*/
		
		let check = new('DeltaHitscanGrazeChecker');
		if (!check)
			return;
		
		check.CheckHitscanGraze(e.thing, e.attackPos, e.damagePosition);
		
		for (int i = 0; i < check._grazed.Size(); i++)
		{
			GrazeEvent graze;
			graze.thing = check._grazed[i];
			graze.grazeSource = e.thing;
			PlayerGrazed(graze);
			
			let grazeAmount = max(5, e.inflictor.GetMissileDamage(0, 1));
			check._grazed[i].AddTension(grazeAmount * check._grazed[i].GetGrazeMultiplier(), true);
			check._grazed[i].A_StartSound("delta/graze", 5, 0);
		}
	}
	
	override void WorldThingRevived(WorldEvent e)
	{
		if (!e.thing)
			return;
		
		for (int i = 0; i < reviving.Size(); i++)
		{
			if (reviving[i])
				continue;
			
			reviving[i] = e.thing;
			return;
		}
		
		reviving[0] = e.thing;
	}
	
	override void WorldThingDamaged(WorldEvent e)
	{
		if (!e.thing || e.damage <= 0)
			return;
		
		for (int i = 0; i < damageEvents.Size(); i++)
		{
			if (damageEvents[i].victim == e.thing && damageEvents[i].source == e.damageSource)
			{
				damageEvents[i].amount += e.damage;
				break;
			}
			
			if (!damageEvents[i].victim)
			{
				damageEvents[i].victim = e.thing;
				damageEvents[i].source = e.damageSource;
				damageEvents[i].inflictor = e.inflictor;
				damageEvents[i].amount = e.damage;
				break;
			}
		}
		
		if (e.damageSource is "DeltaPlayer" && e.damageSource != e.thing
            && !e.damageSource.IsFriend(e.thing) && !(e.thing is "DeltaGrenade" || e.thing is "DeltaGrenadeHitbox"))
		{
			DeltaPlayer ply = DeltaPlayer(e.damageSource);
			
			if (!ply.GetDamageTics())
				ply.AddTension(e.damage / 8);
		}
	}
	
	override void PlayerDied(PlayerEvent e)
	{
		return;
		
		if (deathmatch)
			return;
		
		for (int i = 0; i < MAXPLAYERS; i++)
		{
			if (!playerInGame[i] || !players[i].mo)
				continue;
			if (players[i].mo.health > 0)
				return;
		}
		
		level.SetFrozen(true);
		S_StartSound("delta/hurt", CHAN_AUTO);
		
		for (int i = 0; i < MAXPLAYERS; i++)
		{
			if (!playerInGame[i] || !players[i].mo)
				continue;
			
			EventHandler.SendInterfaceEvent(i, "Died",
				Cvar.GetCvar("prgr_delta_diedFirstTime").GetBool());
		}
	}
	
	override void PlayerEntered(PlayerEvent e)
	{
		EventHandler.SendInterfaceEvent(e.playerNumber, "DeltaResetHUD");
	}
	
	override void PlayerRespawned(PlayerEvent e)
	{
		EventHandler.SendInterfaceEvent(e.playerNumber, "DeltaResetHUD");
	}
	
	override void InterfaceProcess(ConsoleEvent e)
	{
		if (e.IsManual || !(statusBar is "DeltaHud")) return;
		let hud = DeltaHud(statusBar);
		
		if (e.name ~== "DeltaResetHUD")
			hud.ResetHUD();
		else if (e.name ~== "DeltaPlayerDamage")
		{
			Actor source = Actor(GetNetworkEntity(e.args[0])),
				inflictor = Actor(GetNetworkEntity(e.args[1]));
			let amount = e.args[2];
			
			hud.CreateDamageIndicator(source, inflictor);
			hud.CreateDamagePopup(source, amount);
		}
		else if (e.name ~== "DeltaPlayerGraze")
		{
			let source = Actor(GetNetworkEntity(e.args[0]));
			hud.CreateGrazeIndicator(source);
		}
		else if (e.name ~== "DeltaAllPlayersDead")
		{
			
		}
	}
	
	virtual void PlayerGrazed(GrazeEvent e)
	{
		if (e.thing != e.grazeSource)
		{
			EventHandler.SendInterfaceEvent(e.thing.PlayerNumber(),
				"DeltaPlayerGraze",
				e.grazeSource ? e.grazeSource.GetNetworkID() : 0);
		}
	}
}

class DeltaTitleEvents : EventHandler
{
	protected Array<TextureID> _titleBackgrounds;
	private int _curTick, _curFrame, _frameDuration, _fadeDuration;
	
	virtual void SetUpTitles()
	{
		for (int i = 1; i <= 5; i++)
		{
			_titleBackgrounds.Push(TexMan.CheckForTexture("DELTATT" .. i));
		}
	}
	
	override void WorldLoaded(WorldEvent e)
	{
		_frameDuration = 15; // ticks per frame including fade duration
		_fadeDuration = _frameDuration; // ticks to fade between frames
		_curFrame = 0;
		SetUpTitles();
	}
	
	override void WorldTick()
	{
		if (!_titleBackgrounds.Size())
			return;
		
		_curTick++;
		
		if (_curTick != _frameDuration)
			return;
		
		_curTick = 0;
		_curFrame++;
		
		if (_curFrame == _titleBackgrounds.Size())
			_curFrame = 0;
	}
	
	override void RenderOverlay(RenderEvent e)
	{
		if (!_titleBackgrounds.Size())
			return;
		
		Screen.DrawTexture(_titleBackgrounds[_curFrame], false, 0, 0,
			DTA_Fullscreen, true, DTA_FullScreenScale, FSMode_ScaleToFill);
		
		if (!_fadeDuration) // make sure we're not dividing by zero
			return;
		
		int nextFrame = _curFrame == _titleBackgrounds.Size()-1 ? 0
			: _curFrame+1;
		double targetAlpha = max(0,
			(_fadeDuration - _frameDuration + _curTick + 1.) / _fadeDuration);
	
		Screen.DrawTexture(_titleBackgrounds[nextFrame], false, 0, 0,
			DTA_Fullscreen, true, DTA_FullScreenScale, FSMode_ScaleToFill,
			DTA_Alpha, targetAlpha);
	}
}