class DeltaMapsetCompat : StaticEventHandler
{
	protected string _curMapset; // using a string to make this more easily moddable
	// Strings we'll be using out of the box:
	// - default,
	// - LegacyOfRust,
	// - AncientAliens,
	// - BTSX1,
	// - BTSX2,
	// - BTSX3,
	// - Sunlust
	
	override void OnRegister()
	{
		if (_curMapset != "")
			return; // skip this if we already have the mapset we've loaded
		
		/*
			methodology borrowed from SevHUD, code found here:
			https://github.com/SeventhSentinel/sevhud/blob/master/zscript/SevHUD/SevHUD_mapset.zc
		*/
		_curMapset = "default";
		
		string checksum;
		
		if (LevelInfo.MapExists("MAP01"))
		{
			checksum = LevelInfo.MapChecksum("MAP01");
			
			if (checksum == "bf34c34c5dfc8bb47228cc304f9a6748")
				_curMapset = "LegacyOfRust";
			else if (checksum == "ff9c6545037c5e5e27ce0dacd24cdd37")
				_curMapset = "BTSX1";
			else if (checksum == "067cf96073db3cc4a8d887ee240f88da")
				_curMapset = "BTSX2";
			else if (checksum == "4efe4658dc515d0eac6b5b11e4c98ae5")
				_curMapset = "AncientAliens";
			else if (checksum == "56f7ec7f82136186fd133d644d36c28d")
				_curMapset = "Sunlust";
			else if (checksum == "6d1c95a2b07af77823c42500d96277c3")
				_curMapset = "NotEvenRemotelyFair";
		}
		
		Console.Printf("\n\c[DeltaRalsei]Mapset is " .. _curMapset
			.. "\nfirst map checksum: " .. checksum .. "\n\n");
	}
	
	override void WorldLoaded(WorldEvent e)
	{
		SetUpWorld();
	}
	
	protected virtual void SetUpWorld()
	{
		if (!level)
			return;
		
		int num = level.levelNum;
		
		if (_curMapset == "AncientAliens" && num == 30)
			Actor.Spawn("DeltaWeaponsAtEase");
		else if (_curMapset == "BTSX1" && (num == 8 || num == 16 || num == 23 || num == 25))
			Actor.Spawn("DeltaWeaponsAtEase");
		else if (_curMapset == "BTSX2" && (num == 5 || num == 11 || num == 16 || num == 23 || num == 27))
			Actor.Spawn("DeltaWeaponsAtEase");
	}
	
	override void CheckReplacement(ReplaceEvent e)
	{
		if (_curMapset ~== "LegacyOfRust")
		{
			if (e.replacee is "PlasmaRifle")
				e.replacement = "TempIncinerator";
			else if (e.replacee is "BFG9000")
				e.replacement = "TempCalamityBlade";
			else if (e.replacee is "Cell")
				e.replacement = "ID24Fuel";
			else if (e.replacee is "CellPack")
				e.replacement = "ID24FuelTank";
		}
		else
		{
			if (e.replacee is "PlasmaRifle")
				e.replacement = "TempPlasmaRifle";
			else if (e.replacee is "BFG9000")
				e.replacement = "TempBFG9000";
		}
	}
	
	clearscope static string Get()
	{
		let compat = StaticEventHandler.Find("DeltaMapsetCompat");
		if (!compat)
			return "";
		
		return DeltaMapsetCompat(compat)._curMapset;
	}
}