class DeltaSoul : Actor
{
	double alpha;
	PlayerInfo playerParent;
	const BASE_LINGER_TIME = floor(TICRATE * 0.75);
	const SOUL_SHARD_COUNT = 6;
	
	override void Tick()
	{
		Super.Tick();
		
		if (!playerParent)
			return;
		
		SetShade(cl_delta_changeSoulColor ? Cvar.GetCvar("user_delta_soulColor",
			playerParent).GetInt() : 0xffff0000);
	}
	
	Default
	{
		RenderStyle 'Stencil';
		+NOINTERACTION;
		+BRIGHT;
		+FORCEXYBILLBOARD;
	}
	
	States
	{
		Spawn:
			DRSL A random(BASE_LINGER_TIME - 5, BASE_LINGER_TIME + 5);
			DRSL B TICRATE A_StartSound("delta/soul_break", attenuation: 0.5);
			TNT1 A 0
			{
				A_StartSound("delta/soul_shatter", attenuation: 0.5);
				
				let ang = cfrandom(0, 89);
				for (int i = 0; i < 360; i += 360. / SOUL_SHARD_COUNT)
				{
					A_SpawnParticleEx(
						fillColor,											// Color
						TexMan.CheckForTexture("SSRDA0"),					// Texture
						STYLE_Normal,										// Style
						SPF_REPLACE | SPF_FULLBRIGHT | SPF_FACECAMERA |
							SPF_LOCAL_ANIM | SPF_RELVEL | SPF_RELPOS,		// Flags
						TICRATE * 2,										// Lifetime
						10, 												// Size
						ang + i + cfrandom(-3, 3),							// Angle offset
						0, 5, 0,											// Position offset
						cfrandom(-1, 1), cfrandom(-5, -4), cfrandom(3, 4),	// Initial velocity
						0, 0, -.5											// Acceleration
					);
				}
			}
			Stop;
	}
}