// all our random static functions (mostly math related rn) go here
class DeltaUtil
{
	clearscope static double Lerp(double a, double b, double t, bool _clamp = true)
	{
		if (_clamp)
			t = Clamp(t, 0, 1);
		
		return a + ((b - a) * t);
	}
	
	clearscope static double Clamp(double value, double min, double max)
	{
		if (max < min)
		{
			double temp = max;
			max = min;
			min = temp;
		}
		
		return max(min, min(max, value));
	}
	
	clearscope static int Sign(double value)
	{
		if (value < 0)
			return -1;
		if (value > 0)
			return 1;
		
		return 0;
	}
	
	clearscope static Vector2 Vector2Lerp(Vector2 a, Vector2 b, double t, bool _clamp = true)
	{
		double
			x = Lerp(a.x, b.x, t, _clamp),
			y = Lerp(a.y, b.y, t, _clamp);
		
		return (x, y);
	}
	
	clearscope static Vector3 Vector3Lerp(Vector3 a, Vector3 b, double t, bool _clamp = true)
	{
		double
			x = Lerp(a.x, b.x, t, _clamp),
			y = Lerp(a.y, b.y, t, _clamp),
			z = Lerp(a.z, b.z, t, _clamp);
		
		return (x, y, z);
	}
	
	clearscope static Vector3 GetActorForward(Actor a, bool countPitch = true)
	{
		if (!a)
			return (0, 0, 0);
		
		let zOffset = countPitch ? cos(a.pitch) : 1;
		return (zOffset*cos(a.angle), zOffset*sin(a.angle), countPitch ? sin(a.pitch) : 0);
	}
	
	clearscope static Vector3 GetActorRight(Actor a, bool countRoll = false)
	{
		if (!a)
			return (0, 0, 0);
		
		let zOffset = countRoll ? cos(a.roll) : 1;
		return (zOffset*sin(a.angle), zOffset*cos(a.angle), countRoll ? sin(a.roll) : 0);
	}
	
	clearscope static Vector3 GetActorUp(Actor a, bool countRoll = false)
	{
		if (!a)
			return (0, 0, 0);
		
		return GetActorForward(a) cross GetActorRight(a, countRoll);
	}
	
	play static void ForceActorPain(Actor a)
	{
		if (a.Health <= 0 || a.bNoPain)
			return;
		
		state pain = a.ResolveState("Pain.Parry");
		
		if (!pain)
			pain = a.ResolveState("Pain");
		if (!pain)
			return;
		
		a.SetState(pain);
	}
}

class DeltaSpriteCacher : Actor abstract
{
	States
	{
		Cache:
			KCGN A 1;
			KCSW A 1;
			Stop;
	}
}