class DeltaBadExplosion : Actor
{
	protected Vector3 ofs;
	
	Default
	{
		+NOINTERACTION
		+SQUAREPIXELS
		+BRIGHT
		+FORCEXYBILLBOARD
	}
	
	States
	{
		Spawn:
			TNT1 A 3;
			BDEX A 3 A_StartSound("delta/generic_badExplosion",
				flags: CHANF_OVERLAP, attenuation: ATTN_NONE);
			BDEX BCDEFGHIJKLMNOPQ 3;
			Stop;
	}
	
	override void PostBeginPlay()
	{
		Super.PostBeginPlay();
		
		if (master)
			ofs = level.Vec3Diff(master.pos, pos);
	}
	
	override void Tick()
	{
		Super.Tick();
		
		if (!master)
			return;
		
		SetOrigin(level.Vec3Offset(master.pos, ofs), true);
	}
}