class DeltaTrail : Actor
{
	int fadeInTime, holdTime, fadeTime;
	protected int time;
	protected double targetAlpha;
	
	property FadeInTime: fadeInTime;
	property TargetAlpha: targetAlpha;
	property HoldTime: holdTime;
	property FadeTime: fadeTime;
	
	Default
	{
		Speed 2;
		Alpha 0;
		StencilColor "ffffff";
		RenderStyle "Add";
		
		DeltaTrail.FadeInTime 5;
		DeltaTrail.TargetAlpha 1;
		DeltaTrail.HoldTime 0;
		DeltaTrail.FadeTime 15;
		
		+NOINTERACTION;
		+SQUAREPIXELS;
		+MASTERNOSEE;
	}
	
	States
	{
		Spawn:
			#### # 1;
			Wait;
	}
	
	override void PostBeginPlay()
	{
		if (!master)
			Destroy();
		
		sprite = master.sprite;
		frame = master.frame;
		if (holdTime < 0)
			holdTime = 0;
		
		SetOrigin(master.pos, false);
		angle = master.angle;
		vel = DeltaUtil.GetActorForward(master, false) * -speed;
	}
	
	override void Tick()
	{
		Super.Tick();
		if (IsFrozen())
			return;
		
		if (!holdTime)
		{
			A_FadeOut(targetAlpha / fadeTime, FTF_REMOVE | FTF_CLAMP);
			return;
		}
		
		if (alpha < targetAlpha)
		{
			alpha += targetAlpha / fadeInTime;
			if (alpha > targetAlpha)
				alpha = targetAlpha;
			
			return;
		}
		
		holdTime--;
	}
	
	static DeltaTrail SpawnTrail(class<DeltaTrail> trail, Vector3 pos)
	{
		return DeltaTrail(Spawn(trail, pos));
	}
}

class DeltaRainbowTrail : DeltaTrail
{
	Default
	{
		Alpha 0.75;
		RenderStyle "AddStencil";
	}
	
	override void PostBeginPlay()
	{
		let hue = (level.time*2) % 255,
			col = Color(255, hue, 192, 255);
		SetShade(DeltaUtil.HSVtoRGB(col));
		
		Super.PostBeginPlay();
	}
}