class DeltaSoul : Actor
{
	double alpha;
	PlayerInfo playerParent;
	Color defaultColor;
	protected double prevZ;
	const BASE_LINGER_TIME = floor(TICRATE * 0.75);
	const SOUL_SHARD_COUNT = 6;
	
	Default
	{
		Radius 8;
		Height 15;
		RenderStyle 'Stencil';
		StencilColor "ff 00 00";
		
		+NOBLOCKMAP
		+MOVEWITHSECTOR
		+RELATIVETOFLOOR
		+NOGRAVITY
		+BRIGHT
		+FORCEXYBILLBOARD
	}
	
	States
	{
		Spawn:
			DRSL A random(BASE_LINGER_TIME - 3, BASE_LINGER_TIME + 3);
			DRSL B TICRATE-1 A_StartSound("delta/soul_break", attenuation: 0.5);
			DRSL B 1
			{
				invoker.prevZ = prev.z;
			}
		SoulBreak:
			TNT1 A 0
			{
				A_StartSound("delta/soul_shatter", attenuation: 0.5);
				
				let ang = cfrandom(0, 89);
				for (int i = 0; i < 360; i += 360. / SOUL_SHARD_COUNT)
				{
					A_SpawnParticleEx(
						fillColor,											// Color
						TexMan.CheckForTexture("SSRDA0"),					// Texture
						STYLE_Normal,										// Style
						SPF_REPLACE | SPF_FULLBRIGHT | SPF_FACECAMERA |
							SPF_LOCAL_ANIM | SPF_RELVEL | SPF_RELPOS,		// Flags
						TICRATE * 2,										// Lifetime
						10, 												// Size
						ang + i + cfrandom(-3, 3),							// Angle offset
						0, 5, 0,											// Position offset
						cfrandom(-1, 1), cfrandom(-5, -4),
							cfrandom(3, 4) + pos.z - invoker.prevZ,			// Initial velocity
						0, 0, -.5											// Acceleration
					);
				}
			}
			Stop;
	}
	
	override void BeginPlay()
	{
		Super.BeginPlay();
		defaultColor = fillColor;
	}
	
	override void Tick()
	{
		Super.Tick();
		SetSoulColor();
		
		if (curState && curState.InStateSequence(SpawnState))
			CheckSoulCrush();
	}
	
	virtual void SetSoulColor()
	{
		Color col = defaultColor;
		if (playerParent && cl_delta_changeSoulColor)
			col = Cvar.GetCvar("user_delta_soulColor", playerParent).GetInt();
		
		SetShade(col);
	}
	
	virtual void CheckSoulCrush()
	{
		if (abs(ceilingZ - floorZ) < height)
			SetState(ResolveState("SoulBreak"));
	}
}