struct RecoilEvent
{
	Vector3 recoil;
	int startTime, curTime, leadInTime;
	int recoilType; // DeltaRecoilType
}

class DeltaPlayer : PlayerPawn abstract
{
	enum DeltaCrosshairState
	{
		DELTA_XHR_NEUTRAL,
		DELTA_XHR_FRIENDLY,
		DELTA_XHR_ENEMY
	}
	enum DeltaCrouchState
	{
		CS_STANDING,
		CS_CROUCHING,
		CS_SLAMMING,
		CS_SLIDING
	}
	enum DeltaTpResult
	{
		TP_FAIL,
		TP_USE,
		TP_INFINITE
	}
	enum DeltaPsp
	{
		PSP_LEGS = -100,
		PSP_OFFHAND = -50
	}
	enum HeartbeatSetting
	{
		HB_OFF,
		HB_ON,
		HB_LIGHTNERS_ONLY
	}
	enum DeltaRecoilType
	{
		RECOIL_LAND,
		RECOIL_WEAPON,
		RECOIL_DAMAGE
	}
	enum DeltaWeaponAnimType
	{
		DELTA_WEAPONANIM_MELEE,
		DELTA_WEAPONANIM_GUN,
		DELTA_WEAPONANIM_MAGIC
	}
	enum DeltaFootstepType
	{
		FOOTSTEP_NONE,
		FOOTSTEP_BOOTS,
		FOOTSTEP_FLUFF,
		FOOTSTEP_HOOVES
	}
	enum DeltaVoicePriority
	{
		VOX_LEAST_IMPORTANT = -1,	// overriden by anything, overrides nothing
		VOX_BREATHING = 0,
		VOX_MOVEMENT = 10,			// jump/landing grunts, etc.
		VOX_PAIN = 20,				// damage grunts
		VOX_DIALOGUE = 30,			// dialogue for taunts, story, etc.
		VOX_DEATH = 40,				// shut the character the fuck up if they die
		VOX_MOST_IMPORTANT			// overrides all default voice priorities
	}
	
	const COYOTE_TIME = 3;
	const JUMP_BUFFER_TIME = 3;
	const ANIM_GROUNDED_HANG_TIME = 3;
	const MAX_AIR_BOB_TICS = 7;
	const DELTA_AIR_CONTROL = 0.4;
	const DAMAGE_IFRAMES = 10;
	const DRAIN_TIMER_START = TICRATE * 12;			// tp lasts for 12 seconds before we start draining it
	const DRAIN_AMOUNT = 5./TICRATE;
	const DRAIN_GRACE_TICS = 3;						// if we try to call for TP and it's drained below what we need for only a few ticks, let us use it anyway
	const MAX_GRAZE_TICS = 5;
	const DEFAULT_RED_CROSSHAIR_RANGE = 500.;
	const MAX_TURN = 10;
	const DEATH_HANG_FRAMES = TICRATE;
	
	double tensionPoints, maxTensionPoints, bobTimer;
	int grazeTics, tensionDrainTimer, hugReactionTime;
	bool beingHugged, canRespawn;
	
	protected int coyoteTimer; 						// used to handle coyote time
	protected int jumpBuffer, airBobTics, hugTimer;
	protected double customBobPerc;
	protected int damageTics; 						// invulnerability frames, essentially
	protected int lastDamageTaken;
	protected int deathTimer; 						// used for first person death animation
	protected double deathPitchFP, deathPitchTP;
	protected DeltaCrouchState crouchState;
	
	protected double flinchMultiplier;				// wanna be able to make certain characters flinch more or flinch less at incoming damage
	protected int startFlinchTics;
	protected int shakinessMaxHealth;				// lowest possible health where we'll still be at minimum hand shakiness
	protected double minShakiness, maxShakiness;
	protected int oldShakiness;						// used for interpolation
	protected string backAtYouObituary, parryObituary;
	
	protected Array<Actor> grazed;
	
	protected string characterIcon, nameTag, automapIcon;
	protected Color characterColor, overhealColor;
	
	protected LinearValueInterpolator heartbeat, shakiness;
	protected bool didFirstDeathAnim, blind;
	
	protected double angleDiff;
	
	protected state
		SpawnGunState,				SpawnMeleeState,		SpawnMagicState,
		SeeGunState,				SeeMeleeState, 			SeeMagicState,
		PainGunState,				PainMeleeState, 		PainMagicState,
		MissileGunState,			MissileMeleeState, 		MissileMagicState,
		MissileGunNoFlashState,		FinishMissileGunState,
		AirGunState,				AirMeleeState,			AirMagicState,
		AirMissileGunState,			AirMissileMeleeState, 	AirMissileMagicState,
		AirMissileGunNoFlashState,	AirFinishMissileGunState,
		AirPainGunState,			AirPainMeleeState,		AirPainMagicState,
		AirDeathState;
	protected DeltaWeaponAnimType lastAnimType;
	
	protected string
		gunStandSprite, meleeStandSprite, magicStandSprite,
		gunCrouchSprite, meleeCrouchSprite, magicCrouchSprite;
	protected double crouchFactor;
	
	private double _targetRoll;
	private bool _frozenDeath;				// using this for custom ice death that doesn't automatically shatter us lol
	
	private Vector2 _desiredMove, _move;
	
	private Vector2 _currentFlinch;			// used for weapon flinching when taking damage
	private int _flinchTics;
	
	private Vector2 _lastBob;				// saving weapon position for hitstops or when we die
	
	private double _oldTurn, _turn;
	private double _originalHeight;			// used for fixing compatibility issues with maps (mainly Boom maps) that use voodoo doll scripting
	
	private TextureID _characterIconId;		// used for health displays in co-op and team deathmatch
	private TextureID _nameTagId;			// used for character name display in HUD
	private int _automapIcon;
	
	private DeltaCrosshairState _crosshairState;
	
	private RecoilEvent[10] _recoils;
	private double _landPunch, _deltaLandPunch;
	
	private Array<Name> _dynamicLights;
	private PlayerInfo _savedPlayer;
	private Weapon _savedPending;
	
	// Damage types that ignore I-frames.
	static const Name DAMAGE_TYPES_IGNORE_IFRAMES[] =
	{
		'Crush',
		'Telefrag',
		'Falling',
		'Suicide',
		'Exit',
		'Poison'
	};
	
	property HugReactionTime: hugReactionTime;
	property CharacterColor: characterColor;		// mostly used for hud elements
	property OverhealColor: overhealColor;			// used for overheal bar on hud
	property FlinchMultiplier: flinchMultiplier;
	property StartFlinchTics: startFlinchTics;
	property LungeSpeed: lungeSpeed;
	property OffhandIcon: offhandIcon;
	property OffhandTpCost: offhandTpCost;
	property CharacterIcon: characterIcon;
	property NameTag: nameTag;
	property AutomapIcon: automapIcon;
	property GunStandSprite: gunStandSprite;
	property MeleeStandSprite: meleeStandSprite;
	property MagicStandSprite: magicStandSprite;
	property GunCrouchSprite: gunCrouchSprite;
	property MeleeCrouchSprite: meleeCrouchSprite;
	property MagicCrouchSprite: magicCrouchSprite;
	property ShakinessMaxHealth: shakinessMaxHealth;
	property MinShakiness: minShakiness;
	property MaxShakiness: maxShakiness;
	property BackAtYouObituary: backAtYouObituary;	// used specifically if we kill by parrying a projectile back into its original owner
	property ParryObituary: parryObituary;			// used if we kill by parrying otherwise
	
	Default
	{
		Health 200;
		Player.MaxHealth 200;
		Radius 16;
		Speed 0.8;
		Mass 100;
		
		PainChance 256;
		Player.MugShotMaxHealth -1;
		
		Player.DisplayName "DeltaPlayer";
		Player.SoundClass "delta";
		Player.ViewHeight 32.0;
		
		// strafing should be same speed as moving forward
		Player.ForwardMove 1, 1;
		Player.SideMove 1.0416667, 1.25;
		
		Player.AttackZOffset 12;
		Player.JumpZ 12;
		Player.GruntSpeed 3;
		Player.ViewBob 0.3;
		Player.ViewBobSpeed 12;
		Player.FlyBob 0;
		
		DeltaPlayer.HugReactionTime 20;
		DeltaPlayer.CharacterColor Color(127, 127, 127);
		DeltaPlayer.OverhealColor Color(60, 220, 60);
		
		DeltaPlayer.FlinchMultiplier 10;
		DeltaPlayer.StartFlinchTics 5;
		DeltaPlayer.LungeSpeed 45;
		
		DeltaPlayer.OffhandIcon "";
		DeltaPlayer.OffhandTpCost 0;
		
		DeltaPlayer.CharacterIcon "";
		DeltaPlayer.NameTag "";
		DeltaPlayer.AutomapIcon "";
		DeltaPlayer.GunCrouchSprite "";
		DeltaPlayer.MeleeCrouchSprite "";
		DeltaPlayer.MagicCrouchSprite "";
		
		DeltaPlayer.ShakinessMaxHealth 80;
		DeltaPlayer.MinShakiness 0.2;
		DeltaPlayer.MaxShakiness 1;
		
		DeltaPlayer.BackAtYouObituary "$OBIT_DELTA_KPARRYBACK";
		DeltaPlayer.ParryObituary "$OBIT_DELTA_KPARRY";
		
		DeltaPlayer.FootstepType FOOTSTEP_NONE;
		DeltaPlayer.FootstepTime 10;
		DeltaPlayer.VoiceClass "";
		DeltaPlayer.JumpGruntChance 0.; // 0% chance by default, meant to get
										// people to change this
		
		+NOICEDEATH;
		+FLOORCLIP;
		+DONTGIB;
		+SQUAREPIXELS;
		+PLAYERPAWN.NOTHRUSTWHENINVUL;
	}
	
	States
	{
		Spawn:
			TNT1 A 1;
			Loop;
		See:
			TNT1 A 1;
			Loop;
	}
	
	States (Overlay)
	{
		// ====================
		//   OFFHAND OVERLAYS  
		// ====================
		OffhandOverlay:
			TNT1 A 0 A_EndOffhand;
			Stop;
		
		// ================
		//   LEG OVERLAYS
		// ================
		IdleLegs:
			TNT1 A 1;
			Loop;
		WalkLegs:
			TNT1 A 3;
			TNT1 A 2;
		WalkLoopLegs:
			TNT1 A -1;
			Loop;
		CrouchWalkLegs:
			TNT1 A 3;
			TNT1 A 2;
		CrouchWalkLoopLegs:
			TNT1 A -1;
			Loop;
		RunLegs:
			TNT1 A 3;
		RunLoopLegs:
			TNT1 A -1;
			Loop;
		AirLegs:
			TNT1 A 1;
			Loop;
	}
	
	override void BeginPlay()
	{
		_originalHeight = height;
		height = 56;
		crouchFactor = 1;
		_savedPending = WP_NOCHANGE;
		
		Super.BeginPlay();
		ApplyDifficultyModifiers();
		
		// load icon textures before we do (most of) the rest of our initialization
		_offhandIconId = TexMan.CheckForTexture(offhandIcon);
		_characterIconId = TexMan.CheckForTexture(characterIcon);
		_nameTagId = TexMan.CheckForTexture(nameTag);
		_automapIcon = GetSpriteIndex(automapIcon);
		
		// grab our states
		AirGunState = FindState("AirGun");
		AirMeleeState = FindState("AirMelee");
		AirMagicState = FindState("AirMagic");
		SpawnGunState = FindState("SpawnGun");
		SpawnMeleeState = FindState("SpawnMelee");
		SpawnMagicState = FindState("SpawnMagic");
		SeeGunState = FindState("SeeGun");
		SeeMeleeState = FindState("SeeMelee");
		SeeMagicState = FindState("SeeMagic");
		MissileGunState = FindState("MissileGun");
		MissileMeleeState = FindState("MissileMelee");
		MissileMagicState = FindState("MissileMagic");
		MissileGunNoFlashState = FindState("MissileGunNoFlash");
		FinishMissileGunState = FindState("FinishMissileGun");
		AirMissileGunState = FindState("AirMissileGun");
		AirMissileMeleeState = FindState("AirMissileMelee");
		AirMissileMagicState = FindState("AirMissileMagic");
		AirMissileGunNoFlashState = FindState("AirMissileGunNoFlash");
		AirFinishMissileGunState = FindState("AirFinishMissileGun");
		PainGunState = FindState("PainGun");
		PainMeleeState = FindState("PainMelee");
		PainMagicState = FindState("PainMagic");
		AirPainGunState = FindState("AirPainGun");
		AirPainMeleeState = FindState("AirPainMelee");
		AirPainMagicState = FindState("AirPainMagic");
		AirDeathState = FindState("AirDeath");
	}
	
	override void PostBeginPlay()
	{
		Super.PostBeginPlay();
		
		if (player != NULL && player.mo == self)
		{
			// fixing issues with Boom maps that make use of voodoo dolls and conveyor belts
			fullHeight = _originalHeight;
			height = _originalHeight;
			
			if (!netgame && data_delta_respawningFromDeath)
			{
				if (data_delta_previousMap != level.mapName)
				{
					CVar.FindCVar("data_delta_currentDeathsLevel").SetInt(0);
					CVar.FindCVar("data_delta_currentDeathsSngSeg").SetInt(0);
				}
				
				CVar.FindCVar("data_delta_respawningFromDeath").SetBool(false);
			}
			else
			{
				CVar.FindCVar("data_delta_currentDeathsLevel").SetInt(0);
				CVar.FindCVar("data_delta_currentDeathsSngSeg").SetInt(0);
			}
		}
		
		CVar.FindCVar("data_delta_previousMap").SetString(level.mapName);
		coyoteTimer = 0;
		jumpBuffer = 0;
		grazeTics = 0;
		hugTimer = 0;
		deathTimer = -1;
		tensionPoints = 0;
		maxTensionPoints = 250;
		tensionDrainTimer = 0;
		airBobTics = 0;
		beingHugged = false;
		lunging = false;
		isUsingOffhand = false;
		customBobPerc = 1.;
		_turn = 0;
		_oldTurn = 0;
		_targetRoll = 0;
		canRespawn = true;
		SetUpLegs();
		
		if (player && player.ReadyWeapon && player.ReadyWeapon is "DeltaWeapon")
			DeltaWeapon(player.ReadyWeapon).A_ResetAtEase();
		
		if (_automapIcon != -1 && !IsVoodooDoll())
			DeltaPlayerMarker.Create(self);
	}
	
	override void Travelled()
	{
		Super.Travelled();
		
		coyoteTimer = 0;
		jumpBuffer = 0;
		grazeTics = 0;
		hugTimer = 0;
		tensionPoints = 0;
		tensionDrainTimer = 0;
		airBobTics = 0;
		beingHugged = false;
		lunging = false;
		isUsingOffhand = false;
		_turn = 0;
		_oldTurn = 0;
		
		_targetRoll = 0;
		SetUpLegs();
		
		if (!netgame)
			CVar.FindCVar("data_delta_currentDeathsLevel").SetInt(0);
		
		if (player && player.ReadyWeapon && player.ReadyWeapon is "DeltaWeapon")
			DeltaWeapon(player.ReadyWeapon).A_ResetAtEase();
		
		if (_automapIcon != -1)
			DeltaPlayerMarker.Create(self);
	}
	
	override void Tick()
	{
		Actor.Tick();
		HandleIFrames();
		
		if (IsFrozen())
			return;
		
		if (!IsPredicting())
		{
			if (Health <= 0)
				AnimateDeath();
			
			TickFootsteps();
			TickVoice();
		}
		
		if (!IsVoodooDoll() && CanCrouch() && player.playerstate != PST_DEAD)
			Height = FullHeight * crouchFactor;
		else if (health > 0)
			Height = FullHeight;
	}
	
	virtual void AnimateDeath()
	{
		let deathState = IsGrounded()? ResolveState("Death")
			: ResolveState("AirDeath");
		if (curState.InStateSequence(deathState)
			|| (IsGrounded() && curState.InStateSequence(ResolveState("FinishDeath"))))
			return;
		
		SetStateSafe(deathState);
	}
	
	override void PlayerThink()
	{
		if (player.inventoryTics == 5*TICRATE)
			player.inventoryTics = 1;
		
		Super.PlayerThink();
		HandleViewAngles();
		HandleLegs();
		HandlePowerupEffects();
		
		if (IsPredicting())
			return;
		
		HandleHeartbeat();
		
		if (player.PlayerState == PST_DEAD)
			return;
		if (deathTimer >= 0)
			deathTimer = -1;
		if (grazeTics)
			grazeTics--;
		
		AnimatePlayer();
		HandleFlinch();
		HandleHandedness();
		HandleCrosshair();
		HandleLunging();
		DrainTension();
		HandleRalseiHugs();
		HandleAirStuff();
		CheckGraze();
	}
	
	// grabbing code from uzdoom.pk3 and retooling some of it
	override void TickPSprites()
	{
		if (IsFrozen())
			return;
		
		Super.TickPSprites();
		HandleBlindness();
	}
	
	// grabbing code from uzdoom.pk3 and retooling for cleaner, snappier feeling
	override void MovePlayer()
	{
		if (!player)
			return;
		
		UserCmd cmd = player.cmd;
		
		if (!lunging)
		{
			// [RH] 180-degree turn overrides all other yaws
			if (player.turnTicks)
			{
				player.turnTicks--;
				angleDiff = (180. / TURN180_TICKS);
				A_SetAngle(Angle + angleDiff, SPF_INTERPOLATE);
			}
			else
			{
				angleDiff = cmd.yaw * (360./65536.);
				Angle += angleDiff;
			}
			
			_oldTurn = _turn;
			if (abs(_turn) > 0.5)
				_turn /= 2;
			else
				_turn = 0;
			
			_turn = clamp(_turn + angleDiff*0.2, -MAX_TURN, MAX_TURN);
		}
		
		player.onGround = !(player.cheats & (CF_NOCLIP2|CF_FLY)) && pos.z <= floorZ;
		double perc = 1 - airBobTics*1. / MAX_AIR_BOB_TICS;
		
		// killough 10/98:
		//
		// We must apply thrust to the player and bobbing separately, to avoid
		// anomalies. The thrust applied to bobbing is always the same strength on
		// ice, because the player still "works just as hard" to move, while the
		// thrust applied to the movement varies with 'moveFactor'.
		let [friction, moveFactor] = GetFriction();
		let bobFactor = friction < ORIG_FRICTION ? moveFactor : ORIG_FRICTION_FACTOR;
		bobFactor *= perc * perc;
		
		let [fm, sm] = TweakSpeeds (cmd.forwardMove, cmd.sideMove);
		fm *= Speed / 256;
		sm *= Speed / 256;
		
		if (!player.onGround && !bNoGravity && !waterlevel)
		{
			ApplyAirControl(moveFactor, bobFactor);
			
			let airFriction = level.airFriction,
				oldXY = vel.xy;
			
			if (!fm && !sm && airFriction != 0)
			{
				vel.x /= airFriction;
				vel.y /= airFriction;
				
				if (player.mo == self)
					player.vel /= airFriction;
			}
		}
		
		// When crouching, speed and bobbing have to be reduced
		if (CanCrouch() && crouchFactor != 1)
		{
			fm *= crouchFactor;
			sm *= crouchFactor;
			bobFactor *= crouchFactor;
		}
		
		let forwardMove = fm * moveFactor * (35. / GameTicRate),
			sideMove = sm * moveFactor * (35. / GameTicRate);
		
		if ((cmd.forwardMove | cmd.sideMove) && player.cheats & CF_REVERTPLEASE)
		{
			player.cheats &= ~CF_REVERTPLEASE;
			player.camera = player.mo;
		}
		
		if (lunging)
		{
			player.vel = (0, 0);
			return;
		}
		
		let slowFactor = 0.2 * moveFactor/ORIG_FRICTION_FACTOR,
			applySlowing = player.onGround && vel.Length() <= 10.,
			spec = curSector.special;
		
		if (applySlowing && pos.z == curSector.floorPlane.ZatPoint(pos.xy))
		{
			if ((spec >= 40 && spec <= 51) || spec == 84 || spec == 118 ||
				(spec >= 201 && spec <= 244) || spec == 4096)
			{
				applySlowing = false;
			}
			else
			{
				let events = DeltaGlobals.GetLevelEvents();
				
				if (events)
				{
					for (int i = 0; i < curSector.CountTags(); i++)
					{
						if (events.scrollTags.Find(curSector.GetTag(i)) != events.scrollTags.Size())
						{
							applySlowing = false;
							break;
						}
					}
				}
			}
		}
		
		if (forwardMove)
		{
			Bob(Angle, cmd.forwardMove * bobFactor / 256., true);
			ForwardThrust(forwardMove, Angle);
		}
		else if (applySlowing)
		{
			let fwd = DeltaUtil.GetActorForward(self);
			Bob(Angle, -vel.xy dot fwd.xy * slowFactor, true);
			ForwardThrust(-vel.xy dot fwd.xy * slowFactor, Angle);
		}
		
		let a = Angle - 90;
		
		if (sideMove)
		{
			Bob(a, cmd.sideMove * bobFactor / 256., false);
			Thrust(sideMove, a);
		}
		else if (applySlowing)
		{
			let right = DeltaUtil.GetActorRight(self);
			
			Bob(a, -vel.xy dot right.xy * slowFactor, false);
			ForwardThrust(-vel.xy dot right.xy * slowFactor, a);
		}
	}
	
	override int TakeSpecialDamage(Actor inflictor, Actor source, int damage, Name mod)
	{
		let oldDmg = Super.TakeSpecialDamage(inflictor, source, damage, mod);
		if (!source || source.player)
			return oldDmg;
		
		foreach (ignore : DAMAGE_TYPES_IGNORE_IFRAMES)
		{
			if (mod == ignore)
				return oldDmg;
		}
		
		let dmg = (damage + lastDamageTaken) * 1.,
			healthBeforeDmg = Health + lastDamageTaken;
		
		// if we're at 80 or more HP, damage cannot be lethal
		if (healthBeforeDmg >= 80 && dmg >= Health)
			dmg = Health - 1;
		
		return int(dmg);
	}
	
	override int DamageMobj(Actor inflictor, Actor source, int damage, Name mod, int flags, double angle)
	{
		bool ignoreIFrames;
		
		if (flags & DMG_FORCED || (source && source.player))
			ignoreIFrames = true;
		else foreach (damageType : DAMAGE_TYPES_IGNORE_IFRAMES)
		{
			if (mod == damageType)
			{
				ignoreIFrames = true;
				break;
			}
		}
		
		if (_frozenDeath && mod != "Ice")
		{
			Vel = (0, 0, 0);
			A_FreezeDeathChunks();
		}	
		
		if (damageTics > 0 && !ignoreIFrames)
			return 0;
		
		int finalDamage = Super.DamageMobj(inflictor, source, damage, mod, flags, angle);
		lastDamageTaken += finalDamage;
		
		if (finalDamage <= 0 && !InPainState())
			return finalDamage;
		
		if (source)
		{
			let grazeIndex = inflictor? grazed.Find(inflictor) : grazed.Find(source);
			if (inflictor && grazeIndex == grazed.Size())
				grazeIndex = grazed.Find(source);
			
			if (grazeIndex != grazed.Size())
			{
				grazed.Delete(grazeIndex);
				if (!grazed.Size())
					grazeTics = 0;
			}
		}
		
		if (player)
			player.damageCount = clamp(player.damageCount, 10, 25);
		
		if (Health <= 0)
			return finalDamage;
		
		A_StartSound("delta/hurt", CHAN_HEALTH_SOUNDS, 0, 1., 0.5);
		VoiceDamage(finalDamage, mod);
		
		if (!ignoreIFrames)
			damageTics = (inflictor && (inflictor.bIsPuff || inflictor.bIsMonster)) ? -1 : DAMAGE_IFRAMES;
		
		if (mod == 'Falling')
			A_StartSound("delta/fall_damage", CHAN_AUTO);
		else if (mod == 'Drowning')
			A_StartSound("delta/drown", CHAN_AUTO);
		
		double ang = (source && inflictor && inflictor != self) ?
			DeltaAngle(self.angle, AngleTo(inflictor)) + cfrandom(-15, 15)
			: 0;
		DamageFlinch(ang, finalDamage, flags);
		return finalDamage;
	}
	
	override void Die(Actor source, Actor inflictor, int dmgFlags, Name MeansOfDeath)
	{
		Super.Die(source, inflictor, dmgFlags, MeansOfDeath);
		
		if (!netgame)
		{
			CVar.FindCVar("data_delta_respawningFromDeath").SetBool(true);
			CVar.FindCVar("data_delta_currentDeathsLevel").SetInt(data_delta_currentDeathsLevel + 1);
			CVar.FindCVar("data_delta_currentDeathsSngSeg").SetInt(data_delta_currentDeathsSngSeg + 1);
		}
		
		DeltaExtraDeathStuff(); // any extra death functions can be called here
		if (player)
			player.bob = 0;
		
		if (MeansOfDeath == 'Falling')
			A_StartSound("delta/fall_damage", CHAN_AUTO);
		else if (MeansOfDeath == 'Drowning')
			A_StartSound("delta/drown", CHAN_AUTO);
		
		if (lunging)
		{
			let oldVel = Vel / 10.;
			StopLunge();
			Vel = oldVel;
		}
		
		if (MeansOfDeath != 'Suicide')
			VoiceDeath(MeansOfDeath);
		else
		{
			let exp = Spawn("DeltaBadExplosion");
			exp.SetOrigin(pos.PlusZ(fullHeight / 2.), false);
			
			vel.z += frandom[explodeLaunch](10, 15);
		}
		
		deathTimer = 0;
		deathPitchFP = deathPitchTP = Pitch;
		grazeTics = 0;
	}
	
	override void PlayerSquatView(Actor onmobj)
	{
		Super.PlayerSquatView(onMobj);
		
		if (health <= 0)
			return;
		
		_deltaLandPunch = -player.deltaViewHeight / 2;
	}
	
	// taking implementation from uzdoom.pk3, slightly retooling for different look on death
	override void DeathThink()
	{
		if (!player)
			return;
		if (crouchFactor != 1)
			DeltaUncrouch();
		
		deathTimer++;
		if (player.damageCount)
			player.damageCount--;
		if (player.poisonCount)
			player.poisonCount--;
		
		if (IsFrozen() && deathTimer < DEATH_HANG_FRAMES)
			return;
		
		player.onGround = (pos.Z <= floorz);
		
		if (!_frozenDeath && player.onGround && !level.IsFrozen())
		{
			player.deltaViewHeight = 0;
			if (player.viewHeight > 6)
				player.viewHeight -= deathTimer;
			
			if (player.viewHeight < 6)
				player.viewHeight = 6;
			
			if (player.viewHeight == 6)
			{
				if (deathPitchFP != 0)
				{
					double lookDelta = -deathPitchFP / 8.;
					deathPitchFP += lookDelta;
				}
				
				if (abs(deathPitchTP) > 0.01)
				{
					double lookDelta = -deathPitchTP / 8.;
					deathPitchTP += lookDelta;
				}
				else if (!(deathPitchTP ~== 0))
					deathPitchTP = 0;
				
				if ((player.cheats & CF_CHASECAM) || r_deathCamera)
					Pitch = deathPitchTP;
				else
					Pitch = deathPitchFP;
			}
		}
		
		player.mo.CalcHeight();
		
		bool
			playerWantsToRespawn = (player.cmd.buttons & BT_USE),
			forcingRespawn = (deathmatch || alwaysApplyDMFlags) && sv_forceRespawn,
			respawnAllowed = canRespawn || sv_singlePlayerRespawn,
			respawnDisallowed = sv_noRespawn || (!respawnAllowed && !deathmatch);
		
		if (!(playerWantsToRespawn || forcingRespawn) || respawnDisallowed)
			return;
		
		if (level.mapTime >= player.respawn_time
			|| (playerWantsToRespawn && player.Bot == NULL))
		{
			player.cls = NULL; // Force a new class if the player is using a random class
			player.playerState = respawnAllowed ? PST_REBORN : PST_ENTER;
			
			if (special1 > 2)
				special1 = 0;
		}
	}
	
	// reworking calc height to account for custom view bobbing
	override void CalcHeight()
	{
		let bobSpeed = 0.,
			bob = 0.,
			still = false,
			perc = 1 - airBobTics*1. / MAX_AIR_BOB_TICS;
		
		// Regular movement bobbing
		// (needs to be calculated for gun swing even if not on ground)
		
		// killough 10/98: Make bobbing depend only on player-applied motion.
		//
		// Note: don't reduce bobbing here if on ice: if you reduce bobbing here,
		// it causes bobbing jerkiness when the player moves from ice to non-ice,
		// and vice-versa.
		
		if (player.cheats & CF_NOCLIP2 || player.playerState == PST_DEAD)
			player.bob = 0;
		else
		{
			player.bob = player.Vel dot player.Vel;
			still = player.bob == 0;
			
			// [Sierra0451] adjusted this to account for weapons bobbing less
			// when we're in the air, or depending on our player class (Kris
			// reduces bobbing when they're sliding, for example
			player.bob *= player.GetMoveBob() * perc * perc * customBobPerc;
			
			if (player.bob > MAXBOB)
				player.bob = MAXBOB;
			
			bobTimer += player.bob/MAXBOB;
		}
		
		double defaultViewHeight = ViewHeight + player.crouchViewDelta;
		
		if (player.cheats & CF_NOVELOCITY)
		{
			player.viewz = pos.Z + defaultviewheight;
			
			if (player.viewz > ceilingz-4)
				player.viewz = ceilingz-4;
			
			return;
		}
		
		if (!bFly && !still && player.onGround)
		{
			bobSpeed = bobTimer / (ViewBobSpeed * TICRATE / 35.) * 360.;
			bob = player.bob * sin(bobSpeed) * (waterlevel > 1 ? 0.25f : 0.5f);
		}
		
		// move viewheight
		if (player.playerstate == PST_LIVE)
		{
			player.viewheight += player.deltaviewheight;

			if (player.viewheight > defaultviewheight)
			{
				player.viewheight = defaultviewheight;
				player.deltaviewheight = 0;
			}
			else if (player.viewheight < (defaultviewheight/2))
			{
				player.viewheight = defaultviewheight/2;
				if (player.deltaviewheight <= 0)
					player.deltaviewheight = 1 / 65536.;
			}

			if (player.deltaviewheight)
			{
				player.deltaviewheight += 0.25;
				if (!player.deltaviewheight)
					player.deltaviewheight = 1/65536.;
			}
		}

		if (Alternative)
			bob = 0;
		
		player.viewZ = pos.Z + player.viewHeight + (bob * clamp(ViewBob, 0. , 1.5)); // [SP] Allow DECORATE changes to view bobbing speed.

		if (FloorClip && player.playerState != PST_DEAD && pos.Z <= floorz)
			player.viewZ -= FloorClip;
		
		if (player.viewZ > ceilingZ - 4)
			player.viewZ = ceilingZ - 4;
		
		if (player.viewZ < floorZ + 4)
			player.viewZ = floorZ + 4;
	}
	
	// Grabbing GZDoom's player code and retooling it to work with coyote time and jump buffering
	override void CheckJump()
	{
		if (!player)
			return;
		
		// Buffer jump inputs
		if (player.cmd.buttons & BT_JUMP)
			jumpBuffer = JUMP_BUFFER_TIME;
		
		// [RH] check for jump
		if (jumpBuffer > 0)
		{
			jumpBuffer--;
			
			if (waterLevel >= 2)
				Vel.Z = 4 * Speed;
			else if (bNoGravity)
				Vel.Z = 3.;
			else if (level.IsJumpingAllowed() && coyoteTimer <= COYOTE_TIME && Vel.Z <= 0)
				DoJump();
		}
	}
	
	virtual void DoJump()
	{
		if (IsCrouching())
			player.crouchOffset = 0;
		
		double jumpVelZ = TweakJump(JumpZ * 35 / TICRATE);
		Vel.Z = jumpVelZ;
		bOnMobj = false;
		jumpBuffer = 0;
		coyoteTimer = COYOTE_TIME + 1;
		
		if (!IsPredicting())
		{
			A_StartSound("delta/jump", CHAN_BODY, volume: 0.5);
			
			if (frandom(0., 1.) <= jumpGruntChance)
				DoSpeak("jump_grunt");
		}
	}
	
	// [S0451] putting this in a virtual to make it easier to modify player by player <3
	virtual double TweakJump(double jumpZ)
	{
		double jumpFac = 1;
		// [BC] If the player has the high jump power, double their jump velocity.
		// (actually, pick the best factors from all active items.)
		for (let p = Inv; p != null; p = p.Inv)
		{
			let pp = PowerHighJump(p);
			if (pp)
			{
				double f = pp.Strength;
				if (f > jumpFac) jumpFac = f;
			}
		}
		
		if (coyoteTimer > COYOTE_TIME)
			return jumpZ * jumpFac;
		
		let fric = GetFriction();
		if (fric/ORIG_FRICTION < 1.)
			jumpFac *= fric/ORIG_FRICTION;
		return jumpZ * jumpFac;
	}
	
	override void CheckCrouch(bool totallyFrozen)
	{
		if (!player)
			return;
		if (crouchState != CS_STANDING && crouchState != CS_CROUCHING)
			return;
		
		let buttons = player.cmd.buttons;
		
		if (CanCrouch() && player.health > 0 && !totallyFrozen)
		{
			int crouchDir = player.crouching;
			
			if (crouchDir == 0)
				crouchDir = (buttons & BT_CROUCH) ? -1 : 1;
			else if (buttons & BT_CROUCH)
				player.crouching = 0;
			
			if (crouchDir == 1 && IsCrouching() && pos.Z + height < ceilingz)
			{
				CrouchMove(2);
				
				if (crouchFactor ~== 1)
					crouchState = CS_STANDING;
			}
			else if (crouchDir == -1 && crouchFactor > 0.5)
			{
				crouchState = CS_CROUCHING;
				CrouchMove(-2);
			}
		}
		else if (!totallyFrozen)
			DeltaUncrouch();
		
		player.crouchOffset = ViewHeight * (crouchFactor - 1);
	}
	
	virtual void DeltaUncrouch()
	{
		if (player)
			player.Uncrouch();
		
		if (crouchFactor != 1)
			crouchFactor = 1;
	}
	
	// modifying uzdoom's source code (not using Super.CrouchMove cuz i need to
	// insert some stuff more directly)
	override void CrouchMove(int direction)
	{
		if (!player)
			return;
		
		let defaultHeight = FullHeight * 1.,
			savedHeight = Height * 1.,
			crouchSpeed = direction * 1. * CROUCHSPEED,
			oldHeight = player.viewHeight * 1.;
		
		player.crouchDir = direction;
		if (crouchFactor + crouchSpeed < 0.5 || crouchFactor + crouchSpeed > 1)
			return;
		
		crouchFactor += crouchSpeed;
		
		// check whether the move is ok
		Height = defaultHeight * crouchFactor;
		
		if (!TryMove(Pos.XY, false, NULL))
		{
			Height = savedHeight;
			
			if (direction > 0)
			{
				// doesn't fit
				crouchFactor -= crouchSpeed;
				
				if (!IsGrounded())
					SetOrigin((pos.x, pos.y, pos.z + ViewHeight*crouchSpeed), false);
				return;
			}
		}
		
		Height = savedHeight;
		
		crouchFactor = clamp(crouchFactor, 0.5, 1.);
		player.viewHeight = ViewHeight * crouchFactor;
		player.crouchViewDelta = player.viewHeight - ViewHeight;
		
		if (!IsGrounded())
			SetOrigin((pos.x, pos.y, pos.z - ViewHeight*crouchSpeed), true);
		
		// Check for eyes going above/below fake floor due to crouching motion.
		CheckFakeFloorTriggers(pos.Z + oldHeight, true);
	}
	
	override bool CanCollideWith(Actor other, bool passive)
	{
		if (other.bIsMonster && lunging && other != lungeTarget)
			return false;
		if (other.player)
		{
			if (other.player.cheats & CF_PREDICTING)
				return true;
			if (IsFriend(other))
				return false;
		}
		
		return Super.CanCollideWith(other, passive);
	}
	
	// grabbed from uzdoom.pk3, just removed the sv_degeneration check cuz we
	// wanna degenerate regardless :3
	override void CheckDegeneration()
	{
		if (IsVoodooDoll())
			return;
		
		int maxHp = GetMaxHealth(true);
		if (player.health <= maxHp)
			return;
		
		int degenInterval = (health > maxHp*1.5 || health < maxHp*0.5) ? TICRATE * 2 : TICRATE;
		if (!level.mapTime || level.mapTime % degenInterval)
			return;
		
		health = --player.health;
	}
	
	override void AddInventory(Inventory item)
	{
		if (!CountInv(item.GetClass()) && player.PendingWeapon)
			_savedPending = player.PendingWeapon;
		else
			_savedPending = null;
		
		Super.AddInventory(item);
	}
	
	override void HasReceived(Inventory item, class<Inventory> itemCls)
	{
		Super.HasReceived(item, itemCls);
		if (!item && !(item is "Weapon"))
			return;
		if (!player || !_savedPending)
			return;
		if (player.PendingWeapon == WP_NOCHANGE || !player.ReadyWeapon)
			return;
		if (!(player.cmd.buttons & (BT_ATTACK|BT_ALTATTACK)))
			return;
		
		player.PendingWeapon = (_savedPending==player.ReadyWeapon)? WP_NOCHANGE : _savedPending;
	}
	
	virtual Vector2 GetDefaultWBob(double ticFrac)
	{
		if (!player)
			return (0, 0);
		if (lunging)
			return (0, 0);
		
		let weapon = player.ReadyWeapon;
		if (weapon == null || weapon.bDontBob || player.GetWBobSpeed() == 0)
			return (0, 0);
		
		// [XA] Get the current weapon's bob properties.
		let bobSpeed = 360.,
			rangeX = 0.667,
			rangeY = 0.667;
		
		Vector2 p1, p2, r;
		
		for (int i = 0; i < 2; i++)
		{
			// Bob the weapon based on movement speed. ([SP] And user's bob speed setting)
			double angle = (bobSpeed * player.GetWBobSpeed() * 35 /
				TICRATE*(player.BobTimer - 1 + i)) * (360. / 8192.);
			
			Console.Printf("curbob is %.1f, player.bob is %.1f", curbob, player.bob);
			
			// [RH] Smooth transitions between bobbing and not-bobbing frames.
			// This also fixes the bug where you can "stick" a weapon off-center by
			// shooting it when it's at the peak of its swing.
			if (curbob != player.bob)
			{
				if (abs(player.bob - curbob) <= 1)
					curbob = player.bob;
				else
				{
					double zoom = MAX(1., abs(curbob - player.bob) / 40);
					curbob += (curbob > player.bob)? -zoom : zoom;
				}
			}
			
			// The weapon bobbing intensity while firing can be adjusted by the player.
			double BobIntensity = (player.WeaponState & WF_WEAPONBOBBING) ? 1. : player.GetWBobFire();
			
			if (curbob != 0)
			{
				double bobVal = player.bob;
				if (i == 0)
					bobVal = prevBob;
				
				//[SP] Added in decorate player.viewbob checks
				double
					bobx = (bobVal * BobIntensity * RangeX * ViewBob),
					boby = (bobVal * BobIntensity * RangeY * ViewBob);
				
				r.X = bobx*cos(angle);
				r.Y = 0.5f * (boby * (1. - (cos(angle * 2))));
			}
			else
				r = (0, 0);
			
			if (i == 0)
				p1 = r;
			else
				p2 = r;
		}
		
		return p1 * (1. - ticFrac) + p2 * ticFrac;
	}
	
	override Vector2 BobWeapon(double ticFrac)
	{
		if (IsFrozen())
			return _lastBob;
		
		let bobFlinch = (0, 0),
			bob = GetDefaultWBob(ticFrac);
		
		if (_flinchTics)
			bobFlinch = _currentFlinch * ((_flinchTics - ticFrac) / startFlinchTics);
		
		double
			t = level.time,
			s = shakiness ? DeltaUtil.Lerp(oldShakiness, shakiness.GetValue(), ticFrac)/100. : 0,
			shakeX = sin(t/11.) - sin(TICRATE * t * 0.85),
			shakeY = 1 + sin(1.5*t) + 0.5 * sin(TICRATE/2.*t);
		Vector2 shake = (shakeX, shakeY);
		let result = bob + bobFlinch + shake * s + (GetTurn(ticFrac), 0),
			zVelAdd = vel.z * 0.5,
			zVelFac = clamp((airBobTics*2. / MAX_AIR_BOB_TICS)**2, 0, 1);
		
		zVelAdd *= zVelFac;
		double minYOffset = -30, maxYOffset = 30;
		if (player && player.ReadyWeapon && player.ReadyWeapon is "DeltaWeapon")
		{
			let deltaWeap = DeltaWeapon(player.ReadyWeapon);
			minYOffset = deltaWeap.GetMinYOffset();
			maxYOffset = deltaWeap.GetMaxYOffset();
		}
		
		result.y = clamp(result.y + zVelAdd + _landPunch, minYOffset, maxYOffset);
		_lastBob = result;
		return result;
	}
	
	override void CheatGive(string name, int amount)
	{
		if (name ~== "armor")
			return;
		
		if (name ~== "tensionPoints" || name ~== "tension" || name ~== "tp")
		{
			AddTension(amount? amount : maxTensionPoints);
			return;
		}
		
		if (name ~== "all" || name ~== "everything" || name ~== "ammo")
			AddTension(maxTensionPoints);
		
		Super.CheatGive(name, amount);
	}
	
	override void CheatTake(string name, int amount)
	{
		if (name ~== "armor")
			return;
			
		if (name ~== "tensionPoints" || name ~== "tp")
		{
			if (amount < 0)
				return;
			
			if (amount == 0)
			{
				tensionPoints = 0;
				return;
			}
			
			tensionPoints = max(0, tensionPoints - amount);
			tensionDrainTimer = DRAIN_TIMER_START;
		}
		else
			Super.CheatTake(name, amount);
	}
	
	// taking from uzdoom.pk3 and retooling, removing grunts entirely
	override void PlayerLandedMakeGruntSound(actor onMobj)
	{
		// [RH] only make noise if alive
		if (health < 0 || Alternative || jumpBuffer)
			return;
		if (onMobj == NULL && (pos.Z > floorZ || HitFloor()))
			return;
		
		let landVol = 0.5, //IsCrouching()? 0.25 : 0.5
			landVelocity = vel.z,
			hardLandThreshold = 17.,
			veryHardLandThreshold = 21.;
		
		if (landVelocity > veryHardLandThreshold)
		{
			landVol = 1;
			A_StartSound("delta/thud", CHAN_AUTO);
		}
		
		A_StartSound("delta/land", CHAN_BODY, volume: landVol);
	}
	
	override string GetObituary(Actor victim, Actor inflictor, Name mod,
		bool playerAttack)
	{
		if (!inflictor || !inflictor.CountInv("DeltaParried"))
			return Super.GetObituary(victim, inflictor, mod, playerAttack);
		
		let parry = DeltaParried(inflictor.FindInventory("DeltaParried", true));
		if (!parry.oldTarget || parry.oldTarget == inflictor.target)
			return Super.GetObituary(victim, inflictor, mod, playerAttack);
		if (parry.oldTarget == victim)
			return backAtYouObituary;
		
		return parryObituary;
	}
	
	override void PlayIdle()
	{
		let curAnimType = DELTA_WEAPONANIM_MELEE;
		if (player && player.ReadyWeapon && (player.ReadyWeapon is "DeltaWeapon"))
			curAnimType = DeltaWeapon(player.ReadyWeapon).GetAnimType();
		
		if (curAnimType != lastAnimType || InAirState() || InAirPainState() || InSeeState())
			SetStateSafe(A_DeltaGetState("Spawn"));
		
		if (!InSpawnState())
			return;
		
		switch (curAnimType)
		{
			case DELTA_WEAPONANIM_MELEE:
				A_UseMeleeSprite();
				break;
			case DELTA_WEAPONANIM_MAGIC:
				A_UseMagicSprite();
				break;
			default:
				A_UseGunSprite();
				break;
		}
	}
	
	override void PlayRunning()
	{
		let curAnimType = DELTA_WEAPONANIM_MELEE;
		if (player && player.ReadyWeapon && (player.ReadyWeapon is "DeltaWeapon"))
			curAnimType = DeltaWeapon(player.ReadyWeapon).GetAnimType();
		
		if (curAnimType != lastAnimType || InAirState() || InAirPainState() || InSpawnState())
			SetStateSafe(A_DeltaGetState("See"));
		
		if (!InSeeState())
			return;
		
		switch (curAnimType)
		{
			case DELTA_WEAPONANIM_MELEE:
				A_UseMeleeSprite();
				break;
			case DELTA_WEAPONANIM_MAGIC:
				A_UseMagicSprite();
				break;
			default:
				A_UseGunSprite();
				break;
		}
		
		let fwd = min(1, abs(player.cmd.forwardMove / 12800.)),
			side = min(1, abs(player.cmd.sideMove / 10240.)),
			move = max(fwd, side);
		
		int newTics = 4;
		double
			mult = 1,
			maxMult = 8;
		
		mult = move ~== 0? maxMult : (1. / move);
		
		if (IsCrouching())
			mult *= 2;
		if (mult > maxMult)
			mult = maxMult;
		
		newTics = int(newTics * mult);
		
		if (tics != -1 && tics <= newTics)
			return;
		
		A_SetTics(newTics);
	}
	
	// retooled from definition in uzdoom.pk3
	override void FireWeapon(State stat)
	{
		let weapn = player.ReadyWeapon;
		if (!weapn || !(weapn is "DeltaWeapon"))
			return;
		
		DeltaWeapon(weapn).DoFire(stat);
	}

	override void FireWeaponAlt(State stat)
	{
		let weapn = player.ReadyWeapon;
		if (!weapn || !(weapn is "DeltaWeapon") || !(weapn.FindState('AltFire')))
			return;
		
		DeltaWeapon(weapn).DoAltFire(stat);
	}
	
	override void PlayAttacking()
	{
		SetStateSafe(A_DeltaGetState("Missile"));
	}
	
	// specifically overriding in the event we don't want a muzzle flash!
	override void PlayAttacking2()
	{
		let dest = A_DeltaGetState("Missile");
		if (!dest)
			return;
		
		if (dest.InStateSequence(ResolveState("MissileGun")))
			dest = ResolveState("MissileGunNoFlash");
		
		SetStateSafe(dest);
	}
	
	void PlayAir()
	{
		let curAnimType = DELTA_WEAPONANIM_MELEE;
		if (player && player.ReadyWeapon && (player.ReadyWeapon is "DeltaWeapon"))
			curAnimType = DeltaWeapon(player.ReadyWeapon).GetAnimType();
		
		if (curAnimType != lastAnimType || InSeeState() || InSpawnState())
			SetStateSafe(A_DeltaGetState("Air"));
	}
	
	static void SendMapMessage(int playerNum, string message)
	{
		EventHandler.SendInterfaceEvent(playerNum, "MessageIs_" .. message);
	}
	
	static void DismissMapMessage(int playerNum)
	{
		EventHandler.SendInterfaceEvent(playerNum, "DismissMapMessage");
	}
	
	static void SendCannedMessage(int playerNum, int index)
	{
		string message;
		
		switch (index)
		{
			case 0:
				//message = StringTable.Localize("$DW_MOVETUTORIAL");
				message = "Press %s\c- to move.%%%%";
				int forward = Bindings.GetKeysForCommand("+forward"),
					left = Bindings.GetKeysForCommand("+moveleft"),
					back = Bindings.GetKeysForCommand("+back"),
					right = Bindings.GetKeysForCommand("+moveright");
				
				Array<int> keys;
				keys.Push(forward);
				keys.Push(left);
				keys.Push(back);
				keys.Push(right);
				
				let keyStr = KeyBindings.NameAllKeys(keys, false);
				Array<string> keyStrings;
				
				keyStr.Split(keyStrings, ",");
				keyStr = "";
				
				foreach(keyString : keyStrings)
				{
					keyString = "\c[DeltaHighlight]" .. keyString .. "\c-";
					
					if (keyStr != "")
						keyStr = keyStr .. "," .. keyString;
					else
						keyStr = keyString;
				}
				
				message = String.Format(message, keyStr); 
				break;
			default:
				break;
		}
		
		DeltaPlayer.SendMapMessage(playerNum, message);
	}
	
	action state A_DeltaGetState(string prefix)
	{
		return invoker.DeltaGetState(prefix);
	}
	
	virtual state DeltaGetState(string prefix)
	{
		string lwr = prefix;
		lwr.ToLower();
		
		if (lwr == "pain" && !(pos.Z <= floorZ || bOnMobj || bMBFBouncer))
			prefix = "AirPain";
		
		let dest = GetStateByAnimType(prefix, lastAnimType);
		if (!dest)
			return ResolveState(null);
		
		return dest;
	}
	
	virtual void AnimatePlayer()
	{
		if (health <= 0)
			return;

		bool doingMoveInput = player ? (player.cmd.forwardMove || player.cmd.sideMove)
			: false;
		
		if (coyoteTimer <= ANIM_GROUNDED_HANG_TIME)
		{
			if (doingMoveInput && vel.xy.LengthSquared() > 0)
				PlayRunning();
			else
				PlayIdle();
		}
		else
			PlayAir();
	}
	
	void SetTension(double amount, bool resetTimer = true)
	{
		if (amount <= 0)
			amount = 0;
		
		double factor = G_SkillPropertyFloat(SKILLP_AmmoFactor) * sv_ammofactor;
		tensionPoints = clamp(amount, 0, maxTensionPoints);
		
		if (resetTimer)
			tensionDrainTimer = tensionPoints>0? int(ceil(DRAIN_TIMER_START * factor)) : 0;
	}
	
	void AddTension(double amount, bool graze = false, bool resetTimer = true)
	{
		double factor = G_SkillPropertyFloat(SKILLP_AmmoFactor) * sv_ammofactor;
		SetTension(tensionPoints + amount*factor, resetTimer);
		
		if (graze)
			grazeTics = MAX_GRAZE_TICS;
	}
	
	clearscope DeltaTpResult GetTension(double amount)
	{
		if (sv_infiniteAmmo || (FindInventory('PowerInfiniteAmmo', true) != null))
			return TP_INFINITE;
		
		if (amount < 0)
			amount = 0;
		
		let factor = G_SkillPropertyFloat(SKILLP_AmmoFactor) * sv_ammoFactor,
			graceWindow = DRAIN_AMOUNT * factor * DRAIN_GRACE_TICS;
		if (tensionPoints < (tensionDrainTimer? amount : amount - graceWindow))
			return TP_FAIL;
		
		return TP_USE;
	}
	
	bool TryTakeTension(double amount, bool playSound = true)
	{
		switch (GetTension(amount))
		{
			case TP_USE:
				SetTension(tensionPoints - amount);
			case TP_INFINITE:
				return true;
		}
		
		if (playSound)
			A_StartSound("delta/tp_fail", CHAN_ITEM, CHANF_LOCAL | CHANF_NOSTOP);
		return false;
	}
	
	protected void DrainTension()
	{
		if (sv_infiniteAmmo || (FindInventory('PowerInfiniteAmmo', true) != null))
			return;
		
		double factor = G_SkillPropertyFloat(SKILLP_AmmoFactor) * sv_ammoFactor;
		
		if (tensionDrainTimer > 0)
			tensionDrainTimer--;
		else if (tensionPoints > 0)
			SetTension(tensionPoints - DRAIN_AMOUNT/factor, false);
	}
	
	protected state GetStateByAnimType(string prefix,
		out DeltaWeaponAnimType animType, int defaultAnimType = DELTA_WEAPONANIM_MELEE)
	{
		let oldAnimType = animType;
		animType = defaultAnimType;
		
		if (player && player.ReadyWeapon && player.ReadyWeapon is "DeltaWeapon")
			animType = DeltaWeapon(player.ReadyWeapon).GetAnimType();
		
		string suffix;
		
		switch (animType)
		{
			case DELTA_WEAPONANIM_MELEE:
				suffix = "Melee";
				break;
			case DELTA_WEAPONANIM_MAGIC:
				suffix = "Magic";
				break;
			case DELTA_WEAPONANIM_GUN:
			default:
				suffix = "Gun";
				break;
		}
		
		state dest = FindStateByString(prefix .. suffix);
		if (!dest)
			animType = oldAnimType;
		
		return dest;
	}
	
	protected void HandlePowerupEffects()
	{
		if (!(level.time % 3) && CountInv("PowerInvulnerable"))
		{
			let trail = DeltaTrail.SpawnTrail("DeltaRainbowTrail", pos);
			trail.master = self;
		}
	}
	
	protected void HandleHeartbeat()
	{
		if (!heartbeat)
			heartbeat = LinearValueInterpolator.Create(0, 10);
		
		double
			_maxHealth = GetMaxHealth(),
			maxHb = 45.,
			minHb = 15.,
			perc = health * 100. / _maxHealth;
		int targetVal = int(DeltaUtil.Map(perc, maxHb, minHb, 20, 100));
		
		bool heartbeatCvar = (cl_delta_heartbeatSound == HB_ON
			|| (cl_delta_heartbeatSound == HB_LIGHTNERS_ONLY && !(self is "RalseiPlayer")));
		
		// make sure heartbeat only plays if we're
		// below a threshold AND we aren't dead
		if (perc <= maxHb && health > 0 && heartbeatCvar)
			heartbeat.Update(targetVal);
		else if (health > 0 && heartbeatCvar)
			heartbeat.Update(0);
		else if (heartbeat.GetValue() != 0)
			heartbeat.Reset(0);
		
		double vol = heartbeat.GetValue() / 100.;
		
		if (!IsActorPlayingSound(CHAN_HEARTBEAT))
			A_StartSound("delta/heartbeat", CHAN_HEARTBEAT, CHANF_LOOPING, vol, 120);
		else
			A_SoundVolume(CHAN_HEARTBEAT, vol);
	}
	
	protected virtual double GetViewRoll()
	{
		let relVelY = (-Vel.x * sin(-Angle) - Vel.y * cos(-Angle)) / 4.,
			rollTarget = min(10, max(-10, relVelY)) * cl_delta_leanIntensity,
			maxChange = 10. / TICRATE;
		
		if (abs(rollTarget - _targetRoll) > 2)
			maxChange *= 2;
		if (abs(rollTarget - _targetRoll) > 5)
			maxChange *= 2;
		if (abs(rollTarget - _targetRoll) > 10)
			maxChange *= 2;
		
		_targetRoll += min(maxChange, max(-maxChange, rollTarget - _targetRoll));
		return _targetRoll;
	}
	
	protected virtual Vector3 GetRecoilAngles()
	{
		Vector3 recoil;
		
		for (int i = 0; i < _recoils.Size(); i++)
		{
			int start = _recoils[i].startTime, cur = _recoils[i].curTime,
				lead = _recoils[i].leadInTime;
			
			if (cur <= 0)
				continue;
			
			double factor;
			
			if (start - cur < lead)
				factor = (start - cur) / double(lead);
			else
				factor = cur / double(start - lead);
			
			factor *= _recoils[i].recoilType == RECOIL_WEAPON ? cl_delta_weaponRecoil : cl_delta_damageRecoil;
			factor *= factor;
			recoil += _recoils[i].recoil * factor;
		}
		
		return recoil;
	}
	
	protected void HandleViewAngles()
	{
		for (int i = 0; i < _recoils.Size(); i++)
		{
			if (_recoils[i].curTime <= 0 || IsFrozen())
				continue;
			
			_recoils[i].curTime--;
		}
		
		_landPunch += _deltaLandPunch;
		
		if (_landPunch > 5)
		{
			_landPunch = 5;
			_deltaLandPunch = 1 / 65536.;
		}
		else if (_landPunch < 0)
		{
			_landPunch = 0;
			_deltaLandPunch = 0;
		}
		
		if (_deltaLandPunch)
		{
			_deltaLandPunch = max(_deltaLandPunch - 0.175, -0.175 * 7);
			
			if (!_deltaLandPunch)
				_deltaLandPunch = 1 / 65536.;
		}
		
		let recoil = GetRecoilAngles();
		
		if (!(player.cheats & CF_CHASECAM))
		{
			recoil.x += _landPunch;
			recoil.z += GetViewRoll();
		}
		
		A_SetViewPitch(recoil.x, SPF_INTERPOLATE);
		A_SetViewAngle(recoil.y, SPF_INTERPOLATE);
		A_SetViewRoll(recoil.z, SPF_INTERPOLATE);
	}
	
	protected void HandleIFrames()
	{
		if (damageTics < 0)
			damageTics = max(1, DAMAGE_IFRAMES) - 1; // minus one because we take a tic to initialize i-frames
		else 
		{
			lastDamageTaken = 0;
			
			if (damageTics > 0)
				damageTics--;
		}
	}
	
	protected bool RalseiIsHugging()
	{
		string hug = "hugging";
		class<Inventory> hugging = hug;
		return FindInventory(hugging);
	}
	
	protected virtual void HandleRalseiHugs()
	{
		string rals = "FriendsWithRalsei";
		class<Actor> ralseiCheck = rals;
		
		if (ralseiCheck == null)
			return; // don't bother with this if we don't have the ralsei mod
		
		if (RalseiIsHugging() && !beingHugged)
		{
			if (++hugTimer == hugReactionTime)
				beingHugged = true;
		}
		else if (!RalseiIsHugging() && beingHugged)
		{
			hugTimer = 0;
			beingHugged = false;
		}
	}
	
	protected void HandleAirStuff()
	{
		coyoteTimer = (IsGrounded() && vel.z <= 0)? 0 : coyoteTimer+1;
		
		if (IsGrounded() && airBobTics)
			airBobTics--;
		
		if (!IsGrounded())
		{
			if (airBobTics < MAX_AIR_BOB_TICS)
				airBobTics++;
			
			let windVol = clamp(vel.z/-20. - 1, 0., 1.),
				windPitch = DeltaUtil.Map(vel.z/-40. - 0.5, 0., 1., 0.5, 1.5);
			
			if (!IsActorPlayingSound(CHAN_FALL_WIND))
				A_StartSound("delta/falling_wind", CHAN_FALL_WIND, CHANF_LOOP,
					windVol, pitch: windPitch);
			else
			{
				A_SoundVolume(CHAN_FALL_WIND, windVol);
				A_SoundPitch(CHAN_FALL_WIND, windPitch);
			}
		}
		else if (IsActorPlayingSound(CHAN_FALL_WIND))
			A_StopSound(CHAN_FALL_WIND);
	}
	
	protected void HandleFlinch()
	{
		if (_flinchTics > 0)
			_flinchTics--;
		
		if (!shakiness)
			shakiness = LinearValueInterpolator.Create(int(minShakiness * 100), 20);
		
		oldShakiness = shakiness.GetValue();
		
		if (health > shakinessMaxHealth)
		{
			shakiness.Update(0);
			return;
		}
		
		let targetShake = DeltaUtil.Map(health, 1, shakinessMaxHealth,
			maxShakiness*100., minShakiness*100.);
		
		if (health > 0)
			shakiness.Update(int(targetShake));
		else if (shakiness.GetValue() != 0)
			shakiness.Reset(0);
	}
	
	protected void HandleHandedness()
	{
		if (IsVoodooDoll())
			return;
		
		let weapPsp = player.FindPSprite(PSP_WEAPON),
			flashPsp = player.FindPSprite(PSP_FLASH),
			offhandPsp = player.FindPSprite(PSP_OFFHAND),
			legsPsp = player.FindPSprite(PSP_LEGS);
		
		if (weapPsp)
		{
			weapPsp.bFlip = cl_delta_weaponHandedness;
			weapPsp.bMirror = cl_delta_weaponHandedness;
		}
		
		if (flashPsp)
		{
			flashPsp.bFlip = cl_delta_weaponHandedness;
			flashPsp.bMirror = cl_delta_weaponHandedness;
		}
		
		if (offhandPsp)
		{
			offhandPsp.bFlip = cl_delta_weaponHandedness;
			offhandPsp.bMirror = cl_delta_weaponHandedness;
		}
		
		if (legsPsp)
		{
			legsPsp.bFlip = cl_delta_weaponHandedness;
			legsPsp.bMirror = cl_delta_weaponHandedness;
		}
	}
	
	protected void HandleCrosshair()
	{
		if (!cl_delta_crosshairTargetChange)
		{
			_crosshairState = DELTA_XHR_NEUTRAL;
			return;
		}
		
		if (IsVoodooDoll())
			return;
		
		let curWeap = DeltaWeapon(player.ReadyWeapon);
		
		FTranslatedLineTarget t;
		FLineTraceData l;
		double ang = angle;
		double distance = curWeap ? curWeap.GetRedCrosshairRange() : DEFAULT_RED_CROSSHAIR_RANGE;
		double pitch = AimLineAttack(ang, distance, t, 0., ALF_CHECK3D);
		
		LineTrace(ang, distance, pitch, TRF_NOSKY,
			height*0.5 - floorclip + AttackZOffset * crouchFactor, data: l);
		
		let ac = l.HitActor;
		
		if (!ac || ac.curState.InStateSequence(ac.ResolveState("Death")) || 
			((ac is "DeltaGrenade") && ac.curState.InStateSequence(ac.ResolveState("Explode"))))
		{
			_crosshairState = DELTA_XHR_NEUTRAL;
			return;
		}
		
		if (IsFriend(ac))
			_crosshairState = DELTA_XHR_FRIENDLY;
		else if (IsHostile(ac) && !ac.bShadow)
			// TODO: do more thorough crosshair check, let trace pass through
			// shadow enemies instead of just being neutral on them
			_crosshairState = DELTA_XHR_ENEMY;
		else
			_crosshairState = DELTA_XHR_NEUTRAL;
	}
	
	protected void CheckGraze()
	{
		if (damageTics != 0)
			return;
		
		let it = ThinkerIterator.Create("Actor", STAT_DEFAULT);
		foreach (Actor mis : it)
		{
			if (mis is "ArchvileFire")
			{
				if (!mis.target || !mis.tracer)
					continue;
				if (mis.tracer != self || !CheckSight(mis.target))
					continue;
				
				DoGraze(mis);
				continue;
			}
			
			if (!mis.bMissile && !mis.bSkullfly)
			{
				let misIndex = grazed.Find(mis);
				if (misIndex != grazed.Size())
					grazed.Delete(misIndex);
				// mostly making sure lost souls can be first-tic grazed again
				// after slamming into something
				
				continue;
			}
			
			if (!mis.bSkullfly && mis.target == self)
				continue;
			if (!mis.CanCollideWith(self, false))
				continue;
			if (!CheckSight(mis, SF_IGNOREVISIBILITY | SF_IGNOREWATERBOUNDARY))
				continue;
			
			double blockDist = (radius * 6) + (mis.radius * 6);
			double blockHeight = (height * 0.5 * 6) + (mis.height * 0.5 * 6);
			Vector3 diff = level.Vec3Diff(pos, mis.pos);
			
			if (abs(diff.x) > blockDist || abs(diff.y) > blockDist)
				continue;
			if (abs(diff.z) > blockHeight)
				continue;
			
			if (!mis.bSkullfly && mis.target && IsFriend(mis.target))
				continue;
			
			DoGraze(mis);
		}
	}
	
	protected virtual void DoGraze(Actor mis)
	{
		if (!mis)
			return;
		
		if (mis is "ArchvileFire")
		{
			bool firstGraze = grazed.Find(mis) == grazed.Size();
			double grazeAmount = 2 * abs(mis.curState.DistanceTo(mis.SpawnState));
			
			GrazeEvent e;
			e.thing = self;
			e.grazeSource = mis.target;
			
			DeltaGlobals.GetLevelEvents().PlayerGrazed(e);
			
			if (firstGraze)
			{
				AddTension(grazeAmount * GetGrazeMultiplier(), true);
				A_StartSound("delta/graze", 5, 0);
				grazed.Push(mis);
			}
			else
				AddTension(grazeAmount * GetGrazeMultiplier() / TICRATE, true);
			
			return;
		}
		
		int misDmg = mis.GetMissileDamage(0, 1);
		
		if (mis.tracer == self)
			misDmg /= 2;
		if (misDmg <= 0)
			return;
		
		bool firstGraze = grazed.Find(mis) == grazed.Size();
		double grazeAmount = max(5, misDmg);
		
		GrazeEvent e;
		e.thing = self;
		e.grazeSource = mis;
		
		DeltaGlobals.GetLevelEvents().PlayerGrazed(e);
		
		if (firstGraze)
		{
			AddTension(grazeAmount * GetGrazeMultiplier(), true);
			A_StartSound("delta/graze", 5, 0);
			grazed.Push(mis);
		}
		else
			AddTension(grazeAmount * GetGrazeMultiplier() / TICRATE, true);
	}
	
	protected void DamageFlinch(double ang, int dmg, int dmgFlags)
	{
		if (dmgFlags & DMG_NO_PAIN)
			return;
		
		double damageMultiplier = min(0.25, dmg / 50.);
		int damageAddTics = max(0, min(20, dmg / 2));
		bool isExplosion = (dmgFlags & DMG_EXPLOSION);
		
		_flinchTics = startFlinchTics + damageAddTics/2;
		_currentFlinch = (sin(ang), cos(ang)) * flinchMultiplier * damageMultiplier/0.25;
		
		double yrMult = isExplosion ? -3*sin(ang) : sin(ang),
			pMult = cos(ang);
		
		if (abs(sin(ang)) <= 0.1)
			yrMult = 0;
		if (abs(cos(ang)) <= 0.1)
			pMult = 0;
		
		AddRecoil(RECOIL_DAMAGE, 7 + damageAddTics, 2,
			p: -cos(ang) * flinchMultiplier * damageMultiplier,
			r: yrMult * flinchMultiplier * damageMultiplier);
	}
	
	void AddRecoil(DeltaRecoilType recoilType, int startTime, int leadInTime = 0, double p = 0, double y = 0, double r = 0)
	{
		int targetIndex = -1;
		int shortestTime = -1;
		
		for (int i = 0; i < _recoils.Size(); i++)
		{
			if (_recoils[i].curTime <= 0)
			{
				targetIndex = i;
				break;
			}
			
			if (shortestTime < 0 || _recoils[i].curTime < shortestTime)
			{
				targetIndex = i;
				shortestTime = _recoils[i].curTime;
			}
		}
		
		if (targetIndex < 0)
			return;
		
		_recoils[targetIndex].startTime = _recoils[targetIndex].curTime = startTime;
		_recoils[targetIndex].leadInTime = leadInTime;
		_recoils[targetIndex].recoil = (p, y, r);
		_recoils[targetIndex].recoilType = recoilType;
	}
	
	clearscope Color GetCharacterColor()
	{
		return characterColor | 0xff000000;
	}
	
	clearscope Color GetOverhealColor()
	{
		return overhealColor | 0xff000000;
	}
	
	clearscope double GetOffhandTpCost()
	{
		return offhandTpCost;
	}
	
	override bool CanCrouch()
	{
		return level.IsCrouchingAllowed() && Super.CanCrouch();
	}
	
	clearscope bool IsCrouching(bool fullyOnly = false)
	{
		if (!CanCrouch())
			return false;
		
		return fullyOnly ? (crouchFactor == 0.5) : (crouchFactor != 1);
	}
	
	clearscope int GetDamageTics()
	{
		return damageTics;
	}
	
	clearscope virtual double GetGrazeMultiplier()
	{
		return GetIsUsingOffhand()? 0.25 : 1.;
	}
	
	clearscope bool IsLunging()
	{
		return lunging && lungeTarget;
	}
	
	clearscope virtual bool CanLunge()
	{
		return !IsCrouching() && (player.cmd.forwardMove >= 0);
	}
	
	clearscope bool IsGrounded()
	{
		if (player && (player.cheats & (CF_NOCLIP2|CF_FLY)))
			return false;
		
		return pos.Z <= floorZ || bOnMobj;
	}
	
	bool IsPredicting()
	{
		return player && (player.cheats & CF_PREDICTING);
	}
	
	// returns -1 if not dead, otherwise returns how many ticks this character has been dead for
	clearscope int GetDeathTimer()
	{
		return deathTimer;
	}
	
	clearscope TextureID GetCharacterIconID()
	{
		return _characterIconId;
	}
	
	clearscope TextureID GetNameTagID()
	{
		return _nameTagId;
	}
	
	clearscope int GetAutomapIcon()
	{
		return _automapIcon;
	}
	
	clearscope double GetTurn(double ticFrac = 0.)
	{
		return DeltaUtil.Lerp(_oldTurn, _turn, ticFrac);
	}
	
	clearscope double GetCrouchFactor()
	{
		return crouchFactor;
	}
	
	clearscope int GetCrouchState()
	{
		return crouchState;
	}
	
	clearscope DeltaCrosshairState GetCrosshairState()
	{
		return _crosshairState;
	}
	
	clearscope Vector3 GetViewPos()
	{
		return pos.PlusZ(viewHeight * crouchFactor);
	}
	
	clearscope PlayerInfo GetSavedPlayer()
	{
		return _savedPlayer;
	}
	
	clearscope bool IsVoodooDoll()
	{
		return !player || !player.mo || player.mo != self;
	}
}

class DeltaPlayerMarker : MapMarker
{
	protected DeltaPlayer ply;
	
	States
	{
		Spawn:
			#### A -1;
			Stop;
	}
	
	static DeltaPlayerMarker Create(DeltaPlayer ply)
	{
		return DeltaPlayerMarker(Spawn("DeltaPlayerMarker")).Init(ply);
	}
	
	DeltaPlayerMarker Init(DeltaPlayer ply)
	{
		self.ply = ply;
		SetOrigin(ply.pos, false);
		return self;
	}
	
	override void PostBeginPlay()
	{
		Super.PostBeginPlay();
		
		if (!ply || (deathmatch && !players[consolePlayer].mo.IsTeammate(ply)))
		{
			Deactivate(self);
			return;
		}
		
		args[2] = 1;
		sprite = ply.GetAutomapIcon();
	}
	
	override void Tick()
	{
		if (!ply)
		{
			Destroy();
			return;
		}
		
		SetOrigin(ply.pos, true);
		Super.Tick();
	}
}