extend class DeltaPlayer
{
	protected bool isUsingOffhand;
	protected string offhandIcon;
	protected double offhandTpCost;
	protected double preOffhandTp;	// used for refunding TP if offhand fails
	protected int preOffhandTpTimer;
	
	private TextureID _offhandIconId;
	
	virtual void StartOffhand()
	{
		isUsingOffhand = true;
		A_Overlay(PSP_OFFHAND, "OffhandOverlay");
		A_OverlayFlags(PSP_OFFHAND, PSPF_ADDBOB, true);
	}
	
	virtual bool TryStartOffhand()
	{
		if (!CanUseOffhand())
			return false;
		
		preOffhandTp = tensionPoints;
		preOffhandTpTimer = tensionDrainTimer;
		
		if (!TryTakeTension(offhandTpCost))
			return false;
		
		StartOffhand();
		return true;
	}
	
	// Wrap up
	action void A_EndOffhand()
	{
		invoker.isUsingOffhand = false;
	}
	
	clearscope virtual bool CanUseOffhand()
	{
		return true;
	}
	
	clearscope bool GetIsUsingOffhand()
	{
		return isUsingOffhand;
	}
	
	clearscope TextureID GetOffhandIconID()
	{
		return _offhandIconId;
	}
}

// used to modify projectile damage directly!
class DeltaParryDamage : Inventory
{
	Default
	{
		+Inventory.UNDROPPABLE;
		+Inventory.UNTOSSABLE;
	}
	
	override void ModifyDamage(int damage, Name damageType, out int newDamage, bool passive, Actor inflictor, Actor source, int flags)
	{
		if (passive || !inflictor || !inflictor.CountInv("DeltaParried"))
			return;
		
		newDamage = random[parryDamage](22, 24) * max(5, inflictor.GetMissileDamage(0, 1))
            * max(1, G_SkillPropertyFloat(SKILLP_MonsterHealth));
	}
}

class DeltaParried : Inventory
{
	// allows us to save who initially fired the projectile for differentiating
	// between killing a player with their own projectile and killing them with
	// someone else's
	Actor oldTarget;
}