class DeltaPlayerMarker : MapMarker
{
	protected DeltaPlayer ply;
	
	States
	{
		Spawn:
			#### A -1;
			Stop;
	}
	
	static DeltaPlayerMarker Create(DeltaPlayer ply)
	{
		return DeltaPlayerMarker(Spawn("DeltaPlayerMarker")).Init(ply);
	}
	
	DeltaPlayerMarker Init(DeltaPlayer ply)
	{
		self.ply = ply;
		SetOrigin(ply.pos, false);
		return self;
	}
	
	override void PostBeginPlay()
	{
		Super.PostBeginPlay();
		
		if (!ply || (deathmatch && !players[consolePlayer].mo.IsTeammate(ply)))
		{
			Deactivate(self);
			return;
		}
		
		args[2] = 1;
		sprite = ply.GetAutomapIcon();
	}
	
	override void Tick()
	{
		if (!ply)
		{
			Destroy();
			return;
		}
		
		SetOrigin(ply.pos, true);
		Super.Tick();
	}
}