extend class DeltaPlayer
{
	Actor lungeTarget;
	
	protected bool lunging;
	protected double lungeSpeed, lungeStopDistance;
	protected Vector3 preLungeVel;
	
	void StartLunge(Actor target, double stopDistance)
	{
		Console.DebugPrintf(DMSG_NOTIFY, "Starting lunge.");
		
		if (!CanLunge())
		{
			Console.DebugPrintf(DMSG_NOTIFY, "Tried to start lunging but can't, exiting early.");
			return;
		}
		
		preLungeVel = Vel;
		lungeTarget = target;
		lungeStopDistance = stopDistance;
		
		if (LungeBlocked())
		{
			Console.DebugPrintf(DMSG_NOTIFY, "Tried to start lunging but was blocked, exiting early.");
			StopLunge();
			return;
		}
		
		lunging = bNoGravity = true;
		bSolid = false;
		SetStateSafe(ResolveState("Lunge"));
	}
	
	bool LungeBlocked(Actor _target = null)
	{
		if (!_target && !lungeTarget)
			return true;
		if (!_target)
			_target = lungeTarget;
		if (_target.health <= 0)
			return true;
		
		let diff = Vec3To(_target),
			dist = diff.Length(),
			diffUnit = diff.Unit();
		
		bool blockCheck = false; // returns true if we find something blocking us
		
		for (float checkDist = 0; checkDist < dist; checkDist += lungeSpeed)
		{
			let ofs = diffUnit * checkDist,
				posCheck = level.Vec3Offset(pos, ofs);
			
			if (CheckBlock(CBF_DROPOFF | CBF_NOACTORS | CBF_ABSOLUTEPOS, AAPTR_DEFAULT,
				posCheck.x, posCheck.y, posCheck.z))
			{
				return true;
			}
		}
		
		return false;
	}
	
	void HandleLunging()
	{
		if (!lunging || !player)
			return;
		
		AdjustLungeAngles();
		
		Vector3
			diff = Vec3To(lungeTarget),
			diffUnit = diff.Unit();
		double dist = diff.Length() - radius - lungeTarget.radius;
		Vel = diffUnit * min(lungeSpeed, dist);
		
		if (LungeBlocked())
		{
			StopLunge();
			SetStateSafe(SpawnState);
			return;
		}
		
		if (dist <= lungeStopDistance + Vel.Length() ||
			(diff.XY.Length() < lungeStopDistance &&
			abs(diff.z) - height <= lungeStopDistance + abs(Vel.Z)))
		{
			let desiredPos = level.Vec2Diff(pos.xy, lungeTarget.pos.xy);
			desiredPos *= (desiredPos.Length() - lungeStopDistance) / desiredPos.Length();
			StopLunge(true);
			TryMove(pos.XY + desiredPos, 0);
			AdjustLungeAngles();
			player.vel = (0, 0);
		}
	}
	
	protected void AdjustLungeAngles()
	{
		let diff = Vec3To(lungeTarget),
			diffUnit = diff.Unit(),
			angDiff = DeltaAngle(angle, VectorAngle(diff.x, diff.y));
		
		let minChange = 0.5,
			maxChange = 2.;
		
		if (abs(angDiff) > minChange)
		{
			if (angDiff < -maxChange)
				angDiff = -maxChange;
			else if (angDiff > maxChange)
				angDiff = maxChange;
			
			A_SetAngle(angle + angDiff, SPF_INTERPOLATE);
		}
		
		if (!level.IsFreelookAllowed())
			return;
		
		let check = level.Vec3Diff(GetViewPos(), lungeTarget.pos),
			checkUnit = check.Unit(),
			targetPitch = -asin(checkUnit.z);
		
		if (pitch > targetPitch)
			A_SetPitch(targetPitch, SPF_INTERPOLATE);
		else
		{
			check = level.Vec3Diff(GetViewPos(),
				lungeTarget.pos.PlusZ(lungeTarget.height));
			checkUnit = check.Unit();
			targetPitch = -asin(checkUnit.z);
			
			if (pitch < targetPitch)
				A_SetPitch(targetPitch, SPF_INTERPOLATE);
		}
	}
	
	void StopLunge(bool resetVelocity = false)
	{
		Vel = resetVelocity ? (0, 0, 0) : preLungeVel;
		lunging = bNoGravity = false;
		
		if (health > 0)
			bSolid = true;
		if (!player || !player.ReadyWeapon || !(player.ReadyWeapon is "DeltaWeapon"))
			return;
		
		DeltaWeapon(player.ReadyWeapon).MarkReadyToStopLunging();
	}
}