extend class DeltaPlayer
{
	protected int levelOneHp;
	
	property LevelOneHP : levelOneHp;
	
	virtual void HandleBlindness()
	{
		if (!player || !IsBlind())
			return;
		
		let offhandPsp = player.FindPSprite(PSP_OFFHAND);
		if (offhandPsp)
			offhandPsp.sprite = -1;
	}
	
	virtual void ApplyDifficultyModifiers()
	{
		if (sv_delta_levelOneHp)
			maxHealth = health = levelOneHp;
		if (sv_delta_blind)
			blind = true;
	}
	
	bool IsBlind() const
	{
		return blind;
	}
}

class DeltaPacifistFail : Actor
{
	override string GetObituary(Actor victim, Actor inflictor, Name mod, bool playerAttack)
	{
		return victim == inflictor? "$OBIT_DELTA_PACIFISTFAIL" : "";
	}
}