extend class DeltaPlayer
{
	protected DeltaFootstepType footstepType;
	protected double footstepTime, curFootstepTimer;
	
	property FootstepType : footstepType;
	property FootstepTime : footstepTime;
	
	virtual void TickFootsteps()
	{
		if (!player)
			return;
		
		let cmd = player.cmd,
			velFactor = max(abs(desiredMove.y), abs(desiredMove.x));
		
		if (velFactor > 1)
			velFactor = 1;
		
		velFactor *= crouchFactor;
		
		if (velFactor < 0.05 || health <= 0 || reactionTime || !IsGrounded())
		{
			curFootstepTimer = 0;
			return;
		}
		
		curFootstepTimer += velFactor;
		
		if (curFootstepTimer >= footstepTime)
		{
			curFootstepTimer -= footstepTime;
			Step(velFactor);
		}
	}
	
	virtual void Step(double curVel)
	{
		if (reactionTime)
			return;
		
		let terrain = GetFloorTerrain();
		if (!terrain)
			return;
		
		let snd = terrain.StepSound;
		if (!snd)
			snd = terrain.isLiquid? "delta/step_liquid" : "delta/step_generic";
		
		A_StartSound(snd, CHAN_AUTO, volume: min(0.75, curVel));
	}
}