extend class DeltaPlayer
{
	protected int levelOneHp;
	
	property LevelOneHP : levelOneHp;
	
	virtual void ApplyDifficultyModifiers()
	{
		if (sv_delta_levelOneHp)
			maxHealth = health = levelOneHp;
		if (sv_delta_blind)
			blind = true;
	}
}

class DeltaPacifistFail : Actor
{
	override string GetObituary(Actor victim, Actor inflictor, Name mod, bool playerAttack)
	{
		return victim == inflictor? "$OBIT_DELTA_PACIFISTFAIL" : "";
	}
}