extend class DeltaPlayer
{
	const VOICE_CHANNEL = CHAN_VOICE;
	const PAIN_TIMER_START = DAMAGE_IFRAMES + 5;
	
	protected DeltaVoicePriority lastPriority;
	protected string voiceClass;
	protected double jumpGruntChance;
	protected int painTimer, painAmount;
	protected name painMod;
	
	property VoiceClass : voiceClass;
	property JumpGruntChance : jumpGruntChance;
	
	protected void TickVoice()
	{
		if (painTimer > 0 && (lastPriority != VOX_PAIN || !IsActorPlayingSound(VOICE_CHANNEL)))
			painTimer--;
		
		if (painTimer != -1)
			return;
		
		painTimer = PAIN_TIMER_START;
		string painSnd = "light_pain";
		let priorityOffset = 0,
			lowHpThreshold = GetMaxHealth() / 3,
			medThreshold = GetMaxHealth() / 5,
			severeThreshold = GetMaxHealth() / 2;
		
		if (painAmount >= severeThreshold
			|| (painAmount >= medThreshold && health <= lowHpThreshold))
		{
			painSnd = "severe_pain";
			priorityOffset = 2;
		}
		else if (painAmount >= medThreshold || health <= lowHpThreshold)
		{
			painSnd = "medium_pain";
			priorityOffset = 1;
		}
		
		DoSpeak(painSnd, VOX_PAIN + priorityOffset);
		painAmount = 0;
	}
	
	bool CanSpeak(int priority)
	{
		if (!cl_delta_voice)
			return false;
		if (voiceClass == "")
			return false;
		if (priority < VOX_LEAST_IMPORTANT || priority > VOX_MOST_IMPORTANT)
			return false;
		if (!IsActorPlayingSound(VOICE_CHANNEL))
			return true;
		if (lastPriority > priority)
			return false;
		
		// we fallthrough here if our priority is higher or equal to that of
		// the sound currently being played
		return true;
	}
	
	void DoSpeak(string snd, int priority = VOX_LEAST_IMPORTANT, int flags = 0)
	{
		if (!CanSpeak(priority))
			return;
		
		/*	Example: if Kris needs a jump grunt, our voiceClass would be "kris"
			and snd would be "jump_grunt".
			
			Which means targetSnd would be "delta/kris/jump_grunt".	*/
		string targetSnd = "delta/" .. voiceClass .. "/" .. snd;
		//A_Log("targetSnd: " .. targetSnd);
		
		lastPriority = priority;
		A_StartSound(targetSnd, CHAN_VOICE, flags);
	}
	
	void VoiceDamage(int damage, Name mod)
	{
		if (damage <= 0 || health <= 0)
			return;
		
		if (painTimer > 0)
			return;
		if (mod == "Drowning")
			return;
		
		painAmount += damage;
		painMod = mod;
		painTimer = -1;
	}
	
	void VoiceDeath(Name mod)
	{
		if (health > 0 || mod == "Drowning" || mod == "Falling")
			return;
		
		painTimer = -1;
		painAmount = 0;
		string deathSnd = "medium_death";
		
		if (health <= -GetMaxHealth()/2)
			deathSnd = "severe_death";
		
		DoSpeak(deathSnd, VOX_DEATH);
	}
}