extend class DeltaPlayer
{
	protected bool isUsingOffhand;
	protected string offhandIcon;
	protected double offhandTpCost;
	protected double preOffhandTp;	// used for refunding TP if offhand fails
	protected int preOffhandTpTimer;
	
	private TextureID _offhandIconId;
	
	virtual void StartOffhand()
	{
		isUsingOffhand = true;
		A_Overlay(PSP_OFFHAND, "OffhandOverlay");
		A_OverlayFlags(PSP_OFFHAND, PSPF_ADDBOB, true);
	}
	
	virtual bool TryStartOffhand()
	{
		if (!CanUseOffhand())
			return false;
		
		preOffhandTp = tensionPoints;
		preOffhandTpTimer = tensionDrainTimer;
		
		if (!TryTakeTension(offhandTpCost))
			return false;
		
		StartOffhand();
		return true;
	}
	
	// Wrap up
	action void A_EndOffhand()
	{
		invoker.isUsingOffhand = false;
	}
	
	clearscope virtual bool CanUseOffhand()
	{
		return true;
	}
	
	clearscope bool GetIsUsingOffhand()
	{
		return isUsingOffhand;
	}
	
	clearscope TextureID GetOffhandIconID()
	{
		return _offhandIconId;
	}
}