extend class DeltaPlayer
{
	virtual void SetUpLegs()
	{
		A_Overlay(PSP_LEGS, "IdleLegs");
		let off = GetLegsOffset();
		A_OverlayOffset(PSP_LEGS, off.x, off.y);
	}
	
	virtual void HandleLegs()
	{
		if (!player || player.health <= 0 || IsPredicting())
			return;
		
		let psp = player.FindPSprite(PSP_LEGS);
		if (!psp)
			return;
		
		psp.bAddBob = false;
		psp.bAddWeapon = false;
		
		let off = GetLegsOffset();
		A_OverlayOffset(PSP_LEGS, off.x, off.y, WOF_INTERPOLATE);
		
		AnimateLegs();
		
		if (!cl_delta_showLegs)
			psp.frame = -1;
	}
	
	virtual void AnimateLegs()
	{
		let psp = player.FindPSprite(PSP_LEGS);
		
		bool inIdle = LegsInIdleState(),
			inWalk = LegsInWalkState(),
			inRun = LegsInRunState(),
			inAir = LegsInAirState(),
			inCrouchWalk = LegsInCrouchWalkState(),
			inJurisdiction = (inAir || inIdle || inWalk || inRun || inCrouchWalk);
		
		if (inJurisdiction && waterLevel >= 2 && !IsGrounded())
		{
			if (psp)
				psp.frame = -1;
			
			return;
		}
		
		if ((coyoteTimer >= ANIM_GROUNDED_HANG_TIME && pos.z != floorz) && inJurisdiction)
		{
			AnimateLegsAir();
			return;
		}
		
		bool doingMoveInput = player? (player.cmd.forwardMove || player.cmd.sideMove)
			: false,
			running = player? (abs(player.cmd.forwardMove) > 6400
				|| abs(player.cmd.sideMove) > 6144) : false;
		
		if (!inJurisdiction)
			return;
		
		if (doingMoveInput)
			AnimateLegsWalking();
		else
			AnimateLegsIdle();
	}
	
	clearscope Vector2 CalculateLegsOffset(double realPitch)
	{
		double
			fovFactor = (1/90.),
			x = fovFactor * 6400 * cos(pitch + viewPitch) * sin(viewAngle),
			y = (-realPitch) * fovFactor * 200;
		
		if (y < 0)
			y = 0;
		return (x, y);
	}
	
	virtual Vector2 GetLegsOffset()
	{
		return CalculateLegsOffset(pitch + viewPitch - 90);
	}
	
	virtual void AnimateLegsIdle()
	{
		let psp = player.FindPSprite(PSP_LEGS);
		bool inWalk = LegsInWalkState(),
			inRun = LegsInRunState(),
			inAir = LegsInAirState(),
			inCrouchWalk = LegsInCrouchWalkState();
		state targetState;
		
		if (inWalk || inRun || inAir || inCrouchWalk)
			psp.SetState(ResolveState("IdleLegs"));
		
		if (LegsInIdleState())
		{
			int targetFrame = 0;
			double diff = viewHeight - player.viewHeight;
			
			targetFrame = clamp(int(diff / 4.), int(player.deltaViewHeight < 0), 4);
			psp.frame = targetFrame;
		}
	}
	
	virtual void AnimateLegsWalking()
	{
		let inIdle = LegsInIdleState(),
			inWalk = LegsInWalkState(),
			inRun = LegsInRunState(),
			inAir = LegsInAirState(),
			inCrouchWalk = LegsInCrouchWalkState(),
			crouching = IsCrouching(),
			running = player ? ((player.buttons & BT_RUN) && waterLevel < 2) : false;
		
		let psp = player.FindPSprite(PSP_LEGS);
		state targetState;
		
		if (crouching && (inWalk || inRun || inAir || inIdle))
			targetState = inIdle ? ResolveState("CrouchWalkLegs") : ResolveState("CrouchWalkLoopLegs");
		else if (!crouching)
		{
			if (running && (inWalk || inAir || inIdle || inCrouchWalk))
				targetState = inIdle ? ResolveState("RunLegs") : ResolveState("RunLoopLegs");
			else if (!running && (inRun || inAir || inIdle || inCrouchWalk))
				targetState = inIdle ? ResolveState("WalkLegs") : ResolveState("WalkLoopLegs");
		}
		
		if (targetState)
			psp.SetState(targetState);
		
		if (psp.tics == -1)
		{
			int targetTics;
			
			if (inWalk || inRun)
				targetTics = running ? 2 : 4;
			else if (inCrouchWalk)
				targetTics = running ? 4 : 7;
			
			psp.tics = targetTics;
		}
	}
	
	virtual void AnimateLegsAir()
	{
		let psp = player.FindPSprite(PSP_LEGS);
		
		if (LegsInIdleState() || LegsInWalkState() || LegsInRunState() || LegsInCrouchWalkState())
			psp.SetState(ResolveState("AirLegs"));
		
		let stoppedThreshold = 1.,
			slowThreshold = 8.,
			targetFrame = 4,
			airTimeDrop1 = 10,		// tics in the air until our legs can start lowering
									// (makes moving down steps look less jank)
			airTimeDrop2 = 20;
		
		if (vel.z < 0 && coyoteTimer < airTimeDrop1)
			targetFrame = 4;
		else if (vel.z < 0 && coyoteTimer < airTimeDrop2)
			targetFrame = 3;
		else if (vel.z > slowThreshold)
			targetFrame = 0;
		else if (vel.z > stoppedThreshold)
			targetFrame = 1;
		else if (vel.z >= -stoppedThreshold)
			targetFrame = 2;
		else if (vel.z > -slowThreshold)
			targetFrame = 3;
		
		psp.frame = targetFrame;
	}
	
	bool LegsInIdleState()
	{
		let psp = player.FindPSprite(PSP_LEGS);
		if (!psp || !psp.curState)
			return false;
		
		return psp.curState.InStateSequence(ResolveState("IdleLegs"));
	}
	
	bool LegsInWalkState()
	{
		let psp = player.FindPSprite(PSP_LEGS);
		if (!psp || !psp.curState)
			return false;
		
		return psp.curState.InStateSequence(ResolveState("WalkLegs"));
	}
	
	bool LegsInRunState()
	{
		let psp = player.FindPSprite(PSP_LEGS);
		if (!psp || !psp.curState)
			return false;
		
		return psp.curState.InStateSequence(ResolveState("RunLegs"));
	}
	
	bool LegsInAirState()
	{
		let psp = player.FindPSprite(PSP_LEGS);
		if (!psp || !psp.curState)
			return false;
		
		return psp.curState.InStateSequence(ResolveState("AirLegs"));
	}
	
	bool LegsInCrouchWalkState()
	{
		let psp = player.FindPSprite(PSP_LEGS);
		if (!psp || !psp.curState)
			return false;
		
		return psp.curState.InStateSequence(ResolveState("CrouchWalkLegs"));
	}
}