class KrisPlayer : DeltaPlayer
{
	protected bool isSliding;
	protected double slideAngle;
	protected double slideSpeed;		// normal slide speed
	protected double slideAdjustSpeed;	// speed at which strafing will move you while sliding
	protected double slideSlowing;		// time it takes sliding to slow to a stop on flat surface
	
	private double _currentSlideSpeed, _savedSlideSpeed;
	private int _savedSlideSpeedTimer, _slideBuffer;
	private int _slideTics;				// used for smooth transitions into sliding effectss
    
	const MAX_SLIDE_TICS = 7;
	const PARRY_TP_COST = floor(0.4 * 250);
	
	Default
	{
		Height 46;
		Radius 16;
		Speed 0.8;
		Mass 100;
		
		Health 100;
		Player.MaxHealth 100;
		
		Player.DisplayName "$DELTA_CHAR_KRIS";
		Player.ViewHeight 35.0;
		
		Player.WeaponSlot 1, "KrisSword";
		Player.WeaponSlot 2, "KrisRevolver";
		Player.WeaponSlot 3, "KrisShotgun";
		Player.WeaponSlot 4, "KrisSMG";
		// Player.WeaponSlot 5, "KrisGrenadeLauncher";
		// Player.WeaponSlot 6, "KrisCrossbow";
		
		Player.StartItem "KrisSword";
		Player.StartItem "KrisRevolver";
		Player.StartItem "Clip", 15;
		Player.StartItem "DeltaParryDamage"; 	// hacky af workaround for more consistent
												// projectile parry damage
		
		Player.Face "KRF";
		
		DeltaPlayer.HugReactionTime 20;
		DeltaPlayer.CharacterColor Color(0, 162, 232);
		DeltaPlayer.OffhandIcon "SHLDPRRY";
		DeltaPlayer.CharacterIcon "graphics/krisIcon.png";
		DeltaPlayer.GunStandSprite "KRSG";
		DeltaPlayer.MeleeStandSprite "KRSW";
		DeltaPlayer.GunCrouchSprite "KCGN";
		DeltaPlayer.MeleeCrouchSprite "KCSW";
		
		+SQUAREPIXELS;
	}
	
	States
	{
		Spawn:
			TNT1 A 1 NoDelay A_DeltaGetState("Spawn");
			Loop;
		SpawnMelee:
			#### A 1 A_UseMeleeSprite;
			Loop;
		SpawnGun:
			#### A 1 A_UseGunSprite;
			Loop;
		SeeMelee:
			#### BACA -1;
			Loop;
		SeeGun:
			#### BACA -1;
			Loop;
		AirMelee:
			KRSW JKLM 3;
			Loop;
		AirGun:
			KRSG JKLM 3;
			Loop;
		Lunge:
			KRSW D 1;
			Loop;
		MissileMelee:
			#### EEFFGGGHHH 1
			{
				A_UseMeleeSprite();
				
				if (invoker.isSliding)
					return A_Sync(ResolveState("MissileMelee"), ResolveState("SlideMissileMelee"));
				
				return A_SyncIf(!invoker.IsGrounded(), ResolveState("MissileMelee"), ResolveState("AirMissileMelee"));
			}
			Goto SpawnMelee;
		AirMissileMelee:
			KRSW NNOOPPPQQQ 1
			{
				return A_SyncIf(invoker.IsGrounded(), ResolveState("AirMissileMelee"), ResolveState("MissileMelee"));
			}
			Goto AirMelee;
		MissileGun:
			#### DDDD 1
			{
				A_UseGunSprite();
				if (invoker.isSliding)
					return A_Sync(ResolveState("MissileGun"), ResolveState("SlideMissileGun"));
				
				return A_SyncIf(!invoker.IsGrounded(), ResolveState("MissileGun"), ResolveState("AirMissileGun"));
			}
			Goto FinishMissileGun;
		MissileGunNoFlash:
			#### EEEE 1
			{
				A_UseGunSprite();
				if (invoker.isSliding)
					return A_Sync(ResolveState("MissileGun"), ResolveState("SlideMissileGun"));
				
				return A_SyncIf(!invoker.IsGrounded(), ResolveState("MissileGun"), ResolveState("AirMissileGun"));
			}
		FinishMissileGun:
			#### EEEEEEEE 1
			{
				A_UseGunSprite();
				if (invoker.isSliding)
					return A_Sync(ResolveState("MissileGun"), ResolveState("SlideMissileGun"));
				
				return A_SyncIf(!invoker.IsGrounded(), ResolveState("MissileGun"), ResolveState("AirMissileGun"));
			}
			Goto SpawnGun;
		AirMissileGun:
			KRSG NNNNOOOOOOOO 1
			{
				return A_SyncIf(invoker.IsGrounded(), ResolveState("AirMissileGun"), ResolveState("MissileGun"));
			}
			Goto AirGun;
		Slide:
			TNT1 A 0 A_DeltaGetState("Slide");
			Goto Spawn;
		SlideMelee:
			KSLD AAABBBCCC 1
			{
				return A_JumpIf(!invoker.isSliding, "Spawn");
			}
			Loop;
		SlideGun:
			KSLG AAABBBCCC 1
			{
				return A_JumpIf(!invoker.isSliding, "Spawn");
			}
			Loop;
		SlideMissileMelee:
			KSLD DDEEFFFGGG 1
			{
				return A_SyncIf(!invoker.isSliding, ResolveState("SlideMissileMelee"), ResolveState("MissileMelee"));
			}
			Goto SlideMelee;
		SlideMissileGun:
			KSLG EEEEFFFFFFFF 1
			{
				return A_SyncIf(!invoker.isSliding, ResolveState("SlideMissileGun"), ResolveState("MissileGun"));
			}
			Goto SlideGun;
		Pain:
			TNT1 A 1 A_DeltaGetState("Pain");
			Goto Spawn;
		PainMelee:
			KRSW IIIIIIII 1
			{
				A_UseMeleeSprite();
				
				if (invoker.isSliding)
					return A_Sync(ResolveState("PainMelee"), ResolveState("SlidePainMelee"));
				
				return A_SyncIf(!invoker.IsGrounded(), ResolveState("PainMelee"), ResolveState("AirPainMelee"));
			}
			Goto SpawnMelee;
		PainGun:
			KRSG IIIIIIII 1
			{
				A_UseGunSprite();
				
				if (invoker.isSliding)
					return A_Sync(ResolveState("PainGun"), ResolveState("SlidePainGun"));
				
				return A_SyncIf(!invoker.IsGrounded(), ResolveState("PainGun"), ResolveState("AirPainGun"));
			}
			Goto SpawnGun;
		AirPainMelee:
			KRSW RRRRRRRR 1
			{
				A_UseMeleeSprite();
				return A_SyncIf(invoker.IsGrounded(), ResolveState("AirPainMelee"), ResolveState("PainMelee"));
			}
			Goto AirMelee;
		AirPainGun:
			KRSG RRRRRRRR 1
			{
				A_UseGunSprite();
				return A_SyncIf(invoker.IsGrounded(), ResolveState("AirPainGun"), ResolveState("PainGun"));;
			}
			Goto AirGun;
		SlidePainMelee:
			KSLD AAAAAAAA 1
			{
				return A_SyncIf(!invoker.isSliding, ResolveState("SlidePainMelee"), ResolveState("PainMelee"));
			}
			Goto SlideMelee;
		SlidePainGun:
			KSLG AAAAAAAA 1
			{
				return A_SyncIf(!invoker.isSliding, ResolveState("SlidePainGun"), ResolveState("PainGun"));
			}
			Goto SlideGun;
		Parry:
			KPRY AABBCCCCDDDD 1 A_SyncIf(!invoker.IsGrounded(), ResolveState("Parry"), ResolveState("AirParry"));
			Goto Spawn;
		AirParry:
			KPRY FFGGHHHHIIII 1 A_SyncIf(invoker.IsGrounded(), ResolveState("AirParry"), ResolveState("Parry"));
			Goto Spawn;
		ParryMiss:
			KPRY AA 1 A_SyncIf(!invoker.IsGrounded(), ResolveState("ParryMiss"), ResolveState("AirParryMiss"));
			Goto Parry+2;
		AirParryMiss:
			KPRY JJ 1 A_SyncIf(invoker.IsGrounded(), ResolveState("AirParryMiss"), ResolveState("ParryMiss"));
			Goto AirParry+2;
		Death:
			KDTH A 1 A_JumpIfAirborne(ResolveState("AirDeath"));
			KDTH A 5 A_JumpIfAirborne(ResolveState("AirDeath"));
			KDTH B 9;
			KDTH C 3 A_JumpIfAirborne(ResolveState("AirDeath"));
		Death.Falling:
		Death.Crush:
		FinishDeath:
			KDTH D 3;
			KDTH E 3 A_DeathImpact;
			KDTH F 7;
			#### # 1 A_SpawnDeathSoul;
			#### # -1;
			Stop;
		AirDeath:
			KDTH GHIJK -1;
			Loop;
		/*
		Death.Ice:
			DKRF A 2 A_DeltaFreezeDeath;
			#### BCD 2;
			Goto FinishIce;
		FinishIce:
			DKRF E TICRATE;
			#### # 1 A_SpawnDeathSoul;
			#### # -1;
			Stop;
		*/
		
		// ============
		//   OVERLAYS  
		// ============
		OffhandOverlay:
			TNT1 A 0 A_StartOffhand;
		ParryOverlay:
			DKSL A 2 A_KrisShieldParry;
			DKSL B 2;
			DKSL C 2;
			DKSL D 4;
			DKSL E 2;
			TNT1 A 5;
			TNT1 A 1 A_EndOffhand;
			Stop;
		
		SlideOverlay:
			KRSL ABC 1;
			KRSL D -1;
			Stop;
		StopSlideOverlay:
			KRSL EFGH 1;
			Stop;
	}
	
	override void AnimateDeath()
	{
		if (!InAirDeathState())
			return;
		
		int minTics = 3,
			maxTics = 15,
			targetTics = abs(Vel.Z) ~== 0 ? maxTics
				: DeltaUtil.Clamp(maxTics / abs(Vel.Z), minTics, maxTics);
		if (tics == -1 || tics > targetTics)
			tics = targetTics;
		
		let dest = A_CheckDeathLand();
		if (dest)
			SetState(dest);
	}
	
	override void PostBeginPlay()
	{
		Super.PostBeginPlay();
		
		slideSpeed = 18;
		slideAdjustSpeed = 3;
		_savedSlideSpeed = slideSpeed;
		slideSlowing = 6.6;
	}
	
	override void Travelled()
	{
		if (isSliding)
			EndSlide();
		_slideTics = 0;
		
		Super.Travelled();
	}
	
	override void PlayerThink()
	{
		Super.PlayerThink();
		
		if (IsPredicting())
			return;
		
		HandleSlide();
	}
	
	override void CheckJump()
	{
		if (!level.IsJumpingAllowed())
		{
			Super.CheckJump();
			return;
		}
		
		if (isSliding)
		{
			float oldVel = vel.z;
			
			Super.CheckJump();
			
			if (vel.z > oldVel && vel.z == JumpZ * 35 / TICRATE)
				EndSlide();
			
			return;
		}
		
		Super.CheckJump();
	}
	
	override void CheckCrouch(bool totallyFrozen)
	{
		let player = self.player;
		int buttons = player.cmd.buttons;
		
		if (CanCrouch() && player.health > 0 && level.IsCrouchingAllowed()
			&& !totallyfrozen)
		{
			int crouchDir = player.crouching;
			
			if (crouchDir == 0)
				crouchDir = (buttons & BT_CROUCH) ? -1 : 1;
			else if (buttons & BT_CROUCH)
				player.crouching = 0;
			
			if ((buttons & BT_CROUCH) && !(player.oldButtons & BT_CROUCH))
				_slideBuffer = 3;
			else if (_slideBuffer)
				_slideBuffer--;
			
			if (jumpBuffer)
				_slideBuffer = 0;
			
			if (crouchDir == 1 && crouchFactor < 1 && pos.z + height < ceilingz)
				CrouchMove(2);
			else if (crouchDir == -1 && crouchFactor > 0.5)
				CrouchMove(-2);
			
			if (!isSliding && _slideBuffer && (buttons & BT_RUN) && IsGrounded() && IsCrouching())
			{
				let dir = (GetPlayerInput(INPUT_FORWARDMOVE) / 12800., GetPlayerInput(INPUT_SIDEMOVE) / 10240.);
				
				if (abs(dir.x) > 0.1 || abs(dir.y) > 0.1)
					StartSlide(VectorAngle(dir.x, dir.y) - Angle);
			}
			else if (crouchDir == 1 && isSliding)
				EndSlide();
		}
		else if (!totallyfrozen)
			DeltaUncrouch();

		player.crouchOffset = -(ViewHeight) * (1 - crouchFactor);
	}
	
	override void DeltaUncrouch()
	{
		Super.DeltaUncrouch();
		
		if (isSliding)
			EndSlide();
	}
	
	// make sure we're not bobbing if we're sliding
	override void CalcHeight()
	{
		let tempZ = pos.Z + ViewHeight + player.crouchViewDelta;

		if (tempZ > ceilingZ-4)
			tempZ = ceilingZ-4;
		
		Super.CalcHeight();
		
		player.viewZ = player.viewZ + (tempZ - player.viewZ) * (double(_slideTics) / MAX_SLIDE_TICS);
	}
	
	override bool CanCollideWith(Actor other, bool passive)
	{
		if (!isSliding)
			return Super.CanCollideWith(other, passive);
		
		if (other.bIsMonster && other.mass <= 200 && (!other.player || !other.player.cheats & CF_PREDICTING))
			return false;
		
		return Super.CanCollideWith(other, passive);
	}
	
	override bool PreTeleport(Vector3 destPos, double destAngle, int flags)
	{
		let oldAng = angle;
		let result = Super.PreTeleport(destPos, destAngle, flags);
		
		if (result && isSliding)
			slideAngle += DeltaAngle(destAngle, oldAng);
		
		return result;
	}
	
	override void MakeFootsteps()
	{
		if (isSliding)
			return;
		
		Super.MakeFootsteps();
	}
	
	override void PlayerLandedMakeGruntSound(actor onmobj)
	{
		if (!isSliding)
			Super.PlayerLandedMakeGruntSound(onmobj);
	}
	
	override double GetViewRoll()
	{
		double _roll = Super.GetViewRoll();
		_roll += 3 * (double(_slideTics) / MAX_SLIDE_TICS);
		
		return _roll;
	}
	
	override void HandleRalseiHugs()
	{
		Super.HandleRalseiHugs();
		
		if (beingHugged)
		{
			A_SetMugshotState("Normal");	// wanna make sure blush is ALWAYS called
			A_SetMugshotState("Blush");
		}
	}
	
	override double GetGrazeMultiplier()
	{
		return GetIsUsingOffhand() ? 0.25 : 1;
	}
	
	protected void HandleSlide()
	{
		let
			slideX = cos(slideAngle) * _currentSlideSpeed,
			slideY = -sin(slideAngle) * _currentSlideSpeed,
			actorX = cos(Angle),
			actorY = sin(Angle),
			legsOffsetX = 3 * viewAngle*cos(pitch+viewPitch) / (player.fov/90),
			legsOffsetY = 80 - 3 * (pitch+viewPitch) / (player.fov/90);
		
		// 2.35 px every degree up to 34.1 looking down. 0 deg should be 48
		A_OverlayOffset(PSP_LEGS, legsOffsetX, max(38, legsOffsetY), WOF_INTERPOLATE);
			
		if (isSliding)
		{
			if (_slideTics < MAX_SLIDE_TICS)
				_slideTics++;
			
			if (reactionTime)
				return;
			
			let
				sideInput = GetPlayerInput(INPUT_SIDEMOVE) / 10240.,
				adjustFactor = sideInput * slideAdjustSpeed * (_currentSlideSpeed / slideSpeed);
			
			slideX += sin(Angle) * adjustFactor;
			slideY -= cos(Angle) * adjustFactor;
			
			A_ChangeVelocity(slideX, slideY, Vel.Z, CVF_REPLACE);
			
			if (coyoteTimer <= COYOTE_TIME)
			{
				_currentSlideSpeed = max(0, _currentSlideSpeed - (slideSlowing / TICRATE));
				
				if (!IsActorPlayingSound(6))
					A_StartSound("delta/kris/slide_loop", 6, CHANF_LOOPING, _currentSlideSpeed / slideSpeed);
				else
					A_SoundVolume(6, _currentSlideSpeed / slideSpeed);
				
				if (_currentSlideSpeed < 1)
				{
					EndSlide();
					_currentSlideSpeed = 0;
					_savedSlideSpeed = slideSpeed;
				}
				else
				{
					if (_currentSlideSpeed > 1)
						_savedSlideSpeed = _currentSlideSpeed;
					else
						_savedSlideSpeed = slideSpeed;
				}
				
				_savedSlideSpeedTimer = TICRATE / 10;
			}
			else if (IsActorPlayingSound(6))
				A_StopSound(6);
		}
		else
		{
			if (_slideTics > 0)
				_slideTics--;
				
			if (IsActorPlayingSound(6))
				A_StopSound(6);
			
			if (!IsGrounded())
				_savedSlideSpeed = max(_savedSlideSpeed, -Vel.Z * 0.75);
			else
			{
				if (_savedSlideSpeedTimer > 0)
					_savedSlideSpeedTimer--;
				else if (_savedSlideSpeedTimer != -1)
				{
					_savedSlideSpeed = slideSpeed;
					_savedSlideSpeedTimer = -1;
				}
			}
		}
		
		customBobPerc = 1 - (double(_slideTics) / MAX_SLIDE_TICS);
		customBobPerc *= customBobPerc;
	}
	
	protected void StartSlide(double slideAngle, bool resetSpeed = true)
	{
		if (!IsGrounded() || GetIsUsingOffhand())
			return;
		
		self.slideAngle = slideAngle;
		isSliding = true;
		
		if (resetSpeed)
			_currentSlideSpeed = max(_savedSlideSpeed, Vel.PlusZ(-Vel.Z).Length());
		
		if (IsPredicting())
			return;
		
		A_StartSound("delta/kris/slide_start", CHAN_AUTO);
		A_Overlay(PSP_LEGS, "SlideOverlay");
		
		let overlay = player.FindPSprite(PSP_LEGS);
		if (!overlay)
			return;
		
		overlay.bAddWeapon = false;
		overlay.bAddBob = false;
	}
	
	protected void EndSlide()
	{
		isSliding = false;
		
		// prevent legs reappearing if we stop sliding as result of death
		if (Health <= 0)
			return;
		
		let psp = player.FindPSprite(PSP_LEGS);
		if (!psp)
			return;
		
		psp.SetState(ResolveState("StopSlideOverlay"), true);
	}
	
	protected action void A_SpawnDeathSoul(double zOffset = 36)
	{
		let soul = DeltaSoul(Spawn("DeltaSoul", Vec3Offset(0, 0, zOffset)));
		
		if (player)
			soul.playerParent = player;
	}
	
	protected void KrisShieldParry()
	{
		A_StartSound("delta/kris/shield_swing", CHAN_AUTO);
		AddRecoil(RECOIL_WEAPON, 10, 1, p: -1, y: 5);
		
		double distance = 120;
		Array<Actor> targets;
		double dotThreshold = 0.85; // dot product must be larger than this to count as parried
		
		ThinkerIterator it = ThinkerIterator.Create("Actor", STAT_DEFAULT);
		Actor mis;
		
		while (mis = Actor(it.Next()))
		{
			if (!mis.CanCollideWith(self, false))
				continue;
			if (!mis.GetMissileDamage(0, 1) && !mis.bIsMonster)
				continue;
			
			if (mis.bRipper) // rippers can't be parried
				continue;
			if (!mis.bIsMonster && mis.target && IsFriend(mis.target)) // friendly projectiles shouldn't be parried
				continue;
			if (!mis.bMissile && !mis.bSkullfly)
			{
				if (!mis.bIsMonster)
					continue;
				if ((!mis.curState.InStateSequence(mis.ResolveState("Melee"))
						&& (!mis.curState.InStateSequence(mis.ResolveState("Missile")) || !(mis is "Cacodemon")))
						// we only wanna be able to parry an enemy's missile
						// state if it's a cacodemon, as that's the state they
						// use for their bite attack
					|| damageTics != 0)
					continue;
			}
			if (mis.curState.InStateSequence(mis.ResolveState("Death")))
				continue;
			if (mis.bMissile && mis.target == self) // "target" with projectiles is used to figure out who threw it
				continue;
			
			let parriable = DeltaParriable(mis);
			if (parriable && !parriable.CanBeParried())
				continue;
			
			// code largely taken from ThinkerIterator documentation page
			double blockDist = distance + (mis.radius * 1.5);
			double blockHeight = distance + (mis.height * 1.5);
			Vector3 diff = level.Vec3Diff(pos, mis.pos);
			
			if (Distance2DSquared(mis) > blockDist**2)
				continue;
			if (abs(diff.z) > blockHeight)
				continue;
			
			Vector3 forward = DeltaUtil.GetActorForward(self);
			forward = forward.PlusZ(-forward.z);
			
			if ((diff dot forward) < 0.75)
				continue;
			
			targets.Push(mis);
		}
		
		double largestDot = -1;
		int largestDotIndex = -1;
		
		for (int i = 0; i < targets.Size(); i++)
		{
			let t = targets[i];
			let dir = level.Vec3Diff(pos, t.pos).Unit();
			let dotProduct = DeltaUtil.GetActorForward(self) dot dir;
			
			if (dotProduct > largestDot)
			{
				largestDot = dotProduct;
				largestDotIndex = i;
			}
		}
		
		if (largestDotIndex == -1)
		{
			SetState(ResolveState("ParryMiss"));
			return;
		}
		
		TryTakeTension(PARRY_TP_COST, false);
		
		let parried = targets[largestDotIndex];
		let parriable = DeltaParriable(parried);
		
		SetState(ResolveState("Parry"));
		A_QuakeEx(0, 10, 5, 10, 0, 10, "dsempty", QF_RELATIVE | QF_SCALEDOWN);
		A_SetBlend("white", 0.3, 12);
		A_StartSound("delta/kris/shield_parry", CHAN_AUTO, attenuation: 1.0);
		damageTics = 12;
		
		double parryPitch = AimLineAttack(Angle, PLAYERMISSILERANGE,
			flags: ALF_CHECK3D | ALF_NOFRIENDS);
		double newSpeed = parried.bMissile ? 70 : 50;
		Vector2 vecToAng = AngleToVector(angle, 1);
		Vector2 vecToPitch = AngleToVector(parryPitch, 1);
		Vector3 newVel = (vecToAng.x, vecToAng.y, -vecToPitch.y) * newSpeed;
		
		if (parriable)
			parriable.OnParry(self);
		
		if (parried.bMissile)
		{
			int dam = parried.GetMissileDamage(0, bStrifeDamage ? 6 : 12);
			parried.SetOrigin(pos + (0, 0, viewHeight), false);
			
			let inv = DeltaParried(parried.GiveInventoryType("DeltaParried"));
			inv.oldTarget = parried.target;	// mostly for checking if we
											// knocked a player's own
											// projectile back at them for
											// obituaries
			parried.target = self;
			parried.tracer = null;
			
			parried.Vel = newVel;
			parried.Angle = Angle;
			parried.Pitch = parryPitch;
			parried.bForceRadiusDmg = true;
			parried.bForcePain = true;
			return;
		}
		
		let parryDamage = random[parryDmg](60, 90) * max(1,
			G_SkillPropertyFloat(SKILLP_MonsterHealth));
		
		if (parried.bSkullfly)
		{
			parried.Vel = newVel;
			parried.DamageMobj(self, self, parryDamage, 'Parry');
		}
		else if (parried.bIsMonster)
		{
			parried.DamageMobj(self, self, parryDamage, 'Parry');
			DeltaUtil.ForceActorPain(parried);
		}
	}
	
	action void A_KrisShieldParry()
	{
		invoker.KrisShieldParry();
	}
	
	override void DeltaExtraDeathStuff()
	{
		Super.DeltaExtraDeathStuff();
		
		if (isSliding)
			EndSlide();
	}
	
	override bool StartOffhand()
	{
		if (!GetTension(PARRY_TP_COST))
		{
			A_StartSound("delta/tp_fail", CHAN_ITEM, CHANF_LOCAL | CHANF_NOSTOP);
			return false;
		}
		
		return Super.StartOffhand();
	}
	
	void PlaySliding()
	{
		let curAnimType = DELTA_WEAPONANIM_GUN;
		if (player.ReadyWeapon && (player.ReadyWeapon is "DeltaWeapon"))
			curAnimType = DeltaWeapon(player.ReadyWeapon).GetAnimType();
		
		if (curAnimType != lastAnimType || InSeeState() || InSpawnState() || InAirState())
			SetState(A_DeltaGetState("Slide"));
	}
	
	override void AnimatePlayer()
	{
		if (InParryState())
			return;
		
		if (isSliding)
		{
			if (InPainState())
				SetState(A_DeltaGetState("SlidePain"));
			else
				PlaySliding();
		}
		else
		{
			if (InSlideState())
				SetState(SpawnState);
			
			Super.AnimatePlayer();
		}
	}
	
	override bool CanUseOffhand()
	{
		return GetTension(PARRY_TP_COST) != TP_FAIL;
	}
	
	bool InParryState()
	{
		return curState.InStateSequence(ResolveState("Parry"))
			|| curState.InStateSequence(ResolveState("ParryMiss"))
			|| curState.InStateSequence(ResolveState("AirParry"))
			|| curState.InStateSequence(ResolveState("AirParryMiss"));
	}
	
	bool InSlideState()
	{
		return CurState.InStateSequence(ResolveState("SlideMelee"))
			|| CurState.InStateSequence(ResolveState("SlideGun"))
			|| CurState.InStateSequence(ResolveState("SlideMissileMelee"))
			|| CurState.InStateSequence(ResolveState("SlideMissileGun"));
	}
}