class KrisPlayer : DeltaPlayer
{
	protected double slideAngleOffset;
	protected double slideSpeed;		// normal slide speed
	protected double slideAdjustSpeed;	// speed at which strafing will move you while sliding
	protected double slideSlowing;		// time it takes sliding to slow to a stop on flat surface
	
	protected state
		ParryState,				ParryMissState,
		AirParryState,			AirParryMissState,
		SlideMeleeState,		SlideGunState,
		SlideMissileMeleeState, SlideMissileGunState,
		SlideMissileGunNoFlashState, SlideFinishMissileGunState,
		SlidePainMeleeState, SlidePainGunState;
	
	private double _currentSlideSpeed, _savedSlideSpeed;
	private int _savedSlideSpeedTimer;
	private bool _lastCrouchedWhileAirborne, _lastCrouchedWhileGrounded;
	private int _slideTics;				// used for smooth transitions into sliding effects
	private int _slideTime;				// used for nerfing slide spamming
    
	const MAX_SLIDE_TICS = 7;
	const MIN_SLIDE_TIME = TICRATE / 3;
	
	Default
	{
		Height 46;
		Radius 16;
		Speed 0.8;
		Mass 100;
		
		Health 100;
		Player.MaxHealth 100;
		
		Player.DisplayName "$DELTA_CHAR_KRIS";
		Player.ViewHeight 35.0;
		
		Player.WeaponSlot 1, "KrisSword";
		Player.WeaponSlot 2, "KrisRevolver";
		Player.WeaponSlot 3, "KrisShotgun";
		Player.WeaponSlot 4, "KrisSMG";
		Player.WeaponSlot 5, "TempRocketLauncher";//"KrisGrenadeLauncher";
		Player.WeaponSlot 6, "TempIncinerator", "TempPlasmaRifle";//"KrisCrossbow";
		Player.WeaponSlot 7, "TempCalamityBlade", "TempBFG9000";
		
		Player.StartItem "KrisSword";
		Player.StartItem "KrisRevolver";
		Player.StartItem "Clip", 15;
		Player.StartItem "DeltaParryDamage"; 	// hacky af workaround for more consistent
												// projectile parry damage
		
		Player.Face "KRF";
		
		DeltaPlayer.HugReactionTime 20;
		DeltaPlayer.CharacterColor Color(0, 162, 232);
		DeltaPlayer.OffhandIcon "SHLDPRRY";
		DeltaPlayer.OffhandTpCost floor(0.4 * 250);
		
		DeltaPlayer.CharacterIcon "graphics/krisIcon.png";
		DeltaPlayer.NameTag "sprites/hud/krisTag.png";
		DeltaPlayer.GunStandSprite "KRSG";
		DeltaPlayer.MeleeStandSprite "KRSW";
		DeltaPlayer.GunCrouchSprite "KCGN";
		DeltaPlayer.MeleeCrouchSprite "KCSW";
		
		DeltaPlayer.FootstepType FOOTSTEP_BOOTS;
		DeltaPlayer.VoiceClass "kris";
		DeltaPlayer.JumpGruntChance 0.6;
	}
	
	States
	{
		Spawn:
			TNT1 A 1 NoDelay A_DeltaGetState("Spawn");
			Loop;
		SpawnMelee:
			#### A 1 A_UseMeleeSprite;
			Loop;
		SpawnGun:
			#### A 1 A_UseGunSprite;
			Loop;
		SeeMelee:
			#### BACA -1;
			Loop;
		SeeGun:
			#### BACA -1;
			Loop;
		AirMelee:
			KRSW JKLM 3;
			Loop;
		AirGun:
			KRSG JKLM 3;
			Loop;
		Lunge:
			KRSW D 1;
			Loop;
		MissileMelee:
			#### EEFFGGGHHH 1
			{
				A_UseMeleeSprite();
				
				if (invoker.crouchState == CS_SLIDING)
					return A_Sync(MissileMeleeState, SlideMissileMeleeState);
				
				return A_SyncIf(!invoker.IsGrounded(), MissileMeleeState, AirMissileMeleeState);
			}
			Goto SpawnMelee;
		AirMissileMelee:
			KRSW NNOOPPPQQQ 1
			{
				return A_SyncIf(invoker.IsGrounded(), AirMissileMeleeState, MissileMeleeState);
			}
			Goto AirMelee;
		MissileGun:
			#### DDDD 1
			{
				A_UseGunSprite();
				if (invoker.crouchState == CS_SLIDING)
					return A_Sync(MissileGunState, SlideMissileGunState);
				
				return A_SyncIf(!invoker.IsGrounded(), MissileGunState, AirMissileGunState);
			}
			Goto FinishMissileGun;
		MissileGunNoFlash:
			#### EEEE 1
			{
				A_UseGunSprite();
				if (invoker.crouchState == CS_SLIDING)
					return A_Sync(MissileGunNoFlashState, SlideMissileGunNoFlashState);
				
				return A_SyncIf(!invoker.IsGrounded(), MissileGunNoFlashState, AirMissileGunNoFlashState);
			}
		FinishMissileGun:
			#### EEEEEEEE 1
			{
				A_UseGunSprite();
				if (invoker.crouchState == CS_SLIDING)
					return A_Sync(FinishMissileGunState, SlideFinishMissileGunState);
				
				return A_SyncIf(!invoker.IsGrounded(), FinishMissileGunState, AirFinishMissileGunState);
			}
			Goto SpawnGun;
		AirMissileGun:
			KRSG NNNN 1
			{
				A_UseGunSprite();
				return A_SyncIf(invoker.IsGrounded(), AirMissileGunState, MissileGunState);
			}
			Goto AirFinishMissileGun;
		AirMissileGunNoFlash:
			KRSG OOOO 1
			{
				A_UseGunSprite();
				return A_SyncIf(invoker.IsGrounded(), AirMissileGunState, MissileGunState);
			}
		AirFinishMissileGun:
			KRSG OOOOOOOO 1
			{
				A_UseGunSprite();
				return A_SyncIf(invoker.IsGrounded(), AirFinishMissileGunState, FinishMissileGunState);
			}
			Goto AirGun;
		Slide:
			TNT1 A 0 A_DeltaGetState("Slide");
			Goto Spawn;
		SlideMelee:
			KSLD ABC 3;
			Loop;
		SlideGun:
			KSLG ABC 3;
			Loop;
		SlideMissileMelee:
			KSLD DDEEFFFGGG 1 A_SyncIf(invoker.crouchState != CS_SLIDING, SlideMissileMeleeState, MissileMeleeState);
			Goto SlideMelee;
		SlideMissileGun:
			KSLG EEEE 1 A_SyncIf(invoker.crouchState != CS_SLIDING, SlideMissileGunState, MissileGunState);
			Goto SlideFinishMissileGun;
		SlideMissileGunNoFlash:
			KSLG FFFF 1 A_SyncIf(invoker.crouchState != CS_SLIDING, SlideMissileGunNoFlashState, MissileGunNoFlashState);
		SlideFinishMissileGun:
			KSLG FFFFFFFF 1 A_SyncIf(invoker.crouchState != CS_SLIDING, SlideFinishMissileGunState, FinishMissileGunState);
		Pain:
			TNT1 A 1 A_DeltaGetState("Pain");
			Goto Spawn;
		PainMelee:
			KRSW IIIIIIII 1
			{
				A_UseMeleeSprite();
				
				if (invoker.crouchState == CS_SLIDING)
					return A_Sync(PainMeleeState, SlidePainMeleeState);
				
				return A_SyncIf(!invoker.IsGrounded(), PainMeleeState, AirPainMeleeState);
			}
			Goto SpawnMelee;
		PainGun:
			KRSG IIIIIIII 1
			{
				A_UseGunSprite();
				
				if (invoker.crouchState == CS_SLIDING)
					return A_Sync(PainGunState, SlidePainGunState);
				
				return A_SyncIf(!invoker.IsGrounded(), PainGunState, AirPainGunState);
			}
			Goto SpawnGun;
		AirPainMelee:
			KRSW RRRRRRRR 1
			{
				A_UseMeleeSprite();
				return A_SyncIf(invoker.IsGrounded(), AirPainMeleeState, PainMeleeState);
			}
			Goto AirMelee;
		AirPainGun:
			KRSG RRRRRRRR 1
			{
				A_UseGunSprite();
				return A_SyncIf(invoker.IsGrounded(), AirPainGunState, PainGunState);
			}
			Goto AirGun;
		SlidePainMelee:
			KSLD AAAAAAAA 1
			{
				return A_SyncIf(invoker.crouchState != CS_SLIDING, SlidePainMeleeState, PainMeleeState);
			}
			Goto SlideMelee;
		SlidePainGun:
			KSLG AAAAAAAA 1
			{
				return A_SyncIf(invoker.crouchState != CS_SLIDING, SlidePainGunState, PainGunState);
			}
			Goto SlideGun;
		Parry:
			KPRY AABBCCCCDDDD 1 A_SyncIf(!invoker.IsGrounded(), ParryState, AirParryState);
			Goto Spawn;
		AirParry:
			KPRY FFGGHHHHIIII 1 A_SyncIf(invoker.IsGrounded(), AirParryState, ParryState);
			Goto Spawn;
		ParryMiss:
			KPRY AA 1 A_SyncIf(!invoker.IsGrounded(), ParryMissState, AirParryMissState);
			Goto Parry+2;
		AirParryMiss:
			KPRY JJ 1 A_SyncIf(invoker.IsGrounded(), AirParryMissState, ParryMissState);
			Goto AirParry+2;
		Death:
			KDTH A 6;
			KDTH B 9;
			KDTH C 3;
		Death.Falling:
		Death.Crush:
		FinishDeath:
			KDTH D 3;
			KDTH E 3 A_DeathImpact;
			KDTH F 7;
			KDTH F 1 A_SpawnDeathSoul;
			KDTH F -1;
			Stop;
		AirDeath:
			KDTH GHIJK -1;
			Loop;
		
		// may come back to these at later time
		/*
		Death.Ice:
			DKRF A 2 A_DeltaFreezeDeath;
			#### BCD 2;
			Goto FinishIce;
		FinishIce:
			DKRF E TICRATE;
			#### # 1 A_SpawnDeathSoul;
			#### # -1;
			Stop;
		*/
	}
	
	States (Overlay)
	{
		// ====================
		//   OFFHAND OVERLAYS  
		// ====================
		OffhandOverlay:
			TNT1 A 0;
		ParryOverlay:
			DKSL A 2 A_KrisShieldParry;
			DKSL B 2;
			DKSL C 2;
			DKSL D 4;
			DKSL E 2;
			TNT1 A 5;
			TNT1 A 0 A_EndOffhand;
			Stop;
		
		// ================
		//   LEG OVERLAYS
		// ================
		IdleLegs:
			KLEG # 1;
			Loop;
		WalkLegs:
			KLEG A 3;
			KLGW A 2;
		WalkLoopLegs:
			KLGW BCDEFGHI -1;
			Loop;
		CrouchWalkLegs:
			KLEG A 3;
			KLCW A 2;
		CrouchWalkLoopLegs:
			KLCW BCDEFGHI -1;
			Loop;
		RunLegs:
			KLEG A 3;
			KLGR A 2;
		RunLoopLegs:
			KLGR BCDEFGHIJK -1;
			Loop;
		SlideLegs:
			KRSL ABCD 1;
			Wait;
		StopSlideLegs:
			KRSL EFGH 1;
			Goto FinishSlideLegs;
		FinishSlideLegs:
			KRSL H 1;
			Goto IdleLegs;
		AirLegs:
			KLGA # 1;
			Loop;
	}
	
	override void AnimateDeath()
	{
		if (!InAirDeathState())
		{
			Super.AnimateDeath();
			return;
		}
		
		int minTics = 3,
			maxTics = 15,
			targetTics = (abs(Vel.Z) ~== 0 || curSector.gravity ~== 0) ? maxTics
				: clamp(maxTics / curSector.gravity / abs(Vel.Z), minTics, maxTics);
		if (tics == -1 || tics > targetTics)
			tics = targetTics;
		
		let dest = A_CheckDeathLand();
		if (dest)
			SetStateSafe(dest);
	}
	
	override void BeginPlay()
	{
		Super.BeginPlay();
		
		ParryState = FindState("Parry");
		ParryMissState = FindState("ParryMiss");
		AirParryState = FindState("AirParry");
		AirParryMissState = FindState("AirParryMiss");
		SlideMeleeState = FindState("SlideMelee");
		SlideGunState = FindState("SlideGun");
		SlideMissileMeleeState = FindState("SlideMissileMelee");
		SlideMissileGunState = FindState("SlideMissileGun");
		SlideMissileGunNoFlashState = FindState("SlideMissileGunNoFlash");
		SlideFinishMissileGunState = FindState("SlideFinishMissileGun");
		SlidePainMeleeState = FindState("SlidePainMelee");
		SlidePainGunState = FindState("SlidePainGun");
	}
	
	override void PostBeginPlay()
	{
		Super.PostBeginPlay();
		
		slideSpeed = 18;
		slideAdjustSpeed = 3;
		_savedSlideSpeed = slideSpeed;
		slideSlowing = 6.6;
	}
	
	override void Travelled()
	{
		if (crouchState == CS_SLIDING)
			EndSlide();
		
		_slideTics = 0;
		_slideTime = 0;
		
		Super.Travelled();
	}
	
	override void PlayerThink()
	{
		Super.PlayerThink();
		
		if (IsPredicting())
			return;
		
		HandleSlide();
	}
	
	override void MovePlayer()
	{
		Super.MovePlayer();
		slideAngleOffset -= angleDiff;
	}
	
	override void CheckJump()
	{
		if (!level.IsJumpingAllowed())
		{
			Super.CheckJump();
			return;
		}
		
		if (crouchState == CS_SLIDING)
		{
			float oldVel = vel.z;
			
			Super.CheckJump();
			
			if (vel.z > oldVel && vel.z == JumpZ * 35 / TICRATE)
				EndSlide();
			
			return;
		}
		
		Super.CheckJump();
	}
	
	override void CheckCrouch(bool totallyFrozen)
	{
		Super.CheckCrouch(totallyFrozen);
		
		if (!player || totallyFrozen)
			return;
		
		int buttons = player.cmd.buttons,
			crouchDir = (buttons & BT_CROUCH) ? -1 : 1;
		bool doingMoveInput = buttons & (BT_FORWARD | BT_BACK | BT_MOVELEFT | BT_MOVERIGHT);
		
		if (crouchState != CS_SLIDING && ((buttons & BT_CROUCH && !(player.oldButtons & BT_CROUCH))
			|| (crouchDir == -1 && _lastCrouchedWhileAirborne && !_lastCrouchedWhileGrounded))
			&& IsGrounded() && IsCrouching())
		{
			let dir = (GetPlayerInput(INPUT_FORWARDMOVE) / 12800., GetPlayerInput(INPUT_SIDEMOVE) / 10240.);
			
			if (buttons & BT_RUN && (abs(dir.x) > 0.1 || abs(dir.y) > 0.1))
				StartSlide(-VectorAngle(dir.x, dir.y));
		}
		else if (crouchDir == -1 && crouchState == CS_SLIDING)
			CrouchMove(-2);
		else if ((crouchDir == 1 && _slideTime >= MIN_SLIDE_TIME) && crouchState == CS_SLIDING)
			EndSlide();
		
		if (IsGrounded() && crouchState != CS_SLIDING && buttons & BT_CROUCH)
			_lastCrouchedWhileGrounded = true;
		else if (crouchState == CS_SLIDING || !(buttons & BT_CROUCH))
			_lastCrouchedWhileGrounded = false;
		
		if (!IsGrounded() && crouchDir == -1)
			_lastCrouchedWhileAirborne = true;
		else if (crouchDir != -1 || !doingMoveInput || crouchState == CS_SLIDING)
			_lastCrouchedWhileAirborne = false;
	}
	
	override void DeltaUncrouch()
	{
		Super.DeltaUncrouch();
		
		if (crouchState == CS_SLIDING)
			EndSlide();
	}
	
	// make sure we're not bobbing if we're sliding
	override void CalcHeight()
	{
		let tempZ = pos.Z + ViewHeight + player.crouchViewDelta;

		if (tempZ > ceilingZ-4)
			tempZ = ceilingZ-4;
		
		Super.CalcHeight();
		
		player.viewZ = player.viewZ + (tempZ - player.viewZ) * (double(_slideTics) / MAX_SLIDE_TICS);
	}
	
	override bool CanCollideWith(Actor other, bool passive)
	{
		if (crouchState != CS_SLIDING)
			return Super.CanCollideWith(other, passive);
		
		if (other.bIsMonster && other.mass <= 200 && (!other.player || !other.player.cheats & CF_PREDICTING))
			return false;
		
		return Super.CanCollideWith(other, passive);
	}
	
	override void Step(double curVel)
	{
		if (crouchState == CS_SLIDING)
			return;
		
		Super.Step(curVel);
	}
	
	override void PlayerLandedMakeGruntSound(actor onmobj)
	{
		if (crouchState != CS_SLIDING)
			Super.PlayerLandedMakeGruntSound(onmobj);
	}
	
	override double GetViewRoll()
	{
		double _roll = Super.GetViewRoll();
		_roll += 5 * (double(_slideTics) / MAX_SLIDE_TICS);
		
		return _roll;
	}
	
	override void HandleRalseiHugs()
	{
		Super.HandleRalseiHugs();
		
		if (beingHugged)
		{
			A_SetMugshotState("Normal");	// wanna make sure blush is ALWAYS called
			A_SetMugshotState("Blush");
		}
	}
	
	override double GetGrazeMultiplier()
	{
		if (GetIsUsingOffhand())
			return 0.25;
		else if (crouchState == CS_SLIDING)
			return 0.5;
		
		return 1;
	}
	
	protected void HandleSlide()
	{
		let
			slideX = cos(angle + slideAngleOffset) * _currentSlideSpeed,
			slideY = sin(angle + slideAngleOffset) * _currentSlideSpeed,
			actorX = cos(Angle),
			actorY = sin(Angle);
		
		if (crouchState == CS_SLIDING)
		{
			if (_slideTics < MAX_SLIDE_TICS)
				_slideTics++;
			
			_slideTime++;
			
			if (reactionTime)
				return;
			
			let
				sideInput = GetPlayerInput(INPUT_SIDEMOVE) / 10240.,
				adjustFactor = sideInput * slideAdjustSpeed * (_currentSlideSpeed / slideSpeed);
			
			slideX += sin(Angle) * adjustFactor;
			slideY -= cos(Angle) * adjustFactor;
			
			if (player.cheats & CF_FROZEN)
			{
				vel = (0, 0, 0);
				return;
			}
			
			A_ChangeVelocity(slideX, slideY, Vel.Z, CVF_REPLACE);
			
			if (coyoteTimer <= COYOTE_TIME)
			{
				double friction, moveFactor;
				[friction, moveFactor] = GetFriction();
				
				let slowFactor = friction < ORIG_FRICTION ?
					ORIG_FRICTION_FACTOR / moveFactor :
					moveFactor / ORIG_FRICTION_FACTOR;
				
				_currentSlideSpeed = max(0, _currentSlideSpeed - (slideSlowing * slowFactor / TICRATE));
				
				if (!IsActorPlayingSound(CHAN_MOVEMENT))
					A_StartSound("delta/kris/slide_loop", CHAN_MOVEMENT,
						CHANF_LOOPING, _currentSlideSpeed / slideSpeed);
				else
					A_SoundVolume(CHAN_MOVEMENT, _currentSlideSpeed / slideSpeed);
				
				if (_currentSlideSpeed < 1)
				{
					EndSlide();
					_currentSlideSpeed = 0;
					_savedSlideSpeed = slideSpeed;
				}
				else
				{
					if (_currentSlideSpeed > 1)
						_savedSlideSpeed = _currentSlideSpeed;
					else
						_savedSlideSpeed = slideSpeed;
				}
				
				_savedSlideSpeedTimer = TICRATE / 10;
			}
			else if (IsActorPlayingSound(CHAN_MOVEMENT))
				A_StopSound(CHAN_MOVEMENT);
		}
		else
		{
			if (_slideTics > 0)
				_slideTics--;
			
			_slideTime = 0;
			if (IsActorPlayingSound(CHAN_MOVEMENT))
				A_StopSound(CHAN_MOVEMENT);
			
			if (!IsGrounded())
				_savedSlideSpeed = max(_savedSlideSpeed, -Vel.Z * 0.75);
			else
			{
				if (_savedSlideSpeedTimer > 0)
					_savedSlideSpeedTimer--;
				else if (_savedSlideSpeedTimer != -1)
				{
					_savedSlideSpeed = slideSpeed;
					_savedSlideSpeedTimer = -1;
				}
			}
		}
		
		customBobPerc = 1 - (double(_slideTics) / MAX_SLIDE_TICS);
		customBobPerc *= customBobPerc;
	}
	
	protected void StartSlide(double angOffset, bool resetSpeed = true)
	{
		if (!IsGrounded() || GetIsUsingOffhand())
			return;
		
		self.slideAngleOffset = angOffset;
		crouchState = CS_SLIDING;
		_slideTime = 0;
		
		if (resetSpeed)
			_currentSlideSpeed = max(_savedSlideSpeed, Vel.PlusZ(-Vel.Z).Length());
		
		if (IsPredicting())
			return;
		
		A_StartSound("delta/kris/slide_start", CHAN_AUTO);
		let psp = player.FindPSprite(PSP_LEGS);
		if (!psp)
			return;
		
		psp.SetState(ResolveState("SlideLegs"));
	}
	
	protected void EndSlide()
	{
		_slideTime = 0;
		
		// prevent legs reappearing if we stop sliding as result of death
		if (Health <= 0)
		{
			crouchState = CS_STANDING;
			return;
		}
		
		crouchState = CS_CROUCHING;
		let psp = player.FindPSprite(PSP_LEGS);
		if (!psp)
			return;
		
		psp.SetState(ResolveState("StopSlideLegs"));
	}
	
	protected action void A_SpawnDeathSoul(double zOffset = 36)
	{
		let soul = DeltaSoul(Spawn("DeltaSoul", Vec3Offset(0, 0, zOffset))),
			ply = invoker.GetSavedPlayer();
		
		if (ply)
			soul.playerParent = ply;
	}
	
	protected void KrisShieldParry()
	{
		A_StartSound("delta/kris/shield_swing", CHAN_AUTO);
		AddRecoil(RECOIL_WEAPON, 10, 1, p: -1, y: 5);
		
		Array<Actor> targets;
		double
			distance = 120,
			dotThreshold = 0.85; // dot product must be larger than this to count as parried
		
		ThinkerIterator it = ThinkerIterator.Create("Actor", STAT_DEFAULT);
		Actor mis;
		
		while (mis = Actor(it.Next()))
		{
			if (!mis.CanCollideWith(self, false))
				continue;
			if (!mis.GetMissileDamage(0, 1) && !mis.bIsMonster)
				continue;
			
			if (!mis.bIsMonster && mis.target && IsFriend(mis.target)) // friendly projectiles shouldn't be parried
				continue;
			if (!mis.bMissile && !mis.bSkullfly)
			{
				if (!mis.bIsMonster)
					continue;
				if ((!mis.curState.InStateSequence(mis.ResolveState("Melee"))
						&& (!mis.curState.InStateSequence(mis.ResolveState("Missile")) || !(mis is "Cacodemon")))
						// we only wanna be able to parry an enemy's missile
						// state if it's a cacodemon, as that's the state they
						// use for their bite attack
					|| damageTics != 0)
					continue;
			}
			if (mis.curState.InStateSequence(mis.ResolveState("Death")))
				continue;
			if (mis.bMissile && mis.target == self) // "target" with projectiles is used to figure out who threw it
				continue;
			
			let proj = DeltaProjectile(mis);
			if (proj && !proj.CanBeParried())
				continue;
			
			// code largely taken from ThinkerIterator documentation page
			double blockDist = distance + (mis.radius * 1.5);
			double blockHeight = distance + (mis.height * 1.5);
			Vector3 diff = level.Vec3Diff(pos, mis.pos);
			
			if (Distance2DSquared(mis) > blockDist**2)
				continue;
			if (abs(diff.z) > blockHeight)
				continue;
			
			Vector3 forward = DeltaUtil.GetActorForward(self);
			forward = forward.PlusZ(-forward.z);
			
			if ((diff dot forward) < 0.75)
				continue;
			
			targets.Push(mis);
		}
		
		double largestDot = -1;
		int largestDotIndex = -1;
		
		for (int i = 0; i < targets.Size(); i++)
		{
			let t = targets[i];
			let dir = level.Vec3Diff(pos, t.pos).Unit();
			let dotProduct = DeltaUtil.GetActorForward(self) dot dir;
			
			if (dotProduct > largestDot)
			{
				largestDot = dotProduct;
				largestDotIndex = i;
			}
		}
		
		if (largestDotIndex == -1)
		{
			SetState(ResolveState("ParryMiss"));
			tensionDrainTimer = preOffhandTpTimer;
			tensionPoints = preOffhandTp;
			return;
		}
		
		let parried = targets[largestDotIndex];
		let proj = DeltaProjectile(parried);
		
		SetState(ResolveState("Parry"));
		A_QuakeEx(0, 10, 5, 10, 0, 10, "dsempty", QF_RELATIVE | QF_SCALEDOWN);
		A_SetBlend("white", 0.3, 12);
		A_StartSound("delta/kris/shield_parry", CHAN_AUTO, attenuation: 1.0);
		damageTics = 12;
		
		double parryPitch = AimLineAttack(Angle, PLAYERMISSILERANGE,
			flags: ALF_CHECK3D | ALF_NOFRIENDS | ALF_NOWEAPONCHECK);
		double newSpeed = parried.bMissile ? 70 : 50;
		Vector2 vecToAng = AngleToVector(angle, 1);
		Vector2 vecToPitch = AngleToVector(parryPitch, 1);
		Vector3 newVel = (vecToAng.x * vecToPitch.x, vecToAng.y * vecToPitch.x,
			-vecToPitch.y);
		/*
		A_Log("angVec: " .. vecToAng .. ", pitchVec: " .. vecToPitch ..
			", newVel: " .. newVel .. ", length " .. newVel.Length());
		*/
		newVel *= newSpeed;
		
		if (proj)
			proj.OnParry(self);
		
		if (parried.bMissile)
		{
			parried.SetOrigin(pos + (0, 0, viewHeight), false);
			let inv = DeltaParried(parried.GiveInventoryType("DeltaParried"));
			inv.oldTarget = parried.target;	// mostly for checking if we
											// knocked a player's own
											// projectile back at them for
											// obituaries
			parried.target = self;
			parried.tracer = null;
			
			parried.Vel = newVel;
			parried.Angle = Angle;
			parried.Pitch = parryPitch;
			parried.bForcePain = true;
			return;
		}
		
		let parryDamage = random[parryDmg](200, 250) * max(1,
			G_SkillPropertyFloat(SKILLP_MonsterHealth));
		
		if (parried.bSkullfly)
		{
			parried.DamageMobj(self, self, parryDamage, 'Parry', DMG_THRUSTLESS);
			parried.Vel = newVel;
		}
		else if (parried.bIsMonster)
		{
			parried.DamageMobj(self, self, parryDamage, 'Parry', DMG_THRUSTLESS);
			DeltaUtil.ForceActorPain(parried, 'Parry');
			double explodeChance = 0.3;
			
			if (frandom[explodeChance](0, 1) <= explodeChance && 
				parried.health < parried.GetGibHealth())
			{
				Spawn("DeltaBadExplosion", parried.pos);
			}
		}
	}
	
	action void A_KrisShieldParry()
	{
		invoker.KrisShieldParry();
	}
	
	override void DeltaExtraDeathStuff()
	{
		Super.DeltaExtraDeathStuff();
		
		if (crouchState == CS_SLIDING)
			EndSlide();
	}
	
	void PlaySliding()
	{
		let curAnimType = DELTA_WEAPONANIM_MELEE;
		if (player.ReadyWeapon && (player.ReadyWeapon is "DeltaWeapon"))
			curAnimType = DeltaWeapon(player.ReadyWeapon).GetAnimType();
		
		if (curAnimType != lastAnimType || InSeeState() || InSpawnState() || InAirState())
			SetStateSafe(A_DeltaGetState("Slide"));
	}
	
	override void AnimatePlayer()
	{
		if (InParryState())
			return;
		
		if (crouchState == CS_SLIDING)
		{
			if (InPainState())
				SetStateSafe(A_DeltaGetState("SlidePain"));
			else
				PlaySliding();
			
			AnimateLegs();
		}
		else
		{
			if (InSlideState())
				SetStateSafe(SpawnState);
			
			Super.AnimatePlayer();
		}
	}
	
	override Vector2 GetLegsOffset()
	{
		let psp = player.FindPSprite(PSP_LEGS);
		if (!psp)
			return Super.GetLegsOffset();
		
		if (psp.curState.InStateSequence(ResolveState("SlideLegs"))
			|| (psp.curState.InStateSequence(ResolveState("StopSlideLegs")) && 
				!psp.curState.InStateSequence(ResolveState("FinishSlideLegs"))))
			return CalculateLegsOffset(pitch + viewPitch - 29);
		
		return Super.GetLegsOffset();
	}
	
	clearscope bool InParryState()
	{
		return curState.InStateSequence(ParryState) ||
			curState.InStateSequence(ParryMissState) ||
			curState.InStateSequence(AirParryState) ||
			curState.InStateSequence(AirParryMissState);
	}
	
	clearscope bool InSlideState()
	{
		return CurState.InStateSequence(SlideMeleeState) ||
			CurState.InStateSequence(SlideGunState);
	}
	
	override bool InMissileState()
	{
		return Super.InMissileState() ||
			CurState.InStateSequence(SlideMissileMeleeState) ||
			CurState.InStateSequence(SlideMissileGunState) ||
			CurState.InStateSequence(SlideMissileGunNoFlashState) ||
			CurState.InStateSequence(SlideFinishMissileGunState);
	}
}