class RalseiPlayer : DeltaPlayer
{
	bool krisNearby;
	
	Default
	{
		Height 38;
		Radius 16;
		Speed 0.7;
		Mass 90;
		BloodType "DeltaNoBlood"; // this is used so blood sprites and particles
								  // don't show up but Ralsei is still treated
								  // like a living, bleeding actor (rather than
								  // smth like an explosive barrel)
		BloodColor "00 00 00";
		
		Health 180;
		Player.MaxHealth 180;
		DeltaPlayer.LevelOneHP 70;
		
		Player.DisplayName "$DELTA_CHAR_RALSEI";
		Player.ViewHeight 32;
		
		// Player.WeaponSlot 1, "RalseiScarf";
		// Player.WeaponSlot 2, "RalseiFireballs";
		// Player.WeaponSlot 3, "RalseiFireBlast";
		// Player.WeaponSlot 4, "RalseiAK"; 		// fnuuy
		// Player.WeaponSlot 5, "RalseiFlameBombs";
		// Player.WeaponSlot 6, "";
		
		// Player.StartItem "RalseiScarf";
		// Player.StartItem "RalseiHealing";
		
		DeltaPlayer.HugReactionTime 20;
		DeltaPlayer.CharacterColor Color(0, 255, 0);
		DeltaPlayer.OverhealColor Color(255, 255, 0);
		DeltaPlayer.OffhandIcon "";
		DeltaPlayer.CharacterIcon "graphics/ralseiCharIcon.png";
		
		DeltaPlayer.FootstepType FOOTSTEP_FLUFF;
		DeltaPlayer.VoiceClass "ralsei";
		
		+NOBLOODDECALS;
	}
	
	States
	{
		Spawn:
			DRAL A 1
			{
				if (invoker.krisNearby)
					return ResolveState("Blush");
				return ResolveState(null);
			}
			Loop;
		See:
			DRAL BACA -1;
			Loop;
		Blush:
			DRAL I 1;
			Loop;
		BlushWalk:
			DRAL JIKI -1;
			Loop;
		Airborne:
			DRAL DEF 4;
			Loop;
		Pain:
			Goto Spawn;
		Death:
			DRAL G 1 A_StartDeath;
			DRAL G 1 A_CheckDeathLand;
			Wait;
		FinishDeath:
			DRAL H 5 A_DeathImpact;
			DRAL H 2;
			DRAL H 1;
			DRAL H -1;
			Stop;
		Death.Ice:
			DRAF A 2 A_DeltaFreezeDeath;
			DRAF BCD 2;
			Goto FinishIce;
		FinishIce:
			DRAF E TICRATE;
			DRAF E 1;
			DRAF E -1;
			Stop;
	}
}

class DeltaNoBlood : Blood
{
	Default
	{
		+INVISIBLE;
		-ALLOWPARTICLES;
	}
}