class KrisSword : DeltaWeapon
{
	int swingCombo;
	
	Default
	{
		Tag "$TAG_DELTA_SWORD";
		Obituary "$OBIT_DELTA_SWORD";
		Inventory.PickupMessage "$PICKUP_DELTA_SWORD";
		
		Weapon.SlotNumber 1;
		Weapon.SelectionOrder 1200;
		
		DeltaWeapon.AnimType DeltaPlayer.DELTA_WEAPONANIM_MELEE;
		DeltaWeapon.RedCrosshairRange 150;
		DeltaWeapon.MaxLungeDistance 150;
		DeltaWeapon.Crosshair "graphics/hud/reticle/swordReticle.png";
		
		+SQUAREPIXELS
		+Weapon.AXEBLOOD
		+Weapon.MELEEWEAPON
		+Weapon.NOALERT				// wanna handle alerting manually
	}
	
	States
	{
		Ready:
			DKSW A 1 A_DeltaWeaponReady;
			Wait;
		Deselect:
			DKWH AB 2;
			DKWH C 3;
			DKWH D 2 A_StartSound("delta/sword/holster", CHAN_WEAPON,
				CHANF_OVERLAP);
			DKWH E 2;
			TNT1 A 2;
        DeselectAtEase:
			TNT1 A 0 A_SwapWeapon;
			Stop;
		Select:
			TNT1 A 1 A_StartRaiseWeapon;
			TNT1 A 1
			{
				A_StartSound("delta/sword/deploy", CHAN_WEAPON);
				return A_DeltaWeaponReady(WRF_NOFIRE | WRF_NOBOB);
			}
			DKWD AB 2 A_DeltaWeaponReady(WRF_NOBOB);
			Goto FinishSelect;
		SelectFirst:
			TNT1 A 1 A_StartRaiseWeapon;
			TNT1 A 1
			{
				A_StartSound("delta/sword/deploy", CHAN_WEAPON);
				return A_DeltaWeaponReady(WRF_NOFIRE | WRF_NOBOB);
			}
			DKWD A 2 A_DeltaWeaponReady(WRF_NOBOB);
			DKWD B 2 A_StartSound("delta/sword/deploy_hit", CHAN_WEAPON, CHANF_OVERLAP);
		FinishSelect:
			DKWD C 5 A_DeltaWeaponReady(WRF_NOFIRE | WRF_NOBOB);
			DKWD D 2 A_DeltaWeaponReady(WRF_NOFIRE | WRF_NOBOB);
			DKWD E 2 A_DeltaWeaponReady(WRF_NOBOB);
			DKWD FGH 2 A_DeltaWeaponReady(WRF_NOBOB);
			DKWD I 3
			{
				A_StartSound("delta/sword/catch", CHAN_WEAPON,
					CHANF_OVERLAP);
				return A_DeltaWeaponReady(WRF_NOFIRE | WRF_NOBOB);
			}
			Goto Ready;
        AtEase:
            DKWH AB 2 A_DeltaWeaponReady(WRF_NOBOB | WRF_NOSWITCH, true);
			DKWH C 4 A_DeltaWeaponReady(WRF_NOBOB | WRF_NOSWITCH, true);
			DKWH D 2
			{
				A_StartSound("delta/sword/holster", CHAN_WEAPON, CHANF_OVERLAP);
				return A_DeltaWeaponReady(WRF_NOBOB | WRF_NOSWITCH, true);
			}
			DKWH E 2 A_DeltaWeaponReady(WRF_NOBOB | WRF_NOSWITCH, true);
		AtEaseLoop:
            Goto Super::AtEaseLoop;
		AtEaseEnd:
			Goto Select;
		Fire:
			TNT1 A 0
			{
				return ((invoker.swingCombo + 1) % 2) ? ResolveState("LungeR")
					: ResolveState("LungeL");
			}
			Goto SwingR;
		LungeL:
			DKSW K 1 A_DoLunge(ResolveState("SwingL"));
			Loop;
		SwingL:
			DKSW L 1 A_KrisSwordSwing(true);
			DKSW L 1 A_AddRecoil(5, 1, p: 2,
				y: cl_delta_weaponHandedness ? -5 : 5);
			DKSW MN 1;
			DKSW O 4;
			DSKW P 1;
			DKSW QQRRSSTTAAA 1 A_ReFire;
			Goto Ready;
		LungeR:
			DKSW B 1 A_DoLunge(ResolveState("SwingR"));
			Loop;
		SwingR:
			DKSW C 1 A_KrisSwordSwing;
			DKSW C 1 A_AddRecoil(5, 1, p: 2,
				y: cl_delta_weaponHandedness ? 5 : -5);
			DKSW D 1;
			DKSW E 6;
			DKSW FFGGHHIIJJAAA 1 A_ReFire;
			Goto Ready;
	}
	
	action void A_KrisSwordSwing(bool leftSlash = false)
	{
		invoker.swingCombo++;
		invoker.ResetReadyToStopLunging();
		A_OwnerPlayAttack();
		A_StartSound("delta/sword/swing", CHAN_WEAPON, CHANF_OVERLAP,
			pitch: cfrandom(0.95, 1.05));
		
		int dmg, TRACER_COUNT = 16;
		bool hitSomething = false;
		double distance = 80, puffDist = 40,
			zOffset = player.viewz - player.mo.pos.z;
		Array<Actor> targets;
		
		for (double ang = -45; ang <= 45; ang += 45./TRACER_COUNT)
		{
			dmg = random[swordDamage](35, 50);
			FTranslatedLineTarget t;
			FLineTraceData l;
			
			double newAng = Angle + ang;
			double pitch = AimLineAttack(ang, distance, t, 0., ALF_CHECK3D);
			LineTrace(newAng, distance, pitch, TRF_NOSKY, zOffset, data: l);
			
			if (!l.HitActor)
				continue;
			if (targets.Find(l.HitActor) != targets.Size())
				continue;
			if (l.HitActor is "ExplosiveBarrel")
				continue;
			if (l.HitActor.CountInv("DeltaStun"))
				dmg = int(dmg * 1.25);
			
			hitSomething = true;
			LineAttack(newAng, distance, pitch, dmg, "Melee", leftSlash ?
				"KrisSwordPuffL" : "KrisSwordPuffR", LAF_OVERRIDEZ | LAF_ISMELEEATTACK, t, zOffset);
			targets.Push(l.HitActor);
			
			let diff = level.Vec3Diff(player.mo.pos.PlusZ(zOffset), l.HitActor.pos),
				dist = max(5, diff.Length() - l.HitActor.radius);
			
			if (dist < puffDist)
				puffDist = dist;
		}
		
		if (targets.Size())
		{
			//Radius_Quake(2, 3, 0, 1, 0);
			A_QuakeEx(0, 4, 2, 5, 0, 1, "dssilent", QF_RELATIVE | QF_SCALEDOWN);
			A_StartSound("delta/sword/hit", CHAN_WEAPON, CHANF_OVERLAP);
		}
		else
		{
			Actor puff;
			puff = LineAttack(angle, distance, pitch, dmg, "Melee", leftSlash ?
				"KrisSwordPuffL" : "KrisSwordPuffR", LAF_OVERRIDEZ | LAF_ISMELEEATTACK, offsetZ: zOffset);
			
			if (puff)
			{
				hitSomething = true;
				let diff = level.Vec3Diff(player.mo.pos.PlusZ(zOffset), puff.pos),
					dist = max(5, diff.Length());
				
				if (dist < puffDist)
					puffDist = dist;
			}
		}
		
		if (!hitSomething)
			return;
		
		let slsh = Spawn(leftSlash? "KrisSwordSlashL":"KrisSwordSlashR",
			player.mo.pos.PlusZ(zOffset)
				+ DeltaUtil.GetActorForward(player.mo)*puffDist);
		slsh.angle = player.mo.angle;
		slsh.pitch = player.mo.pitch;
	}
}

class KrisSwordPuff : Actor
{
	Default
	{
		ProjectileKickBack 5;
		+NOEXTREMEDEATH
	}
	
	States
	{
		Spawn:
			TNT1 A 0;
			Stop;
	}
}
class KrisSwordPuffL : KrisSwordPuff
{
	Default
	{
		Decal "KrisSwordSlashL";
	}
}
class KrisSwordPuffR : KrisSwordPuff
{
	Default
	{
		Decal "KrisSwordSlashR";
	}
}

class KrisSwordSlashL : Actor
{
	Default
	{
		Gravity 0;
		
		+WALLSPRITE
		+BRIGHT
		+SQUAREPIXELS
	}
	
	States
	{
		Spawn:
			KSLH ABC 2;
			Stop;
	}
}
class KrisSwordSlashR : KrisSwordSlashL
{
	Default
	{
		+XFLIP
	}
}