class KrisSword : DeltaWeapon
{
	bool pulledOutFirstTime;
	int swingCombo;
	
	Default
	{
		Tag "$TAG_DELTA_SWORD";
		Obituary "$OBIT_DELTA_SWORD";
		Inventory.PickupMessage "$PICKUP_DELTA_SWORD";
		
		Weapon.SlotNumber 1;
		Weapon.SelectionOrder 1000;
		
		DeltaWeapon.AnimType DELTA_WEAPONANIM_MELEE;
		DeltaWeapon.RedCrosshairRange 150;
		DeltaWeapon.MaxLungeDistance 150;
		DeltaWeapon.Crosshair "DRSWDRET";
		
		+WEAPON.AXEBLOOD
		+WEAPON.MELEEWEAPON
		+WEAPON.NOALERT				// wanna handle alerting manually
		+SQUAREPIXELS
	}
	
	States
	{
		Ready:
			DKSW A 1 A_DeltaWeaponReady;
			Wait;
		Deselect:
			DKWH A 2 A_JumpIf(invoker._atEase, "Swap");
			#### B 2;
			#### C 4;
			#### D 2 A_StartSound("delta/sword/holster", CHAN_WEAPON,
				CHANF_OVERLAP);
			#### E 2;
			TNT1 A 4;
        Swap:
			#### # 0 A_SwapWeapon;
			Stop;
		Select:
			TNT1 A 2
			{
				A_StartRaiseWeapon();
				A_StartSound("delta/sword/deploy", CHAN_WEAPON);
			}
			DKWD A 2 A_DeltaWeaponReady(WRF_NOBOB | WRF_NOSWITCH);
			DKWD B 2
			{
				if (!invoker.pulledOutFirstTime)
				{
					A_StartSound("delta/sword/deploy_hit", CHAN_WEAPON,
						CHANF_OVERLAP);
					invoker.pulledOutFirstTime = true;
				}
			}
			DKWD C 5;
			DKWD D 2;
			DKWD E 2 A_DeltaWeaponReady(WRF_NOBOB);
			DKWD FGH 2 A_DeltaWeaponReady(WRF_NOBOB);
			DKWD I 3 A_StartSound("delta/sword/catch", CHAN_WEAPON,
				CHANF_OVERLAP);
			DKSW A 1 A_FinishRaiseWeapon;
			Stop;
        AtEase:
            DKWH A 2;
			#### B 2 A_StartSound("delta/sword/holster", CHAN_WEAPON,
				CHANF_OVERLAP);
			#### CD 2;
		AtEaseLoop:
            Goto Super::AtEaseLoop;
		Fire:
			TNT1 A 0
			{
				return ((invoker.swingCombo + 1) % 2) ? ResolveState("LungeR")
					: ResolveState("LungeL");
			}
			Goto SwingR;
		LungeL:
			DKSW K 1 A_DoLunge(ResolveState("SwingL"));
			Loop;
		SwingL:
			DKSW L 1 A_KrisSwordSwing;
			DKSW L 1 A_AddRecoil(5, 1, p: 2,
				y: cl_delta_weaponHandedness ? -5 : 5);
			DKSW MN 1;
			DKSW O 4;
			DSKW P 1;
			DKSW QQRRSSTTAAA 1 A_ReFire;
			Goto Ready;
		LungeR:
			DKSW B 1 A_DoLunge(ResolveState("SwingR"));
			Loop;
		SwingR:
			DKSW C 1 A_KrisSwordSwing;
			DKSW C 1 A_AddRecoil(5, 1, p: 2,
				y: cl_delta_weaponHandedness ? 5 : -5);
			DKSW D 1;
			DKSW E 6;
			DKSW FFGGHHIIJJAAA 1 A_ReFire;
			Goto Ready;
	}
	
	override void BeginPlay()
	{
		Super.BeginPlay();
		pulledOutFirstTime = false;
	}
	
	action void A_KrisSwordSwing()
	{
		invoker.swingCombo++;
		invoker.ResetReadyToStopLunging();
		A_OwnerPlayAttack();
		A_StartSound("delta/sword/swing", CHAN_WEAPON, CHANF_OVERLAP,
			pitch: cfrandom(0.95, 1.05));
		A_AlertMonsters();
		
		int dmg;
		int TRACER_COUNT = 16;
		double distance = 80;
		Array<Actor> targets;		
		double zOffset = player.viewz - player.mo.pos.z;
		
		for (double ang = -45; ang <= 45; ang += 45./TRACER_COUNT)
		{
			dmg = random[swordDamage](35, 50);
			FTranslatedLineTarget t;
			FLineTraceData l;
			
			double newAng = Angle + ang;
			double pitch = AimLineAttack(ang, distance, t, 0., ALF_CHECK3D);
			LineTrace(newAng, distance, pitch, TRF_NOSKY, zOffset, data: l);
			
			if (!l.HitActor)
				continue;
			if (targets.Find(l.HitActor) != targets.Size())
				continue;
			if (l.HitActor is "ExplosiveBarrel")
				continue;
			
			LineAttack(newAng, distance, pitch, dmg, "Melee", "KrisSwordPuff",
				LAF_OVERRIDEZ, t, zOffset);
			targets.Push(l.HitActor);
		}
		
		
		if (targets.Size() > 0)
		{
			Radius_Quake(2, 3, 0, 1, 0);
			A_StartSound("delta/sword/hit", CHAN_WEAPON, CHANF_OVERLAP);
		}
		else
			LineAttack(Angle, distance, Pitch, dmg, "Melee", "KrisSwordPuff",
				LAF_OVERRIDEZ, offsetZ: zOffset);
	}
}

class KrisSwordPuff : BulletPuff
{
	Default
	{
		ProjectileKickBack 5;
		+NOEXTREMEDEATH;
	}
}