class KrisSmg : DeltaWeapon
{
	Default
	{
		Tag "$TAG_DELTA_SMG";
		Obituary "$OBIT_DELTA_KSMG";
		Inventory.PickupMessage "$PICKUP_DELTA_KSMG";
		
		Weapon.SlotNumber 4;
		Weapon.SelectionOrder 600;
		Weapon.AmmoUse 1;
		Weapon.AmmoUse2 1;
		Weapon.AmmoGive 30;
		Weapon.AmmoType "Clip";
		Weapon.AmmoType2 "RocketAmmo";
		DeltaWeapon.Crosshair "graphics/hud/reticle/smgReticle.png";
		DeltaWeapon.TensionUse2 75;
		
		+SQUAREPIXELS
	}
	
	States
	{
		Ready:
			DKSM A 1 A_DeltaWeaponReady;
			Loop;
		Deselect:
			DKSM O 2 A_StartSound("delta/smg/holster", CHAN_WEAPON,
				CHANF_OVERLAP);
			DKSM PQR 2;
			TNT1 A 4;
			TNT1 A 0 A_SwapWeapon;
			Stop;
		Select:
			TNT1 A 0 A_StartRaiseWeapon;
			DKSM G 2 A_StartSound("delta/smg/deploy1", CHAN_WEAPON,
				CHANF_OVERLAP);
			DKSM HIJ 2 A_DeltaWeaponReady(WRF_NOFIRE | WRF_NOBOB);
			DKSM K 1 A_DeltaWeaponReady(WRF_NOBOB);
			DKSM K 1 A_StartSound("delta/smg/deploy2", CHAN_WEAPON,
				CHANF_OVERLAP, pitch: 1.2);
			DKSM LMN 2 A_DeltaWeaponReady(WRF_NOBOB);
			Goto Ready;
		AtEase:
			DKME ABCDE 2 A_DeltaWeaponReady(WRF_NOBOB, true);
		AtEaseLoop:
			DKME F 1 A_DeltaWeaponReady(atEase: true);
			Loop;
		AtEaseEnd:
			DKME EDCBA 2 A_DeltaWeaponReady(WRF_NOBOB);
			Goto Ready;
		DeselectAtEase:
			DKME GHI 2;
			TNT1 A 4;
			TNT1 A 0 A_SwapWeapon;
			Stop;
		Fire:
			DKSM B 1 A_KrisSmgFire;
			DKSM B 1 A_ZoomFactor(1, ZOOM_NOSCALETURNING);
			DKSM C 2 A_RemoveDynamicLight("smgMuzzle");
			DKSM D 1
			{
				if (!invoker.DeltaCheckAmmo(PrimaryFire, true))
					return ResolveState("DoneFiring");
				
				return ResolveState(null);
			}
		Hold: // fallthrough is intentional
			DKSM B 1 A_KrisSmgFire;
			DKSM B 1 A_ZoomFactor(1, ZOOM_NOSCALETURNING);
			DKSM C 2 A_RemoveDynamicLight("smgMuzzle");
			DKSM D 1;
		DoneFiring: // see above
			DKSM EFA 2 A_ReFire;
			Goto Ready;
		AltFire:
			KSMA A 1 A_KrisSmgAltFire;
			KSMA B 2;
			KSMA C 2 A_ZoomFactor;
			KSMA D 2;
			KSMA EFGHI 2 A_DeltaWeaponReady(WRF_NOFIRE | WRF_NOBOB);
			KSMA J 3 A_DeltaWeaponReady(WRF_NOSECONDARY | WRF_NOBOB);
			KSMA K 3 A_DeltaWeaponReady(WRF_NOBOB);
			Goto Ready;
		Spawn:
			DSMG A -1;
			Stop;
	}
	
	protected action void A_KrisSmgFire()
	{
		let spread = min(6, (player.refire/4.) + 0.5);
		// -1 for bullets fires one hitscan and applies spread immediately,
		// regardless of player.refire
		A_FireBullets(spread, spread, -1, random[smgDmg](15, 20), "KrisSmgPuff",
			FBF_USEAMMO | FBF_NORANDOM, spawnHeight: 32 * invoker.GetCrouchFactor());
		A_AddRecoil(5, 1, p: -0.5);
		A_AddDynamicLight("smgMuzzle", "DeltaGenericMuzzle");
		
		if (level.IsFreelookAllowed())
		{
			invoker.owner.pitch = max(player.MinPitch,
				invoker.owner.pitch - 1.25);
		}
		
		A_StartSound("delta/smg/fire", CHAN_WEAPON, CHANF_OVERLAP,
			pitch: cfrandom(0.93, 1.07));
		A_OwnerPlayAttack();
	}
	
	protected action void A_KrisSmgAltFire()
	{
		A_FireProjectile("KrisSmgGrenade");
		A_ZoomFactor(0.99, ZOOM_INSTANT | ZOOM_NOSCALETURNING);
		A_AddRecoil(15, 3, p: -5);
		
		A_StartSound("delta/smg/alt_fire", CHAN_WEAPON, CHANF_OVERLAP,
			pitch: cfrandom(0.93, 1.07));
		A_OwnerPlayAttack(false);
	}
}

class KrisSmgPuff : BulletPuff
{
	Default
	{
		ProjectileKickBack 1;
		+NOEXTREMEDEATH
	}
}

class KrisSmgGrenade : DeltaGrenade
{
	Default
	{
		Speed 35;
		Obituary "$OBIT_DELTA_KSMGALT";
		
		DeltaGrenade.GrenadeType GRENADE_STICKY;
		DeltaGrenade.FuseTime 0.75;
		DeltaGrenade.ArmedSound "delta/smg/grenade_hit_map";
		DeltaGrenade.StickSound "delta/smg/grenade_hit";
		DeltaGrenade.ExplosionSound "delta/smg/grenade_explosion";
		DeltaGrenade.HitboxClass "KrisSmgGrenadeHitbox";
	}
	
	override void BeginPlay()
	{
		Super.BeginPlay();
		GiveInventory("DeltaNoGiveDamageTP", 1);
	}
	
	override void Explode()
	{
		Super.Explode();
		
		double range = 70;
		RadiusAttack(target, 220 + dmgTaken, range, 'KrisSmgGrenade',
			RADF_THRUSTZ, range*0.2);
		
		let diff = level.Vec3Diff(pos, target.pos),
			dist = max(abs(diff.x), abs(diff.y), abs(diff.z));
		if (dist > range || !CheckSight(target, SF_IGNOREVISIBILITY))
			return;
		
		let damageMult = clamp(1.2 - dist/range, 0, 1),
			dmg = int(ceil(25 * damageMult));
		
		target.DamageMobj(self, target, dmg, 'KrisSmgGrenade', DMG_THRUSTLESS);
		
		let knockbackDmg = dmg * 0.5;
		let deltaTarget = DeltaPlayer(target);
		
		if (deltaTarget && !deltaTarget.IsGrounded())
			knockbackDmg *= 2;
		
		if (knockbackDmg > 20)
			knockbackDmg = 20;
		
		target.Vel += diff.Unit() * knockbackDmg;
	}
	
	override string GetObituary(Actor victim, Actor inflictor, Name mod, bool playerAttack)
	{
		if (victim == target)
			return StringTable.Localize("$OBIT_DELTA_KSMGALTSELF");
		
		return Super.GetObituary(victim, inflictor, mod, playerAttack);
	}
	
	States
	{
		Spawn:
			BAL1 AB 4;
			Loop;
		Explode:
			BAL1 A 1; // freeze here for hitstop
			BAL1 C 2 A_GrenadeExplode;
			BAL1 D 3;
			BAL1 E 4;
			Stop;
	}
}

class KrisSmgGrenadeHitbox : DeltaGrenadeHitbox
{
	Default
	{
		Radius 30;
		Height 30;
		Health 20;
	}
}