class KrisShotgun : DeltaWeapon
{
	bool pumped;
	
	Default
	{
		Tag "$TAG_DELTA_SHOTGUN";
		Inventory.PickupMessage "$PICKUP_DELTA_KSHOTGUN";
		
		Weapon.SlotNumber 3;
		Weapon.SelectionOrder 700;
		Weapon.AmmoUse 1;
		Weapon.AmmoUse2 2;
		Weapon.AmmoGive 10;
		Weapon.AmmoType "Shell";
		Weapon.AmmoType2 "Shell";
		DeltaWeapon.Crosshair "DRSHGRET";
		DeltaWeapon.RedCrosshairRange 500;
		DeltaWeapon.TensionUse2 50;
		
		+SQUAREPIXELS
		+WEAPON.NOALERT
	}
	
	States
	{
		Ready:
			DKSG A 1
			{
				if (!invoker.pumped)
					return ResolveState("Pump");
				
				return A_DeltaWeaponReady();
			}
			Loop;
		Deselect:
			DKSH A 2 A_StartSound("delta/shotgun/holster", CHAN_WEAPON,
				CHANF_OVERLAP);
			#### BCDE 2;
			TNT1 A 4;
			#### # 0 A_SwapWeapon;
			Stop;
		Select:
			TNT1 A 2
			{
				A_StartRaiseWeapon();
				A_StartSound("delta/shotgun/deploy1", CHAN_WEAPON,
					CHANF_OVERLAP);
			}
			DKSD ABCD 2;
			#### E 1
			{
				if (invoker.pumped)
					return A_DeltaWeaponReady(WRF_NOBOB);
				
				return ResolveState(null);
			}
			#### E 1 A_StartSound("delta/shotgun/deploy2", CHAN_WEAPON,
				CHANF_OVERLAP);
			#### FGH 2
			{
				if (invoker.pumped)
					return A_DeltaWeaponReady(WRF_NOBOB);
				
				return ResolveState(null);
			}
			DKSG A 1 A_FinishRaiseWeapon;
			Stop;
		Fire:
			DKSG B 2 A_KrisShotgunFire;
			#### C 1 A_RemoveDynamicLight("shotgunMuzzle");
			#### # 1 A_ZoomFactor;
			#### DEFG 2; // fall-through is intentional
		Pump:
			DKSG H 1 A_DeltaWeaponReady(WRF_NOFIRE | WRF_NOBOB);
			#### # 1 A_CheckReload;
			#### IJ 2;
			#### K 2 A_StartSound("delta/shotgun/pumpIn", CHAN_WEAPON,
				CHANF_OVERLAP);
			#### LM 2;
			#### N 2
			{
				A_StartSound("delta/shotgun/pumpOut", CHAN_WEAPON,
					CHANF_OVERLAP);
				invoker.pumped = true;
			}
			#### OPQRST 2;
			Goto Ready;
		AltFire:
			DKSA A 2 A_KrisShotgunAltFire;
			#### B 1 A_RemoveDynamicLight("shotgunMuzzle");
			#### # 1 A_ZoomFactor;
			#### CDEFGHIJKLM 2;
			Goto Pump;
		Spawn:
			DSHG A -1;
			Stop;
	}
	
	override void BeginPlay()
	{
		Super.BeginPlay();
		pumped = true;
	}
	
	override string PickupMessage()
	{
		double chance = 0.0025;
		
		if (cfrandom(0, 1) <= chance)
			return StringTable.Localize("$PICKUP_DELTA_KSHOTGUN_NIGHRIEL");
		
		return Super.PickupMessage();
	}
	
	action void A_KrisShotgunFire()
	{
		A_FireBullets(5.5, 5.5, 8, 9, "KrisShotgunPuff",
			flags: FBF_USEAMMO | FBF_NORANDOM, spawnHeight: 32 * invoker.GetCrouchFactor());
		A_AddDynamicLight("shotgunMuzzle", "DeltaGenericMuzzle");
		A_AddRecoil(10, 1, p: -3);
		invoker.pumped = false;
		
		A_StartSound("delta/shotgun/fire", CHAN_WEAPON, CHANF_OVERLAP);
		A_AlertMonsters();
		
		A_OwnerPlayAttack();
	}
	
	action state A_KrisShotgunAltFire()
	{
		if (!invoker.DepleteAmmo(true))
			return ResolveState("Ready");
		
		A_FireBullets(6.5, 6.5, 16, 10, "KrisShotgunAltPuff", FBF_NORANDOM);
		A_AddDynamicLight("shotgunMuzzle", "DeltaGenericMuzzle");
		A_AddRecoil(20, 3, p: -7);
		invoker.pumped = false;
		
		A_StartSound("delta/shotgun/fire", CHAN_WEAPON, CHANF_OVERLAP);
		A_AlertMonsters();
		
		A_OwnerPlayAttack();
		A_ZoomFactor(0.97, ZOOM_INSTANT | ZOOM_NOSCALETURNING);
		
		if (player.crouchOffset ~== 0)
		{
			Vector2 forward = AngleToVector(player.mo.angle);
			Vector2 up = AngleToVector(player.mo.pitch);
			player.mo.vel -= (forward.x * up.x, forward.y * up.x, -up.y)
				* (player.onGround ? 5 : 10);
		}
		
		return ResolveState(null);
	}
}

class KrisShotgunPuff : BulletPuff
{
	Default
	{
		Obituary "$OBIT_DELTA_KSHOTGUN";
	}
}

class KrisShotgunAltPuff : KrisShotgunPuff
{
	Default
	{
		Obituary "$OBIT_DELTA_KSHOTGUNALT";
	}
}