class KrisShotgun : DeltaWeapon
{
	enum PumpState
	{
		PUMPED = 0,
		NEEDS_PUMP_PRIMARY = 1,
		NEEDS_PUMP_ALT = 2
	}
	
	Default
	{
		Tag "$TAG_DELTA_SHOTGUN";
		Inventory.PickupMessage "$PICKUP_DELTA_KSHOTGUN";
		
		Weapon.SlotNumber 3;
		Weapon.SelectionOrder 700;
		Weapon.AmmoUse 1;
		Weapon.AmmoUse2 2;
		Weapon.AmmoGive 10;
		Weapon.AmmoType "Shell";
		Weapon.AmmoType2 "Shell";
		DeltaWeapon.Crosshair "graphics/hud/reticle/shotgunReticle.png";
		DeltaWeapon.RedCrosshairRange 500;
		DeltaWeapon.TensionUse2 50;
		
		+SQUAREPIXELS
		+Weapon.NOALERT
	}
	
	States
	{
		Ready:
			DKSG A 1
			{
				if (invoker.needsCycling == NEEDS_PUMP_ALT)
					return ResolveState("AltPump");
				if (invoker.needsCycling == NEEDS_PUMP_PRIMARY)
					return ResolveState("Pump");
				
				return A_DeltaWeaponReady();
			}
			Loop;
		Deselect:
			DKSH A 2 A_StartSound("delta/shotgun/holster", CHAN_WEAPON,
				CHANF_OVERLAP);
			DKSH BCDE 2;
			TNT1 A 4;
			TNT1 A 0 A_SwapWeapon;
			Stop;
		Select:
			TNT1 A 2
			{
				A_StartRaiseWeapon();
				A_StartSound("delta/shotgun/deploy1", CHAN_WEAPON,
					CHANF_OVERLAP);
				return A_DeltaWeaponReady(WRF_NOFIRE | WRF_NOBOB);
			}
			DKSD ABCD 2 A_DeltaWeaponReady(WRF_NOFIRE | WRF_NOBOB);
			DKSD E 1
			{
				if (!invoker.needsCycling)
					return A_DeltaWeaponReady(WRF_NOBOB);
				
				return ResolveState(null);
			}
			DKSD E 1 A_StartSound("delta/shotgun/deploy2", CHAN_WEAPON,
				CHANF_OVERLAP);
			DKSD FGH 2
			{
				if (!invoker.needsCycling)
					return A_DeltaWeaponReady(WRF_NOBOB);
				
				return ResolveState(null);
			}
			Goto Ready;
		AtEase:
			DKSE ABCDE 2 A_DeltaWeaponReady(WRF_NOBOB, true);
		AtEaseLoop:
			DKSE F 1 A_DeltaWeaponReady(atEase: true);
			Wait;
		AtEaseEnd:
			DKSE EDCBA 2 A_DeltaWeaponReady(WRF_NOBOB);
			Goto Ready;
		DeselectAtEase:
			DKSE H 2;
			TNT1 A 4;
			TNT1 A 0 A_SwapWeapon;
			Stop;
		Fire:
			DKSG B 2 A_KrisShotgunFire;
			DKSG C 1 A_RemoveDynamicLight("shotgunMuzzle");
			DKSG C 1 A_ZoomFactor;
			DKSG D 2;
			DKSG EFGH 2 A_DeltaWeaponReady(WRF_NOFIRE | WRF_NOBOB);
			DKSG I 1 A_DeltaWeaponReady(WRF_NOFIRE | WRF_NOBOB);
			DKSG I 1 A_CheckReload;
		Pump:
			DKSG J 1 A_DeltaWeaponReady(WRF_NOFIRE | WRF_NOBOB);
			DKSG J 1 A_StartSound("delta/shotgun/pumpIn", CHAN_WEAPON,
				CHANF_OVERLAP);
			DKSG KLM 2;
			DKSG N 2
			{
				A_StartSound("delta/shotgun/pumpOut", CHAN_WEAPON,
					CHANF_OVERLAP);
				invoker.needsCycling = invoker.PUMPED;
			}
			DKSG OPQR 2 A_DeltaWeaponReady(WRF_NOFIRE | WRF_NOBOB);
			Goto Ready;
		AltFire:
			DKSA A 2 A_KrisShotgunAltFire;
			DKSA B 1 A_RemoveDynamicLight("shotgunMuzzle");
			DKSA B 1 A_ZoomFactor;
			DKSA C 2;
			DKSA DEFGH 2 A_DeltaWeaponReady(WRF_NOFIRE | WRF_NOBOB);
			DKSA I 2
			{
				A_StartSound("delta/shotgun/deploy2", CHAN_WEAPON,
					CHANF_OVERLAP, 0.6, pitch: 1.1);
				return A_DeltaWeaponReady(WRF_NOFIRE | WRF_NOBOB);
			}
			DKSA JKL 2 A_DeltaWeaponReady(WRF_NOFIRE | WRF_NOBOB);
			DKSA M 1 A_DeltaWeaponReady(WRF_NOFIRE | WRF_NOBOB);
			DKSA M 1 A_CheckReload;
		AltPump:
			DKSA NOPQ 2 A_DeltaWeaponReady(WRF_NOFIRE | WRF_NOBOB);
			DKSA R 2 A_StartSound("delta/shotgun/pumpIn", CHAN_WEAPON,
				CHANF_OVERLAP);
			DKSA S 2;
			DKSA T 3;
			DKSA U 2
			{
				A_StartSound("delta/shotgun/pumpOut", CHAN_WEAPON,
					CHANF_OVERLAP);
				invoker.needsCycling = invoker.PUMPED;
			}
			DKSA VWXYZ 2 A_DeltaWeaponReady(WRF_NOFIRE | WRF_NOBOB);
			Goto Ready;
		Spawn:
			DSHG A -1;
			Stop;
	}
	
	override string PickupMessage()
	{
		double chance = 0.0025;
		
		if (cfrandom(0, 1) <= chance)
			return StringTable.Localize("$PICKUP_DELTA_KSHOTGUN_NIGHRIEL");
		
		return Super.PickupMessage();
	}
	
	action void A_KrisShotgunFire()
	{
		A_FireBullets(5.5, 5.5, 9, 9, "KrisShotgunPuff",
			flags: FBF_USEAMMO | FBF_NORANDOM, spawnHeight: 32 * invoker.GetCrouchFactor());
		A_AddDynamicLight("shotgunMuzzle", "DeltaGenericMuzzle");
		A_AddRecoil(10, 1, p: -4);
		invoker.needsCycling = NEEDS_PUMP_PRIMARY;
		
		A_StartSound("delta/shotgun/fire", CHAN_WEAPON, CHANF_OVERLAP);
		A_AlertMonsters();
		
		A_OwnerPlayAttack();
	}
	
	action void A_KrisShotgunAltFire()
	{
		A_FireBullets(6.5, 6.5, 16, 10, "KrisShotgunAltPuff", FBF_USEAMMO | FBF_NORANDOM);
		A_AddDynamicLight("shotgunMuzzle", "DeltaGenericMuzzle");
		A_AddRecoil(25, 2, p: -10);
		invoker.needsCycling = NEEDS_PUMP_ALT;
		
		A_StartSound("delta/shotgun/fire", CHAN_WEAPON, CHANF_OVERLAP);
		A_AlertMonsters();
		
		A_OwnerPlayAttack();
		A_OwnerKnockback(5, 10);
	}
}

class KrisShotgunPuff : BulletPuff
{
	Default
	{
		Obituary "$OBIT_DELTA_KSHOTGUN";
	}
}

class KrisShotgunAltPuff : KrisShotgunPuff
{
	Default
	{
		Obituary "$OBIT_DELTA_KSHOTGUNALT";
	}
	
	override void BeginPlay()
	{
		Super.BeginPlay();
		GiveInventory("DeltaNoGiveDamageTP", 1);
	}
}