class KrisRevolver : DeltaWeapon
{
	bool pulledOutFirstTime;
	bool cocked;
	int chargeTics;
	
	const MAX_CHARGE_TICS = 20;
	const CHAN_CHARGE = 15;
	
	Default
	{
		Tag "$TAG_DELTA_REVOLVER";
		Inventory.PickupMessage "$PICKUP_DELTA_REVOLVER";
		
		Weapon.SlotNumber 2;
		Weapon.SelectionOrder 900;
		Weapon.AmmoUse 1;
		Weapon.AmmoUse2 5;
		Weapon.AmmoGive 15;
		Weapon.AmmoType "Clip";
		Weapon.AmmoType2 "Clip";
		DeltaWeapon.Crosshair "DRPSTRET";
		DeltaWeapon.TensionUse2 40;		// 16% TP
		
		+WEAPON.NOALERT; // handling this manually
		+SQUAREPIXELS
	}
	
	States
	{
		Ready:
			DKRV A 1
			{
				if (!invoker.cocked)
					return ResolveState("Cock");
				
				return A_DeltaWeaponReady();
			}
			Loop;
		Deselect:
			DKRH A 2 A_StartSound("delta/revolver/holster1", CHAN_WEAPON,
				CHANF_OVERLAP);
			DKRH BC 2;
			DKRH D 3;
			TNT1 A 4 A_StartSound("delta/revolver/holster2", CHAN_WEAPON,
				CHANF_OVERLAP);
			TNT1 A 0 A_SwapWeapon;
			Stop;
		Select:
			TNT1 A 2 A_StartRaiseWeapon;
			DKRD A 2 A_StartSound("delta/revolver/deploy1", CHAN_WEAPON,
				CHANF_OVERLAP);
			DKRD C 2;
			DKRD DF 2 A_ReadyIfCocked(WRF_NOBOB | WRF_NOSWITCH);
			DKRD G 3
			{
				A_StartSound("delta/revolver/deploy2", CHAN_WEAPON,
					CHANF_OVERLAP);
				return A_ReadyIfCocked(WRF_NOBOB);
			}
			DKRD H 2 A_ReadyIfCocked(WRF_NOBOB);
			DKRD I 2 
			{
				if (invoker.cocked)
					return A_ReadyIfCocked(WRF_NOBOB);
				
				return ResolveState("Cock");
			}
			DKRD J 2 A_ReadyIfCocked(WRF_NOBOB);
			DKRV A 3 A_FinishRaiseWeapon;
			Stop;
		AtEase:
			DKRE ABCDE 2 A_DeltaWeaponReady(WRF_NOBOB | WRF_NOSWITCH, true);
			DKRE F 1 A_DeltaWeaponReady(WRF_NOBOB | WRF_NOSWITCH, true);
		// moved a state early cuz if we switch here, we'll play
		// atEase holster animation instead
		AtEaseLoop:
			DKRE FG 1 A_DeltaWeaponReady(atEase: true);
			Wait;
		AtEaseEnd:
			DKRE EDCBA 2 A_DeltaWeaponReady(WRF_NOBOB | WRF_NOSWITCH);
			Goto Ready;
		DeselectAtEase:
			DKRE HIJ 2;
			TNT1 A 4 A_StartSound("delta/revolver/holster2", CHAN_WEAPON,
				CHANF_OVERLAP);
			TNT1 A 0 A_SwapWeapon;
			Stop;
		Fire:
			DKRV B 1 A_KrisRevolverFire;
			DKRV B 1 A_AddRecoil(10, 1, p: -4);
			DKRV C 1 A_RemoveDynamicLight("revolverMuzzle");
			DKRV D 2 A_ZoomFactor;
			DKRV E 2;
			DKRV E 1 A_CheckReload; // fall-through is intentional
			DKRV F 3;
		Cock:
			DKRV G 2 A_DeltaWeaponReady(WRF_NOFIRE | WRF_NOBOB);
			DKRV H 1;
			DKRV I 2;
			DKRV J 2;
			DKRV J 1 A_StartSound("delta/revolver/cock1", CHAN_WEAPON,
				CHANF_OVERLAP);
			DKRV K 3;
			DKRV L 2;
			DKRV L 2 A_StartSound("delta/revolver/cock2", CHAN_WEAPON,
				CHANF_OVERLAP);
			DKRV N 4 A_Cock;
			DKRV P 3;
			DKRV Q 3 A_ReFire;
			DKRV R 2 A_ReFire;
			Goto Ready;
		AltFire:
			DKRC A 1
			{
				int cTics = invoker.chargeTics;
				if (cTics == invoker.MAX_CHARGE_TICS)
					return ResolveState("ChargeLoop");
				
				return ResolveState("ChargeUp") + cTics;
			}
		ChargeUp:
			#### ##### 1 A_KrisRevolverCharge;
			DKRC AAAAA 1 A_KrisRevolverCharge;
			DKRC BBBB 1
			{
				A_AddDynamicLight("revolverCharge", "DeltaRevolverCharge1");
				return A_KrisRevolverCharge();
			}
			DKRC CCC 1
			{
				A_AddDynamicLight("revolverCharge", "DeltaRevolverCharge2");
				return A_KrisRevolverCharge();
			}
			DKRC DDD 1
			{
				A_AddDynamicLight("revolverCharge", "DeltaRevolverCharge3");
				return A_KrisRevolverCharge();
			}
		ChargeLoop:
			DKRC E 1 A_KrisRevolverCharge(true);
			Loop;
		ChargeShot:
			DKRC F 1 A_KrisRevolverAltFire;
			DKRC F 1 A_AddRecoil(25, 3, p: -10);
			DKRC G 2 A_RemoveDynamicLight("revolverCharge");
			DKRC H 2 A_ZoomFactor;
			DKRC I 2;
			DKRC JKL 3;
			DKRV G 4;
			DKRV H 11 A_DeltaWeaponReady(WRF_NOFIRE | WRF_NOBOB);
			Goto Cock+1;
		Discharge:
			DKRC DDD 1
			{
				A_AddDynamicLight("revolverCharge", "DeltaRevolverCharge3");
				return A_KrisRevolverDischarge();
			}
			DKRC CCC 1
			{
				A_AddDynamicLight("revolverCharge", "DeltaRevolverCharge2");
				return A_KrisRevolverDischarge();
			}
			DKRC BBBB 1
			{
				A_AddDynamicLight("revolverCharge", "DeltaRevolverCharge1");
				return A_KrisRevolverDischarge();
			}
			DKRC A 1
			{
				A_RemoveDynamicLight("revolverCharge");
				return A_KrisRevolverDischarge();
			}
			DKRC AAAA 1 A_KrisRevolverDischarge;
			DKRV AAAAA 1 A_KrisRevolverDischarge;
			Goto Ready;
	}
	
	override void BeginPlay()
	{
		Super.BeginPlay();
		cocked = true;
	}
	
	override Vector2 ModifyBobLayer(Vector2 bob, int layer, double ticFrac)
	{
		let oldBob = Super.ModifyBobLayer(bob, layer, ticFrac),
			chargePerc = GetChargePercent(),
			bobPerc = max(0.2, 1 - chargePerc),
			shakeAmount = 1.5,
			shakePerc = chargePerc * chargePerc,
			shake = (cfrandom(-shakeAmount, shakeAmount), cfrandom(0,
				shakeAmount)) * shakePerc;
		
		return oldBob * bobPerc + shake;
	}
	
	override void OwnerDied()
	{
		Super.OwnerDied();
		
		chargeTics = 0;
		owner.A_StopSound(CHAN_CHARGE);
	}
	
	clearscope protected double GetChargePercent()
	{
		if (chargeTics < 0)
			return 0;
		if (chargeTics >= MAX_CHARGE_TICS)
			return 1;
		
		return double(chargeTics) / MAX_CHARGE_TICS;
	}
	
	protected action void A_KrisRevolverFire()
	{
		A_FireBullets(1, 1, 1, random[revolverDmg](40, 50), "KrisRevolverPuff",
			FBF_USEAMMO | FBF_NORANDOM, spawnHeight: 32 * invoker.GetCrouchFactor());
		A_StartSound("delta/revolver/fire", CHAN_WEAPON, CHANF_OVERLAP);
		A_AlertMonsters();
		A_OwnerPlayAttack();
		A_AddDynamicLight("revolverMuzzle", "DeltaGenericMuzzle");
		invoker.cocked = false;
		
		invoker.chargeTics = 0;
		if (IsActorPlayingSound(CHAN_CHARGE))
			A_StopSound(CHAN_CHARGE);
	}
	
	protected action void A_Cock()
	{
		invoker.cocked = true;
	}
	
	protected action state A_ReadyIfCocked(int flags)
	{
		if (invoker.cocked)
			return A_DeltaWeaponReady(flags);
		
		return ResolveState(null);
	}
	
	protected action state A_KrisRevolverCharge(bool looping = false)
	{
		let ply = invoker.owner.player;
		
		if (!ply)
			return ResolveState(null);
		
		A_WeaponReady(WRF_NOFIRE | WRF_NOBOB | WRF_NOSWITCH);
		
		if (!invoker.CheckAmmo(AltFire, false) || ply.PendingWeapon != WP_NOCHANGE)
			return invoker.chargeTics ? ResolveState("Discharge")
				: ResolveState("Ready");
		
		Weapon.DoReadyWeaponToBob(ply);
		int input = ply.cmd.buttons, oldInput = ply.oldButtons,
			cTics = invoker.chargeTics, maxCTics = invoker.MAX_CHARGE_TICS;
		double shake = 0.5;
		bool fullCharge = cTics == maxCTics;
		
		if ((!(input & BT_ALTATTACK) && (oldInput & BT_ALTATTACK)) ||
			(input & BT_ATTACK))
		{
			return fullCharge ? ResolveState("ChargeShot")
				: (ResolveState("Discharge") + (maxCTics-cTics));
		}
		
		if (fullCharge && !looping)
		{
			A_AddDynamicLight("revolverCharge", "DeltaRevolverChargeFull");
			return ResolveState("ChargeLoop");
		}
		
		if (looping)
			return ResolveState(null);
		
		invoker.chargeTics++;
		
		double perc = invoker.GetChargePercent();
		
		if (IsActorPlayingSound(CHAN_CHARGE))
		{
			A_SoundVolume(CHAN_CHARGE, perc);
			A_SoundPitch(CHAN_CHARGE, perc);
		}
		else
			A_StartSound("delta/revolver/charge", CHAN_CHARGE, CHANF_LOOPING,
				volume: perc, pitch: perc);
		
		shake *= perc * perc;
		return ResolveState(null);
	}
	
	protected action state A_KrisRevolverDischarge()
	{
		if (!invoker.chargeTics)
			return ResolveState("Ready");
		
		invoker.chargeTics--;
		
		if (player.PendingWeapon != WP_NOCHANGE && invoker.chargeTics)
			invoker.chargeTics--;
		
		if (!IsActorPlayingSound(CHAN_CHARGE))
			return ResolveState(null);
		
		if (!invoker.chargeTics)
			A_StopSound(CHAN_CHARGE);
		else 
		{
			double perc = invoker.GetChargePercent();
			A_SoundVolume(CHAN_CHARGE, perc);
			A_SoundPitch(CHAN_CHARGE, perc);
		}
		
		return ResolveState(null);
	}
	
	protected action void A_KrisRevolverAltFire()
	{
		let ply = PlayerPawn(invoker.owner);
		Actor a1, proj;
		[a1, proj] = A_FireProjectile("KrisRevolverChargeShot",
			flags: FPF_NOAUTOAIM);
		
		if (proj)
		{
			let aimPitch = AimLineAttack(ply.angle, PLAYERMISSILERANGE,
				flags: ALF_CHECK3D | ALF_NOFRIENDS),
				angleVec = AngleToVector(ply.angle),
				aimPitchVec = AngleToVector(aimPitch);
			
			proj.Vel = (angleVec.x * aimPitchVec.x, angleVec.y * aimPitchVec.x,
				-aimPitchVec.y) * proj.Speed;
		}
		
		A_StopSound(CHAN_CHARGE);
		A_StartSound("delta/revolver/charge_shot", CHAN_WEAPON, CHANF_OVERLAP);
		A_AlertMonsters();
		A_OwnerPlayAttack();
		A_AddDynamicLight("revolverCharge", "DeltaRevolverChargeShotMuzzle");
		A_ZoomFactor(0.99, ZOOM_INSTANT | ZOOM_NOSCALETURNING);
		invoker.cocked = false;
		invoker.chargeTics = 0;
		
		A_OwnerKnockback(0, 7.5);
	}
}

class KrisRevolverPuff : BulletPuff
{
	Default
	{
		ProjectileKickBack 25;
		Obituary "$OBIT_DELTA_REVOLVER";
		+NOEXTREMEDEATH
	}
}