class DeltaHealthBonus : HealthBonus replaces HealthBonus
{
	override bool TryPickup(in out Actor toucher)
	{
		toucher.GiveBody(5, toucher.GetMaxHealth() + 100);
		GoAwayAndDie();
		return true;
	}
}

class DeltaBerserk : Berserk replaces Berserk
{
	override bool TryPickup(in out Actor toucher)
	{
		toucher.GiveInventory("PowerStrength", 1);
		toucher.GiveBody(toucher.GetMaxHealth());
		GoAwayAndDie();
		return true;
	}
}

class DeltaSoulsphere : Soulsphere replaces Soulsphere
{
	override bool TryPickup(in out Actor toucher)
	{
		int diff = toucher.GetMaxHealth() - toucher.Health;
		
		// if we're more than 100 below max health, we'll always max health out
		// any closer than 100 points, and we just add 100 up to max + 100
		toucher.GiveBody(max(diff, 100), toucher.GetMaxHealth() + 100);
		GoAwayAndDie();
		return true;
	}
}

class DeltaMegasphere : Megasphere replaces Megasphere
{
	Default
	{
		-INVENTORY.ISARMOR; // this isn't an armor pickup anymore, it doesn't give us armor
	}
	
	States
	{
		Spawn:
			Goto Super::Spawn;
		Pickup:
			TNT1 A 0 A_GiveInventory("DeltaTensionMax", 250);
			TNT1 A 0 A_GiveInventory("DeltaMegasphereHealth", 1);
			Stop;
	}
}

class DeltaMegasphereHealth : Health replaces MegasphereHealth
{
	Default
	{
		+INVENTORY.ALWAYSPICKUP;
	}
	
	States
	{
		Pickup:
			Stop;
	}
	
	// making sure no matter who picks this thing up, we always give max overheal!
	override bool TryPickup(in out Actor toucher)
	{
		if (toucher.GiveBody(toucher.GetMaxHealth() + 100, toucher.GetMaxHealth() + 100))
		{
			GoAwayAndDie();
			return true;
		}
		
		return false;
	}
}