class DeltaHealthBonus : HealthBonus replaces HealthBonus
{
	Default
	{
		Inventory.Amount 5; // make sure healing numbers pop up correctly
	}
	
	override bool TryPickup(in out Actor toucher)
	{
		toucher.GiveBody(5, toucher.GetMaxHealth() * 2);
		GoAwayAndDie();
		return true;
	}
}

class DeltaHealth : Health abstract
{
	Default
	{
		Inventory.MaxAmount 0;
	}
	
	override bool TryPickup (in out Actor other)
	{
		PrevHealth = other.player != NULL ? other.player.health : other.health;
		
		// P_GiveBody adds one new feature, applied only if it is possible to
		// pick up negative health: Negative values are treated as positive
		// percentages, ie Amount -100 means 100% health, ignoring max amount.
		if (other.GiveBody(Amount, MaxAmount))
		{
			GoAwayAndDie();
			return true;
		}
		return false;
	}
}

class DeltaHealthPickup : HealthPickup abstract
{
	int maxHealth;
	private bool _alwaysAllowUse;
	private string _useMessage, _lowUseMessage;
	private int _prevHealth;
	
	property UseMessage: _useMessage;
	property LowUseMessage: _lowUseMessage;
	property AlwaysAllowUse: _alwaysAllowUse;
	property MaxHealth: maxHealth;
	
	Default
	{
		Health 10;
		Inventory.MaxAmount 9;
		Inventory.InterHubAmount 9;
		Inventory.Icon "";
		Inventory.UseSound "";
		
		// use a LANGUAGE entry for the messages, these ones are just examples!!
		Inventory.PickupMessage "You picked up a health pickup. Replace this text with your own!";
		DeltaHealthPickup.UseMessage "You used a health pickup. Replace this text with your own!";
		DeltaHealthPickup.LowUseMessage ""; // leave this alone to ALWAYS use the normal message
		DeltaHealthPickup.AlwaysAllowUse false;
		DeltaHealthPickup.MaxHealth 0;
		
		+Inventory.ISHEALTH
	}
	
	virtual string UseMessage()
	{
		if (_lowUseMessage != "" && _prevHealth < owner.GetMaxHealth(true)/4)
			return _lowUseMessage;
		
		return _useMessage;
	}
	
	override bool Use(bool pickup)
	{
		_prevHealth = owner.health;
		let result = owner.GiveBody(health, maxHealth);
		if (_alwaysAllowUse)
			result = true;
		if (result)
			owner.A_Log(UseMessage(), true);
		
		return result;
	}
}

class DeltaStimpack : DeltaHealth replaces Stimpack
{
	Default
	{
		Inventory.Amount 20;
		Inventory.PickupMessage "$GOTSTIM";
	}
	
	States
	{
		Spawn:
			STIM A -1;
			Stop;
	}
}

class DeltaMedikit : DeltaHealth replaces Medikit
{
	Default
	{
		Inventory.Amount 50;
		Inventory.PickupMessage "$GOTMEDIKIT";
		Health.LowMessage 50, "$GOTMEDINEED";
	}
	
	States
	{
		Spawn:
			MEDI A -1;
			Stop;
	}
}

class DeltaBerserk : DeltaHealthPickup replaces Berserk
{
	Default
	{
		Health -100;
		Tag "$TAG_BERSERK";
		
		Inventory.MaxAmount 1;
		Inventory.Icon "PSTRA0";
		Inventory.UseSound "";
		Inventory.PickupMessage "$GOTBERSERK";
		DeltaHealthPickup.UseMessage "$DELTA_USE_BERSERK";
		DeltaHealthPickup.AlwaysAllowUse true;
		
		+COUNTITEM;
		+Inventory.ISHEALTH;
	}
	
	States
	{
		Spawn:
			PSTR A -1 Bright;
			Stop;
	}
	
	override bool Use(bool pickup)
	{
		if (!Super.Use(pickup))
			return false;
		
		owner.A_StartSound("delta/use_powerup", CHAN_AUTO);
		owner.GiveInventory("PowerStrength", 1);
		return true;
	}
}

class DeltaSoulsphere : Soulsphere replaces Soulsphere
{
	override bool TryPickup(in out Actor toucher)
	{
		Amount = toucher.GetMaxHealth(true);
		MaxAmount = Amount*2;
		
		if (toucher.GiveBody(Amount, MaxAmount))
		{
			GoAwayAndDie();
			return true;
		}
		return false;
	}
}

class DeltaMegasphere : Megasphere replaces Megasphere
{
	Default
	{
		-Inventory.ISARMOR; // this isn't an armor pickup anymore, it doesn't give us armor
	}
	
	States
	{
		Spawn:
			Goto Super::Spawn;
		Pickup:
			TNT1 A 0 A_GiveInventory("DeltaTensionMax", 250);
			TNT1 A 0 A_GiveInventory("DeltaMegasphereHealth", 1);
			Stop;
	}
}

class DeltaMegasphereHealth : Health replaces MegasphereHealth
{
	Default
	{
		+Inventory.ALWAYSPICKUP;
	}
	
	States
	{
		Pickup:
			Stop;
	}
	
	// making sure no matter who picks this thing up, we always give max overheal!
	override bool TryPickup(in out Actor toucher)
	{
		Amount = MaxAmount = toucher.GetMaxHealth()*2;
		if (toucher.GiveBody(Amount, Amount))
		{
			GoAwayAndDie();
			return true;
		}
		
		return false;
	}
}