class DeltaNoHud : Inventory
{
	Default
	{
		+Inventory.UNDROPPABLE;
		+Inventory.UNTOSSABLE;
	}
}

// used to modify projectile damage directly!
class DeltaParryDamage : Inventory
{
	Default
	{
		+Inventory.UNDROPPABLE;
		+Inventory.UNTOSSABLE;
	}
	
	override void ModifyDamage(int damage, Name damageType, out int newDamage, bool passive, Actor inflictor, Actor source, int flags)
	{
		if (passive || !inflictor || !inflictor.CountInv("DeltaParried"))
			return;
		
		bool selfDmg = (source && source == self);
		int dmgMult = selfDmg ? random[parryDamage](1, 4) : random[parryDamage](22, 24);
		newDamage = dmgMult * max(5, inflictor.GetMissileDamage(0, 1))
            * max(1, int(!selfDmg) * G_SkillPropertyFloat(SKILLP_MonsterHealth));
	}
}

class DeltaParried : Inventory
{
	// allows us to save who initially fired the projectile for differentiating
	// between killing a player with their own projectile and killing them with
	// someone else's
	Actor oldTarget;
}