class DeltaGrenade : DeltaProjectile abstract
{
	DeltaGrenadeType grenadeType;
	Array<Actor> hitActors;
	double actorBounceFactor, fuseTime;
	sound armedSound, stickSound, explosionSound;
	class<DeltaGrenadeHitbox> hitboxClass;
	DeltaGrenadeHitbox hitbox;
	
	protected double curTime;
	protected bool fuseLit;
	protected bool exploded;
	protected Vector3 stickOffset;
	protected Actor stickVictim;
	protected float extraDamageFactor;
	
	property GrenadeType: grenadeType;
	property ActorBounceFactor: actorBounceFactor;
	property FuseTime: fuseTime;
	property ArmedSound: armedSound;
	property StickSound: stickSound;
	property ExplosionSound: explosionSound;
	property HitboxClass: hitboxClass;
	
	Default
	{
		Radius 6;
		Height 8;
		Speed 35;
		DamageFunction random[grenadeDamage](3, 5);
		Gravity 0.5;
		Projectile;
		BounceType "Grenade";
		BounceFactor 0.2;
		WallBounceFactor 0.2;
		RenderStyle "Add";
		Alpha 1;
		
		DeltaGrenade.GrenadeType GRENADE_NORMAL;
		DeltaGrenade.ActorBounceFactor 0.25;
		DeltaGrenade.FuseTime 3;
		DeltaGrenade.HitboxClass "";
		
		-NOGRAVITY
		+ALLOWBOUNCEONACTORS
		+BOUNCEONACTORS
		+CANBOUNCEWATER
		+ZDOOMTRANS
		+DONTBOUNCEONSKY
		+BRIGHT
	}
	
	override void BeginPlay()
	{
		Super.BeginPlay();
		curTime = fuseTime;
		fuseLit = false;
		exploded = false;
	}
	
	override void PostBeginPlay()
	{
		Super.PostBeginPlay();
		
		if (hitboxClass == null)
			return;
		
		hitbox = DeltaGrenadeHitbox(Actor.Spawn(hitboxClass, pos));
		if (hitbox)
			hitbox.parent = self;
	}
	
	override void Tick()
	{
		Super.Tick();
		
		if (!fuseLit || exploded)
			return;
		
		if (grenadeType == GRENADE_STICKY)
			StickyLogic();
		
		curTime -= 1./TICRATE;
		if (curTime <= 0)
			TryStartExplosion();
	}
	
	override int SpecialMissileHit(Actor victim)
	{
		if (!victim || !target || victim == target)
			return Super.SpecialMissileHit(victim);
		
		if (victim is "DeltaGrenadeHitbox" && DeltaGrenadeHitbox(victim).parent
			&& DeltaGrenadeHitbox(victim).parent == self)
			return MHIT_PASS;
		
		if (victim.bShootable)
			OnGrenadeHitActor(victim);
		
		if (grenadeType == GRENADE_NORMAL
			|| (victim.bSolid && grenadeType == GRENADE_STICKY))
		{
			Vel *= actorBounceFactor;
			hitActors.Push(victim);
		}
		
		return Super.SpecialMissileHit(victim);
	}
	
	override int SpecialBounceHit(Actor bounceMobj, Line bounceLine,
		readonly<SecPlane> bouncePlane, bool is3dFloor)
	{
		if (exploded || !bouncePlane)
			return Super.SpecialBounceHit(bounceMobj, bounceLine, bouncePlane, is3dFloor);
		
		//A_Log("negiC " .. bouncePlane.negiC .. ", 3d floor " .. is3dFloor);
		bool isFloor = is3dFloor ? (bouncePlane.negiC > 0) : (bouncePlane.negiC < 0);
		
		if (grenadeType == GRENADE_STICKY && isFloor)
		{
			Vel = (0, 0, 0);
			if (!fuseLit)
				A_StartSound(armedSound, CHAN_AUTO);
			fuseLit = true;
		}
		else
		{
			if (grenadeType != GRENADE_STICKY)
				fuseLit = true;
			
			Vel *= bounceFactor;
		}
		return Super.SpecialBounceHit(bounceMobj, bounceLine, bouncePlane, is3dFloor);
	}
	
	override bool CanCollideWith(Actor other, bool passive)
	{
		if (target && other == target)
			return false;
		if (other == hitbox)
			return false;
		if (stickVictim)
			return false;
		if (hitActors.Find(other) != hitActors.Size())
			return false;
		
		return Super.CanCollideWith(other, passive);
	}
	
	override void OnParry(Actor parrier)
	{
		grenadeType = GRENADE_CONTACT;
	}
	
	override bool CanBeParried()
	{
		switch (grenadeType)
		{
			case GRENADE_STICKY:
				if (stickVictim || fuseLit)
					return false;
			
			default: // fallthrough is intentional
				return !exploded;
		}
	}
	
	virtual void StickyLogic()
	{
		if (!stickVictim)
			return;
		
		if (stickVictim.health <= 0 && !exploded)
		{
			TryStartExplosion();
			return;
		}
		
		Warp(stickVictim, stickOffset.x, stickOffset.y, stickOffset.z,
			flags: WARPF_ABSOLUTEOFFSET | WARPF_INTERPOLATE);
	}
	
	virtual bool TryStartExplosion()
	{
		if (exploded)
			return false;
		
		fuseLit = false;
		exploded = true;
		SetState(ResolveState("Explode"));
		return true;
	}
	
	virtual void Explode()
	{
		A_NoGravity();
		Vel = (0, 0, 0);
		A_StartSound(explosionSound, CHAN_AUTO, attenuation: 0.5);
	}
	
	virtual void OnGrenadeHitActor(Actor victim)
	{
		if (victim is "DeltaGrenadeHitbox")
		{
			DeltaGrenadeHitbox(victim).parent.TryStartExplosion();
			TryStartExplosion();
			return;
		}
		
		switch (grenadeType)
		{
			case GRENADE_STICKY:
				if (fuseLit)
					break;
				
				stickVictim = victim;
				stickOffset = pos - victim.pos;
				fuseLit = true;
				A_StartSound(stickSound, CHAN_AUTO);
				int dmg = victim.DamageMobj(self, target, random[stickyDamage](5, 10), 'None');
				
				Vel = (0, 0, 0);
				A_NoGravity();
				if (dmg <= 0)
					break;
				
				DeltaUtil.ForceActorPain(victim, 'None');
				break;
				
			case GRENADE_CONTACT:
				TryStartExplosion();
				break;
				
			case GRENADE_NORMAL:
			default:
				Vel *= actorBounceFactor;
				break;
		}
	}
	
	action void A_GrenadeExplode()
	{
		invoker.Explode();
	}
}

class DeltaGrenadeHitbox : Actor abstract
{
	DeltaGrenade parent;
	
	Default
	{
		Radius 10;
		Height 12;
		Health 20;
		
		+SHOOTABLE		// not immune to hitscans!
		+NONSHOOTABLE	// can't be hit by projectiles <3
		+NOBLOOD
	}
	
	override void Tick()
	{
		Super.Tick();
		
		if (parent)
			SetOrigin(parent.pos + (0, 0, parent.height*0.5 - height*0.5), true);
		else
			Destroy();
	}
	
	override bool CanCollideWith(Actor other, bool passive)
	{
		if (parent)
		{
			if (other == parent)
				return false;
			if (parent.target && other == parent.target)
				return false;
		}
		
		return Super.CanCollideWith(other, passive);
	}
	
	override int DamageMobj(Actor inflictor, Actor source, int damage, Name mod,
		int flags, double angle)
	{
		if (!(flags & DMG_INFLICTOR_IS_PUFF))
			return 0;
		
		if (source == parent.target)
			return Super.DamageMobj(inflictor, source, damage * 2, mod, flags, angle);
		
		return Super.DamageMobj(inflictor, source, damage, mod, flags, angle);
	}
	
	override void Die(Actor source, Actor inflictor, int dmgFlags,
		Name meansOfDeath)
	{
		if (parent)
			parent.TryStartExplosion();
		
		Super.Die(source, inflictor, dmgFlags, meansOfDeath);
	}
}