class DeltaGrenade : DeltaParriable
{
	DeltaGrenadeType grenadeType;
	Array<Actor> hitActors;
	double actorBounceFactor, fuseTime;
	sound armedSound, stickSound, explosionSound;
	
	protected double curTime;
	protected bool fuseLit;
	protected bool exploded;
	protected Vector3 stickOffset;
	protected Actor stickVictim;
	
	property GrenadeType: grenadeType;
	property ActorBounceFactor: actorBounceFactor;
	property FuseTime: fuseTime;
	property ArmedSound: armedSound;
	property StickSound: stickSound;
	property ExplosionSound: explosionSound;
	
	Default
	{
		Radius 6;
		Height 8;
		Speed 35;
		DamageFunction 3;
		Gravity 0.5;
		Projectile;
		BounceType "Grenade";
		BounceFactor 0.2;
		WallBounceFactor 0.2;
		RenderStyle "Add";
		Alpha 1;
		
		DeltaGrenade.GrenadeType GRENADE_NORMAL;
		DeltaGrenade.ActorBounceFactor 0.25;
		DeltaGrenade.FuseTime 3;
		
		-NOGRAVITY
		+ALLOWBOUNCEONACTORS
		+BOUNCEONACTORS
		+CANBOUNCEWATER
		+ZDOOMTRANS
		+DONTBOUNCEONSKY
		+BRIGHT
	}
	
	override void BeginPlay()
	{
		Super.BeginPlay();
		curTime = fuseTime;
		fuseLit = false;
		exploded = false;
	}
	
	override void Tick()
	{
		Super.Tick();
		
		if (!fuseLit)
			return;
		
		if (grenadeType == GRENADE_STICKY)
			StickyLogic();
		
		curTime -= 1./TICRATE;
		if (curTime <= 0)
			TryStartExplosion();
	}
	
	override int SpecialMissileHit(Actor victim)
	{
		if (!victim || !target || victim == target)
			return Super.SpecialMissileHit(victim);
		
		if (victim.bShootable)
			OnGrenadeHitActor(victim);
		
		if (grenadeType == GRENADE_NORMAL
			|| (victim.bSolid && grenadeType == GRENADE_STICKY))
		{
			Vel *= actorBounceFactor;
			hitActors.Push(victim);
		}
		
		return Super.SpecialMissileHit(victim);
	}
	
	override int SpecialBounceHit(Actor bounceMobj, Line bounceLine,
		readonly<SecPlane> bouncePlane, bool is3dFloor)
	{
		if (!bouncePlane)
			return Super.SpecialBounceHit(bounceMobj, bounceLine, bouncePlane, is3dFloor);
		
		if (grenadeType == GRENADE_STICKY && bouncePlane.negiC < 0)
		{
			Vel = (0, 0, 0);
			if (!fuseLit)
				A_StartSound(armedSound, CHAN_AUTO);
			fuseLit = true;
		}
		else
		{
			if (grenadeType != GRENADE_STICKY)
				fuseLit = true;
			
			Vel *= bounceFactor;
		}
		return Super.SpecialBounceHit(bounceMobj, bounceLine, bouncePlane, is3dFloor);
	}
	
	override bool CanCollideWith(Actor other, bool passive)
	{
		if (stickVictim)
			return false;
		if (hitActors.Find(other) != hitActors.Size())
			return false;
		
		return Super.CanCollideWith(other, passive);
	}
	
	virtual void StickyLogic()
	{
		if (!stickVictim)
			return;
		
		if (stickVictim.health <= 0 && !exploded)
		{
			TryStartExplosion();
			return;
		}
		
		Warp(stickVictim, stickOffset.x, stickOffset.y, stickOffset.z,
			flags: WARPF_ABSOLUTEOFFSET | WARPF_INTERPOLATE);
	}
	
	virtual bool TryStartExplosion()
	{
		if (exploded)
			return false;
		
		fuseLit = false;
		exploded = true;
		return true;
	}
	
	virtual void Explode()
	{
		A_NoGravity();
		Vel = (0, 0, 0);
		A_StartSound(explosionSound, CHAN_AUTO, attenuation: 0.5);
	}
	
	virtual void OnGrenadeHitActor(Actor victim)
	{
		switch (grenadeType)
		{
			case GRENADE_STICKY:
				if (fuseLit)
					break;
				
				stickVictim = victim;
				stickOffset = pos - victim.pos;
				fuseLit = true;
				A_StartSound(stickSound, CHAN_AUTO);
				Vel = (0, 0, 0);
				A_NoGravity();
				break;
				
			case GRENADE_CONTACT:
				SetState(ResolveState("Explode"));
				break;
				
			case GRENADE_NORMAL:
			default:
				Vel *= actorBounceFactor;
				break;
		}
	}
	
	action void A_GrenadeExplode()
	{
		invoker.TryStartExplosion();
	}
}