// intentionally not in the ZSCRIPT includes!!

/// ---------------------------
///     ZOMBIE REPLACEMENTS    
/// ---------------------------
class DeltaZombieman : Zombieman replaces Zombieman
{
	States
	{
		Missile:
			POSS E 16 Bright A_FaceTarget;
			POSS F 4 Bright A_PosAttack;
			TNT1 A 0 A_JumpIf(skill < SKILL_NORMAL, "MissileDone");
			POSS E 8 Bright A_FaceTarget;
			POSS F 4 Bright A_PosAttack;
		MissileDone:
			POSS E 12;
			Goto See;
	}
}

class DeltaShotgunGuy : ShotgunGuy replaces ShotgunGuy
{
	Default
	{
		+QUICKTORETALIATE;
	}
	
	States
	{
		Missile:
			SPOS E 8 Slow A_FaceTarget;
			SPOS E 8 A_FaceTarget;
			SPOS F 6 Bright A_SposAttackUseAtkSound;
			SPOS EA 8;
			Goto See;
	}
}

class DeltaChaingunGuy : ChaingunGuy replaces ChaingunGuy
{
	double curMinSpread, curMaxSpread;
	
	Default
	{
		AttackSound "";
	}
	
	States
	{
		See:
			TNT1 A 0 A_CPosResetSpread;
			Goto Super::See;
		Pain:
			CPOS G 3;
			CPOS G 9 A_Pain;
			Goto See;
		Missile:
			CPOS E 4
			{
				if (skill < 2)
					A_SetTics(24);
				
				let tele = DeltaTelegraph.SpawnTelegraph("DeltaNoParryTelegraph");
				tele.SetOrigin(invoker.pos.PlusZ(46), false);
				A_FaceTarget();
			}
			CPOS EEE 4 A_FaceTarget;
			CPOS FE 3 Bright Slow
			{
				A_StartSound("weapons/pistol", CHAN_WEAPON, pitch: cfrandom(0.97, 1.03));
				
				let minSpread = invoker.curMinSpread,
					maxSpread = invoker.curMaxSpread,
					crouchMult = 1.,
					targ = DeltaPlayer(invoker.target);
				
				if (targ && targ.GetCrouchState() != DeltaPlayer.CS_STANDING)
					crouchMult = 2;
				
				A_CustomBulletAttack(
					frandom(minSpread, maxSpread) * randomPick(-1, 1), 				// horizontal spread
					frandom(minSpread, maxSpread) * crouchMult * randomPick(-1, 1), // vertical spread
					1,																// number of bullets
					random(5, 9), 													// damage per bullet
					flags: CBAF_EXPLICITANGLE										// flags
						| CBAF_NORANDOM,
					spawnHeight: 40
				);
			}
			CPOS F 1 A_CPosRefire;
			TNT1 A 0 A_CPosTightenSpread;
			Goto Missile+4;
	}
	
	override void BeginPlay()
	{
		Super.BeginPlay();
		A_CPosResetSpread();
	}
	
	protected action void A_CPosResetSpread()
	{
		invoker.curMinSpread = 0.5;
		invoker.curMaxSpread = 10.;
	}
	
	protected action void A_CPosTightenSpread()
	{
		invoker.curMinSpread = max(0.1, invoker.curMinSpread - 0.025);
		invoker.curMaxSpread = max(2., invoker.curMaxSpread - 0.1);
	}
}

/// -----------------------------
///     IMP REPLACEMENT STUFF    
/// -----------------------------
class DeltaImp : DoomImp replaces DoomImp
{
	States
	{
		Melee:
			TROO E 12
			{
				A_GiveInventory("DeltaParriable");
				A_FaceTarget();
			}
			TROO F 4 A_FaceTarget;
			TNT1 A 0 A_TakeInventory("DeltaParriable");
			Goto Missile+2;
		Missile:
			TROO E 10 A_FaceTarget;
			TROO F 4 A_FaceTarget;
			TROO G 8
			{
				if (skill != SKILL_EXPERT || !target || CheckMeleeRange())
				{
					A_FaceTarget();
					A_CustomComboAttack("DoomImpBall", 32, random(16, 21), "imp/melee");
					return;
				}
				
				// try to predict target's movement on expert difficulty
				let [ang, ptch] = DeltaUtil.PredictTarget(self, "DeltaDoomImpBall");
				A_SetAngle(ang);
				A_SpawnProjectile("DeltaDoomImpBall", flags: CMF_AIMDIRECTION, pitch: ptch);
			}
			TROO FE 2;
			Goto See;
		Pain:
			TROO H 2;
			TROO H 6 A_Pain;
			Goto See;
		Pain.WhileMelee:
			TROO H 2;
			TROO H 8 A_Pain;
			TROO A 4;
			Goto See;
	}
	
	override int DamageMobj(Actor inflictor, Actor source, int damage, Name mod, int flags, double angle)
	{
		let statePreDmg = curState,
			result = Super.DamageMobj(inflictor, source, damage, mod, flags, angle);
		if (result <= 0)
			return result;
		
		// if we get hit while we're trying to do a melee attack, we force stagger
		if (damage > 10 && statePreDmg.InStateSequence(ResolveState("Melee")))
			TriggerPainChance("WhileMelee", true);
		
		return result;
	}
}

class DeltaDoomImpBall : DoomImpBall replaces DoomImpBall
{
	Default
	{
		Speed 12;
		FastSpeed 18;
		DamageFunction random[impDamage](7, 12);
	}
}

/// -------------------------------
///     PINKY REPLACEMENT STUFF    
/// -------------------------------
class DeltaPinkyDemon : Demon replaces Demon
{
	int anger;
	double defaultSpeed;
	
	const ANGER_SET = 12;
	
	Default
	{
		Speed 12;
	}
	
	States
	{
		See:
			TNT1 A 0
			{
				if (!invoker.anger)
					return;
				invoker.anger--;
				if (invoker.anger)
					return;
				
				A_SetSpeed(12., invoker.speed - 0.25);
				if (invoker.speed > invoker.defaultSpeed)
					invoker.anger = invoker.ANGER_SET;
			}
			SARG AABBCCDD 2 Fast A_Chase;
			Loop;
		Melee:
			SARG E 4 Fast A_FaceTarget;
			SARG E 8 Fast
			{
				A_GiveInventory("DeltaParriable");
				A_FaceTarget();
			}
			SARG F 4 Fast A_FaceTarget;
			SARG G 8 Fast A_DeltaSargAttack;
			Goto See;
	}
	
	override void BeginPlay()
	{
		Super.BeginPlay();
		A_SetSpeed(frandom(11., 13.));
		defaultSpeed = speed;
	}
	
	override void Tick()
	{
		Super.Tick();
		if (health <= 0 || level.time % 3)
			return;
		
		for (int i = 0; i < int(speed - defaultSpeed) * 5; i++)
		{
			FSpawnParticleParams p;
			let ang = cfrandom(-180, 180);
			
			p.pos = level.Vec3Offset(pos, (cos(ang) * radius, sin(ang) * radius, cfrandom(5, height/2.)));
			p.vel = (cos(ang) * cfrandom(0.5, 2), sin(ang) * cfrandom(0.5, 2), cfrandom(1, 3));
			p.lifetime = crandom(10, 12);
			p.color1 = 0xffc00000;
			p.flags = SPF_FULLBRIGHT;
			p.size = cfrandom(5, 7);
			p.startAlpha = 1;
			p.fadestep = -1;
			level.SpawnParticle(p);
		}
	}
	
	protected action void A_DeltaSargAttack()
	{
		A_CustomMeleeAttack(random(33, 37), "", "");
		A_TakeInventory("DeltaParriable");
		
		if (!CheckMeleeRange())
		{
			A_SetSpeed(min(17., invoker.speed + 0.5));
			invoker.anger = invoker.ANGER_SET;
		}
	}
}

class DeltaSpectre : DeltaPinkyDemon replaces Spectre
{
	Default
	{
		Tag "$FN_SPECTRE";
		RenderStyle "OptFuzzy";
		Alpha 0.5;
		Obituary "$OB_SPECTREHIT";
		
		SeeSound "spectre/sight";
		AttackSound "spectre/melee";
		PainSound "spectre/pain";
		DeathSound "spectre/death";
		ActiveSound "spectre/active";
		
		+SHADOW
	}
}

/// -----------------------------------
///     CACODEMON REPLACEMENT STUFF    
/// -----------------------------------
class DeltaCacodemon : Cacodemon replaces Cacodemon
{
	Default
	{
		BloodColor "Blue";
	}
	
	States
	{
		Melee:
			HEAD B 2 A_FaceTarget;
			HEAD B 3
			{
				let tele = DeltaTelegraph.SpawnTelegraph("DeltaParryTelegraph");
				tele.SetOrigin(invoker.pos.PlusZ(49), false);
				A_GiveInventory("DeltaParriable");
			}
			HEAD C 5 A_FaceTarget;
			HEAD D 5 A_DeltaCacoAttack;
			Goto See;
	}
	
	protected action void A_DeltaCacoAttack()
	{
		A_HeadAttack();
		A_TakeInventory("DeltaParriable");
	}
}

class DeltaCacodemonBall : CacodemonBall replaces CacodemonBall
{
	Default
	{
		Speed 12;
		DamageFunction random[cacoDamage](20, 30);
	}
}

/// ------------------------------------
///     HELL NOBLE REPLACEMENT STUFF    
/// ------------------------------------
class DeltaHellKnight : HellKnight replaces HellKnight
{
	Default
	{
		BloodColor "37 73 2b";
	}
	
	States
	{
		Missile:
			TNT1 A 0 A_Jump(256, "Stomp");
			BOSS E 12
			{
				A_FaceTarget();
			}
			BOSS F 8 A_FaceTarget;
			BOSS G 8 A_BruisAttack;
			Goto See;
		Stomp:
			BOSS H 4 A_ChangeVelocity(z: 4, flags: CVF_REPLACE);
			BOSS A 1 A_ChangeVelocity(z: -10, flags: CVF_REPLACE);
			BOSS A 1 A_CheckStomp;
			Goto See;
	}
	
	protected action void A_CheckStomp()
	{
		
	}
}

class DeltaBaronOfHell : BaronOfHell replaces BaronOfHell
{
	Default
	{
		Speed 10;
		BloodColor "37 73 2b";
	}
	
	States
	{
		See:
			BOSS AABBCCDD 3 A_Chase;
			Loop;
		Pain:
			TNT1 A 0 { invoker.bXFlip = false; }
			Goto Super::Pain;
		Melee:
			BOSS E 12
			{
				if (skill < SKILL_NORMAL)
					A_SetTics(18);
				
				let tele = DeltaTelegraph.SpawnTelegraph("DeltaNoParryTelegraph");
				tele.SetOrigin(invoker.pos.PlusZ(49), false);
				A_FaceTarget();
			}
			BOSS F 4 Slow A_FaceTarget;
			BOSS G 8
			{
				A_FaceTarget();
				
				if (!CheckMeleeRange())
					return ResolveState("FanPattern") + 2;
				
				A_StartSound("baron/melee", CHAN_AUTO);
				if (!invoker.target.DamageMobj(invoker, invoker, random(60, 80), "Melee"))
					return ResolveState(null);
				
				let knockbackAmt = 25.,
					ang = invoker.AngleTo(invoker.target);
				A_ChangeVelocity(cos(ang) * knockbackAmt, sin(ang) * knockbackAmt, 12., CVF_REPLACE, ptr: AAPTR_TARGET);
				return ResolveState(null);
			}
			BOSS A 4;
			Goto See;
		Missile:
			TNT1 A 0 A_Jump(256, "FanPattern", "WideSpread");
			Stop;
		FanPattern:
			BOSS E 10
			{
				invoker.bXFlip = randomPick(false, true);
				A_FaceTarget();
			}
			BOSS F 4 A_FaceTarget;
			BOSS G 2
			{
				A_FaceTarget();
				
				if (skill < SKILL_NORMAL)
					A_SpawnProjectile("BaronBall");
				else
					A_SpawnProjectile("BaronBall", angle: invoker.bXFlip? 30. : -30.);
			}
			BOSS G 2
			{
				if (skill < SKILL_NORMAL)
					return;
				
				A_SpawnProjectile("BaronBall", angle: invoker.bXFlip? 15. : -15.);
			}
			BOSS G 4
			{
				if (skill < SKILL_NORMAL)
					return;
				
				A_SpawnProjectile("BaronBall");
			}
			TNT1 A 0 { invoker.bXFlip = false; }
			Goto See;
		WideSpread:
			BOSS E 10 Slow
			{
				let tele = DeltaTelegraph.SpawnTelegraph("DeltaParryTelegraph");
				tele.SetOrigin(invoker.pos.PlusZ(49), false);
				
				let [ang, ptch] = DeltaUtil.PredictTarget(invoker, "BaronBall");
				A_SetAngle(ang);
				A_SetPitch(ptch);
			}
			BOSS E 4;
			BOSS F 6;
			BOSS G 4 Slow
			{
				A_FaceTarget();
				for (double ang = -30; ang <= 30; ang += skill < SKILL_NORMAL? 30 : 20)
					let proj = A_SpawnProjectile("BaronBall", flags: CMF_AIMOFFSET,
						angle: ang);
			}
			BOSS G 4;
			Goto See;
	}
}

class DeltaBaronBall : BaronBall replaces BaronBall
{
	Default
	{
		Speed 15;
		DamageFunction random[baronDamage](40, 50);
	}
}

class DeltaRocket : Rocket replaces Rocket
{
	Default
	{
		Speed 25;
		FastSpeed 27;
		DamageFunction random[rocketDamage](80, 120);
	}
}