extend class DeltaHud
{
	Array<int> playersSeen;
	protected Le_GlScreen gl_proj;
	protected Le_Viewport viewport;
	
	private TextureID _coopPanelBack, _coopPanelBorders, _deathmatchPanelBack,
		_deathmatchPanelBorders, _deathmatchPanelBarBorders,
		_deathmatchCurrentPlayer;
	
	protected void SetUpMultiplayer()
	{
		_coopPanelBack 				= TexMan.CheckForTexture("COOPBACK");
		_coopPanelBorders			= TexMan.CheckForTexture("sprites/hud/coop panel borders.png");
		_deathmatchPanelBack 		= TexMan.CheckForTexture("DTHMBACK");
		_deathmatchPanelBorders		= TexMan.CheckForTexture("sprites/hud/deathmatch score border.png");
		_deathmatchPanelBarBorders	= TexMan.CheckForTexture("sprites/hud/deathmatch score bar border.png");
		_deathmatchCurrentPlayer 	= TexMan.CheckForTexture("DTHMCPLY");
		
		gl_proj						= new("Le_GlScreen");
	}
	
	protected void DrawMultiplayerUnderlay(double ticFrac)
	{
		if (!gl_proj || automapActive)
			return;
		
		let landscape = Screen.GetWidth() >= Screen.GetHeight(),
			window_aspect = 1.0 * Screen.GetWidth() / Screen.GetHeight(),
			resolution = 960 * (landscape? window_aspect : 1./window_aspect, 1) /
				(Screen.GetHeight()/480);
		
		gl_proj.CacheCustomResolution(resolution);
		gl_proj.CacheFov(CPlayer.fov);
		gl_proj.Reorient(_pos, (_angles.z, _angles.x, _angles.y));
		gl_proj.BeginProjection();
		
		for (int i = 0; i < players.Size(); i++)
		{
			if (!playerInGame[i] || players[i] == CPlayer)
				continue;
			
			let ply = players[i].mo;
			if (!ply || !(ply is "DeltaPlayer"))
				continue;
			
			gl_proj.ProjectActorPosPortal(ply, (0, 0, ply.height+3), ticFrac);
			if (!gl_proj.IsInFront())
				continue;
			
			viewport.FromHud();
			let draw_pos = viewport.SceneToCustom(gl_proj.ProjectToNormal(),
					resolution),
				dist = gl_proj.Distance(),
				trans = "\c-",
				deltaPly = DeltaPlayer(ply),
				maxRenderDist = 1500.,
				targetAlpha = 1.,
				targetScale = clamp(1 - (dist/maxRenderDist), 0., 1.);
			
			if (playersSeen.Find(i) == playersSeen.Size())
			{
				if (!CPlayer.mo.IsTeammate(ply))
					continue;
				
				targetAlpha *= 0.25;
			}
			
			if (deltaPly.IsCrouching())
				targetAlpha *= 0.5;
			
			if (CPlayer.mo.IsTeammate(ply))
			{
				if (players[i].damageCount)
					trans = "\c[DeltaRed]";
				else if (deltaPly.InMissileState())
					trans = "\c[DeltaYellow]";
			}
			else if (ply.health <= 0)
				continue;
			else
				trans = "\c[DeltaRed]";
			
			string username = players[i].GetUserName();
			let xOffset = smallFont.StringWidth(username, false) * 0.5 * targetScale,
				yOffset = smallFont.GetHeight() * targetScale;
			
			Screen.DrawText(smallFont, Font.CR_UNTRANSLATED, draw_pos.x - xOffset,
				draw_pos.y - yOffset, trans .. username,
				DTA_VIRTUALWIDTHF, resolution.x,
				DTA_VIRTUALHEIGHTF, resolution.y, DTA_KEEPRATIO, true,
				DTA_Alpha, targetAlpha, DTA_ScaleX, targetScale, DTA_ScaleY, targetScale);
		}
	}
	
	protected void DrawMultiplayerOverlay()
	{
		if (deathmatch)
			DrawDeathmatch();
		else if (multiplayer)
			DrawCoop();
	}
	
	protected void DrawCoop()
	{
		double curX = _hBorder, curY = _vBorder;
		
		for (int i = 0; i < players.Size(); i++)
		{
			if (!players[i].mo || players[i] == CPlayer)
				continue;
			if (!playerInGame[i])
				continue;
			if (!(players[i].mo is "DeltaPlayer"))
				continue;
			
			DrawMultiplayerHealth(DeltaPlayer(players[i].mo), (curX, curY));
			curY += 34 * _universalScale.y;
		}
	}
	
	protected void DrawDeathmatch()
	{
		if (!CPlayer.mo || !(CPlayer.mo is "DeltaPlayer"))
			return;
		
		/// ---------------------------
		/// DRAWING TEAMMATE HEALTHBARS
		/// ---------------------------
		double curX = _hBorder, curY = _vBorder;
		let ply = DeltaPlayer(CPlayer.mo);
		Array<int> teamsFound;
		
		if (teamplay)
		{
			for (int i = 0; i < players.Size(); i++)
			{
				if (!players[i].mo)
					continue;
				if (!playerInGame[i])
					continue;
				if (!(players[i].mo is "DeltaPlayer"))
					continue;
				
				if (teamsFound.Find(players[i].GetTeam()) == teamsFound.Size())
					teamsFound.Push(players[i].GetTeam());
				
				if (players[i] == CPlayer)
					continue;
				if (!CPlayer.mo.IsTeammate(players[i].mo))
					continue;
				
				DrawMultiplayerHealth(DeltaPlayer(players[i].mo), (curX, curY));
				curY += 34 * _universalScale.y;
			}
		}
		
		int deathmatchW, deathmatchH;
		[deathmatchW, deathmatchH] = TexMan.GetSize(_deathmatchPanelBack);
		let deathmatchPos = (-deathmatchW/2. * _universalScale.x,
			-_vBorder - deathmatchH * _universalScale.y);
		
		DrawTexture(_deathmatchPanelBack, deathmatchPos,
			DI_SCREEN_CENTER_BOTTOM | DI_ITEM_LEFT_TOP, scale: _universalScale);
		DrawTexture(_deathmatchPanelBorders, deathmatchPos,
			DI_SCREEN_CENTER_BOTTOM | DI_ITEM_LEFT_TOP | DI_ITEM_OFFSETS,
			col: ply.GetCharacterColor(), scale: _universalScale);
		
		/// ------------
		/// DRAWING TIME
		/// ------------
		if (timelimit)
		{
			let timeStr = DeltaUtil.GetTimeString(ceil(timelimit * 60. * TICRATE) - level.maptime),
				textWidth = _consoleFont.mFont.StringWidth(timeStr)*1.5,
				fontHeight = _consoleFont.mFont.GetHeight()*1.5;
			
			DrawString(_consoleFont, timeStr,
				(deathmatchPos.x + (41 - textWidth/2.)*_universalScale.x,
					deathmatchPos.y + (35 - fontHeight/2.)*_universalScale.y),
				DI_SCREEN_CENTER_BOTTOM, scale: _universalScale*1.5);
		}
		else
			DrawTexture(_infiniteText,
				(deathmatchPos.x + 44*_universalScale.x, deathmatchPos.y + 35*_universalScale.y),
				DI_SCREEN_CENTER_BOTTOM | DI_ITEM_CENTER, scale: _universalScale*3);
		
		/// -------------
		/// DRAWING FRAGS
		/// -------------
		let leaderFrags = -500;
		let leaderIndex = 0;
		Color barColor;
		TextureID characterIcon;
		double hudFontHeight = _drHudFont.mFont.GetHeight(), sc = 1,
			consoleFontHeight = _consoleFont.mFont.GetHeight() * sc;
		string nameShown = "";
		bool leaderIsUs = false;
		
		// Drawing leader bar (may be us)
		if (teamplay)
		{
			for (uint i = 0; i < uint(teams.Size()); i++)
			{
				if (teamsFound.Find(i) == teamsFound.Size())
					continue;
				
				int curTeamFrags = GetTeamFrags(i);
				
				if (curTeamFrags <= leaderFrags)
					continue;
				
				leaderFrags = curTeamFrags;
				leaderIndex = i;
				leaderIsUs = CPlayer.GetTeam() == i;
				nameShown = teams[i].mName;
				barColor = teams[i].GetPlayerColor();
			}
		}
		else
		{
			for (int i = 0; i < players.Size(); i++)
			{
				if (!playerInGame[i])
					continue;
				if (!(players[i].mo is "DeltaPlayer"))
					continue;
				
				let deltaPly = DeltaPlayer(players[i].mo);
				int curPlyFrags = players[i].fragCount;
				
				if (curPlyFrags < leaderFrags)
					continue;
				if (curPlyFrags == leaderFrags && players[i] != CPlayer && leaderFrags == 0)
					continue;
				
				leaderFrags = curPlyFrags;
				leaderIndex = i;
				nameShown = players[i].GetUserName();
				characterIcon = deltaPly.GetCharacterIconId();
				barColor = players[i].GetColor();
				leaderIsUs = CPlayer == players[i];
			}
		}
		
		barColor |= 0xff000000;
		nameShown.Truncate(16);
		
		Fill(barColor, deathmatchPos.x + 92*_universalScale.x, deathmatchPos.y + 6*_universalScale.y,
			min(1., (max(0., leaderFrags) / max(1., fraglimit))) * 150 * _universalScale.x, 24 * _universalScale.y,
			DI_SCREEN_CENTER_BOTTOM);
		DrawTexture(_deathmatchPanelBarBorders, deathmatchPos + (88*_universalScale.x, 2*_universalScale.y),
			DI_SCREEN_CENTER_BOTTOM | DI_ITEM_LEFT_TOP, col: barColor, scale: _universalScale);
		DrawTexture(characterIcon, deathmatchPos + (94*_universalScale.x, 8*_universalScale.y),
			DI_SCREEN_CENTER_BOTTOM | DI_ITEM_LEFT_TOP,
			box: (25*_universalScale.x, 20*_universalScale.y), scale: _universalScale);
		DrawString(_drHudFont, "" .. leaderFrags,
			deathmatchPos + ((deathmatchW - 8)*_universalScale.x, (18 - hudFontHeight*0.75)*_universalScale.y),
			DI_SCREEN_CENTER_BOTTOM | DI_TEXT_ALIGN_RIGHT, scale: _universalScale*3);
		DrawString(_consoleFont, nameShown,
			(deathmatchPos.x + (teamplay ? 94 : 121)*_universalScale.x, deathmatchPos.y + (18 - consoleFontHeight/2.)*_universalScale.y),
			DI_SCREEN_CENTER_BOTTOM | DI_TEXT_ALIGN_LEFT, scale: _universalScale*sc);
		
		// Bottom bar (second place if we're leader, us otherwise)
		let bottomFrags = -500, bottomIndex = 0;
		barColor = 0x0;
		characterIcon = null;
		
		if (leaderIsUs)
		{
			if (teamplay)
			{
				for (int i = 0; i < teams.Size(); i++)
				{
					if (teamsFound.Find(i) == teamsFound.Size())
						continue;
					
					int curTeamFrags = GetTeamFrags(i);
					
					if (i == leaderIndex || curTeamFrags <= bottomFrags)
						continue;
					
					bottomFrags = curTeamFrags;
					bottomIndex = i;
					nameShown = teams[i].mName;
					barColor = teams[i].GetPlayerColor();
				}
			}
			else
			{
				for (int i = 0; i < players.Size(); i++)
				{
					if (i == leaderIndex)
						continue;
					if (!playerInGame[i])
						continue;
					if (players[i] == CPlayer)
						continue;
					if (!(players[i].mo is "DeltaPlayer"))
						continue;
					
					let deltaPly = DeltaPlayer(players[i].mo);
					int curPlyFrags = players[i].fragCount;
					
					if (curPlyFrags < bottomFrags)
						continue;
					
					bottomFrags = curPlyFrags;
					bottomIndex = i;
					nameShown = players[i].GetUserName();
					characterIcon = deltaPly.GetCharacterIconId();
					barColor = deltaPly.GetCharacterColor();
				}
			}
		}
		else
		{
			if (teamplay)
			{
				int teamIndex = CPlayer.GetTeam();
				nameShown = teams[CPlayer.GetTeam()].mName;
				barColor = teams[teamIndex].GetPlayerColor();
				bottomFrags = GetTeamFrags(teamIndex);
			}
			else
			{
				bottomFrags = CPlayer.fragCount;
				characterIcon = ply.GetCharacterIconId();
				barColor = ply.GetCharacterColor();
				nameShown = CPlayer.GetUserName();
			}
		}
		
		DrawTexture(_deathmatchCurrentPlayer, deathmatchPos +
			(252*_universalScale.x, (leaderIsUs ? 6 : 40)*_universalScale.y),
			DI_SCREEN_CENTER_BOTTOM | DI_ITEM_LEFT_TOP, col: ply.GetCharacterColor(),
			scale: _universalScale);
		
		if (!characterIcon && (!teamplay || teamsFound.Size() == 1))
			return;
		
		barColor |= 0xff000000;
		nameShown.Truncate(16);
		Fill(barColor, deathmatchPos.x + 92*_universalScale.x, deathmatchPos.y + 40*_universalScale.y,
			min(1., (max(0., bottomFrags) / max(1., fraglimit))) * 150 * _universalScale.x, 24 * _universalScale.y,
			DI_SCREEN_CENTER_BOTTOM);
		DrawTexture(_deathmatchPanelBarBorders, deathmatchPos + (88*_universalScale.x, 36*_universalScale.y),
			DI_SCREEN_CENTER_BOTTOM | DI_ITEM_LEFT_TOP, col: barColor, scale: _universalScale);
		DrawTexture(characterIcon, deathmatchPos + (94*_universalScale.x, 42*_universalScale.y),
			DI_SCREEN_CENTER_BOTTOM | DI_ITEM_LEFT_TOP,
			box: (25*_universalScale.x, 20*_universalScale.y), scale: _universalScale);
		DrawString(_drHudFont, "" .. bottomFrags,
			deathmatchPos + ((deathmatchW - 8)*_universalScale.x, (52 - hudFontHeight*0.75)*_universalScale.y),
			DI_SCREEN_CENTER_BOTTOM | DI_TEXT_ALIGN_RIGHT, scale: _universalScale*3);
		DrawString(_consoleFont, nameShown,
			(deathmatchPos.x + (teamplay ? 94 : 121)*_universalScale.x, deathmatchPos.y + (52 - consoleFontHeight/2.)*_universalScale.y),
			DI_SCREEN_CENTER_BOTTOM | DI_TEXT_ALIGN_LEFT, scale: _universalScale*sc);
	}
	
	protected void DrawMultiplayerHealth(DeltaPlayer ply, Vector2 pos)
	{
		double barWidth = _universalScale.x * 100,
		barHeight = _universalScale.y * 7;
		Color iconColor = ply.health > 0 ? 0xffffffff : 0x80ff4040;
		let userStr = ply.player.GetUserName();
		
		// this only works because _consoleFont is monospace
		int charWidth = _consoleFont.mFont.GetCharWidth("0") / 2;
		int panelW, panelH;
		[panelW, panelH] = TexMan.GetSize(_coopPanelBack);
		uint allowedLength = 19;
		
		if (ply.health <= 0)
			allowedLength -= 7;
		
		if (userStr.Length() > allowedLength)
		{
			userStr.Truncate(allowedLength);
			userStr = userStr .. "-";
		}
		
		if (ply.health <= 0)
			userStr = userStr .. " (DEAD)";
		
		DrawTexture(_coopPanelBack, pos, DI_SCREEN_LEFT_TOP | DI_ITEM_LEFT_TOP,
			scale: _universalScale);
		DrawTexture(_coopPanelBorders, pos, DI_SCREEN_LEFT_TOP | DI_ITEM_LEFT_TOP,
			col: ply.GetCharacterColor(), scale: _universalScale);
		DrawTexture(ply.GetCharacterIconID(), pos + _universalScale*6,
			DI_SCREEN_LEFT_TOP | DI_ITEM_LEFT_TOP, box: (25*_universalScale.x, 20*_universalScale.y),
			col: iconColor);
		DrawString(_consoleFont, userStr, pos + (32*_universalScale.x, 8*_universalScale.y),
			scale: _universalScale/2);
		
		double healthPerc = GetHealthPerc(ply);
		Fill(ply.GetCharacterColor(), pos.X + 34*_universalScale.x, pos.Y + 19*_universalScale.y,
			barWidth * min(1, healthPerc), barHeight, DI_SCREEN_LEFT_TOP);
		Fill(ply.GetOverhealColor(), pos.X + 34*_universalScale.x, pos.Y + 19*_universalScale.y,
			barWidth * max(0, healthPerc - 1), barHeight, DI_SCREEN_LEFT_TOP);
		DrawString(_drHudFont, "" .. max(0, ply.Health), (pos.X + 147*_universalScale.x, pos.Y + 20*_universalScale.y),
			DI_SCREEN_LEFT_TOP | DI_TEXT_ALIGN_RIGHT, scale: _universalScale);
	}
	
	protected int GetTeamFrags(int teamIndex)
	{
		let frags = 0;
		
		for (int i = 0; i < players.Size(); i++)
		{
			if (!playerInGame[i])
				continue;
			if (players[i].GetTeam() != teamIndex)
				continue;
			
			frags += players[i].fragCount;
		}
		
		return frags;
	}
}