class DeltaHud : BaseStatusBar
{
	enum DeathCounterType
	{
		DC_OFF,
		DC_LEVEL,
		DC_ENTIRE_RUN
	}
	enum SpeedrunStats
	{
		SPD_OFF,
		SPD_TIMER,
		SPD_SPEED,
		SPD_BOTH
	}
	enum LevelStats
	{
		LVLSTATS_OFF,
		LVLSTATS_INFO,
		LVLSTATS_KILLS_SECRETS,
		LVLSTATS_ALL
	}
	enum ShowMillisecondsType
	{
		SMT_ONLY_IF_NO_MINS = -1,
		SMT_NEVER = 0,
		SMT_ALWAYS
	}
	
	DeltaPlayer ply;
	Vector3 pos, angles;
	protected bool _infiniteAmmo;
	protected double _hBorder, _vBorder, _oldTp, _oldHealth;
	protected Vector2 _universalScale, _inverseUniversalScale;
	protected HUDFont _consoleFont, _noShadowFont, _drHudFont, _tpFont;
	protected TextureID _hpText, _tpBarBack, _tpBarBackMax, _tpBar,
		_tpTimerStencil, _tpHighlight, _leftPanelBack, _leftPanelBorders,
		_vignette, _vignette2, _infiniteText, _defaultCrosshair,
		_offhandCrosshair, _reticleBarOverlay, _reticleBar, _ammoBottom,
		_ammoBottomBorders, _statsBackground, _statsBorders,
		_statsKillIcon, _statsItemIcon, _statsSecretIcon, _statsDeathIcon,
		_statsTimeIcon, _statsSpeedIcon, _invPanel, _invPanelBorders;
	protected InventoryBarState _bar;
	protected DynamicValueInterpolator _tpInterp, _healthInterp;
	
	private Array<class<Ammo> > _ammos;
	private Array<class<Key> > _keys;
	
	const WEAPON_SLOTS_WRAPAROUND = 9;
	
	enum CONTROL_ICON_IDS
	{
		DELTA_CONTROLICON_TEXT = 0xff, // use text for this key and keys below it!
		
		DELTA_CONTROLICON_MOUSE1, DELTA_CONTROLICON_MOUSE2, DELTA_CONTROLICON_MOUSE3,
		DELTA_CONTROLICON_MOUSE4, DELTA_CONTROLICON_MOUSE5, DELTA_CONTROLICON_MOUSE6,
		DELTA_CONTROLICON_MOUSE7, DELTA_CONTROLICON_MOUSE8,
		
		DELTA_CONTROLICON_MAX
	}
	
	Map<int, TextureID> controlIcons;
	Map<name, TextureID> ammoIcons;
	
	override void Init()
	{
		Super.Init();
		completeBorder = false;
		
		_drHudFont 			= HUDFont.Create("DRHUDFONT");
		_consoleFont 		= HUDFont.Create(smallFont);
		_noShadowFont 		= HUDFont.Create("smallFontNoShadow");
		_tpFont 			= HUDFont.Create(smallFont);
		
		_vignette			= TexMan.CheckForTexture("graphics/hud/vignette.png");
		_vignette2			= TexMan.CheckForTexture("graphics/hud/vignette2.png");
		
		_hpText				= TexMan.CheckForTexture("graphics/hud/text/hpText.png");
		_infiniteText		= TexMan.CheckForTexture("graphics/hud/text/infiniteText.png");
		_tpBarBack			= TexMan.CheckForTexture("graphics/hud/newTpBarBack.png");
		_tpBar				= TexMan.CheckForTexture("graphics/hud/newTpBar.png");
		_tpTimerStencil		= TexMan.CheckForTexture("graphics/hud/tpTimerStencil.png");
		_leftPanelBack		= TexMan.CheckForTexture("graphics/hud/newLeftPanel.png");
		_leftPanelBorders	= TexMan.CheckForTexture("graphics/hud/newLeftPanelBorders.png");
		
		_defaultCrosshair	= TexMan.CheckForTexture("graphics/hud/reticle/emptyHandedReticle.png");
		_offhandCrosshair	= TexMan.CheckForTexture("graphics/hud/reticle/offhandReticle.png");
		_reticleBarOverlay	= TexMan.CheckForTexture("graphics/hud/reticle/reticleBarBorder.png");
		_reticleBar			= TexMan.CheckForTexture("graphics/hud/reticle/reticleBar.png");
		
		_statsBackground	= TexMan.CheckForTexture("graphics/hud/stats/statsBottom.png");
		_statsBorders		= TexMan.CheckForTexture("graphics/hud/stats/statsBottomBorders.png");
		_statsKillIcon		= TexMan.CheckForTexture("graphics/hud/stats/statsKills.png");
		_statsItemIcon		= TexMan.CheckForTexture("graphics/hud/stats/statsItems.png");
		_statsSecretIcon	= TexMan.CheckForTexture("graphics/hud/stats/statsSecrets.png");
		_statsDeathIcon		= TexMan.CheckForTexture("graphics/hud/stats/statsDeaths.png");
		_statsTimeIcon		= TexMan.CheckForTexture("graphics/hud/stats/statsTime.png");
		_statsSpeedIcon		= TexMan.CheckForTexture("graphics/hud/stats/statsSpeed.png");
		
		_ammoBottom			= TexMan.CheckForTexture("graphics/hud/newAmmoBottom.png");
		_ammoBottomBorders	= TexMan.CheckForTexture("graphics/hud/newAmmoBottomBorders.png");
		_invPanel 			= TexMan.CheckForTexture("graphics/hud/itemPanel.png");
		_invPanelBorders 	= TexMan.CheckForTexture("graphics/hud/itemPanelBorders.png");
		
		SetUpIndicatorTextures();
		SetUpDamagePopups();
		SetUpBossBars();
		SetUpMessages();
		SetUpMultiplayer();
		
		controlIcons.Insert(DELTA_CONTROLICON_MOUSE1, TexMan.CheckForTexture("graphics/hud/buttons/mouse/leftClick.png"));
		controlIcons.Insert(DELTA_CONTROLICON_MOUSE2, TexMan.CheckForTexture("graphics/hud/buttons/mouse/rightClick.png"));
		controlIcons.Insert(DELTA_CONTROLICON_MOUSE3, TexMan.CheckForTexture("graphics/hud/buttons/mouse/middleClick.png"));
		controlIcons.Insert(DELTA_CONTROLICON_MOUSE4, TexMan.CheckForTexture("graphics/hud/buttons/mouse/mouse4.png"));
		controlIcons.Insert(DELTA_CONTROLICON_MOUSE5, TexMan.CheckForTexture("graphics/hud/buttons/mouse/mouse5.png"));
		controlIcons.Insert(DELTA_CONTROLICON_MOUSE6, TexMan.CheckForTexture("graphics/hud/buttons/mouse/mouse6.png"));
		controlIcons.Insert(DELTA_CONTROLICON_MOUSE7, TexMan.CheckForTexture("graphics/hud/buttons/mouse/mouse7.png"));
		controlIcons.Insert(DELTA_CONTROLICON_MOUSE8, TexMan.CheckForTexture("graphics/hud/buttons/mouse/mouse8.png"));
		
		ammoIcons.Insert('Clip', 		TexMan.CheckForTexture("graphics/hud/ammo/bulletAmmo.png"));
		ammoIcons.Insert('Shell', 		TexMan.CheckForTexture("graphics/hud/ammo/shellAmmo.png"));
		ammoIcons.Insert('RocketAmmo', 	TexMan.CheckForTexture("graphics/hud/ammo/rocketAmmo.png"));
		ammoIcons.Insert('Cell', 		TexMan.CheckForTexture("graphics/hud/ammo/cellAmmo.png"));
		ammoIcons.Insert('ID24Fuel', 	TexMan.CheckForTexture("graphics/hud/ammo/fuelAmmo.png"));
		
		_tpInterp = DynamicValueInterpolator.Create(0, 0.2, 1, 30);
		_healthInterp = DynamicValueInterpolator.Create(0, 0.2, 1, 30);
		_bar = InventoryBarState.Create();
	}
	
	override void Tick()
	{
		Super.Tick();
		
		if (!CPlayer.mo)
			return;
		if (!ply)
		{
			ply = DeltaPlayer(CPlayer.mo);
			if (!ply)
				return;
		}
		
		if (paused || menuActive == Menu.On || consoleState == c_down || consoleState == c_falling)
			return;
		
		if (_deathSequence)
		{
			FreezeDamagePopups();
			TickDeathSequence();
			return;
		}
		
		_infiniteAmmo = sv_infiniteAmmo
			|| (ply.FindInventory('PowerInfiniteAmmo', true) != null);
		
		_oldTp = _tpInterp.GetValue();
		
		double tpInterpTarget = 0.;
		
		if (ply)
			tpInterpTarget = _infiniteAmmo ? ply.maxTensionPoints : ply.tensionPoints;
		
		_tpInterp.Update(int(tpInterpTarget));
		
		_oldHealth = _healthInterp.GetValue();
		_healthInterp.Update(int(GetHealthPerc() * 100));
		
		TickIndicators();
		TickDamagePopups();
		TickBossBars();
		TickMessages();
		
		_keys.Clear();
		
		for (int i = 0; i < Key.GetKeyTypeCount(); i++)
		{
			let keyClass = Key.GetKeyType(i);
			
			if (!ply.CountInv(keyClass))
				continue;
			
			_keys.Push(keyClass);
		}
		
		let weaps = CPlayer.weapons;
		if (!weaps)
			return;
		
		_ammos.Clear();
		
		for (int i = 1;; i++)
		{
			int weapCount = weaps.SlotSize(i);
			
			if (i > WEAPON_SLOTS_WRAPAROUND)
			{
				i = -1;
				continue;
			}
			if (i == 0)
				break;
			
			if (!weapCount)
				continue;
			
			for (int j = 0; j < weapCount; j++)
			{
				if (!ply.CountInv(weaps.GetWeapon(i, j)))
					continue;
				
				Weapon inv = Weapon(ply.FindInventory(weaps.GetWeapon(i, j)));
				
				if (!inv)
					continue;
				if (inv.AmmoType1 && _ammos.Find(inv.AmmoType1) == _ammos.Size())
					_ammos.Push(inv.AmmoType1);
				if (inv.AmmoType2 && _ammos.Find(inv.AmmoType2) == _ammos.Size())
					_ammos.Push(inv.AmmoType2);
			}
		}
	}
	
	protected float GetHealthPerc(DeltaPlayer ply = null)
	{
		if (!self.ply)
			return 0;
		if (!ply)
			ply = self.ply;
		
		let maxHp = ply.GetMaxHealth();
		if (maxHp == 0)
			return 0;
		
		return clamp(ply.health * 1. / maxHp, 0, 2);
	}
	
	override void Draw(int state, double ticFrac)
	{
		Super.Draw(state, ticFrac);
		DrawDeathSequence(ticFrac);
		
		if (!ply || state == HUD_None || !cl_delta_showHud)
			return;
		
		_universalScale = GetHudScale() * 0.5;
		_inverseUniversalScale = _universalScale / cl_delta_hudScale;
		_universalScale = (1/_universalScale.x, 1/_universalScale.y) * cl_delta_hudScale;
		
		_hBorder = 35 * _universalScale.x;
		_vBorder = 25 * _universalScale.y;
		
		if (_deathSequence && _deathSequence.gameOverState > DeltaGameOver.FREEZE_FRAME)
			return;
		
		if (GetHealthPerc() <= 0.4
			&& cl_delta_lowHealthVignette && !automapActive)
		{
			double
				maxSine = 0.125,
				alpha = (1 - (GetHealthPerc() / 0.4)) * (1 - maxSine),
				sine = maxSine;
			if (CPlayer.health > 0)
				sine *= sin(3 * (level.time + ticFrac));
			
			Screen.DrawTexture(_vignette, false, 0, 0, DTA_Fullscreen, true,
				DTA_FullScreenScale, FSMode_ScaleToScreen,
				DTA_Alpha, min(1, alpha + sine), DTA_Color, ply.GetPainFlash());
		}
		
		let airTime = max(0, CPlayer.air_finished - level.mapTime + 1),
			airPerc = double(airTime) / level.airSupply;
		
		if (ply.waterLevel >= 2 && airPerc <= 0.4 && !automapActive)
		{
			double alpha = 1 - (airPerc / 0.4);
			Screen.DrawTexture(_vignette2, false, 0, 0, DTA_Fullscreen, true,
				DTA_FullScreenScale, FSMode_ScaleToScreen, DTA_Alpha, alpha,
				DTA_Color, Color(255, 0, 0, 0));
		}
		
		BeginHUD();
		DrawMultiplayerUnderlay(ticFrac);
		DrawBossBars();
		DrawIndicators(ticFrac);
		DrawMultiplayerOverlay();
		
		if (CPlayer.Health <= 0 && !_deathSequence)
			return;
		
		DrawMessages(ticFrac);
		
		if (!ply.CountInv("DeltaNoHud"))
		{
			DrawLeftPanel(ticFrac);
			DrawRightPanel();
		}
		
		DrawReticle(ticFrac);
		DrawOxygen();
	}
	
	override void ShowPop(int popNum)
	{
		Super.ShowPop(popNum);
		Console.Printf("ShowPop called, popNum is " .. popNum);
	}
	
	void ResetHUD()
	{
		_tpInterp.Reset(0);
		_healthInterp.Reset(int(GetHealthPerc() * 100));
		ClearIndicators();
		ClearDamagePopups();
	}
	
	protected TextureID GetMainBindingIcon(string cmd)
	{
		int k = Bindings.GetKeysForCommand(cmd);
		
		// not a mouse button!
		if (k <= DELTA_CONTROLICON_TEXT || k >= DELTA_CONTROLICON_MAX)
			return null;
		
		return controlIcons.GetIfExists(k);
	}
	
	protected void DisplayBinding(string cmd, Vector2 pos, int flags, Vector2 scale)
	{
		let tex = GetMainBindingIcon(cmd);
		
		if (tex)
			DrawTexture(tex, pos, flags, scale: scale);
		else
		{
			int k = Bindings.GetKeysForCommand(cmd);
			string keys = Keybindings.NameKeys(k, 0);
			double newY = pos.y;
			
			if (flags & DI_ITEM_VCENTER)
				newY -= smallFont.GetHeight() / 2 * _universalScale.y;
			
			DrawString(_consoleFont, keys, (pos.x, newY), flags, scale: scale);
		}
	}
	
	protected void DrawHpBar(double ticFrac)
	{
		double
			barWidth = 120 * _universalScale.x,
			barHeight = 12 * _universalScale.y,
			healthInterpValue = DeltaUtil.Lerp(_oldHealth,
				_healthInterp.GetValue(), ticFrac) * 0.01;
		
		Fill(0xffff0000, _hBorder + 63*_universalScale.x,
			-_vBorder - 22*_universalScale.y, barWidth * min(1, healthInterpValue),
			barHeight, DI_SCREEN_LEFT_BOTTOM);
		
		let hpPerc = GetHealthPerc();
		
		Fill(ply.GetCharacterColor(), _hBorder + 63*_universalScale.x,
			-_vBorder - 22*_universalScale.y, barWidth * min(1, hpPerc),
			barHeight, DI_SCREEN_LEFT_BOTTOM);
		
		if (hpPerc > 1)
		{
			Fill(0xffff0000, _hBorder + 63*_universalScale.x,
				-_vBorder - 22*_universalScale.y,
				barWidth * max(0, healthInterpValue-1), barHeight,
				DI_SCREEN_LEFT_BOTTOM);
			Fill(ply.GetOverhealColor(), _hBorder + 63*_universalScale.x,
				-_vBorder - 22*_universalScale.y, barWidth * (hpPerc-1),
				barHeight, DI_SCREEN_LEFT_BOTTOM);
		}
		
		bool showLowHealth = hpPerc <= 0.33;
		let trns = showLowHealth? "\c[DeltaLowHealth]" : "",
			hpText = trns .. max(0, ply.health),
			maxHpText = trns .. max(0, ply.GetMaxHealth()),
			maxHpWidth = _drHudFont.mFont.StringWidth(maxHpText) * 2,
			slashWidth = _drHudFont.mFont.GetCharWidth("/");
		
		DrawTexture(_hpText, (_hBorder + 46*_universalScale.x,
			-_vBorder - 20*_universalScale.y), DI_SCREEN_LEFT_BOTTOM
			| DI_ITEM_LEFT_TOP, scale: _universalScale,
			col: showLowHealth ? 0xffffff00 : 0xffffffff);
		DrawString(_drHudFont, maxHpText, (_hBorder + 183*_universalScale.x,
			-_vBorder - 35*_universalScale.y), DI_SCREEN_LEFT_BOTTOM
			| DI_TEXT_ALIGN_RIGHT, scale: _universalScale*2);
		DrawString(_drHudFont, trns.. "/",
			(_hBorder + (182-maxHpWidth)*_universalScale.x,
				-_vBorder - 35*_universalScale.y),
			DI_SCREEN_LEFT_BOTTOM | DI_TEXT_ALIGN_RIGHT, scale: _universalScale);
		DrawString(_drHudFont, hpText,
			(_hBorder + (182-slashWidth-maxHpWidth)*_universalScale.x,
				-_vBorder - 35*_universalScale.y),
			DI_SCREEN_LEFT_BOTTOM | DI_TEXT_ALIGN_RIGHT, scale: _universalScale*2);
	}
	
	protected void DrawTpBar(double ticFrac)
	{
		let tpPos = (_hBorder, -_vBorder - 149*_universalScale.y),
			sc = 1.,
			tpPerc = _infiniteAmmo? 1. : ply.tensionPoints / ply.maxTensionPoints;
		
		DrawTexture(_tpBarBack, tpPos,
			DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_TOP, scale: sc * _universalScale);
		
		Screen.EnableStencil(true);
		Screen.SetStencil(0, SOP_Increment, SF_ColorMaskOff);
		
		let barPos = tpPos + (13*_universalScale.x, 19*_universalScale.y) * sc;
		
		// defining stencil mask
		DrawTexture(_tpBar, barPos, DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_TOP,
			scale: sc * _universalScale);
		
		Screen.SetStencil(1, SOP_Keep, SF_AllOn);
		
		// using stencil mask
		double
			tpLerp = DeltaUtil.Lerp(_oldTp, _tpInterp.GetValue(), ticFrac),
			tpBarHeight = 167 * sc * _universalScale.x;
		
		let lerpPerc = _infiniteAmmo? 1. : (tpLerp / ply.maxTensionPoints);
		
		Fill(0xffff0000, barPos.x, barPos.y, lerpPerc * tpBarHeight,
			15*sc*_universalScale.y, DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_BOTTOM);
		Fill((tpPerc < 1)? 0xffff7f27 : 0xffffff00, barPos.x, barPos.y,
			tpPerc * tpBarHeight, 15*sc*_universalScale.y,
			DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_BOTTOM);
		
		let tipPerc = max(tpPerc, lerpPerc);
		if (tipPerc > 0 && tipPerc < 1)
			Fill(0xffffffff, barPos.x + tpBarHeight * tipPerc, barPos.y,
				2 * sc * _universalScale.x, 19 * sc * _universalScale.y,
				DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_BOTTOM);
		
		Screen.ClearStencil();
		Screen.SetStencil(0, SOP_Increment, SF_ColorMaskOff);
		
		// defining stencil mask
		DrawTexture(_tpTimerStencil,
			(tpPos.x + 2 * sc * _universalScale.x, tpPos.y + 14 * sc * _universalScale.y),
			DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_TOP, scale: _universalScale * sc);
		
		Screen.SetStencil(1, SOP_Keep, SF_AllOn);
		
		// using stencil mask
		double tpTimer = 1.;
		
		if (!_infiniteAmmo)
			tpTimer = clamp(ply.tensionDrainTimer /
				(ply.DRAIN_TIMER_START
					* G_SkillPropertyFloat(SKILLP_AmmoFactor) * sv_ammoFactor),
				0, 1);
		
		Fill(0xffffffff, tpPos.x + 2 * sc * _universalScale.x,
			tpPos.y + 14 * sc * _universalScale.y,
			189 * sc * tpTimer * _universalScale.x, 25 * sc * _universalScale.y);
		
		Screen.EnableStencil(false);
		Screen.ClearStencil();
		
		if (_infiniteAmmo)
		{
			DrawTexture(_infiniteText, tpPos + (51*_universalScale.x, 2.5*_universalScale.y),
				DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_TOP, scale: _universalScale,
				col: 0x80000000);
			DrawTexture(_infiniteText, tpPos + (50*_universalScale.x, 1.5*_universalScale.y),
				DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_TOP, scale: _universalScale);
			return;
		}
		
		let tpFont = (tpPerc >= 1)? _consoleFont : _tpFont,
			tpText = (tpPerc >= 1)? "\c[DeltaYellow]MAX" : String.Format("%d%%", int(tpPerc * 100));
		double tpTextWidth = tpFont.mFont.StringWidth(tpText) * sc;
		
		DrawString(tpFont, tpText,
			(tpPos.x + (80 - tpTextWidth)*_universalScale.x, tpPos.y - 4*_universalScale.y),
			DI_SCREEN_LEFT_BOTTOM, alpha: 1., scale: _universalScale*sc);
	}
	
	const STATS_NUM = 6;
	
	protected void DrawLevelStats(DeltaPlayer ply)
	{
		let levelStats = cl_delta_showLevelStats,
			deathCounter = cl_delta_showDeathCounter,
			speedrunStats = cl_delta_showSpeedrunStats,
			curY = -_vBorder - 7*_universalScale.y,
			infoX = _hBorder + 195*_universalScale.x;
		
		bool showStats = false;
		bool stats[STATS_NUM] =
		{
			levelStats >= LVLSTATS_KILLS_SECRETS,			// kills
			levelStats >= LVLSTATS_KILLS_SECRETS,			// secrets
			levelStats == LVLSTATS_ALL,						// items
			deathCounter && !netgame,						// deaths
			speedrunStats && speedrunStats != SPD_SPEED,	// time
			speedrunStats && speedrunStats != SPD_TIMER		// speed
		};
		
		let h = 10 * _universalScale.y;
		for (int i = 0; i < STATS_NUM; i++)
		{
			if (!stats[i] && !automapActive)
				continue;
			
			h += 17 * _universalScale.y;
			
			if (showStats)
				continue;
			
			infoX += 100 * _universalScale.x;
			showStats = true;
		}
		
		if (levelStats >= LVLSTATS_INFO || automapActive)
		{
			let author = level.authorName,
				fontH = _consoleFont.mFont.GetHeight(),
				infoY = -_vBorder - fontH*_universalScale.y;
			
			if (author != "")
			{
				DrawString(_consoleFont, "\c[DeltaKris]by " .. author, (infoX, infoY),
					DI_SCREEN_LEFT_BOTTOM | DI_TEXT_ALIGN_LEFT,
					scale: _universalScale);
				infoY -= (fontH - 2) * _universalScale.y;
			}
			
			DrawString(_consoleFont, level.levelName, (infoX, infoY),
				DI_SCREEN_LEFT_BOTTOM | DI_TEXT_ALIGN_LEFT, scale: _universalScale);
		}
		
		if (!showStats)
			return;
		
		DrawTexture(_statsBackground, (_hBorder + 195*_universalScale.x,
			curY), DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_TOP,
			scale: _universalScale);
		DrawTexture(_statsBorders, (_hBorder + 195*_universalScale.x,
			curY), DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_TOP,
			scale: _universalScale, col: ply.GetCharacterColor());
		Fill(Color(170, 0, 0, 0), _hBorder + 195*_universalScale.x,
			curY - h, 100 * _universalScale.x, h, DI_SCREEN_LEFT_BOTTOM);
		Fill(ply.GetCharacterColor(), _hBorder + 197*_universalScale.x,
			curY - h + 2*_universalScale.y, 2 * _universalScale.x,
			h - 2*_universalScale.y, DI_SCREEN_LEFT_BOTTOM);
		Fill(ply.GetCharacterColor(), _hBorder + 291*_universalScale.x,
			curY - h + 2*_universalScale.y, 2 * _universalScale.x,
			h - 2*_universalScale.y, DI_SCREEN_LEFT_BOTTOM);
		Fill(ply.GetCharacterColor(), _hBorder + 199*_universalScale.x,
			curY - h + 2*_universalScale.y, 94 * _universalScale.x,
			2*_universalScale.y, DI_SCREEN_LEFT_BOTTOM);
		
		curY += 6 * _universalScale.y;
		let curFont = _tpFont,
			halfFontH = curFont.mFont.GetGlyphHeight("0") / 2.;
		
		for (int i = stats.Size() - 1; i >= 0; i--)
		{
			if (!stats[i] && !automapActive)
				continue;
			
			TextureID iconTex;
			string text = "",
				perfectTrans = "\c[DeltaYellow]",
				zeroTrans = "\c[DeltaGrey]";
			bool noKillsSecretsItems = !level.Total_Monsters && !level.Total_Secrets
				&& !level.Total_Items;
			int scoreState = 0; // -1 = none in map, 0 = incomplete, 1 = perfect
			
			switch (i)
			{
				case 0: // kills
					iconTex = _statsKillIcon;
					text = CPlayer.KillCount .. "/" .. level.Total_Monsters;
					scoreState = (noKillsSecretsItems)? -1 :
						level.Killed_Monsters >= level.Total_Monsters;
					break;
				case 1: // secrets
					iconTex = _statsSecretIcon;
					text = CPlayer.SecretCount .. "/" .. level.Total_Secrets;
					scoreState = (noKillsSecretsItems)? -1 :
						level.Found_Secrets >= level.Total_Secrets;
					break;
				case 2: // items
					iconTex = _statsItemIcon;
					text = CPlayer.ItemCount .. "/" .. level.Total_Items;
					scoreState = (noKillsSecretsItems)? -1 :
						level.Found_Items >= level.Total_Items;
					break;
				case 3: // deaths
					iconTex = _statsDeathIcon;
					int deathCount = deathCounter == DC_ENTIRE_RUN?
						data_delta_currentDeathsSngSeg : data_delta_currentDeathsLevel;
					text = String.Format("%d", deathCount);
					scoreState = deathCount == 0;
					break;
				case 4: // time
					iconTex = _statsTimeIcon;
					text = DeltaUtil.GetTimeString(level.mapTime, SMT_ALWAYS);
					int par = level.info.parTime;
					scoreState = par && (level.mapTime/TICRATE < par);
					break;
				case 5: // speed
					iconTex = _statsSpeedIcon;
					text = String.Format("%u u/s", ply.vel.Length() * TICRATE);
					break;
				default:
					break;
			}
			
			if (scoreState == -1)
				text = "--/--";
			
			let textW = curFont.mFont.StringWidth(text, false);
			
			if (scoreState == -1)
				text = zeroTrans .. text;
			else if (scoreState == 1)
				text = perfectTrans .. text;
			
			curY -= 17 * _universalScale.y;
			DrawTexture(iconTex, (_hBorder + 204*_universalScale.x, curY),
				DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT | DI_ITEM_VCENTER,
				scale: _universalScale, col: ply.GetCharacterColor());
			DrawString(curFont, text, (_hBorder + (286 - textW)*_universalScale.x,
				curY - halfFontH*_universalScale.y),
				DI_SCREEN_LEFT_BOTTOM | DI_TEXT_ALIGN_LEFT, scale: _universalScale);
		}
	}
	
	protected void DrawLeftPanel(double ticFrac)
	{
		if (!ply)
			return;
		
		DrawTexture(_leftPanelBack, (_hBorder, -_vBorder), DI_SCREEN_LEFT_BOTTOM
			| DI_ITEM_LEFT_BOTTOM, scale: _universalScale);
		DrawTexture(_leftPanelBorders, (_hBorder, -_vBorder),
			DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_BOTTOM, scale: _universalScale,
			col: ply.GetCharacterColor());
		
		let currentFace = GetMugshot(4, Mugshot.DISABLEOUCH | Mugshot.DISABLERAMPAGE);
		DrawTexture(currentFace, (_hBorder + 8*_universalScale.x,
			-_vBorder - 25*_universalScale.y), DI_SCREEN_LEFT_BOTTOM
			| DI_ITEM_LEFT | DI_ITEM_VCENTER, scale: _universalScale);
		DrawTexture(ply.GetNameTagID(),
			(_hBorder + 47*_universalScale.x, -_vBorder - 40*_universalScale.y),
			DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_TOP, scale: _universalScale);
		
		DrawHpBar(ticFrac);
		DrawKeys(_hBorder + 69*_universalScale.x,
			-_vBorder - 99*_universalScale.y, 119*_universalScale.x,
			43*_universalScale.y);
		DrawTpBar(ticFrac);
		
		let offhandTpCost = ply.GetOffhandTpCost(),
			offhandColor =
				(ply.CanUseOffhand() && ply.GetTension(ply.GetOffhandTpCost()) == DeltaPlayer.TP_FAIL)?
					0x80606060 : (ply.GetIsUsingOffhand()? 0xffffa060 : 0xffffffff);
		
		DisplayBinding("+offhand", (_hBorder + 8*_universalScale.x,
			-_vBorder - 73*_universalScale.y), DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_TOP,
			_universalScale);
		DrawTexture(ply.GetOffhandIconID(),
			(_hBorder + 28*_universalScale.x, -_vBorder - 84*_universalScale.y),
			DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_TOP, col: offhandColor,
			scale: _universalScale);
		let str = String.Format("%d%% TP", offhandTpCost * 100 / ply.maxTensionPoints),
			textW = _tpFont.mFont.StringWidth(str, false);
		DrawString(_tpFont, str,
			(_hBorder + (31 - textW/2.)*_universalScale.x, -_vBorder - 102*_universalScale.y),
			DI_SCREEN_LEFT_BOTTOM, scale: _universalScale);
		
		DrawDamagePopups((_hBorder + (10+TexMan.GetSize(currentFace)/2.)*_universalScale.x,
			-_vBorder - 25*_universalScale.y), ticFrac);
		
		if (deathmatch)
			return;
		
		DrawLevelStats(ply);
	}
	
	protected void DrawRightPanel()
	{
		if (!ply)
			return;
		
		DrawAmmo();
		DrawInventory();
	}
	
	protected void DrawInventory()
	{
		let [invW, invH] = TexMan.GetSize(_invPanel);
		let [ammoW, ammoH] = TexMan.GetSize(_ammoBottom);
		double
			widgetW = invW * _universalScale.x,
			widgetH = invH * _universalScale.y;
		
		let panelX = -_hBorder - (ammoW + 2)*_universalScale.x;
		DrawTexture(_invPanel, (panelX, -_vBorder), 
			DI_SCREEN_RIGHT_BOTTOM | DI_ITEM_RIGHT_BOTTOM, scale: _universalScale);
		DrawTexture(_invPanelBorders, (panelX, -_vBorder), 
			DI_SCREEN_RIGHT_BOTTOM | DI_ITEM_RIGHT_BOTTOM | DI_ITEM_OFFSETS,
			col: ply.GetCharacterColor(), scale: _universalScale);
		
		let invFirst = ValidateInvFirst(1);
		if (!invFirst)
			return;
		
		DrawString(_drHudFont, "" .. invFirst.Amount,
			(panelX - widgetW + 5*_universalScale.x, -_vBorder - widgetH + 20*_universalScale.y),
			DI_SCREEN_RIGHT_BOTTOM | DI_ITEM_LEFT_TOP, scale: _universalScale * 3);
		
		TextureID icon = invFirst.Icon;
		if (icon.IsNull() && invFirst.SpawnState && invFirst.SpawnState.sprite != 0)
			icon = invFirst.SpawnState.GetSpriteTexture(0);
		if (!icon.IsValid())
			return;
		
		DrawTexture(icon,
			(panelX - widgetW + 46*_universalScale.x, -_vBorder - widgetH + 24*_universalScale.y),
			DI_SCREEN_RIGHT_BOTTOM | DI_ITEM_CENTER, box: _universalScale*32, scale: _universalScale);
	}
	
	protected void DrawAmmo()
	{
		if (!_ammos.Size())
			return;
		
		DrawTexture(_ammoBottom, (-_hBorder, -_vBorder),
			DI_SCREEN_RIGHT_BOTTOM | DI_ITEM_RIGHT_BOTTOM, scale: _universalScale);
		DrawTexture(_ammoBottomBorders, (-_hBorder, -_vBorder),
			DI_SCREEN_RIGHT_BOTTOM | DI_ITEM_RIGHT_BOTTOM,
			col: ply.GetCharacterColor(), scale: _universalScale);
		
		int ammoW, ammoH;
		[ammoW, ammoH] = TexMan.GetSize(_ammoBottom);
		
		double widgetWidth = ammoW * _universalScale.x,
			hPerAmmo = 22 * _universalScale.y,
			h = _ammos.Size() * hPerAmmo + (ammoH+1)*_universalScale.y;
		
		Fill(Color(170, 0, 0, 0), -_hBorder - widgetWidth,
			-_vBorder - h - (ammoH-1)*_universalScale.y, widgetWidth,
			h - _universalScale.y, DI_SCREEN_RIGHT_BOTTOM);
		Fill(ply.GetCharacterColor(), -_hBorder - (ammoW-2)*_universalScale.x,
			-_vBorder - h - 2*_universalScale.y,
			2*_universalScale.x, h - (ammoH-3)*_universalScale.y);
		Fill(ply.GetCharacterColor(), -_hBorder - 4*_universalScale.x,
			-_vBorder - h - 2*_universalScale.y,
			2*_universalScale.x, h - (ammoH-3)*_universalScale.y);
		Fill(ply.GetCharacterColor(), -_hBorder - (ammoW-2)*_universalScale.x,
			-_vBorder - h - 4*_universalScale.y,
			widgetWidth - 4*_universalScale.x, 2*_universalScale.y);
		
		for (int i = 0; i < _ammos.Size(); i++)
		{
			let am = _ammos[_ammos.Size() - 1 - i];
			let amCount = ply.CountInv(am);
			let ammoIcon = ammoIcons.GetIfExists(am.GetClassName());
			double curAlpha = 0.2;
			let weap = CPlayer.ReadyWeapon;
			
			if (weap && (am == weap.AmmoType1 || am == weap.AmmoType2))
				curAlpha = 1;
			
			DrawTexture(ammoIcon, (-_hBorder - widgetWidth + 8*_universalScale.x,
				-_vBorder - (4+ammoH)*_universalScale.y - hPerAmmo*i),
				DI_ITEM_LEFT_BOTTOM | DI_SCREEN_RIGHT_BOTTOM,
				alpha: curAlpha,
				box: _universalScale*16, scale: _universalScale);
			
			if (_infiniteAmmo)
				DrawTexture(_infiniteText, (-_hBorder - 8*_universalScale.x,
					-_vBorder - (4+ammoH)*_universalScale.y - hPerAmmo*i),
					DI_ITEM_RIGHT_BOTTOM | DI_SCREEN_RIGHT_BOTTOM,
					alpha: curAlpha, scale: _universalScale*2);
			else
				DrawString(_drHudFont, "" .. amCount,
					(-_hBorder - (8*_universalScale.x), -_vBorder -
						(i+1)*hPerAmmo - (ammoH-2)*_universalScale.y),
					DI_SCREEN_RIGHT_BOTTOM | DI_TEXT_ALIGN_RIGHT,
					alpha: curAlpha,
					scale: _universalScale*3);
		}
	}
	
	protected void DrawKeys(double x, double y, double maxW, double maxH)
	{
		if (!ply)
			return;
		
		let spacing = 1.,
			keyBox = 16.,
			totalWidth = spacing + keyBox;
		int rowLimit = int(maxW / (totalWidth * _universalScale.x));
		
		for (int j = 0; j < _keys.Size(); j++)
		{
			int xPlace = j % rowLimit, yPlace = j / rowLimit;
			
			readonly<Key> curKey = GetDefaultByType(_keys[j]);
			TextureID icon;
			
			if (curKey.SpawnState && curKey.SpawnState.sprite != 0)
				icon = curKey.SpawnState.GetSpriteTexture(0);
			
			if (icon.IsNull())
				icon = curKey.Icon;
			
			if (!icon.IsValid())
				continue;
			
			DrawTexture(icon, (x + keyBox/2.*_universalScale.x, y + keyBox/2.*_universalScale.y)
				+ (xPlace * totalWidth*_universalScale.x, yPlace * totalWidth*_universalScale.y),
				DI_SCREEN_LEFT_BOTTOM | DI_ITEM_CENTER,
				box: keyBox * _universalScale, scale: _universalScale);
		}
	}
	
	protected void DrawReticle(double ticFrac)
	{
		if (automapActive || !ply || !cl_delta_showCrosshair)
			return;
		
		DrawQuickInfo(ticFrac);
		
		if (ply.GetIsUsingOffhand())
			return;
		
		let crosshair = _defaultCrosshair,
			weap = DeltaWeapon(CPlayer.ReadyWeapon),
			xhairState = ply.GetCrosshairState();
		
		if (weap && !weap.GetAtEase())
			crosshair = weap.GetCrosshair();
		
		Color xhairColor = xhairState == DeltaPlayer.DELTA_XHR_NEUTRAL ?
			cl_delta_crosshairColor : (xhairState == DeltaPlayer.DELTA_XHR_FRIENDLY ?
			cl_delta_crosshairFriendlyColor : cl_delta_crosshairEnemyColor);
		xhairColor |= 0xff000000;
		DrawTexture(crosshair, (0, 0), DI_SCREEN_CENTER | DI_ITEM_CENTER,
			scale: _universalScale * 0.5, col: xhairColor);
		
		if (!ply.CanUseOffhand()
			|| ply.GetTension(ply.GetOffhandTpCost()) == DeltaPlayer.TP_FAIL
			|| !cl_delta_showOffhandIndicator)
		{
			return;
		}
		
		DrawTexture(_offhandCrosshair, (0, 0), DI_SCREEN_CENTER | DI_ITEM_CENTER,
			scale: _universalScale * 0.5, col: 0xff000000 | cl_delta_offhandIndicatorColor);
	}
	
	protected void DrawQuickInfo(double ticFrac)
	{
		if (!cl_delta_showQuickInfo)
			return;
		if (ply.CountInv("DeltaNoHud"))
			return;
		
		let reticleBarOffset = (-75 * _universalScale.x, 0);
		
		Screen.EnableStencil(true);
		Screen.SetStencil(0, SOP_Increment, SF_ColorMaskOff);
		
		// defining stencil mask
		DrawTexture(_reticleBar, reticleBarOffset, 
			DI_SCREEN_CENTER | DI_ITEM_VCENTER | DI_ITEM_RIGHT,
			scale: _universalScale * 0.5);
		
		if (!_infiniteAmmo)
		{
			reticleBarOffset.x *= -1;
			DrawTextureRotated(_reticleBar, reticleBarOffset,
				DI_SCREEN_CENTER | DI_ITEM_VCENTER | DI_ITEM_RIGHT, 180,
				scale: _inverseUniversalScale * 2);
			reticleBarOffset.x *= -1;
		}
		
		Screen.SetStencil(1, SOP_Keep, SF_AllOn);
		
		// using stencil mask
		int width, height;
		[width, height] = TexMan.GetSize(_reticleBar);
		double
			realWidth = width * _universalScale.x * 0.5,
			realHeight = height * _universalScale.y * 0.5,
			curX = reticleBarOffset.x - realWidth,
			curY = reticleBarOffset.y + realHeight*0.5;
		
		Fill(0xc0550000, curX, curY, realWidth, -realHeight, DI_SCREEN_CENTER);
		
		let hpPerc = GetHealthPerc(),
			healthInterpValue = DeltaUtil.Lerp(_oldHealth,
				_healthInterp.GetValue(), ticFrac) / 100.;
		
		Fill(Color(255, 255, 0, 0), curX, curY, realWidth,
			-realHeight * healthInterpValue, DI_SCREEN_CENTER);
		Fill(ply.GetCharacterColor(), curX, curY, realWidth,
			-realHeight * min(hpPerc, 1),
			DI_SCREEN_CENTER);
		
		if (hpPerc > 1)
		{
			Fill(Color(255, 255, 0, 0), curX, curY, realWidth,
				-realHeight * max(0, healthInterpValue-1), DI_SCREEN_CENTER);
			Fill(ply.GetOverhealColor(), curX, curY, realWidth,
				-realHeight * max(0, hpPerc-1), DI_SCREEN_CENTER);
		}
		
		if (!_infiniteAmmo)
		{
			double tp = ply.tensionPoints, maxTp = ply.maxTensionPoints,
				tpLerp = DeltaUtil.Lerp(_oldTp, _tpInterp.GetValue(), ticFrac);
			curX = -reticleBarOffset.x - realWidth*0.5;
			Fill(0xc0550000, curX, curY, realWidth, -realHeight,
				DI_SCREEN_CENTER);
			Fill(Color(255, 255, 0, 0), curX, curY, realWidth,
				-realHeight * clamp(tpLerp / maxTp, 0, 1),
				DI_SCREEN_CENTER);
			Fill(0xffffa040, curX, curY, realWidth,
				-realHeight * clamp(tp/maxTp, 0, 1),
				DI_SCREEN_CENTER);
			Fill(0xffffffff, curX,
				curY - realHeight * clamp(tp/maxTp, 0, 1),
				realWidth, _universalScale.y * 0.5, DI_SCREEN_CENTER);
		}
		
		Screen.EnableStencil(false);
		Screen.ClearStencil();
		
		DrawTexture(_reticleBarOverlay, reticleBarOffset,
			DI_SCREEN_CENTER | DI_ITEM_VCENTER | DI_ITEM_RIGHT,
			scale: _universalScale * 0.5);
		
		if (!_infiniteAmmo)
		{
			reticleBarOffset.x *= -1;
			DrawTextureRotated(_reticleBarOverlay, reticleBarOffset,
				DI_SCREEN_CENTER | DI_ITEM_VCENTER | DI_ITEM_RIGHT, 180,
				scale: _inverseUniversalScale * 2);
		}
	}
	
	protected void DrawOxygen()
	{
		if (CPlayer.health <= 0 && CPlayer.lastDamageType != "Drowning")
			return;
		
		let airTime = max(0, CPlayer.air_finished - level.mapTime + 1),
			airPerc = double(airTime) / level.airSupply,
			airBarWidth = 50 * _universalScale.x;
		
		if (airTime == level.airSupply)
			return;
		
		let normCol = Color(192, 0, 128, 255),
			lowCol = Color(192, 192, 24, 24),
			lowFadeTics = 10,
			lowFade = min(lowFadeTics, level.airSupply*0.4 - airTime) / lowFadeTics,
			barR = int(DeltaUtil.Lerp(normCol.r, lowCol.r, lowFade)),
			barG = int(DeltaUtil.Lerp(normCol.g, lowCol.g, lowFade)),
			barB = int(DeltaUtil.Lerp(normCol.b, lowCol.b, lowFade));
		Color barCol = Color(192, barR, barG, barB);
		
		Fill(Color(128, barCol.r/2, barCol.g/2, barCol.b/2), -airBarWidth / 2.,
			50*_universalScale.y, airBarWidth, 5*_universalScale.y,
			DI_SCREEN_CENTER);
		Fill(barCol, -airBarWidth / 2.,
			50*_universalScale.y, airBarWidth * airPerc,
			5*_universalScale.y, DI_SCREEN_CENTER);
	}
}

class DeltaAltHUD : AltHUD
{
	override void DrawInGame(PlayerInfo CPlayer)
	{
		// kept blank so we don't draw an alt hud at all
	}
}