class DeltaHud : BaseStatusBar
{
	protected double _hBorder, _vBorder, _oldAngle, _currAngle;
	protected Vector3 _oldPos, _currPos;
	protected Vector2 _universalScale, _inverseUniversalScale;
	protected HUDFont _consoleFont, _drHudFont, _tpFont;
	protected TextureID _hpText, _tpBarBack, _tpBarBackMax, _tpBar,
		_tpTimerStencil, _tpHighlight, _leftPanelBack, _leftPanelBorders,
		_vignette, _vignette2, _infiniteText, _defaultCrosshair,
		_offhandCrosshair, _reticleBarOverlay, _reticleBar, _ammoBottom,
		_ammoBottomBorders;
	
	protected double _oldTp, _oldHealth, _oldTicFrac, _deltaTime;
	protected DynamicValueInterpolator _tpInterp, _healthInterp;
	
	private Array<class<Ammo> > _ammos;
	private Array<class<Key> > _keys;
	
	const WEAPON_SLOTS_WRAPAROUND = 9;
	
	enum CONTROL_ICON_IDS
	{
		DELTA_CONTROLICON_TEXT = 0xff, // use text for this key and keys below it!
		
		DELTA_CONTROLICON_MOUSE1, DELTA_CONTROLICON_MOUSE2, DELTA_CONTROLICON_MOUSE3,
		DELTA_CONTROLICON_MOUSE4, DELTA_CONTROLICON_MOUSE5, DELTA_CONTROLICON_MOUSE6,
		DELTA_CONTROLICON_MOUSE7, DELTA_CONTROLICON_MOUSE8,
		
		DELTA_CONTROLICON_MAX
	}
	
	Map<int, TextureID> controlIcons;
	Map<name, TextureID> ammoIcons;
	
	override void Init()
	{
		Super.Init();
		
		_drHudFont = HUDFont.Create("DRHUDFONT");
		_consoleFont = HUDFont.Create(smallFont);
		_tpFont = HUDFont.Create(smallFont, spacing: -2);
		
		_hpText				= TexMan.CheckForTexture("DRHPTEXT");
		_tpBarBack			= TexMan.CheckForTexture("sprites/hud/new tp bar back.png");
		_tpBar				= TexMan.CheckForTexture("sprites/hud/new tp bar.png");
		_tpTimerStencil		= TexMan.CheckForTexture("sprites/hud/tp timer stencil.png");
		_tpHighlight		= TexMan.CheckForTexture("DRTPHLGT");
		_leftPanelBack		= TexMan.CheckForTexture("sprites/hud/new left panel back.png");
		_leftPanelBorders	= TexMan.CheckForTexture("sprites/hud/new left panel borders.png");
		_vignette			= TexMan.CheckForTexture("sprites/hud/vignette.png");
		_vignette2			= TexMan.CheckForTexture("sprites/hud/vignette2.png");
		_infiniteText		= TexMan.CheckForTexture("DRINFTXT");
		_defaultCrosshair	= TexMan.CheckForTexture("DRMTYRET");
		_offhandCrosshair	= TexMan.CheckForTexture("DROFHRET");
		_reticleBarOverlay	= TexMan.CheckForTexture("DRRTBOVR");
		_reticleBar			= TexMan.CheckForTexture("DRRETBAR");
		_ammoBottom			= TexMan.CheckForTexture("sprites/hud/new ammo panel bottom.png");
		_ammoBottomBorders	= TexMan.CheckForTexture("sprites/hud/new ammo panel bottom borders.png");
		
		SetUpMultiplayerTextures();
		SetUpIndicatorTextures();
		SetUpDamagePopups();
		SetUpBossBars();
		
		controlIcons.Insert(DELTA_CONTROLICON_MOUSE1, TexMan.CheckForTexture("DRMSELCL"));
		controlIcons.Insert(DELTA_CONTROLICON_MOUSE2, TexMan.CheckForTexture("DRMSERCL"));
		controlIcons.Insert(DELTA_CONTROLICON_MOUSE3, TexMan.CheckForTexture("DRMSEMCL"));
		controlIcons.Insert(DELTA_CONTROLICON_MOUSE4, TexMan.CheckForTexture("DRMSEBT4"));
		controlIcons.Insert(DELTA_CONTROLICON_MOUSE5, TexMan.CheckForTexture("DRMSEBT5"));
		controlIcons.Insert(DELTA_CONTROLICON_MOUSE6, TexMan.CheckForTexture("DRMSEBT6"));
		controlIcons.Insert(DELTA_CONTROLICON_MOUSE7, TexMan.CheckForTexture("DRMSEBT7"));
		controlIcons.Insert(DELTA_CONTROLICON_MOUSE8, TexMan.CheckForTexture("DRMSEBT8"));
		
		ammoIcons.Insert('Clip', 		TexMan.CheckForTexture("DRAMBULL"));
		ammoIcons.Insert('Shell', 		TexMan.CheckForTexture("DRAMSHEL"));
		ammoIcons.Insert('RocketAmmo', 	TexMan.CheckForTexture("DRAMROCK"));
		ammoIcons.Insert('Cell', 		TexMan.CheckForTexture("DRAMPLAS"));
		ammoIcons.Insert('ID24Fuel', 	TexMan.CheckForTexture("DRAMFUEL"));
		
		_tpInterp = DynamicValueInterpolator.Create(0, 0.2, 1, 30);
		_healthInterp = DynamicValueInterpolator.Create(0, 0.2, 1, 30);
	}
	
	override void Tick()
	{
		Super.Tick();
		
		if (!CPlayer.mo)
			return;
		
		bool infiniteAmmo = sv_infiniteAmmo
			|| (CPlayer.mo.FindInventory('PowerInfiniteAmmo', true) != null);
		DeltaPlayer ply = DeltaPlayer(CPlayer.mo);
		
		_oldTp = _tpInterp.GetValue();
		
		int tpInterpTarget;
		
		if (ply)
			tpInterpTarget = infiniteAmmo ? ply.maxTensionPoints : ply.tensionPoints;
		else
			tpInterpTarget = 0;
		
		_tpInterp.Update(tpInterpTarget);
		
		_oldHealth = _healthInterp.GetValue();
		_healthInterp.Update(floor(GetHealthPerc() * 100));
		
		TickIndicators();
		TickDamagePopups();
		TickBossBars();
		
		let weaps = CPlayer.weapons;
		if (!weaps)
			return;
		
		_ammos.Clear();
		
		for (int i = 1;; i++)
		{
			int weapCount = weaps.SlotSize(i);
			
			if (i > WEAPON_SLOTS_WRAPAROUND)
			{
				i = -1;
				continue;
			}
			if (i == 0)
				break;
			
			if (!weapCount)
				continue;
			
			for (int j = 0; j < weapCount; j++)
			{
				if (!CPlayer.mo.CountInv(weaps.GetWeapon(i, j)))
					continue;
				
				Weapon inv = Weapon(CPlayer.mo.FindInventory(weaps.GetWeapon(i, j)));
				
				if (!inv)
					continue;
				if (inv.AmmoType1 && _ammos.Find(inv.AmmoType1) == _ammos.Size())
					_ammos.Push(inv.AmmoType1);
				if (inv.AmmoType2 && _ammos.Find(inv.AmmoType2) == _ammos.Size())
					_ammos.Push(inv.AmmoType2);
			}
		}
		
		_keys.Clear();
		
		for (int i = 0; i < Key.GetKeyTypeCount(); i++)
		{
			let keyClass = Key.GetKeyType(i);
			
			if (!CPlayer.mo.CountInv(keyClass))
				continue;
			
			_keys.Push(keyClass);
		}
	}
	
	protected float GetHealthPerc()
	{
		if (!CPlayer || !CPlayer.mo)
			return 0;
		
		return CPlayer.mo.GetMaxHealth() == 0 ? 0
			: min(2, CPlayer.Health / float(CPlayer.mo.GetMaxHealth()));
	}
	
	override void Draw(int state, double ticFrac)
	{
		Super.Draw(state, ticFrac);
		_deltaTime = abs(ticFrac - _oldTicFrac);
		_oldTicFrac = ticFrac;
		
		if (state == HUD_None || !cl_delta_showHud)
			return;
		
		_universalScale = GetHudScale() * 0.5;
		_inverseUniversalScale = _universalScale / cl_delta_hudScale;
		_universalScale = (1/_universalScale.x, 1/_universalScale.y) * cl_delta_hudScale;
		
		_hBorder = 35 * _universalScale.x;
		_vBorder = 25 * _universalScale.y;
		
		if (GetHealthPerc() <= 0.4 && cl_delta_lowHealthVignette && !automapActive)
		{
			double alpha = 1 - (GetHealthPerc() / 0.4);
			Screen.DrawTexture(_vignette, false, 0, 0, DTA_Fullscreen, true,
				DTA_FullScreenScale, FSMode_ScaleToScreen, DTA_Alpha, alpha,
				DTA_Color, CPlayer.mo.GetPainFlash());
		}
		
		let airTime = max(0, CPlayer.air_finished - level.mapTime + 1),
			airPerc = double(airTime) / level.airSupply;
		
		if (CPlayer.mo.waterLevel >= 2 && airPerc <= 0.4 && !automapActive)
		{
			double alpha = 1 - (airPerc / 0.4);
			Screen.DrawTexture(_vignette2, false, 0, 0, DTA_Fullscreen, true,
				DTA_FullScreenScale, FSMode_ScaleToScreen, DTA_Alpha, alpha,
				DTA_Color, Color(255, 0, 0, 0));
		}
		
		BeginHUD(1, false);
		
		DrawMultiplayerUnderlay();
		DrawBossBars();
		DrawIndicators(ticFrac);
		DrawMultiplayerOverlay();
		
		if (CPlayer.Health > 0)
		{
			bool infAmmo = sv_infiniteAmmo || (CPlayer.mo.FindInventory('PowerInfiniteAmmo', true) != null);
			DrawLeftPanel(infAmmo, ticFrac);
			DrawRightPanel(infAmmo);
			DrawReticle(infAmmo, ticFrac);
			DrawOxygen();
		}
		else
			DrawDeathStuff();
	}
	
	void ResetHUD()
	{
		_tpInterp.Reset(0);
		_healthInterp.Reset(GetHealthPerc() * 100);
		ClearIndicators();
		ClearDamagePopups();
	}
	
	protected TextureID GetMainBindingIcon(string cmd)
	{
		int k = Bindings.GetKeysForCommand(cmd);
		
		// not a mouse button!
		if (k <= DELTA_CONTROLICON_TEXT || k >= DELTA_CONTROLICON_MAX)
			return null;
		
		return controlIcons.GetIfExists(k);
	}
	
	protected void DisplayBinding(string cmd, Vector2 pos, int flags, Vector2 scale)
	{
		let tex = GetMainBindingIcon(cmd);
		
		if (tex)
			DrawTexture(tex, pos, flags, scale: scale);
		else
		{
			int k = Bindings.GetKeysForCommand(cmd);
			string keys = Keybindings.NameKeys(k, 0);
			double newY = pos.y;
			
			if (flags & DI_ITEM_VCENTER)
				newY -= smallFont.GetHeight() / 2 * _universalScale.y;
			
			DrawString(_consoleFont, keys, (pos.x, newY), flags, scale: scale);
		}
	}
	
	protected void DrawHpBar(double ticFrac)
	{
		let ply = DeltaPlayer(CPlayer.mo);
		double
			barWidth = 120 * _universalScale.x,
			barHeight = 12 * _universalScale.y,
			healthInterpValue = DeltaUtil.Lerp(_oldHealth,
				_healthInterp.GetValue(), ticFrac) * 0.01;
		
		Fill(0xffff0000, _hBorder + 63*_universalScale.x,
			-_vBorder - 22*_universalScale.y, barWidth * min(1, healthInterpValue),
			barHeight, DI_SCREEN_LEFT_BOTTOM);
		
		let hpPerc = GetHealthPerc();
		
		Fill(ply.GetCharacterColor(), _hBorder + 63*_universalScale.x,
			-_vBorder - 22*_universalScale.y, barWidth * min(1, hpPerc),
			barHeight, DI_SCREEN_LEFT_BOTTOM);
		
		if (hpPerc > 1)
		{
			Fill(0xffff0000, _hBorder + 63*_universalScale.x,
				-_vBorder - 22*_universalScale.y,
				barWidth * max(0, healthInterpValue-1), barHeight,
				DI_SCREEN_LEFT_BOTTOM);
			Fill(ply.GetOverhealColor(), _hBorder + 63*_universalScale.x,
				-_vBorder - 22*_universalScale.y, barWidth * (hpPerc-1),
				barHeight, DI_SCREEN_LEFT_BOTTOM);
		}
		
		bool showLowHealth = hpPerc <= 0.33;
		let trns = showLowHealth? "\c[DeltaLowHealth]" : "",
			hpText = trns .. max(0, ply.health),
			maxHpText = trns .. max(0, ply.GetMaxHealth()),
			maxHpWidth = _drHudFont.mFont.StringWidth(maxHpText) * 2,
			slashWidth = _drHudFont.mFont.GetCharWidth("/");
		
		DrawTexture(_hpText, (_hBorder + 46*_universalScale.x,
			-_vBorder - 20*_universalScale.y), DI_SCREEN_LEFT_BOTTOM
			| DI_ITEM_LEFT_TOP, scale: _universalScale,
			col: showLowHealth ? 0xffffff00 : 0xffffffff);
		DrawString(_drHudFont, maxHpText, (_hBorder + 183*_universalScale.x,
			-_vBorder - 35*_universalScale.y), DI_SCREEN_LEFT_BOTTOM
			| DI_TEXT_ALIGN_RIGHT, scale: _universalScale*2);
		DrawString(_drHudFont, trns.. "/",
			(_hBorder + (182-maxHpWidth)*_universalScale.x,
				-_vBorder - 35*_universalScale.y),
			DI_SCREEN_LEFT_BOTTOM | DI_TEXT_ALIGN_RIGHT, scale: _universalScale);
		DrawString(_drHudFont, hpText,
			(_hBorder + (182-slashWidth-maxHpWidth)*_universalScale.x,
				-_vBorder - 35*_universalScale.y),
			DI_SCREEN_LEFT_BOTTOM | DI_TEXT_ALIGN_RIGHT, scale: _universalScale*2);
	}
	
	protected void DrawTpBar(bool infiniteAmmo, double ticFrac)
	{
		let ply = DeltaPlayer(CPlayer.mo),
			tpPos = (_hBorder, -_vBorder - 149*_universalScale.y);
		
		double sc = 1.,
			tpPerc = infiniteAmmo? 1. : ply.tensionPoints / ply.maxTensionPoints;
		
		DrawTexture(_tpBarBack, tpPos,
			DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_TOP, scale: sc * _universalScale);
		
		Screen.EnableStencil(true);
		Screen.SetStencil(0, SOP_Increment, SF_ColorMaskOff);
		
		let barPos = tpPos + (13*_universalScale.x, 19*_universalScale.y) * sc;
		
		// defining stencil mask
		DrawTexture(_tpBar, barPos, DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_TOP,
			scale: sc * _universalScale);
		
		Screen.SetStencil(1, SOP_Keep, SF_AllOn);
		
		// using stencil mask
		double
			tpLerp = DeltaUtil.Lerp(_oldTp, _tpInterp.GetValue(), ticFrac),
			tpBarHeight = 167 * sc * _universalScale.x;
		
		let lerpPerc = infiniteAmmo? 1. : (tpLerp / ply.maxTensionPoints);
		
		Fill(0xffff0000, barPos.x, barPos.y, lerpPerc * tpBarHeight,
			15*sc*_universalScale.y, DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_BOTTOM);
		Fill((tpPerc < 1)? 0xffff7f27 : 0xffffff00, barPos.x, barPos.y,
			tpPerc * tpBarHeight, 15*sc*_universalScale.y,
			DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_BOTTOM);
		
		let tipPerc = max(tpPerc, lerpPerc);
		if (tipPerc > 0 && tipPerc < 1)
			Fill(0xffffffff, barPos.x + tpBarHeight * tipPerc, barPos.y,
				2 * sc * _universalScale.x, 19 * sc * _universalScale.y,
				DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_BOTTOM);
		
		Screen.ClearStencil();
		Screen.SetStencil(0, SOP_Increment, SF_ColorMaskOff);
		
		// defining stencil mask
		DrawTexture(_tpTimerStencil,
			(tpPos.x + 2 * sc * _universalScale.x, tpPos.y + 14 * sc * _universalScale.y),
			DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_TOP, scale: _universalScale * sc);
		
		Screen.SetStencil(1, SOP_Keep, SF_AllOn);
		
		// using stencil mask
		double tpTimer = 1.;
		
		if (!infiniteAmmo)
			tpTimer = DeltaUtil.Clamp(ply.tensionDrainTimer /
				(ply.DRAIN_TIMER_START
					* G_SkillPropertyFloat(SKILLP_AmmoFactor) * sv_ammoFactor),
				0, 1);
		
		Fill(0xffffffff, tpPos.x + 2 * sc * _universalScale.x,
			tpPos.y + 14 * sc * _universalScale.y,
			189 * sc * tpTimer * _universalScale.x, 25 * sc * _universalScale.y);
		
		Screen.EnableStencil(false);
		Screen.ClearStencil();
		
		let tpFont = (tpPerc >= 1)? _consoleFont : _tpFont,
			tpText = (tpPerc >= 1)? "\c[DeltaYellow]MAX" : String.Format("%d%%", int(tpPerc * 100)),
			tpTextWidth = tpFont.mFont.StringWidth(tpText);
		tpTextWidth *= sc;
		
		if (tpPerc < 1)
			tpTextWidth -= tpText.CodePointCount() * 2;
		
		DrawString(tpFont, tpText,
			(tpPos.x + (80 - tpTextWidth)*_universalScale.x, tpPos.y - 4*_universalScale.y),
			DI_SCREEN_LEFT_BOTTOM, alpha: 1., scale: _universalScale*sc);
	}
	
	protected void DrawLeftPanel(bool infiniteAmmo, double ticFrac)
	{
		DeltaPlayer ply = DeltaPlayer(CPlayer.mo);
		if (!ply)
			return;
		
		DrawTexture(_leftPanelBack, (_hBorder, -_vBorder), DI_SCREEN_LEFT_BOTTOM
			| DI_ITEM_LEFT_BOTTOM, scale: _universalScale);
		DrawTexture(_leftPanelBorders, (_hBorder, -_vBorder),
			DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_BOTTOM, scale: _universalScale,
			col: ply.GetCharacterColor());
		
		let currentFace = GetMugshot(4, Mugshot.DISABLEOUCH | Mugshot.DISABLERAMPAGE);
		DrawTexture(currentFace, (_hBorder + 8*_universalScale.x,
			-_vBorder - 25*_universalScale.y), DI_SCREEN_LEFT_BOTTOM
			| DI_ITEM_LEFT | DI_ITEM_VCENTER, scale: _universalScale);
		DrawTexture(ply.GetNameTagID(),
			(_hBorder + 47*_universalScale.x, -_vBorder - 40*_universalScale.y),
			DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_TOP, scale: _universalScale);
		
		DrawHpBar(ticFrac);
		DrawKeys(_hBorder + 69*_universalScale.x,
			-_vBorder - 99*_universalScale.y, 119*_universalScale.x,
			43*_universalScale.y);
		DrawTpBar(infiniteAmmo, ticFrac);
		
		let offhandTpCost = ply.GetOffhandTpCost(),
			offhandColor =
				(ply.CanUseOffhand() && ply.GetTension(ply.GetOffhandTpCost()) == TP_FAIL)?
					0x80606060 : (ply.GetIsUsingOffhand()? 0xffffa060 : 0xffffffff);
		
		DisplayBinding("+offhand", (_hBorder + 8*_universalScale.x,
			-_vBorder - 73*_universalScale.y), DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_TOP,
			_universalScale);
		DrawTexture(ply.GetOffhandIconID(),
			(_hBorder + 28*_universalScale.x, -_vBorder - 84*_universalScale.y),
			DI_SCREEN_LEFT_BOTTOM | DI_ITEM_LEFT_TOP, col: offhandColor,
			scale: _universalScale);
		let str = String.Format("%d%% TP", offhandTpCost * 100 / ply.maxTensionPoints),
			textW = _tpFont.mFont.StringWidth(str, false);
		DrawString(_tpFont, str, (_hBorder + (33 - textW/2.)*_universalScale.x, -_vBorder - 102*_universalScale.y),
			DI_SCREEN_LEFT_BOTTOM, scale: _universalScale);
		
		DrawDamagePopups((_hBorder + (10+TexMan.GetSize(currentFace)/2.)*_universalScale.x,
			-_vBorder - 25*_universalScale.y), ticFrac);
	}
	
	protected void DrawRightPanel(bool infiniteAmmo)
	{
		let ply = DeltaPlayer(CPlayer.mo);
		if (!ply)
			return;
		
		if (!_ammos.Size())
			return;
		
		DrawTexture(_ammoBottom, (-_hBorder, -_vBorder),
			DI_SCREEN_RIGHT_BOTTOM | DI_ITEM_RIGHT_BOTTOM, scale: _universalScale);
		DrawTexture(_ammoBottomBorders, (-_hBorder, -_vBorder),
			DI_SCREEN_RIGHT_BOTTOM | DI_ITEM_RIGHT_BOTTOM,
			col: ply.GetCharacterColor(), scale: _universalScale);
		
		int ammoW, ammoH;
		[ammoW, ammoH] = TexMan.GetSize(_ammoBottom);
		
		double widgetWidth = ammoW * _universalScale.x,
			hPerAmmo = 22 * _universalScale.y,
			h = _ammos.Size() * hPerAmmo + (ammoH+1)*_universalScale.y;
		
		Fill(Color(170, 0, 0, 0), -_hBorder - widgetWidth,
			-_vBorder - h - (ammoH-1)*_universalScale.y, widgetWidth,
			h - _universalScale.y, DI_SCREEN_RIGHT_BOTTOM);
		Fill(ply.GetCharacterColor(), -_hBorder - (ammoW-2)*_universalScale.x,
			-_vBorder - h - 2*_universalScale.y,
			2*_universalScale.x, h - (ammoH-3)*_universalScale.y);
		Fill(ply.GetCharacterColor(), -_hBorder - 4*_universalScale.x,
			-_vBorder - h - 2*_universalScale.y,
			2*_universalScale.x, h - (ammoH-3)*_universalScale.y);
		Fill(ply.GetCharacterColor(), -_hBorder - (ammoW-2)*_universalScale.x,
			-_vBorder - h - 4*_universalScale.y,
			widgetWidth - 4*_universalScale.x, 2*_universalScale.y);
		
		for (int i = 0; i < _ammos.Size(); i++)
		{
			let am = _ammos[_ammos.Size() - 1 - i];
			let amCount = CPlayer.mo.CountInv(am);
			let ammoIcon = ammoIcons.GetIfExists(am.GetClassName());
			double curAlpha = 0.2;
			let weap = CPlayer.ReadyWeapon;
			
			if (weap && (am == weap.AmmoType1 || am == weap.AmmoType2))
				curAlpha = 1;
			
			DrawTexture(ammoIcon, (-_hBorder - widgetWidth + 8*_universalScale.x,
				-_vBorder - (4+ammoH)*_universalScale.y - hPerAmmo*i),
				DI_ITEM_LEFT_BOTTOM | DI_SCREEN_RIGHT_BOTTOM,
				alpha: curAlpha,
				box: _universalScale*16, scale: _universalScale);
			
			if (infiniteAmmo)
				DrawTexture(_infiniteText, (-_hBorder - 8*_universalScale.x,
					-_vBorder - (4+ammoH)*_universalScale.y - hPerAmmo*i),
					DI_ITEM_RIGHT_BOTTOM | DI_SCREEN_RIGHT_BOTTOM,
					alpha: curAlpha, scale: _universalScale*2);
			else
				DrawString(_drHudFont, "" .. amCount,
					(-_hBorder - (8*_universalScale.x), -_vBorder -
						(i+1)*hPerAmmo - (ammoH-2)*_universalScale.y),
					DI_SCREEN_RIGHT_BOTTOM | DI_TEXT_ALIGN_RIGHT,
					alpha: curAlpha,
					scale: _universalScale*3);
		}
	}
	
	protected void DrawKeys(double x, double y, double maxW, double maxH)
	{
		if (!CPlayer.mo)
			return;
		
		let spacing = 1.,
			keyBox = 16.,
			totalWidth = spacing + keyBox;
		int rowLimit = maxW / (totalWidth*_universalScale.x);
		
		for (int j = 0; j < _keys.Size(); j++)
		{
			int xPlace = j % rowLimit, yPlace = j / rowLimit;
			
			readonly<Key> curKey = GetDefaultByType(_keys[j]);
			TextureID icon;
			
			if (curKey.SpawnState && curKey.SpawnState.sprite != 0)
				icon = curKey.SpawnState.GetSpriteTexture(0);
			
			if (icon.IsNull())
				icon = curKey.Icon;
			
			if (!icon.IsValid())
				continue;
			
			DrawTexture(icon, (x + keyBox/2.*_universalScale.x, y + keyBox/2.*_universalScale.y)
				+ (xPlace * totalWidth*_universalScale.x, yPlace * totalWidth*_universalScale.y),
				DI_SCREEN_LEFT_BOTTOM | DI_ITEM_CENTER,
				box: keyBox * _universalScale, scale: _universalScale);
		}
	}
	
	protected void DrawReticle(bool infiniteAmmo, double ticFrac)
	{
		if (CPlayer.cheats & CF_CHASECAM || automapActive
			|| !(CPlayer.mo is "DeltaPlayer") || !cl_delta_showCrosshair)
			return;
		
		DeltaPlayer ply = DeltaPlayer(CPlayer.mo);
		DrawQuickInfo(infiniteAmmo, ticFrac);
		
		if (ply.GetIsUsingOffhand())
			return;
		
		let crosshair = _defaultCrosshair,
			weap = DeltaWeapon(CPlayer.ReadyWeapon),
			xhairState = ply.GetCrosshairState();
		
		if (weap && !weap.GetAtEase())
			crosshair = weap.GetCrosshair();
		
		Color xhairColor = xhairState == DELTA_XHR_NEUTRAL ?
			cl_delta_crosshairColor : (xhairState == DELTA_XHR_FRIENDLY ?
			cl_delta_crosshairFriendlyColor : cl_delta_crosshairEnemyColor);
		xhairColor |= 0xff000000;
		DrawTexture(crosshair, (0, 0), DI_SCREEN_CENTER | DI_ITEM_CENTER,
			scale: _universalScale * 0.5, col: xhairColor);
		
		if (!ply.CanUseOffhand()
			|| ply.GetTension(ply.GetOffhandTpCost()) == TP_FAIL
			|| !cl_delta_showOffhandIndicator)
		{
			return;
		}
		
		DrawTexture(_offhandCrosshair, (0, 0), DI_SCREEN_CENTER | DI_ITEM_CENTER,
			scale: _universalScale * 0.5, col: 0xff000000 | cl_delta_offhandIndicatorColor);
	}
	
	protected void DrawQuickInfo(bool infiniteAmmo, double ticFrac)
	{
		if (!cl_delta_showQuickInfo)
			return;
		
		DeltaPlayer ply = DeltaPlayer(CPlayer.mo);
		let reticleBarOffset = (-75 * _universalScale.x, 0);
		
		Screen.EnableStencil(true);
		Screen.SetStencil(0, SOP_Increment, SF_ColorMaskOff);
		
		// defining stencil mask
		DrawTexture(_reticleBar, reticleBarOffset, 
			DI_SCREEN_CENTER | DI_ITEM_VCENTER | DI_ITEM_RIGHT,
			scale: _universalScale * 0.5);
		
		if (!infiniteAmmo)
		{
			reticleBarOffset.x *= -1;
			DrawTextureRotated(_reticleBar, reticleBarOffset,
				DI_SCREEN_CENTER | DI_ITEM_VCENTER | DI_ITEM_RIGHT, 180,
				scale: _inverseUniversalScale * 2);
			reticleBarOffset.x *= -1;
		}
		
		Screen.SetStencil(1, SOP_Keep, SF_AllOn);
		
		// using stencil mask
		int width, height;
		[width, height] = TexMan.GetSize(_reticleBar);
		double
			realWidth = width * _universalScale.x * 0.5,
			realHeight = height * _universalScale.y * 0.5,
			curX = reticleBarOffset.x - realWidth,
			curY = reticleBarOffset.y + realHeight*0.5;
		
		Fill(0xc0550000, curX, curY, realWidth, -realHeight, DI_SCREEN_CENTER);
		
		double healthInterpValue = DeltaUtil.Lerp(_oldHealth,
			_healthInterp.GetValue(), ticFrac) / 100.;
		
		Fill(Color(255, 255, 0, 0), curX, curY, realWidth,
			-realHeight * healthInterpValue, DI_SCREEN_CENTER);
		Fill(ply.GetCharacterColor(), curX, curY, realWidth,
			-realHeight * DeltaUtil.Clamp(GetHealthPerc(), 0, 1),
			DI_SCREEN_CENTER);
		
		if (GetHealthPerc() > 1)
		{
			Fill(Color(255, 255, 0, 0), curX, curY, realWidth,
				-realHeight * max(0, healthInterpValue-1), DI_SCREEN_CENTER);
			Fill(ply.GetOverhealColor(), curX, curY, realWidth,
				-realHeight * max(0, GetHealthPerc()-1), DI_SCREEN_CENTER);
		}
		
		if (!infiniteAmmo)
		{
			double tp = ply.tensionPoints, maxTp = ply.maxTensionPoints,
				tpLerp = DeltaUtil.Lerp(_oldTp, _tpInterp.GetValue(), ticFrac);
			curX = -reticleBarOffset.x - realWidth*0.5;
			Fill(0xc0550000, curX, curY, realWidth, -realHeight,
				DI_SCREEN_CENTER);
			Fill(Color(255, 255, 0, 0), curX, curY, realWidth,
				-realHeight * DeltaUtil.Clamp(tpLerp / maxTp, 0, 1),
				DI_SCREEN_CENTER);
			Fill(0xffffa040, curX, curY, realWidth,
				-realHeight * DeltaUtil.Clamp(tp/maxTp, 0, 1),
				DI_SCREEN_CENTER);
			Fill(0xffffffff, curX,
				curY - realHeight * DeltaUtil.Clamp(tp/maxTp, 0, 1),
				realWidth, _universalScale.y * 0.5, DI_SCREEN_CENTER);
		}
		
		Screen.EnableStencil(false);
		Screen.ClearStencil();
		
		DrawTexture(_reticleBarOverlay, reticleBarOffset,
			DI_SCREEN_CENTER | DI_ITEM_VCENTER | DI_ITEM_RIGHT,
			scale: _universalScale * 0.5);
		
		if (!infiniteAmmo)
		{
			reticleBarOffset.x *= -1;
			DrawTextureRotated(_reticleBarOverlay, reticleBarOffset,
				DI_SCREEN_CENTER | DI_ITEM_VCENTER | DI_ITEM_RIGHT, 180,
				scale: _inverseUniversalScale * 2);
		}
	}
	
	protected void DrawOxygen()
	{
		if (!CPlayer)
			return;
		
		let airTime = max(0, CPlayer.air_finished - level.mapTime + 1),
			airPerc = double(airTime) / level.airSupply,
			airBarWidth = 50 * _universalScale.x;
		
		if (airTime == level.airSupply)
			return;
		
		let normCol = Color(192, 0, 128, 255),
			lowCol = Color(192, 192, 24, 24),
			lowFadeTics = 10,
			lowFade = min(lowFadeTics, level.airSupply*0.4 - airTime) / lowFadeTics;
		int barR = DeltaUtil.Lerp(normCol.r, lowCol.r, lowFade),
			barG = DeltaUtil.Lerp(normCol.g, lowCol.g, lowFade),
			barB = DeltaUtil.Lerp(normCol.b, lowCol.b, lowFade);
		Color barCol = Color(192, barR, barG, barB);
		
		Fill(Color(128, barCol.r/2, barCol.g/2, barCol.b/2), -airBarWidth / 2.,
			50*_universalScale.y, airBarWidth, 5*_universalScale.y,
			DI_SCREEN_CENTER);
		Fill(barCol, -airBarWidth / 2.,
			50*_universalScale.y, airBarWidth * airPerc,
			5*_universalScale.y, DI_SCREEN_CENTER);
	}
	
	protected void DrawDeathStuff()
	{
		DeltaPlayer ply = DeltaPlayer(CPlayer.mo);
		if (!ply)
			return;
		
		int reminderTimer = ply.GetDeathTimer() - TICRATE * 20;
		double textSpeed = 1/2.;
		
		if (multiplayer && !deathmatch) // we can respawn whenever in deathmatch
			return;
		if (reminderTimer < 0)
			return;
		if (!cl_delta_showDeathText)
			return;
		
		String respawnReminder = StringTable.Localize("$TXT_DELTA_RESPAWNMSG1"),
			reminderThisFrame = respawnReminder;
		reminderThisFrame.Truncate(reminderTimer * textSpeed);
		
		int xOffset = -_consoleFont.mFont.StringWidth(respawnReminder) / 2 * _universalScale.x;
		int yOffset = -50 * _universalScale.y;
		DrawString(_consoleFont, reminderThisFrame, (xOffset, yOffset),
			DI_SCREEN_CENTER, scale: _universalScale);
		
		reminderTimer -= respawnReminder.Length() / textSpeed + (TICRATE/2);
		if (reminderTimer < 0)
			return;
		
		respawnReminder = StringTable.Localize("$TXT_DELTA_RESPAWNMSG2");
		reminderThisFrame = respawnReminder;
		reminderThisFrame.Truncate(reminderTimer * textSpeed);
		xOffset = -_consoleFont.mFont.StringWidth(respawnReminder) / 2 * _universalScale.x;
		yOffset += _consoleFont.mFont.GetHeight() * _universalScale.y * 2;
		
		DrawString(_consoleFont, reminderThisFrame, (xOffset, yOffset),
			DI_SCREEN_CENTER, scale: _universalScale);
		
		reminderTimer -= respawnReminder.Length() / textSpeed + (TICRATE);
		if (reminderTimer < 0)
			return;
		
		int useBind, useless;
		[useBind, useless] = Bindings.GetKeysForCommand("+use");
		String keyNames = KeyBindings.NameKeys(useBind, 0);
		keyNames.ToUpper();
		
		string targetFormat = (deathmatch || (dmflags2 & LEVEL2_ALLOWRESPAWN)
			|| sv_singleplayerrespawn
			|| G_SkillPropertyInt(SKILLP_PlayerRespawn))
			? "$TXT_DELTA_RESPAWNREMINDDM" : "$TXT_DELTA_RESPAWNREMIND";
		respawnReminder = String.Format(StringTable.Localize(targetFormat), keyNames);
		reminderThisFrame = respawnReminder;
		reminderThisFrame.Truncate(reminderTimer * textSpeed);
		xOffset = -_consoleFont.mFont.StringWidth(respawnReminder) / 2 * _universalScale.x;
		yOffset += _consoleFont.mFont.GetHeight() * _universalScale.y * 3;
		
		DrawString(_consoleFont, reminderThisFrame, (xOffset, yOffset),
			DI_SCREEN_CENTER, scale: _universalScale);
	}
}

class DeltaAltHUD : AltHUD
{
	override void DrawInGame(PlayerInfo CPlayer)
	{
		// kept blank so we don't draw an alt hud at all
	}
}