class DeltaWeapon : Weapon
{
	protected int animType;					// (DeltaWeaponAnimType) used to determine if third person sprite uses melee, gun, or magic animations when holding this weapon
	protected double redCrosshairRange;		// maximum distance an enemy can be at from player and still have red crosshairs when aimed at
	protected double maxLungeDistance;		// maximum distance the lunge check will detect targets from
	protected double stopLungeDistance;		// distance user must be at during lunge before they stop and attack
	protected string altFireIcon;			// used for displaying alt fire key and cost (keep as null if you don't want anything there)
	protected string crosshair;
    protected bool atEase;
	protected bool hasBeenPickedUp;			// used to determine if we should do inspect animation upon pulling this out or not
	protected int easeTics;
	protected int needsCycling;				// used to determine if we need to cycle our weapon after pulling it out (say for cocking a revolver or pumping a shotgun)
											// this is an int and not a bool so as to allow for different types of cycling (kris's shotgun uses this)
	
	protected double tensionUse, tensionUse2, minYOffset, maxYOffset;
	protected sound dryFireSound;
	
	protected state AtEaseLoopState, DeselectAtEaseState;
	
	private bool _lungeReadyToStop;
	private TextureID _altFireIconId, _crosshairId;
	private int _deltaWeaponFlags, _backpackTics;
	
	const EASE_TICS_SET_ATTACK = -25;
	const TP_FAIL_SOUND = "delta/tp_fail";
	
	property AnimType: animType;
	property RedCrosshairRange: redCrosshairRange;
	property MaxLungeDistance: maxLungeDistance;
	property StopLungeDistance: stopLungeDistance;
	property TensionUse: tensionUse;
	property TensionUse2: tensionUse2;
	property AltFireIcon: altFireIcon;
	property Crosshair: crosshair;
	property DryFireSound: dryFireSound;
	property MinYOffset: minYOffset;
	property MaxYOffset: maxYOffset;
	
	flagdef NO_CONSUME_AMMO: _deltaWeaponFlags, 0;
	flagdef NO_CONSUME_ALT_AMMO: _deltaWeaponFlags, 1;
	
	Default
	{
		DeltaWeapon.AnimType DeltaPlayer.DELTA_WEAPONANIM_GUN;
		DeltaWeapon.RedCrosshairRange PLAYERMISSILERANGE / 2.;
		DeltaWeapon.MaxLungeDistance -1;
		DeltaWeapon.StopLungeDistance 5;
		DeltaWeapon.TensionUse 0;
		DeltaWeapon.TensionUse2 0;
		DeltaWeapon.DryFireSound "delta/dry_fire";
		DeltaWeapon.MinYOffset -25;
		DeltaWeapon.MaxYOffset 25;
	}
	
	States
	{
		AtEaseLoop:
			TNT1 A 1 A_DeltaWeaponReady(atEase: true);
			Loop;
	}
	
	override void BeginPlay()
	{
		hasBeenPickedUp = false;
		needsCycling = 0;
		
		Super.BeginPlay();
		
		_altFireIconId = TexMan.CheckForTexture(altFireIcon);
		_crosshairId = TexMan.CheckForTexture(crosshair);
		AtEaseLoopState = ResolveState("AtEaseLoop");
		DeselectAtEaseState = ResolveState("DeselectAtEase");
	}
	
	override void DoEffect()
	{
		Super.DoEffect();
		
		if (!owner || !owner.player)
			return;
		if (!needsCycling || !DeltaCheckAmmo(EitherFire, false, playSounds: false))
			return;
		if (owner.player.ReadyWeapon == self)
		{
			_backpackTics = 0;
			return;
		}
		
		_backpackTics++;
		HandleBackpackCycle(_backpackTics);
	}
	
	override bool CheckAmmo(int fireMode, bool autoSwitch, bool requireAmmo,
		int ammoCount)
	{
		return DeltaCheckAmmo(fireMode, autoSwitch, requireAmmo, ammoCount, false);
	}
	
	virtual bool DeltaCheckAmmo(int fireMode, bool autoSwitch,
		bool requireAmmo = false, int ammoCount = -1, bool playSounds = true)
	{
		if (!owner || sv_infiniteammo
			|| (owner.FindInventory('PowerInfiniteAmmo', true) != null))
			return true;
		
		if (!(owner is "DeltaPlayer"))
		{
			if (autoSwitch)
				PlayerPawn(owner).PickNewWeapon(null);
			
			return false;
		}
		
		let hasAltFire = FindState('AltFire') != null;
		
		if (fireMode == EitherFire)
		{
			bool gotEither = DeltaCheckAmmo(PrimaryFire, false, playSounds: false)
				|| (hasAltFire && DeltaCheckAmmo(AltFire, false, playSounds: false));
			
			if (!gotEither && autoSwitch)
				PlayerPawn(Owner).PickNewWeapon (null);
			
			return gotEither;
		}
		
		let altFire = (fireMode == AltFire);
		let optional = (altFire? bAlt_Ammo_Optional : bAmmo_Optional);
		let useBoth = (altFire? bAlt_Uses_Both : bPrimary_Uses_Both);

		if (!requireAmmo && optional)
			return true;
		
		int lAmmoUse1,
			lAmmoUse2 = AmmoUse2,
			count1 = ((Ammo1 != null) ? Ammo1.Amount : 0),
			count2 = ((Ammo2 != null) ? Ammo2.Amount : 0);
		double lTensionUse1,
			lTensionUse2 = tensionUse2,
			tensionCount = DeltaPlayer(owner).tensionPoints;
		
		if (bDehAmmo && Ammo1 == null)
		{
			lAmmoUse1 = 0;
			lTensionUse1 = 0;
		}
		else if (ammoCount >= 0)
			lAmmoUse1 = lAmmoUse2 = ammoCount;
		else
		{
			lAmmoUse1 = AmmoUse1;
			lTensionUse1 = tensionUse;
		}
		
		int enough = (count1 >= lAmmoUse1 && tensionCount >= lTensionUse1)
			| ((hasAltFire && count2 >= lAmmoUse2 && tensionCount >= lTensionUse2) << 1),
		enoughMask = useBoth ? 3 : (1 << altFire);
		
		if ((altFire && !hasAltFire) ||
			((enough & enoughMask) != enoughMask) && !(enough && bAmmo_CheckBoth))
		{
			// out of ammo, pick a weapon to change to
			if (autoSwitch && enough != (1 << !altFire))
				PlayerPawn(Owner).PickNewWeapon (null);
			
			if (playSounds)
			{
				if (count1 < lAmmoUse1 || count2 < lAmmoUse2)
					owner.A_StartSound(dryFireSound, CHAN_AUTO, CHANF_LOCAL | CHANF_NOSTOP);
				else if (tensionCount < lTensionUse1 || tensionCount < lTensionUse2)
					owner.A_StartSound(TP_FAIL_SOUND, CHAN_AUTO, CHANF_LOCAL | CHANF_NOSTOP);
			}
			
			return false;
		}
		
		return true;
	}
	
	override bool DepleteAmmo(bool altFire, bool checkEnough, int ammoUse, bool forceAmmoUse)
	{
		if (checkEnough && (!owner || !(owner is "DeltaPlayer")
			|| DeltaPlayer(owner).GetTension(altFire? tensionUse2 : tensionUse) == DeltaPlayer.TP_FAIL))
			return false;
		if (!Super.DepleteAmmo(altFire, checkEnough, ammoUse, forceAmmoUse))
			return false;
		
		TakeTension(altFire);
		return true;
	}
	
	override state GetUpState()
	{
		if (hasBeenPickedUp)
			return Super.GetUpState();
		
		let dest = FindState("SelectFirst", true);
		if (dest)
			return dest;
		
		return Super.GetUpState();
	}
	
	override state GetDownState()
	{
		if (!owner || !owner.player)
			return Super.GetDownState();
		
		let psp = owner.player.GetPSprite(PSP_WEAPON);
		if (!psp)
			return Super.GetDownState();
		if (owner.health <= 0)
			return psp.curState;
		if (!psp.curState.InStateSequence(AtEaseLoopState))
			return Super.GetDownState();
		
		let dest = FindState("DeselectAtEase");
		if (dest)
			return dest;
		
		return Super.GetDownState();
	}
	
	virtual bool TakeTension(bool altFire)
	{
		let deltaOwner = DeltaPlayer(owner);
		double amount = altFire ? tensionUse2 : tensionUse;
		
		if (amount < 0 || !deltaOwner)
			return false;
		if (amount == 0)
			return true;
		
		return deltaOwner.TryTakeTension(amount);
	}
	
	virtual void DoFire(State stat = null)
	{
		let ply = owner.player;
		if (!ply)
			return;
		if (!bNO_CONSUME_AMMO && !DeltaCheckAmmo(PrimaryFire, true))
			return;
		
		ply.WeaponState &= ~WF_WEAPONBOBBING;
		bAltFire = false;
		if (stat == null)
			stat = GetAtkState(!!ply.refire);
		
		if (!bNoAlert)
			owner.A_AlertMonsters();
		
		ply.SetPsprite(PSP_WEAPON, stat);
		A_ResetAtEase();
	}
	
	virtual void DoAltFire(State stat = null)
	{
		let ply = owner.player;
		if (!ply)
			return;
		if (!bNO_CONSUME_ALT_AMMO && !DeltaCheckAmmo(AltFire, true))
			return;
		
		ply.WeaponState &= ~WF_WEAPONBOBBING;
		bAltFire = true;
		if (stat == null)
			stat = GetAltAtkState(!!ply.refire);
		
		if (!bNoAlert)
			owner.A_AlertMonsters();
		
		ply.SetPsprite(PSP_WEAPON, stat);
		A_ResetAtEase();
	}
	
	virtual void HandleBackpackCycle(int backpackTics)
	{
		if (backpackTics < GetBackpackCycleTics())
			return;
		
		needsCycling = 0; // reset cycling state
	}
	
	// making this a virtual instead of a property so custom weapons could
	// potentially override this based on, for example, what kind of cycling
	// they need (i.e. potentially cycling for an alt-fire could take longer
	// than cycling for primary)
	virtual int GetBackpackCycleTics()
	{
		return GameTicRate * 5; // five seconds by default
	}
	
	action void A_ResetAtEase()
	{
		invoker.atEase = false;
		invoker.easeTics = invoker.EASE_TICS_SET_ATTACK;
	}
	
	action void A_OwnerPlayAttack(bool muzzleFlash = true)
	{
		let ply = PlayerPawn(invoker.owner);
		if (!ply)
			return;
		
		if (muzzleFlash)
			ply.PlayAttacking();
		else
			ply.PlayAttacking2();
	}
	
	action void A_StartRaiseWeapon()
	{
		// some code taken from original UZDoom A_Raise code and reworked
		if (player == null)
			return;
		if (player.PendingWeapon != WP_NOCHANGE)
		{
			player.mo.DropWeapon();
			return;
		}
		if (player.ReadyWeapon == null)
			return;
		
		let psp = player.GetPSprite(PSP_WEAPON);
		if (!psp)
			return;
		
		invoker.atEase = false;
		A_SetCrosshair(-1);
		
		// skip native sprite raising, we want to do our own deploy animations
		psp.y = WEAPONTOP;
	}
	
	action void A_FinishRaiseWeapon()
	{
		let psp = player.GetPSprite(PSP_WEAPON);
		if (!psp)
			return;
		
		psp.SetState(invoker.GetReadyState());
	}
	
	action state A_DeltaWeaponReady(int flags = 0, bool atEase = false)
	{
		let ply = DeltaPlayer(invoker.owner);
		invoker.hasBeenPickedUp = true;
        
		A_WeaponReady(flags);
		
        if (flags & WRF_NOBOB || (ply && ply.GetIsUsingOffhand()))
			return ResolveState(null);
		
		let iter = ThinkerIterator.Create("DeltaWeaponsAtEase");
		invoker.atEase = iter.Next();
		
		// if our at ease state is not changing, don't do anything
		if (invoker.atEase == atEase)
		{
			if (invoker.easeTics < 0)
				invoker.easeTics++;
			
			return ResolveState(null);
		}
		
        if (invoker.atEase)
		{
			invoker.easeTics++;
			
			if (invoker.easeTics > 0)
				return ResolveState("AtEase");
		}
		else
		{
			let endEase = ResolveState("AtEaseEnd");
			if (endEase)
				return endEase;
			
			return invoker.GetUpState();
		}
		
        return ResolveState(null);
	}
	
	action void A_SwapWeapon()
	{
		// some code taken from A_Lower in uzdoom.pk3
		if (!player || !player.ReadyWeapon)
			return;
		
		let psp = player.GetPSprite(PSP_WEAPON);
		if (!psp)
			return;
		
		A_ClearDynamicLights();
		ResetPSprite(psp);
		player.mo.BringUpWeapon();
	}
	
	action state A_DoLunge(state attackState)
	{
		let deltaOwner = DeltaPlayer(self);
		if (!deltaOwner || !deltaOwner.CanLunge()
			|| invoker._lungeReadyToStop || (player.cmd.buttons & BT_BACK))
		{
			invoker._lungeReadyToStop = false;
			
			A_OwnerPlayAttack();
			return attackState;
		}
		
		if (!deltaOwner.IsLunging())
		{
			Actor currMo, targetMo;
			double shortestDistance = invoker.maxLungeDistance + self.radius;
			
			let iter = BlockThingsIterator.Create(deltaOwner, shortestDistance);
			
			while (iter.Next())
			{
				currMo = iter.thing;
				
				if (!currMo || (currMo.health <= 0)
					|| (!currMo.bIsMonster && !(currMo is "PlayerPawn"))
					|| invoker.owner.IsFriend(currMo)
					|| currMo.bNeverTarget) continue;
				
				Vector3
					diff = level.Vec3Diff(pos, currMo.pos),
					diffNorm = diff.Unit(),
					forward = DeltaUtil.GetActorForward(deltaOwner, false);
				double
					targetAngle = VectorAngle(diff.x, diff.y),
					targetPitch = asin(diffNorm.z),
					distance = diff.Length(),
					diffDot = (diff.x, diff.y).Unit() dot (forward.x, forward.y);
				
				if (diffDot < 0.9)
					continue;
				if (abs(targetPitch) > 80)
					continue;
				
				if (distance <= shortestDistance)
				{
					shortestDistance = distance;
					targetMo = currMo;
				}
				
				if (shortestDistance <= invoker.stopLungeDistance)
					return attackState;
			}
			
			// skip lunge and immediately attack if we don't have a target
			// or if our target is a charging lost soul or equivalent
			// (i.e. if lunging at them would end up hurting us)
			if (!targetMo)
				return attackState;
			if (targetMo.bSkullfly)
				return attackState;
			
			deltaOwner.StartLunge(targetMo, invoker.stopLungeDistance);
		}
		
		if (invoker._lungeReadyToStop)
		{
			invoker._lungeReadyToStop = false;
			return attackState;
		}
		
		return ResolveState(null);
	}
	
	action void A_OwnerKnockback(double groundKnockback, double airKnockback,
		bool crouchNullifies = true)
	{
		double kb = player.onGround ? groundKnockback : airKnockback;
		
		if (crouchNullifies && (player.cmd.buttons & BT_CROUCH))
			return;
		if (kb ~== 0)
			return;
		
		let kbVec = DeltaUtil.GetActorForward(player.mo) * kb;
		player.mo.vel -= kbVec;
	}
	
	action state A_CheckOffhand(bool bob = false, statelabel dest = "Select")
	{
		let deltaOwner = DeltaPlayer(invoker.owner);
		
		if (deltaOwner.GetIsUsingOffhand())
			return ResolveState(null);
		if (deltaOwner.player.PendingWeapon == WP_NOCHANGE)
			return (dest == "Select")? invoker.GetUpState() : ResolveState(dest);
		
		A_SwapWeapon();
		return ResolveState(null);
	}
	
	action void A_AddRecoil(int startTime, int leadInTime = 0, double p = 0, double y = 0, double r = 0)
	{
		DeltaPlayer(invoker.owner).AddRecoil(DeltaPlayer.RECOIL_WEAPON, startTime, leadInTime, p, y, r);
	}
	
	action void A_AddDynamicLight(Name lightId, Name lightDef)
	{
		let deltaPly = DeltaPlayer(invoker.owner);
		
		if (!deltaPly)
			return;
		
		deltaPly.A_AddDynamicLight(lightId, lightDef);
	}
	
	action void A_RemoveDynamicLight(Name lightId)
	{
		let deltaPly = DeltaPlayer(invoker.owner);
		
		if (!deltaPly)
			return;
		
		deltaPly.A_RemoveDynamicLight(lightId);
	}
	
	action void A_ClearDynamicLights()
	{
		let deltaPly = DeltaPlayer(invoker.owner);
		
		if (!deltaPly)
			return;
		
		deltaPly.A_ClearDynamicLights();
	}
	
	void MarkReadyToStopLunging()
	{
		_lungeReadyToStop = true;
	}
	
	void ResetReadyToStopLunging()
	{
 		_lungeReadyToStop = false;
	}
	
	clearscope float GetRedCrosshairRange()
	{
		return redCrosshairRange;
	}
	
	// returns a DeltaWeaponAnimType (see enum in DeltaPlayer for more info)
	clearscope int GetAnimType()
	{
		return animType;
	}
	
	clearscope bool GetAtEase()
	{
		if (!owner || !owner.player)
			return false;
		
		let psp = owner.player.FindPSprite(PSP_WEAPON);
		if (!psp)
			return false;
		
		return InStateSequence(psp.curState, AtEaseLoopState)
			|| InStateSequence(psp.curState, DeselectAtEaseState);
	}
	
	clearscope double GetMinYOffset()
	{
		return minYOffset;
	}
	
	clearscope double GetMaxYOffset()
	{
		return maxYOffset;
	}
	
	clearscope double GetCrouchFactor()
	{
		if (!player || !player.mo)
			return -1;
		if (player.mo is "DeltaPlayer")
			return DeltaPlayer(player.mo).GetCrouchFactor();
		
		return -1;
	}
	
	ui TextureID GetAltFireIcon()
	{
		return _altFireIconId;
	}
	
	ui TextureID GetCrosshair()
	{
		return _crosshairId;
	}
}

// Dummy object meant to make DeltaWarriors players put their weapons to the side
// (i.e. they wouldn't have their weapons drawn in, say, Castle Town)
class DeltaWeaponsAtEase : Actor {}