class DeltaWeaponPickup : Weapon
{
	protected Map<string, class<DeltaWeapon> > actualPickups;
	
	Default
	{}
	
	States
	{
		Spawn:
			TNT1 A 0;
			#### A 1 A_GetWeaponSprite;
			Wait;
		Ready:
		Select:
		Deselect:
		Fire:
			TNT1 A 1;
			Loop;
	}
	
	override void BeginPlay()
	{
		Super.BeginPlay();
		AddPickups();
	}
	
	virtual void AddPickups() {}
	
	class<DeltaWeapon> GetWeapon()
	{
		let ply = players[consoleplayer].mo;
		if (!ply || !(ply is "DeltaPlayer"))
			return null;
		
		return actualPickups.Get(DeltaPlayer(ply).GetClassName());
	}
	
	action void A_GetWeaponSprite()
	{
		// consolePlayer used here on purpose!
		// we WANT this to be able to look different for each player if, say,
		// one is playing as Kris and another as Susie
		let weapClass = invoker.GetWeapon();
		if (!weapClass)
			return;
		
		let weap = GetDefaultByType(weapClass);
		if (!weap || !weap.SpawnState)
			return;
		
		sprite = weap.SpawnState.sprite;
	}
	
	override string PickupMessage()
	{
		let weap = GetWeapon();
		if (!weap)
			return Super.PickupMessage();
		
		return GetDefaultByType(weap).PickupMessage();
	}
	
	override bool TryPickup(in out Actor toucher)
	{
		let weap = GetWeapon();
		if (!weap)
			return false;
		
		let realWeap = Weapon(Spawn(weap));
		realWeap.bDropped = bDropped;
		
		if (!realWeap.TryPickup(toucher))
		{
			realWeap.Destroy();
			return false;
		}
		
		GoAwayAndDie();
		return true;
	}
	
	override bool CanPickup(Actor toucher)
	{
		let weap = GetWeapon();
		if (!weap)
			return false;
		
		return GetDefaultByType(weap).CanPickup(toucher);
	}
	
	override void AttachToOwner(Actor other) { }
}

// Doom replacers
class DeltaChainsaw : Weapon replaces Chainsaw
{
	Default
	{
		+WEAPON.NO_AUTO_SWITCH
	}
	
	States
	{
		Spawn:
			CSAW A -1;
			Stop;
		Select:
			TNT1 A 0;
			Goto Ready;
		Deselect:
			TNT1 A 0;
			Stop;
		Ready:
			TNT1 A 1;
			Loop;
		Fire:
			Goto Ready;
	}
	
	override bool CheckAmmo(int fireMode, bool autoSwitch, bool requireAmmo, int ammoCount)
	{
		return false;
	}
	
	override string PickupMessage()
	{
		return String.Format(StringTable.Localize("$PICKUP_DELTA_CHAINSAW"),
			GetDefaultByType('Chainsaw').GetTag().MakeLower());
	}
}

class PistolReplacer : DeltaWeaponPickup replaces Pistol
{
	override void AddPickups()
	{
		actualPickups.Insert("KrisPlayer", "KrisRevolver");
	}
}

class ShotgunReplacer : DeltaWeaponPickup replaces Shotgun
{
	override void AddPickups()
	{
		actualPickups.Insert("KrisPlayer", "KrisShotgun");
	}
}

class SuperShotgunReplacer : DeltaWeaponPickup replaces SuperShotgun
{
	override void AddPickups()
	{
		actualPickups.Insert("KrisPlayer", "KrisShotgun");
	}
}

class ChaingunReplacer : DeltaWeaponPickup replaces Chaingun
{
	override void AddPickups()
	{
		actualPickups.Insert("KrisPlayer", "KrisSMG");
	}
}

/// -----------------------------------------------------------------
/// TEMPORARY REPLACERS FOR WEAPONS THAT HAVEN'T BEEN IMPLEMENTED YET
/// -----------------------------------------------------------------
class TempRocketLauncher : DeltaWeapon replaces RocketLauncher
{
	Default
	{
		Tag "$TAG_ROCKETLAUNCHER";
		
		Inventory.PickupMessage "$GOTLAUNCHER";
		Weapon.SelectionOrder 2500;
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 2;
		Weapon.AmmoType "RocketAmmo";
		DeltaWeapon.Crosshair "DRRCKRET";
		
		+WEAPON.NOAUTOFIRE;
		+WEAPON.EXPLOSIVE;
	}
	
	States
	{
		Ready:
			MISG A 1 A_DeltaWeaponReady;
			Loop;
		Deselect:
			MISG A 1 A_Lower;
			Loop;
		Select:
			MISG A 1 A_Raise;
			Loop;
		Fire:
			MISG B 8 A_GunFlash;
			MISG B 12
			{
				A_FireMissile();
				A_OwnerPlayAttack(true);
			}
			MISG B 0 A_ReFire;
			Goto Ready;
		Flash:
			MISF A 3 Bright A_Light1;
			MISF B 4 Bright;
			MISF CD 4 Bright A_Light2;
			Goto LightDone;
		Spawn:
			LAUN A -1;
			Stop;
	}
}

class TempPlasmaRifle : DeltaWeapon
{
	Default
	{
		Tag "$TAG_PLASMARIFLE";
		
		Inventory.PickupMessage "$GOTPLASMA";
		Weapon.SelectionOrder 100;
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 40;
		Weapon.AmmoType "Cell";
		DeltaWeapon.Crosshair "DRPLSRET";
	}
	
	States
	{
		Ready:
			PLSG A 1 A_DeltaWeaponReady;
			Loop;
		Deselect:
			PLSG A 1 A_Lower;
			Loop;
		Select:
			PLSG A 1 A_Raise;
			Loop;
		Fire:
			PLSG A 1
			{
				A_FirePlasma();
				A_OwnerPlayAttack();
			}
			PLSG A 2 A_OwnerPlayAttack(false);
			PLSG B 20 A_ReFire;
			Goto Ready;
		Flash:
			PLSF A 4 Bright A_Light1;
			Goto LightDone;
			PLSF B 4 Bright A_Light1;
			Goto LightDone;
		Spawn:
			PLAS A -1;
			Stop;
	}
}

class TempBFG9000 : DeltaWeapon
{
	Default
	{
		Height 20;
		Tag "$TAG_BFG9000";
		
		Inventory.PickupMessage "$GOTBFG9000";
		Weapon.SelectionOrder 2800;
		Weapon.AmmoUse 40;
		Weapon.AmmoGive 40;
		Weapon.AmmoType "Cell";
		DeltaWeapon.Crosshair "DRPLSRET";
		
		+WEAPON.NOAUTOFIRE;
		+WEAPON.BFG;
	}
	
	States
	{
		Ready:
			BFGG A 1 A_DeltaWeaponReady;
			Loop;
		Deselect:
			BFGG A 1 A_Lower;
			Loop;
		Select:
			BFGG A 1 A_Raise;
			Loop;
		Fire:
			BFGG A 0 A_OwnerPlayAttack(false);
			BFGG A 4 A_BFGSound;
			BFGG AAAA 4 A_OwnerPlayAttack(false);
			BFGG B 10 A_GunFlash;
			BFGG B 10 A_FireBFG;
			BFGG B 20 A_ReFire;
			Goto Ready;
		Flash:
			BFGF A 0 A_OwnerPlayAttack;
			BFGF A 11 Bright A_Light1;
			BFGF B 6 Bright A_Light2;
			Goto LightDone;
		Spawn:
			BFUG A -1;
			Stop;
		OldFire:
			BFGG A 10 A_BFGSound;
			BFGG BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 1
			{
				A_FireOldBFG();
				A_OwnerPlayAttack();
			}
			BFGG B 0
			{
				A_Light0();
				A_OwnerPlayAttack(false);
			}
			BFGG B 20 A_ReFire;
			Goto Ready;
	}
}

class TempIncinerator : DeltaWeapon replaces ID24Incinerator
{
	Default
	{
		Tag "$TAG_ID24INCINERATOR";
		
		Inventory.PickupMessage "$ID24_GOTINCINERATOR";
		Weapon.SelectionOrder 120;
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 20;
		Weapon.AmmoType "ID24Fuel";
		DeltaWeapon.Crosshair "DRPLSRET";
	}
	
	States
	{
		Spawn:
			INCN A -1;
			Stop;
		Ready:
			FLMG A 1 A_DeltaWeaponReady;
			Loop;
		Deselect:
			FLMG A 1 A_Lower;
			Loop;
		Select:
			FLMG A 1 A_Raise;
			Loop;
		Fire:
			FLMF A 0 BRIGHT A_Jump(128, "FireAltSound");
			FLMF A 0 BRIGHT A_StartSound("weapons/incinerator/fire1", CHAN_WEAPON);
			Goto DoFire;
		FireAltSound:
			FLMF A 0 BRIGHT A_StartSound("weapons/incinerator/fire2", CHAN_WEAPON);
			Goto DoFire;
		DoFire:
			FLMF A 0 BRIGHT A_GunFlash;
			FLMF A 0 BRIGHT A_OwnerPlayAttack;
			FLMF A 0 BRIGHT MBF21_ConsumeAmmo(1);
			FLMF A 1 BRIGHT MBF21_WeaponProjectile("ID24IncineratorFlame", 0, 0, 0, 0);
			FLMF B 1 BRIGHT;
			FLMG A 1;
			FLMG A 0 A_ReFire;
			Goto Ready;
		Flash:
			TNT1 A 2 A_Light2;
			TNT1 A 1 A_Light1;
			Goto LightDone;
	}
}

class TempCalamityBlade : DeltaWeapon replaces ID24CalamityBlade
{
	Default
	{
		Tag "$TAG_ID24CALAMITYBLADE";
		
		Inventory.PickupMessage "$ID24_GOTCALAMITYBLADE";
		Weapon.SelectionOrder 1000;
		Weapon.AmmoUse 10;
		Weapon.AmmoGive 20;
		Weapon.AmmoType "ID24Fuel";
		DeltaWeapon.Crosshair "DRPLSRET";
		
		+WEAPON.NOAUTOAIM;
	}
	
	action void A_CheckAmmo(StateLabel st, int amount)
	{
		MBF21_CheckAmmo(ResolveState(st), amount);
	}
	
	action void A_GunFlashTo(StateLabel st, int dontchangeplayer)
	{
		MBF21_GunFlashTo(ResolveState(st), dontchangeplayer);
	}
	
	action void A_RefireTo(StateLabel st, int skipcheck)
	{
		MBF21_RefireTo(ResolveState(st), skipcheck);
	}
	
	States
	{
		Spawn:
			CBLD A -1;
			Stop;
		Ready:
			HETG A 1 A_DeltaWeaponReady;
			Loop;
		Deselect:
			HETG A 1 A_Lower;
			Loop;
		Select:
			HETG A 1 A_Raise;
			Loop;
		Fire:
		Hold0:
			HETG A 0 MBF21_ConsumeAmmo(0);
			HETG A 0 A_GunFlashTo("Hold0Flash", 1);
			HETG A 1 A_StartSound("weapons/calamityblade/charge", CHAN_WEAPON);
			HETG AAAAA 1 A_OwnerPlayAttack(false);
			HETG AAAAA 1 A_OwnerPlayAttack(false);
			HETG AAAAA 1 A_OwnerPlayAttack(false);
			HETG AAAA 1 A_OwnerPlayAttack(false);
			HETG A 0 A_CheckAmmo("Hold0FireProjectiles", 0);
			HETG A 0 A_RefireTo("Hold1", 0);
			Goto Hold0FireProjectiles;
		Hold1:
			HETG A 0 MBF21_ConsumeAmmo(0);
			HETG A 0 A_GunFlashTo("Hold1Flash", 1);
			HETG A 1 A_StartSound("weapons/calamityblade/charge", CHAN_WEAPON);
			HETG AAAAA 1 A_OwnerPlayAttack(false);
			HETG AAAAA 1 A_OwnerPlayAttack(false);
			HETG AAAAA 1 A_OwnerPlayAttack(false);
			HETG AAAA 1 A_OwnerPlayAttack(false);
			HETG A 0 A_CheckAmmo("Hold1FireProjectiles", 0);
			HETG A 0 A_RefireTo("Hold2", 0);
			Goto Hold1FireProjectiles;
		Hold2:
			HETG A 0 MBF21_ConsumeAmmo(0);
			HETG A 0 A_GunFlashTo("Hold2Flash", 1);
			HETG A 1 A_StartSound("weapons/calamityblade/charge", CHAN_WEAPON);
			HETG AAAAA 1 A_OwnerPlayAttack(false);
			HETG AAAAA 1 A_OwnerPlayAttack(false);
			HETG AAAAA 1 A_OwnerPlayAttack(false);
			HETG AAAA 1 A_OwnerPlayAttack(false);
			HETG A 0 A_CheckAmmo("Hold2FireProjectiles", 0);
			HETG A 0 A_RefireTo("Hold3", 0);
			Goto Hold2FireProjectiles;
		Hold3:
			HETG A 0 MBF21_ConsumeAmmo(0);
			HETG A 0 A_GunFlashTo("Hold3Flash", 1);
			HETG A 1 A_StartSound("weapons/calamityblade/charge", CHAN_WEAPON);
			HETG AAAAA 1 A_OwnerPlayAttack(false);
			HETG AAAAA 1 A_OwnerPlayAttack(false);
			HETG AAAAA 1 A_OwnerPlayAttack(false);
			HETG AAAA 1 A_OwnerPlayAttack(false);
			HETG A 0 A_CheckAmmo("Hold3FireProjectiles", 0);
			HETG A 0 A_RefireTo("Hold4", 0);
			Goto Hold3FireProjectiles;
		Hold4:
			HETG A 0 MBF21_ConsumeAmmo(0);
			HETG A 0 A_GunFlashTo("Hold4Flash", 1);
			HETG A 0 A_OwnerPlayAttack(false);
			HETG A 1 A_StartSound("weapons/calamityblade/charge", CHAN_WEAPON);
			HETG AAAAA 1 A_OwnerPlayAttack(false);
			HETG AAAAA 1 A_OwnerPlayAttack(false);
			HETG AAAAA 1 A_OwnerPlayAttack(false);
			HETG AAAA 1 A_OwnerPlayAttack(false);
			Goto Hold4FireProjectiles;
		Hold4FireProjectiles:
			HETF A 0 BRIGHT A_OwnerPlayAttack;
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -35, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -30, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -25, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -20, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -15, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -10, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -5, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 0, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 5, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 10, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 15, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 20, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 25, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 30, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 35, 0, 0, 0);
			Goto FireAnim;
		Hold3FireProjectiles:
			HETF A 0 BRIGHT A_OwnerPlayAttack;
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -27.5, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -22.5, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -17.5, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -12.5, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -7.5, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -2.5, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 2.5, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 7.5, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 12.5, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 17.5, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 22.5, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 27.5, 0, 0, 0);
			Goto FireAnim;
		Hold2FireProjectiles:
			HETF A 0 BRIGHT A_OwnerPlayAttack;
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -20, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -15, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -10, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -5, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 0, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 5, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 10, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 15, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 20, 0, 0, 0);
			Goto FireAnim;
		Hold1FireProjectiles:
			HETF A 0 BRIGHT A_OwnerPlayAttack;
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -12.5, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -7.5, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -2.5, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 2.5, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 7.5, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 12.5, 0, 0, 0);
			Goto FireAnim;
		Hold0FireProjectiles:
			HETF A 0 BRIGHT A_OwnerPlayAttack;
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -5, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 0, 0, 0, 0);
			HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 5, 0, 0, 0);
			Goto FireAnim;
		FireAnim:
			HETF A 0 BRIGHT A_StartSound("weapons/calamityblade/shoot", CHAN_WEAPON);
			HETF A 3 BRIGHT A_GunFlash;
			HETF B 5 BRIGHT;
			HETG D 4;
			HETG C 4;
			HETG B 4;
			HETG A 0 A_ReFire;
			Goto Ready;
		Hold0Flash:
			HETC A 6 BRIGHT;
			HETC BCD 5 BRIGHT;
			Goto LightDone;
		Hold1Flash:
			HETC E 6 BRIGHT;
			HETC FGH 5 BRIGHT;
			Goto LightDone;
		Hold2Flash:
			HETC I 6 BRIGHT;
			HETC JKL 5 BRIGHT;
			Goto LightDone;
		Hold3Flash:
			HETC M 6 BRIGHT;
			HETC NOP 5 BRIGHT;
			Goto LightDone;
		Hold4Flash:
			HETC Q 6 BRIGHT;
			HETC RST 5 BRIGHT;
			Goto LightDone;
		Flash:
			TNT1 A 3 A_Light1;
			TNT1 A 5 A_Light2;
			Goto LightDone;
	}
}