class DeltaWeaponPickup : Weapon
{
	protected Map<string, class<Weapon> > actualPickups;
	
	Default
	{}
	
	States
	{
		Spawn:
			TNT1 A 0;
			#### A 1 A_GetWeaponSprite;
			Wait;
		Ready:
		Select:
		Deselect:
		Fire:
			TNT1 A 1;
			Loop;
	}
	
	override void BeginPlay()
	{
		Super.BeginPlay();
		AddPickups();
	}
	
	virtual void AddPickups() {}
	
	class<Weapon> GetWeapon(PlayerPawn ply = null)
	{
		if (!ply)
			ply = players[consoleplayer].mo;
		if (!ply || !(ply is "DeltaPlayer"))
			return null;
		
		return actualPickups.Get(DeltaPlayer(ply).GetClassName());
	}
	
	action void A_GetWeaponSprite()
	{
		// consolePlayer used here on purpose!
		// we WANT this to be able to look different for each player if, say,
		// one is playing as Kris and another as Susie
		let weapClass = invoker.GetWeapon();
		if (!weapClass)
			return;
		
		let weap = GetDefaultByType(weapClass);
		if (!weap || !weap.SpawnState)
			return;
		
		sprite = weap.SpawnState.sprite;
	}
	
	override string PickupMessage()
	{
		let weap = GetWeapon();
		if (!weap)
			return Super.PickupMessage();
		
		return GetDefaultByType(weap).PickupMessage();
	}
	
	override bool CanPickup(Actor toucher)
	{
		let weap = GetWeapon();
		if (!weap)
			return false;
		
		return GetDefaultByType(weap).CanPickup(toucher);
	}
	
	override bool TryPickup(in out Actor toucher)
	{
		let weap = GetWeapon();
		if (!weap)
			return false;
		
		let realWeap = Weapon(Spawn(weap));
		realWeap.bDropped = bDropped;
		
		if (bDropped)
			realWeap.ModifyDropAmount(-1);
		
		if (!realWeap.CallTryPickup(toucher))
		{
			realWeap.Destroy();
			return false;
		}
		
		GoAwayAndDie();
		return true;
	}
	
	override void AttachToOwner(Actor other) { }
}

// Doom replacers
class DeltaChainsaw : Weapon replaces Chainsaw
{
	Default
	{
		+WEAPON.NO_AUTO_SWITCH
	}
	
	States
	{
		Spawn:
			CSAW A -1;
			Stop;
		Select:
			TNT1 A 0;
			Goto Ready;
		Deselect:
			TNT1 A 0;
			Stop;
		Ready:
			TNT1 A 1;
			Loop;
		Fire:
			Goto Ready;
	}
	
	override bool CheckAmmo(int fireMode, bool autoSwitch, bool requireAmmo, int ammoCount)
	{
		return false;
	}
	
	override string PickupMessage()
	{
		return String.Format(StringTable.Localize("$PICKUP_DELTA_CHAINSAW"),
			GetDefaultByType('Chainsaw').GetTag().MakeLower());
	}
}

class PistolReplacer : DeltaWeaponPickup replaces Pistol
{
	override void AddPickups()
	{
		actualPickups.Insert("KrisPlayer", "KrisRevolver");
	}
}

class ShotgunReplacer : DeltaWeaponPickup replaces Shotgun
{
	override void AddPickups()
	{
		actualPickups.Insert("KrisPlayer", "KrisShotgun");
	}
}

class SuperShotgunReplacer : DeltaWeaponPickup replaces SuperShotgun
{
	override void AddPickups()
	{
		actualPickups.Insert("KrisPlayer", "KrisShotgun");
	}
}

class ChaingunReplacer : DeltaWeaponPickup replaces Chaingun
{
	override void AddPickups()
	{
		actualPickups.Insert("KrisPlayer", "KrisSMG");
	}
}

class RocketLauncherReplacer : DeltaWeaponPickup replaces RocketLauncher
{
	override void AddPickups()
	{
		actualPickups.Insert("KrisPlayer", "RocketLauncher");
	}
}